import * as wasm from '../pkg/finstack_wasm.js';

export const analytics = {
  // Risk metrics — return-based
  sharpe: wasm.sharpe,
  sortino: wasm.sortino,
  volatility: wasm.volatility,
  meanReturn: wasm.meanReturn,
  cagrFromPeriods: wasm.cagrFromPeriods,
  downsideDeviation: wasm.downsideDeviation,
  geometricMean: wasm.geometricMean,
  omegaRatio: wasm.omegaRatio,
  gainToPain: wasm.gainToPain,
  modifiedSharpe: wasm.modifiedSharpe,
  // Risk metrics — tail
  valueAtRisk: wasm.valueAtRisk,
  expectedShortfall: wasm.expectedShortfall,
  parametricVar: wasm.parametricVar,
  cornishFisherVar: wasm.cornishFisherVar,
  skewness: wasm.skewness,
  kurtosis: wasm.kurtosis,
  tailRatio: wasm.tailRatio,
  outlierWinRatio: wasm.outlierWinRatio,
  outlierLossRatio: wasm.outlierLossRatio,
  // Risk metrics — rolling
  rollingSharpeValues: wasm.rollingSharpeValues,
  rollingSortinoValues: wasm.rollingSortinoValues,
  rollingVolatilityValues: wasm.rollingVolatilityValues,
  // Returns
  simpleReturns: wasm.simpleReturns,
  compSum: wasm.compSum,
  compTotal: wasm.compTotal,
  cleanReturns: wasm.cleanReturns,
  convertToPrices: wasm.convertToPrices,
  rebase: wasm.rebase,
  excessReturns: wasm.excessReturns,
  // Risk metrics — rolling (dated)
  rollingSharpe: wasm.rollingSharpe,
  rollingSortino: wasm.rollingSortino,
  rollingVolatility: wasm.rollingVolatility,
  // Drawdown
  toDrawdownSeries: wasm.toDrawdownSeries,
  maxDrawdown: wasm.maxDrawdown,
  meanEpisodeDrawdown: wasm.meanEpisodeDrawdown,
  meanDrawdown: wasm.meanDrawdown,
  drawdownDetails: wasm.drawdownDetails,
  maxDrawdownDuration: wasm.maxDrawdownDuration,
  cdar: wasm.cdar,
  ulcerIndex: wasm.ulcerIndex,
  painIndex: wasm.painIndex,
  calmar: wasm.calmar,
  recoveryFactor: wasm.recoveryFactor,
  martinRatio: wasm.martinRatio,
  sterlingRatio: wasm.sterlingRatio,
  burkeRatio: wasm.burkeRatio,
  painRatio: wasm.painRatio,
  // Benchmark
  trackingError: wasm.trackingError,
  informationRatio: wasm.informationRatio,
  rSquared: wasm.rSquared,
  upCapture: wasm.upCapture,
  downCapture: wasm.downCapture,
  captureRatio: wasm.captureRatio,
  battingAverage: wasm.battingAverage,
  treynor: wasm.treynor,
  mSquared: wasm.mSquared,
  beta: wasm.beta,
  greeks: wasm.greeks,
  rollingGreeks: wasm.rollingGreeks,
  multiFactorGreeks: wasm.multiFactorGreeks,
  // Consecutive
  countConsecutive: wasm.countConsecutive,
  // Aggregation
  groupByPeriod: wasm.groupByPeriod,
  periodStats: wasm.periodStats,
  // Lookback selectors
  mtdSelect: wasm.mtdSelect,
  qtdSelect: wasm.qtdSelect,
  ytdSelect: wasm.ytdSelect,
  fytdSelect: wasm.fytdSelect,
  // Backtesting
  classifyBreaches: wasm.classifyBreaches,
  kupiecTest: wasm.kupiecTest,
  christoffersenTest: wasm.christoffersenTest,
  trafficLight: wasm.trafficLight,
  runBacktest: wasm.runBacktest,
  // GARCH volatility models
  fitGarch11: wasm.fitGarch11,
  fitEgarch11: wasm.fitEgarch11,
  fitGjrGarch11: wasm.fitGjrGarch11,
  garch11Forecast: wasm.garch11Forecast,
  ljungBox: wasm.ljungBox,
  archLm: wasm.archLm,
  aic: wasm.aic,
  bic: wasm.bic,
  hqic: wasm.hqic,
  // Comps — comparable company analysis
  percentileRank: wasm.percentileRank,
  zScore: wasm.zScore,
  peerStats: wasm.peerStats,
  regressionFairValue: wasm.regressionFairValue,
  computeMultiple: wasm.computeMultiple,
  scoreRelativeValue: wasm.scoreRelativeValue,
};
