import * as wasm from '../pkg/finstack_wasm.js';

export const portfolio = {
  parsePortfolioSpec: wasm.parsePortfolioSpec,
  buildPortfolioFromSpec: wasm.buildPortfolioFromSpec,
  portfolioResultTotalValue: wasm.portfolioResultTotalValue,
  portfolioResultGetMetric: wasm.portfolioResultGetMetric,
  aggregateMetrics: wasm.aggregateMetrics,
  valuePortfolio: wasm.valuePortfolio,
  aggregateFullCashflows: wasm.aggregateFullCashflows,
  applyScenarioAndRevalue: wasm.applyScenarioAndRevalue,
  optimizePortfolio: wasm.optimizePortfolio,
  replayPortfolio: wasm.replayPortfolio,
  parametricVarDecomposition: wasm.parametricVarDecomposition,
  parametricEsDecomposition: wasm.parametricEsDecomposition,
  historicalVarDecomposition: wasm.historicalVarDecomposition,
  evaluateRiskBudget: wasm.evaluateRiskBudget,
  rollEffectiveSpread: wasm.rollEffectiveSpread,
  amihudIlliquidity: wasm.amihudIlliquidity,
  daysToLiquidate: wasm.daysToLiquidate,
  liquidityTier: wasm.liquidityTier,
  lvarBangia: wasm.lvarBangia,
  almgrenChrissImpact: wasm.almgrenChrissImpact,
  kyleLambda: wasm.kyleLambda,
};
