"""Ergonomic helpers for building expression ASTs.

This is a typed stub for `finstack.core.expr_helpers` (implemented in Python).
The underlying expression types come from the Rust extension module.
"""

from __future__ import annotations

from typing import TypeAlias, Union

from .expr import Expr

ExprLike: TypeAlias = Union["ExprWrapper", Expr, float, int]

class ExprWrapper:
    """Wrapper around :class:`~finstack.core.expr.Expr` that adds operator overloading."""

    def __init__(self, expr: Expr) -> None: ...
    @property
    def expr(self) -> Expr: ...
    def unwrap(self) -> Expr: ...
    def with_id(self, id: int) -> ExprWrapper: ...

    # Arithmetic
    def __add__(self, other: ExprLike) -> ExprWrapper: ...
    def __radd__(self, other: ExprLike) -> ExprWrapper: ...
    def __sub__(self, other: ExprLike) -> ExprWrapper: ...
    def __rsub__(self, other: ExprLike) -> ExprWrapper: ...
    def __mul__(self, other: ExprLike) -> ExprWrapper: ...
    def __rmul__(self, other: ExprLike) -> ExprWrapper: ...
    def __truediv__(self, other: ExprLike) -> ExprWrapper: ...
    def __rtruediv__(self, other: ExprLike) -> ExprWrapper: ...
    def __mod__(self, other: ExprLike) -> ExprWrapper: ...
    def __rmod__(self, other: ExprLike) -> ExprWrapper: ...
    def __neg__(self) -> ExprWrapper: ...

    # Comparisons (return expression nodes, not booleans)
    def __eq__(self, other: ExprLike) -> ExprWrapper: ...  # type: ignore[override]
    def __ne__(self, other: ExprLike) -> ExprWrapper: ...  # type: ignore[override]
    def __lt__(self, other: ExprLike) -> ExprWrapper: ...
    def __le__(self, other: ExprLike) -> ExprWrapper: ...
    def __gt__(self, other: ExprLike) -> ExprWrapper: ...
    def __ge__(self, other: ExprLike) -> ExprWrapper: ...

    # Logical
    def __and__(self, other: ExprLike) -> ExprWrapper: ...
    def __rand__(self, other: ExprLike) -> ExprWrapper: ...
    def __or__(self, other: ExprLike) -> ExprWrapper: ...
    def __ror__(self, other: ExprLike) -> ExprWrapper: ...
    def __invert__(self) -> ExprWrapper: ...
    def __repr__(self) -> str: ...

def col(name: str) -> ExprWrapper: ...
def lit(value: float) -> ExprWrapper: ...
def lag(expr: ExprLike, periods: int = 1) -> ExprWrapper: ...
def lead(expr: ExprLike, periods: int = 1) -> ExprWrapper: ...
def diff(expr: ExprLike, periods: int = 1) -> ExprWrapper: ...
def pct_change(expr: ExprLike, periods: int = 1) -> ExprWrapper: ...
def growth_rate(expr: ExprLike, periods: int = 1) -> ExprWrapper: ...
def cumsum(expr: ExprLike) -> ExprWrapper: ...
def cumprod(expr: ExprLike) -> ExprWrapper: ...
def cummin(expr: ExprLike) -> ExprWrapper: ...
def cummax(expr: ExprLike) -> ExprWrapper: ...
def rolling_mean(expr: ExprLike, window: int) -> ExprWrapper: ...
def rolling_sum(expr: ExprLike, window: int) -> ExprWrapper: ...
def rolling_std(expr: ExprLike, window: int) -> ExprWrapper: ...
def rolling_var(expr: ExprLike, window: int) -> ExprWrapper: ...
def rolling_min(expr: ExprLike, window: int) -> ExprWrapper: ...
def rolling_max(expr: ExprLike, window: int) -> ExprWrapper: ...
def if_then_else(condition: ExprLike, then_expr: ExprLike, else_expr: ExprLike) -> ExprWrapper: ...
