"""Core factor-model vocabulary types."""

from __future__ import annotations

from typing import Any

class FactorId:
    """Unique identifier for a risk factor."""

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PricingMode:
    """Strategy used when extracting factor sensitivities."""

    value: str
    def __init__(self, value: str) -> None: ...
    @staticmethod
    def delta_based() -> PricingMode: ...
    @staticmethod
    def full_repricing() -> PricingMode: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class FactorType:
    """Broad classification of a risk factor."""

    value: str
    def __init__(self, value: str) -> None: ...
    @staticmethod
    def rates() -> FactorType: ...
    @staticmethod
    def credit() -> FactorType: ...
    @staticmethod
    def equity() -> FactorType: ...
    @staticmethod
    def fx() -> FactorType: ...
    @staticmethod
    def volatility() -> FactorType: ...
    @staticmethod
    def commodity() -> FactorType: ...
    @staticmethod
    def inflation() -> FactorType: ...
    @staticmethod
    def custom(name: str) -> FactorType: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DependencyType:
    """Classification used by dependency filters and matching config."""

    value: str
    def __init__(self, value: str) -> None: ...
    @staticmethod
    def discount() -> DependencyType: ...
    @staticmethod
    def forward() -> DependencyType: ...
    @staticmethod
    def credit() -> DependencyType: ...
    @staticmethod
    def spot() -> DependencyType: ...
    @staticmethod
    def vol() -> DependencyType: ...
    @staticmethod
    def fx() -> DependencyType: ...
    @staticmethod
    def series() -> DependencyType: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class CurveType:
    """Classification of a curve dependency's role."""

    value: str
    def __init__(self, value: str) -> None: ...
    @staticmethod
    def discount() -> CurveType: ...
    @staticmethod
    def forward() -> CurveType: ...
    @staticmethod
    def hazard() -> CurveType: ...
    @staticmethod
    def inflation() -> CurveType: ...
    @staticmethod
    def base_correlation() -> CurveType: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class UnmatchedPolicy:
    """Policy for handling dependencies that do not match any factor."""

    value: str
    def __init__(self, value: str) -> None: ...
    @staticmethod
    def strict() -> UnmatchedPolicy: ...
    @staticmethod
    def residual() -> UnmatchedPolicy: ...
    @staticmethod
    def warn() -> UnmatchedPolicy: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class RiskMeasure:
    """Risk measure used when aggregating factor exposures."""

    kind: str
    confidence: float | None
    def __init__(self, value: str, confidence: float | None = None) -> None: ...
    @staticmethod
    def variance() -> RiskMeasure: ...
    @staticmethod
    def volatility() -> RiskMeasure: ...
    @staticmethod
    def var(confidence: float) -> RiskMeasure: ...
    @staticmethod
    def expected_shortfall(confidence: float) -> RiskMeasure: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# Re-exported from finstack.portfolio.factor_model

RiskMeasureLike = str | dict[str, dict[str, float]]

class MarketDependency:
    kind: str
    id: str | None
    dependency_type: str
    def to_json(self) -> str: ...

class BumpSizeConfig:
    rates_bp: float
    credit_bp: float
    equity_pct: float
    fx_pct: float
    vol_points: float
    overrides: list[tuple[str, float]]
    def __init__(
        self,
        rates_bp: float = 1.0,
        credit_bp: float = 1.0,
        equity_pct: float = 1.0,
        fx_pct: float = 1.0,
        vol_points: float = 1.0,
        overrides: list[tuple[str, float]] | None = None,
    ) -> None: ...

class MarketMapping:
    kind: str
    curve_ids: list[str]
    units: str | None
    tenor_weights: list[tuple[float, float]]

    @staticmethod
    def curve_parallel(curve_ids: list[str], units: str) -> MarketMapping: ...
    @staticmethod
    def curve_bucketed(curve_id: str, tenor_weights: list[tuple[float, float]]) -> MarketMapping: ...
    @staticmethod
    def equity_spot(tickers: list[str]) -> MarketMapping: ...
    @staticmethod
    def fx_rate(base: str, quote: str) -> MarketMapping: ...
    @staticmethod
    def vol_shift(surface_ids: list[str], units: str) -> MarketMapping: ...
    def to_json(self) -> str: ...

class FactorDefinition:
    id: str
    factor_type: str
    market_mapping: MarketMapping
    description: str | None
    def __init__(
        self,
        id: str,
        factor_type: str,
        market_mapping: MarketMapping,
        description: str | None = None,
    ) -> None: ...

class FactorCovarianceMatrix:
    factor_ids: list[str]
    def __init__(self, factor_ids: list[str], matrix: list[list[float]]) -> None: ...
    def matrix(self) -> list[list[float]]: ...
    def n_factors(self) -> int: ...
    def variance(self, factor_id: str) -> float: ...
    def covariance(self, lhs: str, rhs: str) -> float: ...
    def correlation(self, lhs: str, rhs: str) -> float: ...
    def to_json(self) -> str: ...

class AttributeFilter:
    tags: list[str]
    meta: list[tuple[str, str]]
    def __init__(
        self,
        tags: list[str] | None = None,
        meta: list[tuple[str, str]] | None = None,
    ) -> None: ...

class DependencyFilter:
    dependency_type: str | None
    curve_type: str | None
    id: str | None
    def __init__(
        self,
        dependency_type: str | None = None,
        curve_type: str | None = None,
        id: str | None = None,
    ) -> None: ...

class MappingRule:
    dependency_filter: DependencyFilter
    attribute_filter: AttributeFilter
    factor_id: str
    def __init__(
        self,
        dependency_filter: DependencyFilter,
        attribute_filter: AttributeFilter,
        factor_id: str,
    ) -> None: ...

class FactorNode:
    factor_id: str | None
    filter: AttributeFilter
    children: list[FactorNode]
    def __init__(
        self,
        factor_id: str | None = None,
        filter: AttributeFilter | None = None,
        children: list[FactorNode] | None = None,
    ) -> None: ...

class HierarchicalConfig:
    dependency_filter: DependencyFilter
    root: FactorNode
    def __init__(
        self,
        root: FactorNode,
        dependency_filter: DependencyFilter | None = None,
    ) -> None: ...

class MatchingConfig:
    kind: str
    @staticmethod
    def mapping_table(rules: list[MappingRule]) -> MatchingConfig: ...
    @staticmethod
    def cascade(configs: list[MatchingConfig]) -> MatchingConfig: ...
    @staticmethod
    def hierarchical(config: HierarchicalConfig) -> MatchingConfig: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> MatchingConfig: ...

class FactorModelConfig:
    factors: list[FactorDefinition]
    covariance: FactorCovarianceMatrix
    matching: MatchingConfig
    pricing_mode: str
    risk_measure: Any
    bump_size: BumpSizeConfig | None
    unmatched_policy: str | None

    def __init__(
        self,
        factors: list[FactorDefinition],
        covariance: FactorCovarianceMatrix,
        matching: MatchingConfig,
        pricing_mode: str,
        risk_measure: RiskMeasureLike | None = None,
        bump_size: BumpSizeConfig | None = None,
        unmatched_policy: str | None = None,
    ) -> None: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> FactorModelConfig: ...

__all__ = [
    "FactorId",
    "PricingMode",
    "FactorType",
    "DependencyType",
    "CurveType",
    "UnmatchedPolicy",
    "RiskMeasure",
    "MarketDependency",
    "BumpSizeConfig",
    "MarketMapping",
    "FactorDefinition",
    "FactorCovarianceMatrix",
    "FactorModelConfig",
    "MatchingConfig",
    "AttributeFilter",
    "DependencyFilter",
    "MappingRule",
    "FactorNode",
    "HierarchicalConfig",
]
