"""Type-safe identifiers and rate helpers mirroring finstack_core::types.

This module provides:
- ID newtypes: CurveId, InstrumentId, IndexId, PriceId, UnderlyingId
- Rate helpers: Rate, Bps, Percentage
- Credit ratings: CreditRating, RatingNotch, NotchedRating, RatingLabel,
  RatingFactorTable, moodys_warf_factor

These types prevent accidental mismatches and provide clear conversion semantics.
"""

from __future__ import annotations

from typing import Any, Tuple

class CurveId:
    """Type-safe identifier for market data curves.

    Parameters
    ----------
    id : str
        String identifier for the curve.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __getnewargs__(self) -> tuple[str]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class InstrumentId:
    """Type-safe identifier for financial instruments.

    Parameters
    ----------
    id : str
        String identifier for the instrument.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __getnewargs__(self) -> tuple[str]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class IndexId:
    """Type-safe identifier for market indices.

    Parameters
    ----------
    id : str
        String identifier for the index.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PriceId:
    """Type-safe identifier for market prices/scalars.

    Parameters
    ----------
    id : str
        String identifier for the price.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class UnderlyingId:
    """Type-safe identifier for underlying assets.

    Parameters
    ----------
    id : str
        String identifier for the underlying.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Rate:
    """Financial rate stored as decimal (0.05 = 5%).

    Parameters
    ----------
    decimal : float
        Rate as a decimal value (e.g. 0.05 for 5%).
    """

    def __init__(self, decimal: float) -> None: ...
    @staticmethod
    def from_decimal(decimal: float) -> Rate:
        """Create a rate from a decimal value (0.05 = 5%)."""
        ...

    @staticmethod
    def from_percent(percent: float) -> Rate:
        """Create a rate from a percentage value (5.0 = 5%)."""
        ...

    @staticmethod
    def from_bps(bps: int) -> Rate:
        """Create a rate from basis points (500 bps = 5%)."""
        ...

    def as_decimal(self) -> float:
        """Get the rate as a decimal value."""
        ...

    def as_percent(self) -> float:
        """Get the rate as a percentage value."""
        ...

    def as_bps(self) -> int:
        """Get the rate as basis points (rounded to nearest integer)."""
        ...

    def __format__(self, spec: str) -> str:
        """Format with a format specifier.

        Use '.2%' for percentage, '.4f' for decimal.

        Examples
        --------
        >>> f"{Rate.from_decimal(0.05):.2%}"
        '5.00%'
        """
        ...

    def __getnewargs__(self) -> tuple[float]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Rate) -> bool: ...
    def __le__(self, other: Rate) -> bool: ...
    def __gt__(self, other: Rate) -> bool: ...
    def __ge__(self, other: Rate) -> bool: ...
    def __add__(self, other: Rate) -> Rate: ...
    def __sub__(self, other: Rate) -> Rate: ...
    def __mul__(self, scalar: float) -> Rate: ...
    def __truediv__(self, scalar: float) -> Rate: ...
    def __neg__(self) -> Rate: ...

class Bps:
    """Basis points - a unit of measure for rates (1 bp = 0.01%).

    Parameters
    ----------
    bps : int
        Basis points value.
    """

    def __init__(self, bps: int) -> None: ...
    def as_bps(self) -> int:
        """Get the basis points as an integer."""
        ...

    def as_decimal(self) -> float:
        """Convert to decimal representation."""
        ...

    def as_percent(self) -> float:
        """Convert to percentage representation."""
        ...

    def as_rate(self) -> Rate:
        """Convert to Rate."""
        ...

    def __getnewargs__(self) -> tuple[int]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Bps) -> bool: ...
    def __le__(self, other: Bps) -> bool: ...
    def __gt__(self, other: Bps) -> bool: ...
    def __ge__(self, other: Bps) -> bool: ...
    def __add__(self, other: Bps) -> Bps: ...
    def __sub__(self, other: Bps) -> Bps: ...
    def __mul__(self, scalar: int) -> Bps: ...
    def __truediv__(self, scalar: int) -> Bps: ...
    def __neg__(self) -> Bps: ...

class Percentage:
    """A percentage value (5.0 = 5%).

    Parameters
    ----------
    percent : float
        Percentage value.
    """

    def __init__(self, percent: float) -> None: ...
    def as_percent(self) -> float:
        """Get the percentage value."""
        ...

    def as_decimal(self) -> float:
        """Convert to decimal representation."""
        ...

    def as_rate(self) -> Rate:
        """Convert to Rate."""
        ...

    def as_bps(self) -> int:
        """Convert to basis points."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Percentage) -> bool: ...
    def __le__(self, other: Percentage) -> bool: ...
    def __gt__(self, other: Percentage) -> bool: ...
    def __ge__(self, other: Percentage) -> bool: ...
    def __add__(self, other: Percentage) -> Percentage: ...
    def __sub__(self, other: Percentage) -> Percentage: ...
    def __mul__(self, scalar: float) -> Percentage: ...
    def __truediv__(self, scalar: float) -> Percentage: ...
    def __neg__(self) -> Percentage: ...

# Credit ratings

class RatingNotch:
    """Notch adjustment for credit ratings (plus/flat/minus)."""

    PLUS: "RatingNotch"
    FLAT: "RatingNotch"
    MINUS: "RatingNotch"

    @property
    def name(self) -> str:
        """Lower-case label (``plus``, ``flat``, ``minus``)."""
        ...

    @property
    def symbol(self) -> str:
        """Symbol representation (``+``, ``'', ``-``)."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CreditRating:
    """Agency-agnostic credit rating scale (AAA … NR)."""

    AAA: "CreditRating"
    AA: "CreditRating"
    A: "CreditRating"
    BBB: "CreditRating"
    BB: "CreditRating"
    B: "CreditRating"
    CCC: "CreditRating"
    CC: "CreditRating"
    C: "CreditRating"
    D: "CreditRating"
    NR: "CreditRating"

    def __init__(self, value: str) -> None: ...
    def with_notch(self, notch: RatingNotch) -> "NotchedRating": ...
    def is_investment_grade(self) -> bool: ...
    def is_speculative_grade(self) -> bool: ...
    def is_default(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NotchedRating:
    """Credit rating with notch information."""

    def __init__(self, rating: CreditRating, notch: RatingNotch | None = ...) -> None: ...
    @classmethod
    def parse(cls, value: str) -> "NotchedRating":
        """Parse a rating string (e.g., ``\"AA-\"``, ``\"B3\"``, ``\"NR\"``)."""
        ...

    @property
    def base(self) -> CreditRating:
        """Base credit rating without notch."""
        ...

    @property
    def notch(self) -> RatingNotch:
        """Notch component."""
        ...

    def is_investment_grade(self) -> bool: ...
    def is_speculative_grade(self) -> bool: ...
    def is_default(self) -> bool: ...
    def without_notch(self) -> "NotchedRating": ...
    def moodys(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RatingLabel:
    """Stable display label for ratings."""

    @classmethod
    def generic(cls, rating: NotchedRating) -> "RatingLabel": ...
    @classmethod
    def moodys(cls, rating: NotchedRating) -> "RatingLabel": ...
    @property
    def value(self) -> str:
        """String representation of the label."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RatingFactorTable:
    """Rating-to-factor mapping (e.g., Moody's WARF table)."""

    @classmethod
    def moodys_standard(cls) -> "RatingFactorTable":
        """Standard Moody's WARF factor table."""
        ...

    def get_factor(self, rating: NotchedRating | CreditRating | str) -> float:
        """Lookup factor for a rating (falls back to default when missing)."""
        ...

    @property
    def agency(self) -> str: ...
    @property
    def methodology(self) -> str: ...
    @property
    def default_factor(self) -> float: ...
    def __repr__(self) -> str: ...

def moodys_warf_factor(rating: NotchedRating | CreditRating | str) -> float:
    """Convenience wrapper returning Moody's WARF factor for a rating."""
    ...

__all__ = [
    "CurveId",
    "InstrumentId",
    "IndexId",
    "PriceId",
    "UnderlyingId",
    "Rate",
    "Bps",
    "Percentage",
    "RatingNotch",
    "CreditRating",
    "NotchedRating",
    "RatingLabel",
    "RatingFactorTable",
    "moodys_warf_factor",
]
