"""Type-safe identifiers and rate helpers mirroring finstack_core::types.

This module provides:
- ID newtypes: CurveId, InstrumentId, IndexId, PriceId, UnderlyingId
- Rate helpers: Rate, Bps, Percentage

These types prevent accidental mismatches and provide clear conversion semantics.
"""

class CurveId:
    """Type-safe identifier for market data curves.

    Parameters
    ----------
    id : str
        String identifier for the curve.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class InstrumentId:
    """Type-safe identifier for financial instruments.

    Parameters
    ----------
    id : str
        String identifier for the instrument.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class IndexId:
    """Type-safe identifier for market indices.

    Parameters
    ----------
    id : str
        String identifier for the index.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PriceId:
    """Type-safe identifier for market prices/scalars.

    Parameters
    ----------
    id : str
        String identifier for the price.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class UnderlyingId:
    """Type-safe identifier for underlying assets.

    Parameters
    ----------
    id : str
        String identifier for the underlying.
    """

    def __init__(self, id: str) -> None: ...
    def as_str(self) -> str:
        """Get the string representation of this ID."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Rate:
    """Financial rate stored as decimal (0.05 = 5%)."""

    @staticmethod
    def from_decimal(decimal: float) -> Rate:
        """Create a rate from a decimal value (0.05 = 5%)."""
        ...

    @staticmethod
    def from_percent(percent: float) -> Rate:
        """Create a rate from a percentage value (5.0 = 5%)."""
        ...

    @staticmethod
    def from_bps(bps: int) -> Rate:
        """Create a rate from basis points (500 bps = 5%)."""
        ...

    def as_decimal(self) -> float:
        """Get the rate as a decimal value."""
        ...

    def as_percent(self) -> float:
        """Get the rate as a percentage value."""
        ...

    def as_bps(self) -> int:
        """Get the rate as basis points (rounded to nearest integer)."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Rate) -> bool: ...
    def __le__(self, other: Rate) -> bool: ...
    def __gt__(self, other: Rate) -> bool: ...
    def __ge__(self, other: Rate) -> bool: ...
    def __add__(self, other: Rate) -> Rate: ...
    def __sub__(self, other: Rate) -> Rate: ...
    def __mul__(self, scalar: float) -> Rate: ...
    def __truediv__(self, scalar: float) -> Rate: ...
    def __neg__(self) -> Rate: ...

class Bps:
    """Basis points - a unit of measure for rates (1 bp = 0.01%).

    Parameters
    ----------
    bps : int
        Basis points value.
    """

    def __init__(self, bps: int) -> None: ...
    def as_bps(self) -> int:
        """Get the basis points as an integer."""
        ...

    def as_decimal(self) -> float:
        """Convert to decimal representation."""
        ...

    def as_percent(self) -> float:
        """Convert to percentage representation."""
        ...

    def as_rate(self) -> Rate:
        """Convert to Rate."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Bps) -> bool: ...
    def __le__(self, other: Bps) -> bool: ...
    def __gt__(self, other: Bps) -> bool: ...
    def __ge__(self, other: Bps) -> bool: ...
    def __add__(self, other: Bps) -> Bps: ...
    def __sub__(self, other: Bps) -> Bps: ...
    def __mul__(self, scalar: int) -> Bps: ...
    def __truediv__(self, scalar: int) -> Bps: ...
    def __neg__(self) -> Bps: ...

class Percentage:
    """A percentage value (5.0 = 5%).

    Parameters
    ----------
    percent : float
        Percentage value.
    """

    def __init__(self, percent: float) -> None: ...
    def as_percent(self) -> float:
        """Get the percentage value."""
        ...

    def as_decimal(self) -> float:
        """Convert to decimal representation."""
        ...

    def as_rate(self) -> Rate:
        """Convert to Rate."""
        ...

    def as_bps(self) -> int:
        """Convert to basis points."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Percentage) -> bool: ...
    def __le__(self, other: Percentage) -> bool: ...
    def __gt__(self, other: Percentage) -> bool: ...
    def __ge__(self, other: Percentage) -> bool: ...
    def __add__(self, other: Percentage) -> Percentage: ...
    def __sub__(self, other: Percentage) -> Percentage: ...
    def __mul__(self, scalar: float) -> Percentage: ...
    def __truediv__(self, scalar: float) -> Percentage: ...
    def __neg__(self) -> Percentage: ...

__all__ = [
    "CurveId",
    "InstrumentId",
    "IndexId",
    "PriceId",
    "UnderlyingId",
    "Rate",
    "Bps",
    "Percentage",
]
