"""Structured credit enum types."""

from __future__ import annotations
from datetime import date
from typing import Any
from enum import IntEnum

class AssetType:
    PRIME_CREDIT_CARD: "AssetType"
    SUBPRIME_CREDIT_CARD: "AssetType"
    SUPER_PRIME_CREDIT_CARD: "AssetType"
    COMMERCIAL_CREDIT_CARD: "AssetType"
    FEDERAL_STUDENT_LOAN: "AssetType"
    PRIVATE_STUDENT_LOAN: "AssetType"
    FFELP_STUDENT_LOAN: "AssetType"
    CONSOLIDATION_STUDENT_LOAN: "AssetType"
    @classmethod
    def first_lien_loan(cls, industry: str | None = None) -> "AssetType": ...
    @classmethod
    def second_lien_loan(cls, industry: str | None = None) -> "AssetType": ...
    @classmethod
    def revolver_loan(cls, industry: str | None = None) -> "AssetType": ...
    @classmethod
    def bridge_loan(cls, industry: str | None = None) -> "AssetType": ...
    @classmethod
    def mezzanine_loan(cls, industry: str | None = None) -> "AssetType": ...
    @classmethod
    def high_yield_bond(cls, industry: str | None = None) -> "AssetType": ...
    @classmethod
    def investment_grade_bond(cls, industry: str | None = None) -> "AssetType": ...
    @classmethod
    def distressed_bond(cls, industry: str | None = None) -> "AssetType": ...
    @classmethod
    def emerging_markets_bond(cls, industry: str | None = None) -> "AssetType": ...
    @classmethod
    def single_family_mortgage(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def multifamily_mortgage(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def commercial_mortgage(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def industrial_mortgage(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def retail_mortgage(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def office_mortgage(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def hotel_mortgage(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def other_mortgage(cls, property_type: str, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def new_auto_loan(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def used_auto_loan(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def lease_auto_loan(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def fleet_auto_loan(cls, ltv: float | None = None) -> "AssetType": ...
    @classmethod
    def equipment(cls, equipment_type: str) -> "AssetType": ...
    @classmethod
    def generic(cls, description: str, asset_class: str) -> "AssetType": ...
    def is_amortizing(self) -> bool: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "AssetType": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PaymentMode:
    @classmethod
    def pro_rata(cls) -> "PaymentMode": ...
    @classmethod
    def sequential(cls, triggered_by: str, trigger_date: date) -> "PaymentMode": ...
    @classmethod
    def hybrid(cls, description: str) -> "PaymentMode": ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "PaymentMode": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class TriggerConsequence:
    DIVERT_CASH_FLOW: "TriggerConsequence"
    TRAP_EXCESS_SPREAD: "TriggerConsequence"
    ACCELERATE_AMORTIZATION: "TriggerConsequence"
    STOP_REINVESTMENT: "TriggerConsequence"
    REDUCE_MANAGER_FEE: "TriggerConsequence"
    @classmethod
    def custom(cls, description: str) -> "TriggerConsequence": ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "TriggerConsequence": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class TrancheBehaviorType(IntEnum):
    Standard = 0

class TrancheCoupon:
    @classmethod
    def fixed(cls, rate: float) -> "TrancheCoupon": ...
    @classmethod
    def floating(cls, spec: Any) -> "TrancheCoupon": ...
    def current_rate(self, date: date) -> float: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "TrancheCoupon": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class RecipientType:
    EQUITY: "RecipientType"
    @classmethod
    def service_provider(cls, name: str) -> "RecipientType": ...
    @classmethod
    def manager_fee(cls, fee_type: "ManagementFeeType") -> "RecipientType": ...
    @classmethod
    def tranche(cls, tranche_id: str) -> "RecipientType": ...
    @classmethod
    def reserve_account(cls, account_id: str) -> "RecipientType": ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "RecipientType": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ManagementFeeType(IntEnum):
    Senior = 0
    Subordinated = 1
    Incentive = 2

class PaymentCalculation:
    RESIDUAL_CASH: "PaymentCalculation"
    @classmethod
    def fixed_amount(cls, amount: float, currency: str) -> "PaymentCalculation": ...
    @classmethod
    def percentage_of_collateral(cls, rate: float, annualized: bool = True) -> "PaymentCalculation": ...
    @classmethod
    def tranche_interest(cls, tranche_id: str) -> "PaymentCalculation": ...
    @classmethod
    def tranche_principal(cls, tranche_id: str, target_balance: float | None = None) -> "PaymentCalculation": ...
    @classmethod
    def reserve_replenishment(cls, target_balance_amount: float, currency: str) -> "PaymentCalculation": ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "PaymentCalculation": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class CoverageTestType(IntEnum):
    OC = 0
    IC = 1

class RoundingConvention(IntEnum):
    Nearest = 0
    Floor = 1
    Ceiling = 2

class DiversionCondition:
    ALWAYS: "DiversionCondition"
    @classmethod
    def coverage_test_failed(cls, test_id: str) -> "DiversionCondition": ...
    @classmethod
    def custom_expression(cls, expr: str) -> "DiversionCondition": ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "DiversionCondition": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ValidationError:
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

__all__ = [
    "AssetType",
    "PaymentMode",
    "TriggerConsequence",
    "TrancheBehaviorType",
    "TrancheCoupon",
    "RecipientType",
    "ManagementFeeType",
    "PaymentCalculation",
    "CoverageTestType",
    "RoundingConvention",
    "DiversionCondition",
    "ValidationError",
]
