"""Structured credit pool types."""

from __future__ import annotations
from datetime import date
from typing import Any

class PoolAsset:
    @classmethod
    def floating_rate_loan(
        cls,
        id: str,
        balance_amount: float,
        currency: str,
        spread_bps: float,
        index_id: str,
        maturity: date,
        day_count: str = "ACT_360",
    ) -> "PoolAsset": ...
    @classmethod
    def fixed_rate_bond(
        cls,
        id: str,
        balance_amount: float,
        currency: str,
        rate: float,
        maturity: date,
        day_count: str = "THIRTY_360",
    ) -> "PoolAsset": ...
    @classmethod
    def from_dict(cls, data: Any) -> "PoolAsset": ...
    def to_dict(self) -> Any: ...
    def with_rating(self, rating: str) -> "PoolAsset": ...
    def with_industry(self, industry: str) -> "PoolAsset": ...
    def with_obligor(self, obligor_id: str) -> "PoolAsset": ...
    def current_yield(self) -> float: ...
    def spread_bps_value(self) -> float: ...
    def remaining_term(self, as_of: date) -> float: ...
    def is_amortizing(self) -> bool: ...
    @property
    def id(self) -> str: ...
    @property
    def asset_type(self) -> str: ...
    @property
    def balance(self) -> Any: ...
    @property
    def rate(self) -> float: ...
    @property
    def spread_bps(self) -> float | None: ...
    @property
    def index_id(self) -> str | None: ...
    @property
    def maturity(self) -> date: ...
    @property
    def credit_quality(self) -> str | None: ...
    @property
    def industry(self) -> str | None: ...
    @property
    def obligor_id(self) -> str | None: ...
    @property
    def is_defaulted(self) -> bool: ...
    @property
    def recovery_amount(self) -> Any | None: ...
    @property
    def purchase_price(self) -> Any | None: ...
    @property
    def acquisition_date(self) -> date | None: ...
    @property
    def day_count(self) -> str: ...
    @property
    def smm_override(self) -> float | None: ...
    @property
    def mdr_override(self) -> float | None: ...
    def __repr__(self) -> str: ...

class RepLine:
    def __init__(
        self,
        id: str,
        balance_amount: float,
        currency: str,
        rate: float,
        maturity: date,
        seasoning_months: int = 0,
    ) -> None: ...
    @classmethod
    def from_dict(cls, data: Any) -> "RepLine": ...
    def to_dict(self) -> Any: ...
    def with_cpr(self, cpr: float) -> "RepLine": ...
    def with_cdr(self, cdr: float) -> "RepLine": ...
    def with_recovery_rate(self, rate: float) -> "RepLine": ...
    def spread_bps_value(self) -> float: ...
    @property
    def id(self) -> str: ...
    @property
    def balance(self) -> Any: ...
    @property
    def rate(self) -> float: ...
    @property
    def spread_bps(self) -> float | None: ...
    @property
    def index_id(self) -> str | None: ...
    @property
    def maturity(self) -> date: ...
    @property
    def seasoning_months(self) -> int: ...
    @property
    def day_count(self) -> str: ...
    @property
    def cpr(self) -> float | None: ...
    @property
    def cdr(self) -> float | None: ...
    @property
    def recovery_rate(self) -> float | None: ...
    def __repr__(self) -> str: ...

class Pool:
    def __init__(self, id: str, deal_type: str, currency: str = "USD") -> None: ...
    @classmethod
    def from_dict(cls, data: Any) -> "Pool": ...
    def to_dict(self) -> Any: ...
    def add_asset(self, asset: PoolAsset) -> "Pool": ...
    def aggregate_to_rep_lines(self, as_of: date) -> "Pool": ...
    def total_balance(self) -> Any: ...
    def performing_balance(self) -> Any: ...
    def weighted_avg_coupon(self) -> float: ...
    def weighted_avg_maturity(self, as_of: date) -> float: ...
    def diversity_score(self) -> float: ...
    def weighted_avg_spread(self) -> float: ...
    @property
    def pool_id(self) -> str: ...
    @property
    def deal_type(self) -> str: ...
    @property
    def asset_count(self) -> int: ...
    @property
    def rep_line_count(self) -> int: ...
    def __repr__(self) -> str: ...

class PoolStats:
    @classmethod
    def from_dict(cls, data: Any) -> "PoolStats": ...
    def to_dict(self) -> Any: ...
    @property
    def weighted_avg_coupon(self) -> float: ...
    @property
    def weighted_avg_spread(self) -> float: ...
    @property
    def weighted_avg_life(self) -> float: ...
    @property
    def weighted_avg_maturity(self) -> float: ...
    @property
    def weighted_avg_rating_factor(self) -> float: ...
    @property
    def diversity_score(self) -> float: ...
    @property
    def num_obligors(self) -> int: ...
    @property
    def num_industries(self) -> int: ...
    @property
    def cumulative_default_rate(self) -> float: ...
    @property
    def recovery_rate(self) -> float: ...
    @property
    def prepayment_rate(self) -> float: ...
    def __repr__(self) -> str: ...

class ReinvestmentPeriod:
    @classmethod
    def from_dict(cls, data: Any) -> "ReinvestmentPeriod": ...
    def to_dict(self) -> Any: ...
    @property
    def end_date(self) -> date: ...
    @property
    def is_active(self) -> bool: ...
    @property
    def criteria(self) -> "ReinvestmentCriteria": ...
    def __repr__(self) -> str: ...

class ReinvestmentCriteria:
    @classmethod
    def from_dict(cls, data: Any) -> "ReinvestmentCriteria": ...
    def to_dict(self) -> Any: ...
    @property
    def max_price(self) -> float: ...
    @property
    def min_yield(self) -> float: ...
    @property
    def maintain_credit_quality(self) -> bool: ...
    @property
    def maintain_wal(self) -> bool: ...
    @property
    def apply_eligibility_criteria(self) -> bool: ...
    def __repr__(self) -> str: ...

class ConcentrationCheckResult:
    @property
    def has_violations(self) -> bool: ...
    @property
    def violations(self) -> list["ConcentrationViolation"]: ...
    @property
    def violation_count(self) -> int: ...
    def __repr__(self) -> str: ...

class ConcentrationViolation:
    @property
    def violation_type(self) -> str: ...
    @property
    def identifier(self) -> str: ...
    @property
    def current_level(self) -> float: ...
    @property
    def limit(self) -> float: ...
    def __repr__(self) -> str: ...

def calculate_pool_stats(pool: Pool, as_of: date) -> PoolStats: ...

__all__ = [
    "PoolAsset",
    "RepLine",
    "Pool",
    "PoolStats",
    "ReinvestmentPeriod",
    "ReinvestmentCriteria",
    "ConcentrationCheckResult",
    "ConcentrationViolation",
    "calculate_pool_stats",
]
