"""Structured credit pricing functions and types."""

from __future__ import annotations
from datetime import date
from typing import Any

def generate_cashflows(instrument: Any, market: Any, as_of: date) -> list[tuple[date, Any]]: ...
def generate_tranche_cashflows(instrument: Any, tranche_id: str, market: Any, as_of: date) -> Any: ...
def run_simulation(instrument: Any, market: Any, as_of: date) -> Any: ...
def execute_waterfall(
    waterfall: Any,
    tranches: Any,
    pool: Any,
    available_cash_amount: float,
    interest_collections_amount: float,
    currency: str,
    payment_date: date,
    period_start: date,
    pool_balance_amount: float,
    market: Any,
) -> Any: ...

class CoverageTest:
    @classmethod
    def new_oc(
        cls, required_ratio: float, include_cash: bool = True, performing_only: bool = True
    ) -> "CoverageTest": ...
    @classmethod
    def new_oc_with_id(
        cls, id: str, required_ratio: float, include_cash: bool = True, performing_only: bool = True
    ) -> "CoverageTest": ...
    @classmethod
    def new_ic(cls, required_ratio: float) -> "CoverageTest": ...
    @classmethod
    def new_ic_with_id(cls, id: str, required_ratio: float) -> "CoverageTest": ...
    def id(self) -> str: ...
    def required_level(self) -> float: ...
    @classmethod
    def from_dict(cls, data: Any) -> "CoverageTest": ...
    def to_dict(self) -> Any: ...
    def __repr__(self) -> str: ...

class DiversionRule:
    def __init__(
        self, id: str, source_tier_id: str, target_tier_id: str, condition_json: str, priority: int
    ) -> None: ...
    @classmethod
    def on_test_failure(
        cls, id: str, source_tier_id: str, target_tier_id: str, test_id: str, priority: int
    ) -> "DiversionRule": ...
    @property
    def rule_id(self) -> str: ...
    @property
    def source_tier_id(self) -> str: ...
    @property
    def target_tier_id(self) -> str: ...
    @property
    def priority(self) -> int: ...
    @property
    def condition(self) -> str: ...
    def is_active(self, test_results: dict[str, bool]) -> bool: ...
    @classmethod
    def from_dict(cls, data: Any) -> "DiversionRule": ...
    def to_dict(self) -> Any: ...
    def __repr__(self) -> str: ...

class DiversionEngine:
    def __init__(self) -> None: ...
    def add_rule(self, rule: DiversionRule) -> "DiversionEngine": ...
    def validate(self) -> None: ...
    def get_active_diversions(self, test_results: dict[str, bool]) -> dict[str, str]: ...
    @property
    def rule_count(self) -> int: ...
    @classmethod
    def from_dict(cls, data: Any) -> "DiversionEngine": ...
    def to_dict(self) -> Any: ...
    def __repr__(self) -> str: ...

__all__ = [
    "generate_cashflows",
    "generate_tranche_cashflows",
    "run_simulation",
    "execute_waterfall",
    "CoverageTest",
    "DiversionRule",
    "DiversionEngine",
]
