"""Structured credit deal configuration types."""

from __future__ import annotations
from datetime import date
from typing import Any, Dict

class DefaultAssumptions:
    def __init__(
        self,
        base_cdr_annual: float | None = None,
        base_recovery_rate: float | None = None,
        base_cpr_annual: float | None = None,
        psa_speed: float | None = None,
        sda_speed: float | None = None,
        abs_speed_monthly: float | None = None,
    ) -> None: ...
    @classmethod
    def clo_standard(cls) -> "DefaultAssumptions": ...
    @classmethod
    def rmbs_standard(cls) -> "DefaultAssumptions": ...
    @classmethod
    def abs_auto_standard(cls) -> "DefaultAssumptions": ...
    @classmethod
    def cmbs_standard(cls) -> "DefaultAssumptions": ...
    @property
    def base_cdr_annual(self) -> float: ...
    @property
    def base_recovery_rate(self) -> float: ...
    @property
    def base_cpr_annual(self) -> float: ...
    @property
    def psa_speed(self) -> float | None: ...
    @property
    def sda_speed(self) -> float | None: ...
    @property
    def abs_speed_monthly(self) -> float | None: ...
    @property
    def cpr_by_asset_type(self) -> Dict[str, float]: ...
    @property
    def cdr_by_asset_type(self) -> Dict[str, float]: ...
    @property
    def recovery_by_asset_type(self) -> Dict[str, float]: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "DefaultAssumptions": ...
    def __repr__(self) -> str: ...

class DealFees:
    def __init__(
        self,
        trustee_fee_annual: Any,
        senior_mgmt_fee_bps: float = 0.0,
        subordinated_mgmt_fee_bps: float = 0.0,
        servicing_fee_bps: float = 0.0,
        master_servicer_fee_bps: float | None = None,
        special_servicer_fee_bps: float | None = None,
    ) -> None: ...
    @classmethod
    def clo_standard(cls, currency: str = "USD") -> "DealFees": ...
    @classmethod
    def abs_standard(cls, currency: str = "USD") -> "DealFees": ...
    @classmethod
    def cmbs_standard(cls, currency: str = "USD") -> "DealFees": ...
    @classmethod
    def rmbs_standard(cls, currency: str = "USD") -> "DealFees": ...
    @property
    def trustee_fee_annual(self) -> Any: ...
    @property
    def senior_mgmt_fee_bps(self) -> float: ...
    @property
    def subordinated_mgmt_fee_bps(self) -> float: ...
    @property
    def servicing_fee_bps(self) -> float: ...
    @property
    def master_servicer_fee_bps(self) -> float | None: ...
    @property
    def special_servicer_fee_bps(self) -> float | None: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "DealFees": ...
    def __repr__(self) -> str: ...

class DealDates:
    def __init__(
        self,
        closing_date: date,
        first_payment_date: date,
        maturity: date,
        frequency: Any | None = None,
    ) -> None: ...
    def with_reinvestment_end(self, date: date) -> "DealDates": ...
    @property
    def closing_date(self) -> date: ...
    @property
    def first_payment_date(self) -> date: ...
    @property
    def reinvestment_end_date(self) -> date | None: ...
    @property
    def maturity(self) -> date: ...
    @property
    def frequency(self) -> str: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "DealDates": ...
    def __repr__(self) -> str: ...

class CoverageTestConfig:
    def __init__(self) -> None: ...
    def add_oc_test(self, tranche_id: str, trigger_level: float) -> "CoverageTestConfig": ...
    def add_ic_test(self, tranche_id: str, trigger_level: float) -> "CoverageTestConfig": ...
    @property
    def oc_triggers(self) -> Dict[str, float]: ...
    @property
    def ic_triggers(self) -> Dict[str, float]: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "CoverageTestConfig": ...
    def __repr__(self) -> str: ...

class MarketConditions:
    def __init__(self, refi_rate: float = 0.0) -> None: ...
    @property
    def refi_rate(self) -> float: ...
    @property
    def original_rate(self) -> float | None: ...
    @property
    def hpa(self) -> float | None: ...
    @property
    def unemployment(self) -> float | None: ...
    @property
    def seasonal_factor(self) -> float | None: ...
    @property
    def custom_factors(self) -> Dict[str, float]: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "MarketConditions": ...
    def __repr__(self) -> str: ...

class CreditFactors:
    def __init__(self) -> None: ...
    @property
    def credit_score(self) -> int | None: ...
    @property
    def dti(self) -> float | None: ...
    @property
    def ltv(self) -> float | None: ...
    @property
    def delinquency_days(self) -> int: ...
    @property
    def unemployment_rate(self) -> float | None: ...
    @property
    def custom_factors(self) -> Dict[str, float]: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "CreditFactors": ...
    def __repr__(self) -> str: ...

class DealMetadata:
    def __init__(self) -> None: ...
    @property
    def manager_id(self) -> str | None: ...
    @property
    def servicer_id(self) -> str | None: ...
    @property
    def master_servicer_id(self) -> str | None: ...
    @property
    def special_servicer_id(self) -> str | None: ...
    @property
    def trustee_id(self) -> str | None: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "DealMetadata": ...
    def __repr__(self) -> str: ...

class DealOverrides:
    def __init__(self) -> None: ...
    @property
    def cpr_annual(self) -> float | None: ...
    @property
    def abs_speed(self) -> float | None: ...
    @property
    def psa_speed_multiplier(self) -> float | None: ...
    @property
    def cdr_annual(self) -> float | None: ...
    @property
    def sda_speed_multiplier(self) -> float | None: ...
    @property
    def recovery_rate(self) -> float | None: ...
    @property
    def recovery_lag_months(self) -> int | None: ...
    @property
    def reinvestment_price(self) -> float | None: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "DealOverrides": ...
    def __repr__(self) -> str: ...

class CreditModelConfig:
    def __init__(self) -> None: ...
    @property
    def prepayment_spec(self) -> Any: ...
    @property
    def default_spec(self) -> Any: ...
    @property
    def recovery_spec(self) -> Any: ...
    @property
    def stochastic_prepay_spec(self) -> Any | None: ...
    @property
    def stochastic_default_spec(self) -> Any | None: ...
    @property
    def correlation_structure(self) -> Any | None: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "CreditModelConfig": ...
    def __repr__(self) -> str: ...

class DealConfig:
    @classmethod
    def standard(cls, deal_type_str: str, dates: DealDates, currency: str = "USD") -> "DealConfig": ...
    @classmethod
    def clo_standard(cls, dates: DealDates, currency: str = "USD") -> "DealConfig": ...
    @classmethod
    def rmbs_standard(cls, dates: DealDates, currency: str = "USD") -> "DealConfig": ...
    @classmethod
    def abs_standard(cls, dates: DealDates, currency: str = "USD") -> "DealConfig": ...
    @classmethod
    def cmbs_standard(cls, dates: DealDates, currency: str = "USD") -> "DealConfig": ...
    @property
    def dates(self) -> DealDates: ...
    @property
    def fees(self) -> DealFees: ...
    @property
    def coverage_tests(self) -> CoverageTestConfig: ...
    @property
    def default_assumptions(self) -> DefaultAssumptions: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "DealConfig": ...
    def __repr__(self) -> str: ...

__all__ = [
    "DefaultAssumptions",
    "DealFees",
    "DealDates",
    "CoverageTestConfig",
    "MarketConditions",
    "CreditFactors",
    "DealMetadata",
    "DealOverrides",
    "CreditModelConfig",
    "DealConfig",
]
