"""Stochastic pricing types for structured credit."""

from __future__ import annotations
from typing import Any

class PricingMode:
    @classmethod
    def tree(cls) -> "PricingMode": ...
    @classmethod
    def monte_carlo(cls, num_paths: int = 10000, antithetic: bool = True) -> "PricingMode": ...
    @classmethod
    def hybrid(cls, tree_periods: int = 12, mc_paths: int = 5000) -> "PricingMode": ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "PricingMode": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class CorrelationStructure:
    @classmethod
    def flat(cls, asset_corr: float, prepay_default_corr: float = 0.3) -> "CorrelationStructure": ...
    @classmethod
    def sectored(cls, intra: float, inter: float, prepay_default: float = 0.3) -> "CorrelationStructure": ...
    @classmethod
    def matrix(cls, correlations: list[float], labels: list[str]) -> "CorrelationStructure": ...
    @classmethod
    def rmbs_standard(cls) -> "CorrelationStructure": ...
    @classmethod
    def clo_standard(cls) -> "CorrelationStructure": ...
    @classmethod
    def cmbs_standard(cls) -> "CorrelationStructure": ...
    @classmethod
    def abs_auto_standard(cls) -> "CorrelationStructure": ...
    def asset_correlation(self) -> float: ...
    def validate(self) -> None: ...
    def bump_asset(self, delta: float) -> "CorrelationStructure": ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "CorrelationStructure": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class StochasticDefaultSpec:
    @classmethod
    def deterministic(cls, spec_dict: Any) -> "StochasticDefaultSpec": ...
    @classmethod
    def gaussian_copula(cls, base_cdr: float, correlation: float = 0.3) -> "StochasticDefaultSpec": ...
    @classmethod
    def factor_correlated(
        cls, base_spec_dict: Any, factor_loading: float = 0.3, cdr_volatility: float = 0.5
    ) -> "StochasticDefaultSpec": ...
    @classmethod
    def rmbs_standard(cls) -> "StochasticDefaultSpec": ...
    @classmethod
    def clo_standard(cls) -> "StochasticDefaultSpec": ...
    def is_stochastic(self) -> bool: ...
    def base_rate(self) -> float: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "StochasticDefaultSpec": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class StochasticPrepaySpec:
    @classmethod
    def deterministic(cls, spec_dict: Any) -> "StochasticPrepaySpec": ...
    @classmethod
    def factor_correlated(
        cls, base_spec_dict: Any, factor_loading: float = 0.3, cpr_volatility: float = 0.3
    ) -> "StochasticPrepaySpec": ...
    @classmethod
    def richard_roll(
        cls, base_cpr: float, refi_sensitivity: float = 0.5, pool_coupon: float = 0.06
    ) -> "StochasticPrepaySpec": ...
    @classmethod
    def regime_switching(
        cls, low_cpr: float, high_cpr: float, transition_up: float = 0.1, transition_down: float = 0.2
    ) -> "StochasticPrepaySpec": ...
    @classmethod
    def rmbs_agency(cls, pool_coupon: float = 0.045) -> "StochasticPrepaySpec": ...
    @classmethod
    def clo_standard(cls) -> "StochasticPrepaySpec": ...
    def is_stochastic(self) -> bool: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "StochasticPrepaySpec": ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class StochasticPricingResult:
    @property
    def npv(self) -> Any: ...
    @property
    def clean_price(self) -> float: ...
    @property
    def dirty_price(self) -> float: ...
    @property
    def expected_loss(self) -> Any: ...
    @property
    def unexpected_loss(self) -> Any: ...
    @property
    def expected_shortfall(self) -> Any: ...
    @property
    def es_confidence(self) -> float: ...
    @property
    def num_paths(self) -> int: ...
    @property
    def pricing_mode(self) -> str: ...
    @property
    def tranche_results(self) -> list["TranchePricingResult"]: ...
    def loss_ratio(self) -> float: ...
    def __repr__(self) -> str: ...

class TranchePricingResult:
    @property
    def tranche_id(self) -> str: ...
    @property
    def seniority(self) -> str: ...
    @property
    def npv(self) -> Any: ...
    @property
    def expected_loss(self) -> Any: ...
    @property
    def unexpected_loss(self) -> Any: ...
    @property
    def expected_shortfall(self) -> Any: ...
    @property
    def attachment(self) -> float: ...
    @property
    def detachment(self) -> float: ...
    @property
    def average_life(self) -> float: ...
    @property
    def spread(self) -> float: ...
    @property
    def credit_duration(self) -> float: ...
    def thickness(self) -> float: ...
    def loss_multiple(self) -> float: ...
    def __repr__(self) -> str: ...

__all__ = [
    "PricingMode",
    "CorrelationStructure",
    "StochasticDefaultSpec",
    "StochasticPrepaySpec",
    "StochasticPricingResult",
    "TranchePricingResult",
]
