"""Structured credit tranche types."""

from __future__ import annotations
from datetime import date
from typing import Any

class CoverageTrigger:
    def __init__(self, trigger_level: float, consequence: str) -> None: ...
    def with_cure_level(self, cure_level: float) -> "CoverageTrigger": ...
    def is_breached(self, current_level: float) -> bool: ...
    def is_cured(self, current_level: float) -> bool: ...
    @property
    def trigger_level(self) -> float: ...
    @property
    def cure_level(self) -> float | None: ...
    @property
    def consequence(self) -> str: ...
    def __repr__(self) -> str: ...

class CreditEnhancement:
    def __init__(
        self,
        subordination_amount: float,
        oc_amount: float,
        reserve_amount: float,
        currency: str,
        excess_spread: float = 0.0,
        cash_trap_active: bool = False,
    ) -> None: ...
    @property
    def subordination(self) -> Any: ...
    @property
    def overcollateralization(self) -> Any: ...
    @property
    def reserve_account(self) -> Any: ...
    @property
    def excess_spread(self) -> float: ...
    @property
    def cash_trap_active(self) -> bool: ...
    def __repr__(self) -> str: ...

class Tranche:
    @classmethod
    def from_dict(cls, data: Any) -> "Tranche": ...
    def to_dict(self) -> Any: ...
    @classmethod
    def builder(cls) -> "TrancheBuilder": ...
    def thickness(self) -> float: ...
    def is_first_loss(self) -> bool: ...
    def is_impaired(self, cumulative_loss_pct: float) -> bool: ...
    def loss_allocation(self, cumulative_loss_pct: float, total_pool_balance_amount: float, currency: str) -> Any: ...
    def current_balance_after_losses(
        self, cumulative_loss_pct: float, total_pool_balance_amount: float, currency: str
    ) -> Any: ...
    def with_rating(self, rating_str: str) -> "Tranche": ...
    def revolving(self) -> "Tranche": ...
    @property
    def tranche_id(self) -> str: ...
    @property
    def attachment_point(self) -> float: ...
    @property
    def detachment_point(self) -> float: ...
    @property
    def seniority(self) -> str: ...
    @property
    def rating(self) -> str | None: ...
    @property
    def original_balance(self) -> Any: ...
    @property
    def current_balance(self) -> Any: ...
    @property
    def maturity(self) -> date: ...
    @property
    def payment_priority(self) -> int: ...
    @property
    def is_revolving(self) -> bool: ...
    @property
    def day_count(self) -> str: ...
    @property
    def coupon_rate(self) -> float: ...
    @property
    def target_balance(self) -> Any | None: ...
    @property
    def oc_trigger(self) -> "CoverageTrigger | None": ...
    @property
    def ic_trigger(self) -> "CoverageTrigger | None": ...
    @property
    def credit_enhancement(self) -> "CreditEnhancement": ...
    @property
    def frequency(self) -> str: ...
    @property
    def deferred_interest(self) -> Any: ...
    @property
    def can_reinvest(self) -> bool: ...
    @property
    def expected_maturity(self) -> date | None: ...
    def with_oc_trigger(self, trigger: "CoverageTrigger") -> "Tranche": ...
    def with_ic_trigger(self, trigger: "CoverageTrigger") -> "Tranche": ...
    def with_expected_maturity(self, date: date) -> "Tranche": ...
    def __repr__(self) -> str: ...

class TrancheBuilder:
    def __init__(self) -> None: ...
    def id(self, name: str) -> "TrancheBuilder": ...
    def attachment_detachment(self, attachment: float, detachment: float) -> "TrancheBuilder": ...
    def seniority(self, seniority_str: str) -> "TrancheBuilder": ...
    def balance(self, amount: float, currency: str) -> "TrancheBuilder": ...
    def coupon_fixed(self, rate: float) -> "TrancheBuilder": ...
    def coupon_floating(self, spec_json: Any) -> "TrancheBuilder": ...
    def maturity(self, date: date) -> "TrancheBuilder": ...
    def rating(self, rating_str: str) -> "TrancheBuilder": ...
    def frequency(self, tenor_str: str) -> "TrancheBuilder": ...
    def day_count(self, dc_str: str) -> "TrancheBuilder": ...
    def build(self) -> Tranche: ...
    def __repr__(self) -> str: ...

class TrancheStructure:
    def __init__(self, tranches: list[Tranche]) -> None: ...
    @classmethod
    def from_dict(cls, data: Any) -> "TrancheStructure": ...
    def to_dict(self) -> Any: ...
    def by_seniority(self, seniority: str) -> list[Tranche]: ...
    def senior_to(self, tranche_id: str) -> list[Tranche]: ...
    def senior_balance(self, tranche_id: str) -> Any: ...
    def subordination_amount(self, tranche_id: str) -> Any: ...
    @property
    def tranche_count(self) -> int: ...
    @property
    def total_size(self) -> Any: ...
    @property
    def tranches(self) -> list[Tranche]: ...
    def __repr__(self) -> str: ...

__all__ = [
    "CoverageTrigger",
    "CreditEnhancement",
    "Tranche",
    "TrancheBuilder",
    "TrancheStructure",
]
