"""Structured credit utility functions."""

from __future__ import annotations

def cpr_to_smm(cpr: float) -> float: ...
def smm_to_cpr(smm: float) -> float: ...
def cdr_to_mdr(cdr: float) -> float: ...
def mdr_to_cdr(mdr: float) -> float: ...
def psa_to_cpr(psa_speed: float, month: int) -> float: ...
def validate_waterfall(waterfall_json: str) -> list[str]: ...
def is_valid_waterfall(waterfall_json: str) -> bool: ...

__all__ = [
    "cpr_to_smm",
    "smm_to_cpr",
    "cdr_to_mdr",
    "mdr_to_cdr",
    "psa_to_cpr",
    "validate_waterfall",
    "is_valid_waterfall",
]
