"""Structured credit waterfall engine bindings."""

from __future__ import annotations
from typing import Any
from enum import IntEnum

class AllocationMode(IntEnum):
    Sequential = 0
    ProRata = 1

class PaymentType(IntEnum):
    Fee = 0
    Interest = 1
    Principal = 2
    Residual = 3

class WaterfallTier:
    def __init__(self, tier_id: str, priority: int, payment_type: PaymentType) -> None: ...
    def add_recipient(self, recipient_id: str, recipient_type: str, calculation: str) -> "WaterfallTier": ...
    def add_fixed_fee(self, recipient_id: str, provider_name: str, amount: float, currency: str) -> "WaterfallTier": ...
    def add_tranche_interest(self, recipient_id: str, tranche_id: str) -> "WaterfallTier": ...
    def add_tranche_principal(self, recipient_id: str, tranche_id: str) -> "WaterfallTier": ...
    def set_allocation_mode(self, mode: AllocationMode) -> "WaterfallTier": ...
    def set_divertible(self, divertible: bool) -> "WaterfallTier": ...
    @property
    def tier_id(self) -> str: ...
    @property
    def priority(self) -> int: ...
    @property
    def recipient_count(self) -> int: ...
    def __repr__(self) -> str: ...

class Recipient:
    def __init__(self, id: str, recipient_type_json: str, calculation_json: str) -> None: ...
    def with_weight(self, weight: float) -> "Recipient": ...
    @classmethod
    def fixed_fee(cls, id: str, provider_name: str, amount: float, currency: str) -> "Recipient": ...
    @classmethod
    def tranche_interest(cls, id: str, tranche_id: str) -> "Recipient": ...
    @classmethod
    def tranche_principal(cls, id: str, tranche_id: str, target_balance: float | None = None) -> "Recipient": ...
    @property
    def recipient_id(self) -> str: ...
    @property
    def weight(self) -> float | None: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "Recipient": ...
    def __repr__(self) -> str: ...

class WaterfallCoverageTrigger:
    def __init__(self, tranche_id: str, oc_trigger: float | None = None, ic_trigger: float | None = None) -> None: ...
    @property
    def tranche_id(self) -> str: ...
    @property
    def oc_trigger(self) -> float | None: ...
    @property
    def ic_trigger(self) -> float | None: ...
    def __repr__(self) -> str: ...

class CoverageTestRules:
    def __init__(self, par_value_threshold: float | None = None) -> None: ...
    @classmethod
    def empty(cls) -> "CoverageTestRules": ...
    def is_empty(self) -> bool: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "CoverageTestRules": ...
    def __repr__(self) -> str: ...

class Waterfall:
    def __init__(self, currency: str = "USD") -> None: ...
    @classmethod
    def builder(cls, currency: str = "USD") -> "WaterfallBuilder": ...
    def add_tier(self, tier: WaterfallTier) -> "Waterfall": ...
    def add_coverage_trigger(self, trigger: WaterfallCoverageTrigger) -> "Waterfall": ...
    def with_coverage_rules(self, rules: CoverageTestRules) -> "Waterfall": ...
    @classmethod
    def standard_sequential(cls, currency: str, tranches: Any, fee_recipients: list[Recipient]) -> "Waterfall": ...
    @property
    def tier_count(self) -> int: ...
    @property
    def base_currency(self) -> str: ...
    def to_dict(self) -> Any: ...
    @classmethod
    def from_dict(cls, data: Any) -> "Waterfall": ...
    def __repr__(self) -> str: ...

class WaterfallBuilder:
    def __init__(self, currency: str = "USD") -> None: ...
    def add_tier(self, tier: WaterfallTier) -> "WaterfallBuilder": ...
    def add_coverage_trigger(self, trigger: WaterfallCoverageTrigger) -> "WaterfallBuilder": ...
    def coverage_rules(self, rules: CoverageTestRules) -> "WaterfallBuilder": ...
    def build(self) -> Waterfall: ...
    def __repr__(self) -> str: ...

__all__ = [
    "AllocationMode",
    "PaymentType",
    "WaterfallTier",
    "Recipient",
    "WaterfallCoverageTrigger",
    "CoverageTestRules",
    "Waterfall",
    "WaterfallBuilder",
]
