//! Euler discretization for the Cheyette + rough vol process.
//!
//! Advances the two-dimensional Markov state (x, y) of the Cheyette model
//! with stochastic volatility driven by a Volterra fractional Brownian motion.
//!
//! # Noise Layout
//!
//! The discretization expects `z` with two entries:
//!
//! - `z[0]` — independent standard normal for the uncorrelated rate component
//! - `z[1]` — fBM increment dB_H for the current step (pre-generated by the
//!   engine's fractional noise integration)
//!
//! # Rate–Vol Correlation
//!
//! Rate noise is correlated with the fBM driver by normalizing the fBM
//! increment to unit variance:
//!
//! ```text
//! Z_corr = ρ (dB_H / dt^H) + √(1 − ρ²) Z_indep
//! dW_rate = Z_corr √dt
//! ```
//!
//! where `dt^H = √Var(dB_H)` for stationary fBM increments.
//!
//! # Euler Steps
//!
//! ```text
//! σ(t) = σ₀(t+dt) · exp(η · W̃_H(t) − ½ · η² · (t+dt)^{2H})
//! x(t+dt) = x(t) + [y(t) − κ·x(t)] · dt + σ(t) · √dt · Z_corr
//! y(t+dt) = y(t) + [σ(t)² − 2κ·y(t)] · dt
//! ```
//!
//! The y update is deterministic given σ(t).
//!
//! # Work Buffer
//!
//! `work[0]` stores the running accumulated Volterra integral W̃_H(t). The
//! engine must zero the work buffer before each new path (see
//! [`simulate_path_fractional`](crate::engine_fractional::simulate_path_fractional)).
//!
//! # References
//!
//! - Cheyette, O. (1994). "Markov Representation of the Heath-Jarrow-Morton
//!   Model." Working paper.
//! - Andersen, L. & Piterbarg, V. (2010). *Interest Rate Modeling*, Volume II,
//!   Chapter 12.
//! - Bayer, C., Friz, P. & Gatheral, J. (2016). "Pricing under rough
//!   volatility." *Quantitative Finance*, 16(6), 887–904.

use super::super::process::cheyette_rough::CheyetteRoughVolProcess;
use super::super::traits::Discretization;
use finstack_core::math::fractional::HurstExponent;

/// Euler discretization for the Cheyette + rough vol process.
///
/// This scheme reconstructs the stochastic volatility from the base vol curve
/// and the accumulated fractional Brownian motion path at each time step, then
/// applies an Euler–Maruyama update to both the rate state x and the
/// deterministic variance accumulator y.
///
/// See the [module-level documentation](self) for details on noise layout,
/// correlation handling, and the work buffer.
#[derive(Debug, Clone)]
pub struct CheyetteRoughEuler {
    /// Hurst exponent for the fBM generator.
    hurst: HurstExponent,
}

impl CheyetteRoughEuler {
    /// Create a new Cheyette rough vol Euler discretization.
    ///
    /// # Arguments
    ///
    /// * `hurst` - Validated Hurst exponent, must match the process.
    pub fn new(hurst: HurstExponent) -> Self {
        Self { hurst }
    }

    /// Return the stored Hurst exponent.
    pub fn hurst(&self) -> HurstExponent {
        self.hurst
    }
}

impl Discretization<CheyetteRoughVolProcess> for CheyetteRoughEuler {
    fn step(
        &self,
        process: &CheyetteRoughVolProcess,
        t: f64,
        dt: f64,
        x: &mut [f64],
        z: &[f64],
        work: &mut [f64],
    ) {
        let p = process.params();
        let h = p.hurst.value();
        let eta = p.eta;
        let rho = p.rho;

        let z_indep = z[0]; // Independent standard normal
        let db_h = z[1]; // fBM increment for this step (pre-generated)

        // Accumulate Volterra integral: W̃_H(t) += dB_H
        work[0] += db_h;

        // Reconstruct stochastic volatility:
        //   σ(t) = σ₀(t+dt) · exp(η · W̃_H(t) − ½ · η² · (t+dt)^{2H})
        let two_h = 2.0 * h;
        let t_next = t + dt;
        let sigma_base = p.sigma_base_value(t_next);
        let exponent = eta * work[0] - 0.5 * eta * eta * t_next.powf(two_h);
        let sigma_t = (sigma_base * exponent.exp()).max(0.0);

        // Correlate rate noise with fBM driver.
        // Normalize fBM increment to unit variance: dB_H has std dev = dt^H.
        let sigma_h = dt.powf(h);
        let z_correlated = if sigma_h > 1e-15 {
            rho * (db_h / sigma_h) + (1.0 - rho * rho).max(0.0).sqrt() * z_indep
        } else {
            z_indep
        };

        let x_cur = x[0];
        let y_cur = x[1];

        // Euler step for x: dx = [y − κ·x] dt + σ(t) · √dt · Z_corr
        x[0] += (y_cur - p.kappa * x_cur) * dt + sigma_t * dt.sqrt() * z_correlated;

        // Deterministic step for y: dy = [σ(t)² − 2κ·y] dt
        x[1] += (sigma_t * sigma_t - 2.0 * p.kappa * y_cur) * dt;
    }

    fn work_size(&self, _process: &CheyetteRoughVolProcess) -> usize {
        1 // work[0] = accumulated W̃_H(t)
    }
}

#[cfg(test)]
mod tests {
    use super::super::super::process::cheyette_rough::{
        CheyetteRoughVolParams, CheyetteRoughVolProcess,
    };
    use super::*;
    use finstack_core::market_data::term_structures::ForwardVarianceCurve;
    use finstack_core::math::fractional::HurstExponent;

    fn make_process() -> CheyetteRoughVolProcess {
        let sigma_base = ForwardVarianceCurve::flat(0.005).expect("valid flat curve");
        let hurst = HurstExponent::new(0.1).expect("valid hurst");
        let phi_points = vec![(0.0, 0.02), (10.0, 0.03)];
        let params = CheyetteRoughVolParams::new(0.03, sigma_base, hurst, 1.5, -0.3, &phi_points)
            .expect("valid");
        CheyetteRoughVolProcess::new(params)
    }

    #[test]
    fn test_single_step_zero_shocks() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![0.0, 0.0];
        let z = vec![0.0, 0.0]; // No shocks
        let mut work = vec![0.0];

        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

        // With x=0, y=0, and zero shocks:
        // dx = [0 - 0.03*0]*dt + sigma(t)*0 = 0
        // dy = [sigma(t)^2 - 0]*dt > 0 (sigma(t) > 0 even with zero fBM)
        assert!(
            x[0].abs() < 1e-10,
            "x should remain near zero with zero shocks: got {}",
            x[0]
        );
        assert!(
            x[1] > 0.0,
            "y should increase due to sigma(t)^2 term: got {}",
            x[1]
        );
    }

    #[test]
    fn test_single_step_deterministic() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));
        let p = process.params();

        let dt = 0.01_f64;
        let h = p.hurst.value();
        let eta = p.eta;
        let kappa = p.kappa;
        let rho = p.rho;

        let z_indep = 0.5;
        let db_h = 0.02;
        let x0 = 0.001;
        let y0 = 0.0001;

        let mut x = vec![x0, y0];
        let z = vec![z_indep, db_h];
        let mut work = vec![0.0];

        disc.step(&process, 0.0, dt, &mut x, &z, &mut work);

        // Manually compute expected result
        let w_h = db_h;
        let two_h = 2.0 * h;
        let t_next = dt;
        let sigma_base = p.sigma_base_value(t_next);
        let exponent = eta * w_h - 0.5 * eta * eta * t_next.powf(two_h);
        let sigma_t = (sigma_base * exponent.exp()).max(0.0);

        let sigma_h = dt.powf(h);
        let z_corr = rho * (db_h / sigma_h) + (1.0 - rho * rho).max(0.0).sqrt() * z_indep;

        let expected_x = x0 + (y0 - kappa * x0) * dt + sigma_t * dt.sqrt() * z_corr;
        let expected_y = y0 + (sigma_t * sigma_t - 2.0 * kappa * y0) * dt;

        assert!(
            (x[0] - expected_x).abs() < 1e-14,
            "x step mismatch: got {}, expected {}",
            x[0],
            expected_x
        );
        assert!(
            (x[1] - expected_y).abs() < 1e-14,
            "y step mismatch: got {}, expected {}",
            x[1],
            expected_y
        );
    }

    #[test]
    fn test_sigma_reconstruction() {
        let sigma_base_val = 0.005_f64;
        let h = 0.1_f64;
        let eta = 1.5_f64;
        let t = 0.5_f64;
        let w_h = 0.03_f64;

        // σ(t) = σ₀(t) · exp(η · W̃_H − ½ · η² · t^{2H})
        let two_h = 2.0 * h;
        let exponent = eta * w_h - 0.5 * eta * eta * t.powf(two_h);
        let sigma = sigma_base_val * exponent.exp();

        // With positive w_h, sigma should be above the base
        assert!(
            sigma > 0.0,
            "Reconstructed sigma should be positive: {sigma}"
        );

        // With zero accumulation, sigma should be below base due to convexity correction
        let exponent_zero = -0.5 * eta * eta * t.powf(two_h);
        let sigma_zero = sigma_base_val * exponent_zero.exp();
        assert!(sigma_zero > 0.0);
        assert!(
            sigma_zero < sigma_base_val,
            "Sigma should be below base level due to convexity correction"
        );
    }

    #[test]
    fn test_y_state_is_deterministic_given_sigma() {
        // y update: dy = [σ(t)² − 2κ·y] dt
        // This should be fully determined by sigma(t), y, kappa, and dt.
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let y0 = 0.0001_f64;
        let dt = 0.01_f64;

        // Run with different z_indep values but same db_h — y should be identical
        let db_h = 0.02_f64;

        let mut x1 = vec![0.0, y0];
        let z1 = vec![0.5, db_h];
        let mut work1 = vec![0.0];
        disc.step(&process, 0.0, dt, &mut x1, &z1, &mut work1);

        let mut x2 = vec![0.0, y0];
        let z2 = vec![-1.5, db_h];
        let mut work2 = vec![0.0];
        disc.step(&process, 0.0, dt, &mut x2, &z2, &mut work2);

        // y should be identical because it depends only on sigma(t) (via db_h) and y
        assert!(
            (x1[1] - x2[1]).abs() < 1e-15,
            "y should be deterministic given sigma: {} vs {}",
            x1[1],
            x2[1]
        );

        // x should differ because z_indep affects the rate noise
        assert!(
            (x1[0] - x2[0]).abs() > 1e-10,
            "x should differ for different z_indep values"
        );
    }

    #[test]
    fn test_work_buffer_reset_across_paths() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![0.0, 0.0];
        let z = vec![0.0, 0.05]; // Non-zero fBM increment
        let mut work = vec![0.0];

        // Simulate a few steps of path 1
        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);
        disc.step(&process, 0.01, 0.01, &mut x, &z, &mut work);

        let w_h_after_path1 = work[0];
        assert!(
            w_h_after_path1.abs() > 1e-15,
            "Work buffer should accumulate fBM increments"
        );

        // Start path 2 — engine zeros work buffer before each path
        x[0] = 0.0;
        x[1] = 0.0;
        work[0] = 0.0;
        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

        // After a single step from t=0, work[0] should be exactly the single
        // fBM increment (accumulator was zeroed by engine before path)
        assert!(
            (work[0] - 0.05).abs() < 1e-15,
            "Work buffer should reset at path start: got {}",
            work[0]
        );
    }

    #[test]
    fn test_work_size() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        assert_eq!(disc.work_size(&process), 1);
    }

    #[test]
    fn test_multiple_steps_no_nan() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![0.0, 0.0];
        let mut work = vec![0.0];

        let shocks = [
            (0.3, 0.01),
            (-0.5, -0.02),
            (1.2, 0.03),
            (-0.8, -0.01),
            (0.1, 0.005),
        ];

        let dt = 0.01;
        for (i, &(z0, z1)) in shocks.iter().enumerate() {
            let t = i as f64 * dt;
            let z = vec![z0, z1];
            disc.step(&process, t, dt, &mut x, &z, &mut work);

            assert!(
                x[0].is_finite(),
                "x became non-finite at step {i}: {}",
                x[0]
            );
            assert!(
                x[1].is_finite(),
                "y became non-finite at step {i}: {}",
                x[1]
            );
        }
    }
}
