//! Euler discretization for the rBergomi process.
//!
//! Operates in log-spot for numerical stability. The variance is reconstructed
//! from the forward variance curve and accumulated fBM path at each step.
//!
//! # Noise Layout
//!
//! The discretization expects `z` with two entries:
//!
//! - `z[0]` — independent standard normal for the uncorrelated spot component
//! - `z[1]` — fBM increment dB_H for the current step (pre-generated by the
//!   engine's fractional noise integration)
//!
//! # Spot–Vol Correlation
//!
//! Spot noise is correlated with the fBM driver by normalizing the fBM
//! increment to unit variance:
//!
//! ```text
//! Z_corr = ρ (dB_H / dt^H) + √(1 − ρ²) Z_indep
//! dW_spot = Z_corr √dt
//! ```
//!
//! where `dt^H = √Var(dB_H)` for stationary fBM increments. This is the
//! standard approach in rBergomi implementations (McCrickerd & Pakkanen 2018).
//!
//! # Work Buffer
//!
//! `work[0]` stores the running accumulated Volterra integral Ŵ_H(t). The
//! engine must zero the work buffer before each new path (see
//! [`simulate_path_fractional`](crate::engine_fractional::simulate_path_fractional)).
//!
//! # References
//!
//! - Bayer, C., Friz, P., & Gatheral, J. (2016). "Pricing under rough
//!   volatility." *Quantitative Finance*, 16(6), 887–904.
//! - McCrickerd, R. & Pakkanen, M. S. (2018). "Turbocharging Monte Carlo
//!   pricing for the rough Bergomi model." *Quantitative Finance*, 18(11),
//!   1877–1886.

use super::super::process::rough_bergomi::RoughBergomiProcess;
use super::super::traits::Discretization;
use finstack_core::math::fractional::HurstExponent;

/// Euler discretization for the rBergomi process.
///
/// This scheme reconstructs the variance from the forward variance curve and
/// the accumulated fractional Brownian motion path at each time step. It is
/// the only supported discretization for [`RoughBergomiProcess`] because the
/// non-Markovian variance dynamics cannot be expressed through the standard
/// `drift`/`diffusion` interface.
///
/// See the [module-level documentation](self) for details on noise layout,
/// correlation handling, and the work buffer.
#[derive(Debug, Clone)]
pub struct RoughBergomiEuler {
    /// Hurst exponent for the fBM generator.
    hurst: HurstExponent,
}

impl RoughBergomiEuler {
    /// Create a new rBergomi Euler discretization.
    ///
    /// # Arguments
    ///
    /// * `hurst` - Validated Hurst exponent, must match the process.
    pub fn new(hurst: HurstExponent) -> Self {
        Self { hurst }
    }

    /// Return the stored Hurst exponent.
    pub fn hurst(&self) -> HurstExponent {
        self.hurst
    }
}

impl Discretization<RoughBergomiProcess> for RoughBergomiEuler {
    fn step(
        &self,
        process: &RoughBergomiProcess,
        t: f64,
        dt: f64,
        x: &mut [f64],
        z: &[f64],
        work: &mut [f64],
    ) {
        let params = process.params();
        let h = params.hurst.value();
        let eta = params.eta;
        let rho = params.rho;

        let z_indep = z[0]; // Independent standard normal
        let db_h = z[1]; // fBM increment for this step (pre-generated)

        // Accumulate Volterra integral: Ŵ_H(t) += dB_H
        work[0] += db_h;

        // Reconstruct variance:
        //   V_t = ξ₀(t + dt) exp(η Ŵ_H(t) − ½ η² (t + dt)^{2H})
        let two_h = 2.0 * h;
        let t_next = t + dt;
        let exponent = eta * work[0] - 0.5 * eta * eta * t_next.powf(two_h);
        let v_t = (params.xi.value(t_next) * exponent.exp()).max(0.0);

        // Correlate spot noise with fBM driver.
        // Normalize fBM increment to unit variance: dB_H has std dev = dt^H.
        let sigma_h = dt.powf(h);
        let z_correlated = if sigma_h > 1e-15 {
            rho * (db_h / sigma_h) + (1.0 - rho * rho).max(0.0).sqrt() * z_indep
        } else {
            z_indep
        };

        // Log-spot update:
        //   S_{t+dt} = S_t exp((r − q − ½V_t) dt + √V_t √dt Z_corr)
        let drift = (params.r - params.q - 0.5 * v_t) * dt;
        let diffusion = v_t.sqrt() * dt.sqrt() * z_correlated;
        x[0] *= (drift + diffusion).exp();
    }

    fn work_size(&self, _process: &RoughBergomiProcess) -> usize {
        1 // work[0] = accumulated Ŵ_H(t)
    }
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic)]
mod tests {
    use super::super::super::process::rough_bergomi::{RoughBergomiParams, RoughBergomiProcess};
    use super::*;
    use finstack_core::market_data::term_structures::ForwardVarianceCurve;
    use finstack_core::math::fractional::HurstExponent;

    fn make_process() -> RoughBergomiProcess {
        let xi = ForwardVarianceCurve::flat(0.04).expect("valid flat curve");
        let hurst = HurstExponent::new(0.1).expect("valid hurst");
        let params = RoughBergomiParams::new(0.05, 0.02, hurst, 1.9, -0.9, xi).expect("valid");
        RoughBergomiProcess::new(params)
    }

    #[test]
    fn test_single_step_zero_shocks() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![100.0];
        let z = vec![0.0, 0.0]; // No shocks
        let mut work = vec![0.0];

        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

        // Spot should remain close to initial with small drift
        assert!(x[0] > 0.0, "Spot must remain positive");
        assert!(
            (x[0] - 100.0).abs() < 5.0,
            "Spot should stay near 100 with zero shocks: got {}",
            x[0]
        );
    }

    #[test]
    fn test_single_step_deterministic() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));
        let params = process.params();

        let s0 = 100.0;
        let dt = 0.01_f64;
        let h = params.hurst.value();
        let eta = params.eta;
        let r = params.r;
        let q = params.q;
        let rho = params.rho;

        let z_indep = 0.5;
        let db_h = 0.02;

        let mut x = vec![s0];
        let z = vec![z_indep, db_h];
        let mut work = vec![0.0];

        disc.step(&process, 0.0, dt, &mut x, &z, &mut work);

        // Manually compute expected result
        let w_h = db_h;
        let two_h = 2.0 * h;
        let t_next = dt;
        let exponent = eta * w_h - 0.5 * eta * eta * t_next.powf(two_h);
        let v = (params.xi.value(t_next) * exponent.exp()).max(0.0);

        let sigma_h = dt.powf(h);
        let z_corr = rho * (db_h / sigma_h) + (1.0 - rho * rho).max(0.0).sqrt() * z_indep;

        let drift = (r - q - 0.5 * v) * dt;
        let diff = v.sqrt() * dt.sqrt() * z_corr;
        let expected = s0 * (drift + diff).exp();

        assert!(
            (x[0] - expected).abs() < 1e-12,
            "Single step mismatch: got {}, expected {}",
            x[0],
            expected
        );
    }

    #[test]
    fn test_variance_reconstruction() {
        let xi = ForwardVarianceCurve::flat(0.04).expect("valid flat curve");
        let h = 0.1_f64;
        let eta = 1.9_f64;
        let t = 0.5_f64;
        let w_h = 0.03_f64;

        // V_t = ξ₀(t) exp(η Ŵ_H − ½ η² t^{2H})
        let two_h = 2.0 * h;
        let exponent = eta * w_h - 0.5 * eta * eta * t.powf(two_h);
        let v = xi.value(t) * exponent.exp();

        // With flat ξ₀ = 0.04 and small w_h, variance should be positive
        assert!(v > 0.0, "Reconstructed variance should be positive: {v}");

        // With zero accumulation, variance should equal ξ₀(t) * exp(-½η²t^{2H})
        let exponent_zero = -0.5 * eta * eta * t.powf(two_h);
        let v_zero = xi.value(t) * exponent_zero.exp();
        assert!(v_zero > 0.0);
        assert!(
            v_zero < 0.04,
            "Variance should be below flat level due to convexity correction"
        );
    }

    #[test]
    fn test_work_buffer_reset_across_paths() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![100.0];
        let z = vec![0.0, 0.05]; // Non-zero fBM increment
        let mut work = vec![0.0];

        // Simulate a few steps of path 1
        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);
        disc.step(&process, 0.01, 0.01, &mut x, &z, &mut work);

        let w_h_after_path1 = work[0];
        assert!(
            w_h_after_path1.abs() > 1e-15,
            "Work buffer should accumulate fBM increments"
        );

        // Start path 2 — engine zeros work buffer before each path
        x[0] = 100.0;
        work[0] = 0.0;
        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

        // After a single step from t=0, work[0] should be exactly the single
        // fBM increment (accumulator was zeroed by engine before path)
        assert!(
            (work[0] - 0.05).abs() < 1e-15,
            "Work buffer should reset at path start: got {}",
            work[0]
        );
    }

    #[test]
    fn test_spot_stays_positive_under_large_shocks() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        for &z_val in &[-3.0, -2.0, 2.0, 3.0] {
            let mut x = vec![100.0];
            let z = vec![z_val, z_val * 0.1];
            let mut work = vec![0.0];

            disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

            assert!(
                x[0] > 0.0,
                "Spot must remain positive with z={z_val}: got {}",
                x[0]
            );
        }
    }

    #[test]
    fn test_work_size() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        assert_eq!(disc.work_size(&process), 1);
    }
}
