"""Direct FX valuation instrument wrappers."""

from __future__ import annotations

from typing import Any

class _FxInstrument:
    def __init__(self, spec: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    @staticmethod
    def from_json(json: str) -> "_FxInstrument": ...
    def to_json(self) -> str: ...
    def price(self, market: Any, as_of: str, model: str = "default") -> str: ...
    def price_with_metrics(
        self,
        market: Any,
        as_of: str,
        model: str = "default",
        metrics: list[str] = ...,
        pricing_options: str | None = None,
    ) -> str: ...

class _FxOptionInstrument(_FxInstrument):
    def delta(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def gamma(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def vega(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def theta(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def rho(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def foreign_rho(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def vanna(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def volga(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def greeks(self, market: Any, as_of: str, model: str = "default") -> dict[str, float]: ...

class FxSpot(_FxInstrument): ...
class FxForward(_FxInstrument): ...
class FxSwap(_FxInstrument): ...
class Ndf(_FxInstrument): ...
class FxOption(_FxOptionInstrument): ...
class FxDigitalOption(_FxOptionInstrument): ...
class FxTouchOption(_FxOptionInstrument): ...
class FxBarrierOption(_FxOptionInstrument): ...
class FxVarianceSwap(_FxInstrument): ...
class QuantoOption(_FxOptionInstrument): ...

__all__: list[str]
