"""Commodity swaption instrument (builder-only API)."""

from __future__ import annotations
from typing import Self

from datetime import date

from ....core.currency import Currency
from ....core.dates.daycount import DayCount
from ...common import InstrumentType

class CommoditySwaptionBuilder:
    """Fluent builder returned by :meth:`CommoditySwaption.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def commodity_type(self, commodity_type: str) -> CommoditySwaptionBuilder: ...
    def ticker(self, ticker: str) -> CommoditySwaptionBuilder: ...
    def unit(self, unit: str) -> CommoditySwaptionBuilder: ...
    def currency(self, currency: str | Currency) -> CommoditySwaptionBuilder: ...
    def option_type(self, option_type: str) -> CommoditySwaptionBuilder: ...
    def expiry(self, expiry: date) -> CommoditySwaptionBuilder: ...
    def swap_start(self, swap_start: date) -> CommoditySwaptionBuilder: ...
    def swap_end(self, swap_end: date) -> CommoditySwaptionBuilder: ...
    def swap_frequency(self, swap_frequency: str) -> CommoditySwaptionBuilder: ...
    def fixed_price(self, fixed_price: float) -> CommoditySwaptionBuilder: ...
    def notional(self, notional: float) -> CommoditySwaptionBuilder: ...
    def forward_curve_id(self, curve_id: str) -> CommoditySwaptionBuilder: ...
    def discount_curve_id(self, curve_id: str) -> CommoditySwaptionBuilder: ...
    def vol_surface_id(self, curve_id: str) -> CommoditySwaptionBuilder: ...
    def calendar_id(self, calendar_id: str | None = ...) -> CommoditySwaptionBuilder: ...
    def bdc(self, bdc: str) -> CommoditySwaptionBuilder: ...
    def day_count(self, day_count: DayCount | str) -> CommoditySwaptionBuilder: ...
    def implied_volatility(self, implied_volatility: float | None = ...) -> CommoditySwaptionBuilder: ...
    def build(self) -> CommoditySwaption: ...

class CommoditySwaption:
    """Option to enter a fixed-for-floating commodity swap."""

    @classmethod
    def builder(cls, instrument_id: str) -> CommoditySwaptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def commodity_type(self) -> str: ...
    @property
    def ticker(self) -> str: ...
    @property
    def unit(self) -> str: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def option_type(self) -> str: ...
    @property
    def expiry(self) -> date: ...
    @property
    def swap_start(self) -> date: ...
    @property
    def swap_end(self) -> date: ...
    @property
    def swap_frequency(self) -> str: ...
    @property
    def fixed_price(self) -> float: ...
    @property
    def notional(self) -> float: ...
    @property
    def forward_curve_id(self) -> str: ...
    @property
    def discount_curve_id(self) -> str: ...
    @property
    def vol_surface_id(self) -> str: ...
    @property
    def day_count(self) -> DayCount: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def to_json(self) -> str:
        """Serialize to JSON in envelope format.

        Returns:
            str: JSON string with schema version and tagged instrument spec.
        """
        ...

    @classmethod
    def from_json(cls, json_str: str) -> "Self":
        """Deserialize from JSON in envelope format.

        Args:
            json_str: JSON string in envelope format.

        Returns:
            The deserialized instrument.

        Raises:
            ValueError: If JSON is malformed or contains a different instrument type.
        """
        ...
