"""Commodity forward instrument (builder-only API)."""

from __future__ import annotations
from datetime import date

from ....core.currency import Currency
from ...common import InstrumentType

class CommodityForwardBuilder:
    """Fluent builder returned by :meth:`CommodityForward.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def commodity_type(self, commodity_type: str) -> CommodityForwardBuilder: ...
    def ticker(self, ticker: str) -> CommodityForwardBuilder: ...
    def quantity(self, quantity: float) -> CommodityForwardBuilder: ...
    def unit(self, unit: str) -> CommodityForwardBuilder: ...
    def maturity(self, maturity: date) -> CommodityForwardBuilder: ...
    def currency(self, currency: str | Currency) -> CommodityForwardBuilder: ...
    def forward_curve_id(self, curve_id: str) -> CommodityForwardBuilder: ...
    def discount_curve_id(self, curve_id: str) -> CommodityForwardBuilder: ...
    def multiplier(self, multiplier: float) -> CommodityForwardBuilder: ...
    def quoted_price(self, quoted_price: float | None = ...) -> CommodityForwardBuilder: ...
    def spot_id(self, spot_id: str | None = ...) -> CommodityForwardBuilder: ...
    def settlement_type(self, settlement_type: str | None = ...) -> CommodityForwardBuilder: ...
    def exchange(self, exchange: str | None = ...) -> CommodityForwardBuilder: ...
    def contract_month(self, contract_month: str | None = ...) -> CommodityForwardBuilder: ...
    def position(self, position: str | None = ...) -> CommodityForwardBuilder: ...
    def contract_price(self, contract_price: float | None = ...) -> CommodityForwardBuilder: ...
    def convention(self, convention: str | None = ...) -> CommodityForwardBuilder: ...
    def settlement_lag_days(self, lag_days: int | None = ...) -> CommodityForwardBuilder: ...
    def settlement_calendar_id(self, calendar_id: str | None = ...) -> CommodityForwardBuilder: ...
    def settlement_bdc(self, bdc: str | None = ...) -> CommodityForwardBuilder: ...
    def build(self) -> CommodityForward: ...

class CommodityForward:
    """Commodity forward or futures contract."""

    @classmethod
    def builder(cls, instrument_id: str) -> CommodityForwardBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def commodity_type(self) -> str: ...
    @property
    def ticker(self) -> str: ...
    @property
    def quantity(self) -> float: ...
    @property
    def unit(self) -> str: ...
    @property
    def multiplier(self) -> float: ...
    @property
    def maturity(self) -> date: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def quoted_price(self) -> float | None: ...
    @property
    def forward_curve_id(self) -> str: ...
    @property
    def discount_curve_id(self) -> str: ...
    @property
    def exchange(self) -> str | None: ...
    @property
    def contract_month(self) -> str | None: ...
    @property
    def position(self) -> str: ...
    @property
    def contract_price(self) -> float | None: ...
    @property
    def convention(self) -> str | None: ...
    @property
    def settlement_lag_days(self) -> int | None: ...
    @property
    def settlement_calendar_id(self) -> str | None: ...
    @property
    def settlement_bdc(self) -> str | None: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def is_at_market(self) -> bool: ...
    def effective_settlement_lag(self) -> int: ...
    def effective_settlement_calendar(self) -> str | None: ...
    def effective_settlement_bdc(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
