"""Commodity spread option instrument (builder-only API)."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.dates.daycount import DayCount
from ...common import InstrumentType

class CommoditySpreadOptionBuilder:
    """Fluent builder returned by :meth:`CommoditySpreadOption.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def currency(self, currency: str | Currency) -> CommoditySpreadOptionBuilder: ...
    def option_type(self, option_type: str) -> CommoditySpreadOptionBuilder: ...
    def expiry(self, expiry: date) -> CommoditySpreadOptionBuilder: ...
    def strike(self, strike: float) -> CommoditySpreadOptionBuilder: ...
    def notional(self, notional: float) -> CommoditySpreadOptionBuilder: ...
    def leg1_forward_curve_id(self, curve_id: str) -> CommoditySpreadOptionBuilder: ...
    def leg2_forward_curve_id(self, curve_id: str) -> CommoditySpreadOptionBuilder: ...
    def leg1_vol_surface_id(self, curve_id: str) -> CommoditySpreadOptionBuilder: ...
    def leg2_vol_surface_id(self, curve_id: str) -> CommoditySpreadOptionBuilder: ...
    def discount_curve_id(self, curve_id: str) -> CommoditySpreadOptionBuilder: ...
    def correlation(self, correlation: float) -> CommoditySpreadOptionBuilder: ...
    def day_count(self, day_count: DayCount | str) -> CommoditySpreadOptionBuilder: ...
    def build(self) -> CommoditySpreadOption: ...

class CommoditySpreadOption:
    """Option on the spread between two commodity forward prices."""

    @classmethod
    def builder(cls, instrument_id: str) -> CommoditySpreadOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def option_type(self) -> str: ...
    @property
    def expiry(self) -> date: ...
    @property
    def strike(self) -> float: ...
    @property
    def notional(self) -> float: ...
    @property
    def leg1_forward_curve_id(self) -> str: ...
    @property
    def leg2_forward_curve_id(self) -> str: ...
    @property
    def leg1_vol_surface_id(self) -> str: ...
    @property
    def leg2_vol_surface_id(self) -> str: ...
    @property
    def discount_curve_id(self) -> str: ...
    @property
    def correlation(self) -> float: ...
    @property
    def day_count(self) -> DayCount: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
