"""Commodity swap instrument (builder-only API)."""

from __future__ import annotations
from datetime import date
from typing import List, Self

from ....core.currency import Currency
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...cashflow.builder import CashFlowSchedule
from ...common import InstrumentType

class CommoditySwapBuilder:
    """Fluent builder returned by :meth:`CommoditySwap.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def commodity_type(self, commodity_type: str) -> CommoditySwapBuilder: ...
    def ticker(self, ticker: str) -> CommoditySwapBuilder: ...
    def unit(self, unit: str) -> CommoditySwapBuilder: ...
    def currency(self, currency: str | Currency) -> CommoditySwapBuilder: ...
    def quantity(self, quantity: float) -> CommoditySwapBuilder: ...
    def fixed_price(self, fixed_price: float) -> CommoditySwapBuilder: ...
    def floating_index_id(self, curve_id: str) -> CommoditySwapBuilder: ...
    def pay_fixed(self, pay_fixed: bool) -> CommoditySwapBuilder: ...
    def start_date(self, start_date: date) -> CommoditySwapBuilder: ...
    def end_date(self, end_date: date) -> CommoditySwapBuilder: ...
    def payment_frequency(self, payment_frequency: str) -> CommoditySwapBuilder: ...
    def discount_curve_id(self, curve_id: str) -> CommoditySwapBuilder: ...
    def calendar_id(self, calendar_id: str | None = ...) -> CommoditySwapBuilder: ...
    def bdc(self, bdc: str | None = ...) -> CommoditySwapBuilder: ...
    def index_lag_days(self, index_lag_days: int | None = ...) -> CommoditySwapBuilder: ...
    def build(self) -> CommoditySwap: ...

class CommoditySwap:
    """Commodity swap (fixed-for-floating commodity price exchange)."""

    @classmethod
    def builder(cls, instrument_id: str) -> CommoditySwapBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def commodity_type(self) -> str: ...
    @property
    def ticker(self) -> str: ...
    @property
    def unit(self) -> str: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def quantity(self) -> float: ...
    @property
    def fixed_price(self) -> float: ...
    @property
    def pay_fixed(self) -> bool: ...
    @property
    def start_date(self) -> date: ...
    @property
    def end_date(self) -> date: ...
    @property
    def floating_index_id(self) -> str: ...
    @property
    def discount_curve_id(self) -> str: ...
    @property
    def payment_frequency(self) -> str: ...
    @property
    def calendar_id(self) -> str | None: ...
    @property
    def bdc(self) -> str: ...
    @property
    def index_lag_days(self) -> int | None: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def fixed_leg_pv(self, market: "MarketContext", as_of: date) -> float: ...
    def floating_leg_pv(self, market: "MarketContext", as_of: date) -> float: ...
    def payment_schedule(self, as_of: date) -> List[date]: ...
    def cashflow_schedule(self, market: "MarketContext", as_of: date) -> CashFlowSchedule: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def to_json(self) -> str:
        """Serialize to JSON in envelope format.

        Returns:
            str: JSON string with schema version and tagged instrument spec.
        """
        ...

    @classmethod
    def from_json(cls, json_str: str) -> "Self":
        """Deserialize from JSON in envelope format.

        Args:
            json_str: JSON string in envelope format.

        Returns:
            The deserialized instrument.

        Raises:
            ValueError: If JSON is malformed or contains a different instrument type.
        """
        ...
