"""Common valuation parameter enums exposed to Python."""

from typing import ClassVar

class OptionType:
    """Option type enumeration (call or put)."""

    CALL: ClassVar[OptionType]
    PUT: ClassVar[OptionType]

    @classmethod
    def from_name(cls, name: str) -> OptionType: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class ExerciseStyle:
    """Exercise style enumeration (European, American, Bermudan)."""

    EUROPEAN: ClassVar[ExerciseStyle]
    AMERICAN: ClassVar[ExerciseStyle]
    BERMUDAN: ClassVar[ExerciseStyle]

    @classmethod
    def from_name(cls, name: str) -> ExerciseStyle: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class SettlementType:
    """Settlement type enumeration (physical or cash)."""

    PHYSICAL: ClassVar[SettlementType]
    CASH: ClassVar[SettlementType]

    @classmethod
    def from_name(cls, name: str) -> SettlementType: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PayReceive:
    """Pay/receive leg direction enumeration."""

    PAY_FIXED: ClassVar[PayReceive]
    RECEIVE_FIXED: ClassVar[PayReceive]

    @classmethod
    def from_name(cls, name: str) -> PayReceive: ...
    @property
    def name(self) -> str: ...
    def is_payer(self) -> bool: ...
    def is_receiver(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BarrierType:
    """Barrier direction/type enumeration for barrier options."""

    UP_AND_OUT: ClassVar[BarrierType]
    UP_AND_IN: ClassVar[BarrierType]
    DOWN_AND_OUT: ClassVar[BarrierType]
    DOWN_AND_IN: ClassVar[BarrierType]

    def is_knock_out(self) -> bool: ...
    def is_knock_in(self) -> bool: ...
    def is_up(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

__all__ = [
    "OptionType",
    "ExerciseStyle",
    "SettlementType",
    "PayReceive",
    "BarrierType",
]
