"""Common valuation parameter enums exposed to Python."""

from __future__ import annotations
from typing import ClassVar

class OptionType:
    """Option type enumeration (call or put)."""

    CALL: ClassVar[OptionType]
    PUT: ClassVar[OptionType]

    @classmethod
    def from_name(cls, name: str) -> OptionType: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class ExerciseStyle:
    """Exercise style enumeration (European, American, Bermudan)."""

    EUROPEAN: ClassVar[ExerciseStyle]
    AMERICAN: ClassVar[ExerciseStyle]
    BERMUDAN: ClassVar[ExerciseStyle]

    @classmethod
    def from_name(cls, name: str) -> ExerciseStyle: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class SettlementType:
    """Settlement type enumeration (physical or cash)."""

    PHYSICAL: ClassVar[SettlementType]
    CASH: ClassVar[SettlementType]

    @classmethod
    def from_name(cls, name: str) -> SettlementType: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PayReceive:
    """Pay/receive leg direction enumeration."""

    PAY_FIXED: ClassVar[PayReceive]
    RECEIVE_FIXED: ClassVar[PayReceive]

    @classmethod
    def from_name(cls, name: str) -> PayReceive: ...
    @property
    def name(self) -> str: ...
    def is_payer(self) -> bool: ...
    def is_receiver(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BarrierType:
    """Barrier direction/type enumeration for barrier options."""

    UP_AND_OUT: ClassVar[BarrierType]
    UP_AND_IN: ClassVar[BarrierType]
    DOWN_AND_OUT: ClassVar[BarrierType]
    DOWN_AND_IN: ClassVar[BarrierType]

    def is_knock_out(self) -> bool: ...
    def is_knock_in(self) -> bool: ...
    def is_up(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class VolatilityModel:
    """Volatility model for option pricing."""

    BLACK: ClassVar[VolatilityModel]
    NORMAL: ClassVar[VolatilityModel]

    @classmethod
    def from_name(cls, name: str) -> VolatilityModel: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class CashSettlementMethod:
    """Cash settlement method for cash-settled swaptions."""

    PAR_YIELD: ClassVar[CashSettlementMethod]
    ISDA_PAR_PAR: ClassVar[CashSettlementMethod]
    ZERO_COUPON: ClassVar[CashSettlementMethod]

    @classmethod
    def from_name(cls, name: str) -> CashSettlementMethod: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class CapFloorVolType:
    """Volatility convention for cap/floor pricing."""

    LOGNORMAL: ClassVar[CapFloorVolType]
    SHIFTED_LOGNORMAL: ClassVar[CapFloorVolType]
    NORMAL: ClassVar[CapFloorVolType]

    @classmethod
    def from_name(cls, name: str) -> CapFloorVolType: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

__all__ = [
    "OptionType",
    "ExerciseStyle",
    "SettlementType",
    "PayReceive",
    "BarrierType",
    "VolatilityModel",
    "CashSettlementMethod",
    "CapFloorVolType",
]
