//! Cashflow construction helpers for interest rate swaps.
//!
//! This module centralizes cashflow schedule generation for `InterestRateSwap`:
//! - Fixed-leg and floating-leg `CashFlowSchedule` builders
//! - Signed dated flows used by `CashflowProvider`
//! - Combined full schedules with `CFKind` metadata
//!
//! Pricing logic (discounting, forwards, PV) lives in `pricer.rs` and consumes
//! these schedules where appropriate.
//!
//! # Important: Accrual-End Dates vs Payment Dates
//!
//! **All schedules generated by this module use accrual-end dates, not payment dates.**
//!
//! The `CashFlow::date` field represents the end of the accrual period, which is
//! typically when the coupon "fixes" or finalizes. The actual payment date may differ
//! due to `payment_lag_days` configured on the leg specification.
//!
//! For example, with `payment_lag_days = 2`:
//! - Accrual period: Jan 1 → Apr 1 (date = Apr 1)
//! - Actual payment: Apr 3 (2 business days after accrual end)
//!
//! The pricer applies payment delay when discounting, so the PV calculation uses
//! the correct payment date. Consumers who need actual payment dates should apply
//! `add_payment_delay()` from `crate::instruments::rates::irs::dates`.

use finstack_core::dates::Date;
use finstack_core::money::Money;
use finstack_core::Result;
use rust_decimal::Decimal;

use crate::cashflow::builder::{
    CashFlowSchedule, FixedCouponSpec, FloatingCouponSpec, FloatingRateSpec, Notional,
};
use crate::cashflow::traits::DatedFlows;
use crate::instruments::rates::irs::{InterestRateSwap, PayReceive};

/// Build an unsigned fixed-leg cashflow schedule for an IRS.
///
/// The resulting schedule has positive notionals and coupon amounts; caller is
/// responsible for applying `PayReceive` sign conventions.
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build the schedule
///
/// # Returns
///
/// A `CashFlowSchedule` containing all fixed leg cashflows with `CFKind::Fixed`
/// or `CFKind::Stub` classifications. Amounts are unsigned (positive).
///
/// # Errors
///
/// Returns an error if the cashflow schedule cannot be built (e.g., invalid
/// date ranges or calendar lookups fail).
///
/// # Examples
///
/// ```
/// use finstack_valuations::instruments::rates::irs::{InterestRateSwap, cashflow};
///
/// # fn example() -> finstack_core::Result<()> {
/// let irs = InterestRateSwap::example()?;
/// let schedule = cashflow::fixed_leg_schedule(&irs)?;
///
/// // Schedule contains fixed coupon flows
/// assert!(!schedule.flows.is_empty());
/// # Ok(())
/// # }
/// ```
pub fn fixed_leg_schedule(irs: &InterestRateSwap) -> Result<CashFlowSchedule> {
    let fixed = irs.resolved_fixed_leg();
    let mut fixed_b = CashFlowSchedule::builder();
    let _ = fixed_b
        .principal(irs.notional, fixed.start, fixed.end)
        .fixed_cf(FixedCouponSpec {
            coupon_type: crate::cashflow::builder::CouponType::Cash,
            rate: fixed.rate,
            freq: fixed.frequency,
            dc: fixed.day_count,
            bdc: fixed.bdc,
            calendar_id: fixed
                .calendar_id
                .clone()
                .unwrap_or_else(|| "weekends_only".to_string()),
            stub: fixed.stub,
            end_of_month: fixed.end_of_month,
            payment_lag_days: fixed.payment_lag_days,
        });
    let mut sched = fixed_b.build_with_curves(None)?;
    // IRS do not exchange notionals; return coupon-only schedule as documented.
    sched.flows.retain(|cf| {
        cf.kind == crate::cashflow::primitives::CFKind::Fixed
            || cf.kind == crate::cashflow::primitives::CFKind::Stub
    });
    Ok(sched)
}

/// Build an unsigned floating-leg cashflow schedule for an IRS.
///
/// The schedule encodes reset dates, payment dates, and accrual metadata. The
/// amounts are unsigned; caller is responsible for applying `PayReceive`.
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build the schedule
///
/// # Returns
///
/// A `CashFlowSchedule` containing all floating leg cashflows with `CFKind::FloatReset`
/// classifications. Amounts are unsigned (positive) and represent notional × spread
/// × accrual factor (forward rates must be added separately by the pricer).
///
/// # Errors
///
/// Returns an error if the cashflow schedule cannot be built (e.g., invalid
/// date ranges or calendar lookups fail).
///
/// # Examples
///
/// ```
/// use finstack_valuations::instruments::rates::irs::{InterestRateSwap, cashflow};
///
/// # fn example() -> finstack_core::Result<()> {
/// let irs = InterestRateSwap::example()?;
/// let schedule = cashflow::float_leg_schedule(&irs)?;
///
/// // Schedule contains floating rate reset flows
/// assert!(!schedule.flows.is_empty());
/// # Ok(())
/// # }
/// ```
pub fn float_leg_schedule(irs: &InterestRateSwap) -> Result<CashFlowSchedule> {
    float_leg_schedule_with_curves(irs, None)
}

/// Build an unsigned floating-leg cashflow schedule for an IRS with market curves.
///
/// When curves are provided, the schedule includes actual forward rate projections.
/// Without curves, only the spread contribution is used (useful for structure-only schedules).
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build the schedule
/// * `curves` - Optional market context containing forward curves
///
/// # Returns
///
/// A `CashFlowSchedule` containing all floating leg cashflows with `CFKind::FloatReset`
/// classifications.
pub fn float_leg_schedule_with_curves(
    irs: &InterestRateSwap,
    curves: Option<&finstack_core::market_data::context::MarketContext>,
) -> Result<CashFlowSchedule> {
    let float = irs.resolved_float_leg();
    let mut float_b = CashFlowSchedule::builder();
    let _ = float_b
        .principal(irs.notional, float.start, float.end)
        .floating_cf(FloatingCouponSpec {
            rate_spec: FloatingRateSpec {
                index_id: float.forward_curve_id.to_owned(),
                spread_bp: float.spread_bp,
                gearing: Decimal::ONE,
                gearing_includes_spread: true,
                floor_bp: None,
                cap_bp: None,
                all_in_floor_bp: None,
                index_cap_bp: None,
                reset_freq: float.frequency,
                reset_lag_days: float.reset_lag_days,
                dc: float.day_count,
                bdc: float.bdc,
                calendar_id: float
                    .calendar_id
                    .clone()
                    .unwrap_or_else(|| "weekends_only".to_string()),
                fixing_calendar_id: float.fixing_calendar_id.clone(),
                end_of_month: float.end_of_month,
                payment_lag_days: float.payment_lag_days,
                overnight_compounding: None,
                fallback: if curves.is_some() {
                    crate::cashflow::builder::FloatingRateFallback::Error
                } else {
                    crate::cashflow::builder::FloatingRateFallback::SpreadOnly
                },
            },
            coupon_type: crate::cashflow::builder::CouponType::Cash,
            freq: float.frequency,
            stub: float.stub,
        });
    let mut sched = float_b.build_with_curves(curves)?;
    // IRS do not exchange notionals; return coupon-only schedule as documented.
    sched
        .flows
        .retain(|cf| cf.kind == crate::cashflow::primitives::CFKind::FloatReset);
    Ok(sched)
}

/// Build signed dated flows for an IRS, suitable for `CashflowProvider`.
///
/// Returns a vector of `(date, amount)` with signs applied according to
/// `PayReceive` and fixed/float leg direction.
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build dated flows
///
/// # Returns
///
/// A vector of `(Date, Money)` tuples with:
/// - Fixed leg flows: positive for ReceiveFixed, negative for PayFixed
/// - Floating leg flows: negative for ReceiveFixed, positive for PayFixed
///
/// # Errors
///
/// Returns an error if either leg's cashflow schedule cannot be built.
///
/// # Examples
///
/// ```
/// use finstack_valuations::instruments::rates::irs::{InterestRateSwap, cashflow, PayReceive};
///
/// # fn example() -> finstack_core::Result<()> {
/// let irs = InterestRateSwap::example()?;
/// let flows = cashflow::signed_dated_flows(&irs)?;
///
/// // PayFixed swap has negative fixed leg flows, positive float leg flows
/// assert!(!flows.is_empty());
/// # Ok(())
/// # }
/// ```
pub fn signed_dated_flows(irs: &InterestRateSwap) -> Result<DatedFlows> {
    signed_dated_flows_with_curves(irs, None)
}

/// Build signed dated flows for an IRS with market curves.
///
/// When curves are provided, floating leg amounts include forward rate projections.
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build dated flows
/// * `curves` - Optional market context containing forward curves
pub fn signed_dated_flows_with_curves(
    irs: &InterestRateSwap,
    curves: Option<&finstack_core::market_data::context::MarketContext>,
) -> Result<DatedFlows> {
    let fixed_sched = fixed_leg_schedule(irs)?;
    let float_sched = float_leg_schedule_with_curves(irs, curves)?;

    let mut flows: Vec<(Date, Money)> = Vec::new();

    // Fixed leg: sign depends on PayReceive
    for cf in fixed_sched.flows {
        if cf.kind == crate::cashflow::primitives::CFKind::Fixed
            || cf.kind == crate::cashflow::primitives::CFKind::Stub
        {
            let amt = match irs.side {
                PayReceive::ReceiveFixed => cf.amount,
                PayReceive::PayFixed => cf.amount * -1.0,
            };
            flows.push((cf.date, amt));
        }
    }

    // Floating leg: opposite sign to fixed leg
    for cf in float_sched.flows {
        if cf.kind == crate::cashflow::primitives::CFKind::FloatReset {
            let amt = match irs.side {
                PayReceive::ReceiveFixed => cf.amount * -1.0,
                PayReceive::PayFixed => cf.amount,
            };
            flows.push((cf.date, amt));
        }
    }

    // Sort flows by date
    flows.sort_by_key(|(date, _)| *date);

    Ok(flows)
}

/// Build a full, signed cashflow schedule with `CFKind` metadata for an IRS.
///
/// This combines fixed and floating leg schedules, applies sign conventions,
/// and sorts flows by date and CFKind priority.
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build the full schedule
///
/// # Returns
///
/// A `CashFlowSchedule` containing all cashflows from both legs with:
/// - Proper sign conventions applied based on `PayReceive`
/// - `CFKind` metadata preserved for each flow
/// - Flows sorted by date and kind priority
///
/// # Errors
///
/// Returns an error if either leg's cashflow schedule cannot be built.
///
/// # Examples
///
/// ```
/// use finstack_valuations::instruments::rates::irs::{InterestRateSwap, cashflow};
///
/// # fn example() -> finstack_core::Result<()> {
/// let irs = InterestRateSwap::example()?;
/// let schedule = cashflow::full_signed_schedule(&irs)?;
///
/// // Combined schedule has flows from both fixed and floating legs
/// assert!(!schedule.flows.is_empty());
///
/// // Flows are sorted by date
/// for i in 1..schedule.flows.len() {
///     assert!(schedule.flows[i].date >= schedule.flows[i-1].date);
/// }
/// # Ok(())
/// # }
/// ```
pub fn full_signed_schedule(irs: &InterestRateSwap) -> Result<CashFlowSchedule> {
    full_signed_schedule_with_curves(irs, None)
}

/// Build a full, signed cashflow schedule with `CFKind` metadata for an IRS with market curves.
///
/// When curves are provided, floating leg amounts include forward rate projections.
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build the full schedule
/// * `curves` - Optional market context containing forward curves
pub fn full_signed_schedule_with_curves(
    irs: &InterestRateSwap,
    curves: Option<&finstack_core::market_data::context::MarketContext>,
) -> Result<CashFlowSchedule> {
    use finstack_core::cashflow::{CFKind, CashFlow};

    let fixed_sched = fixed_leg_schedule(irs)?;
    let float_sched = float_leg_schedule_with_curves(irs, curves)?;

    // Combine flows from both legs with proper CFKind classification
    let mut all_flows: Vec<CashFlow> = Vec::new();

    // Add fixed leg flows
    for cf in fixed_sched.flows {
        if cf.kind == CFKind::Fixed || cf.kind == CFKind::Stub {
            let amt = match irs.side {
                PayReceive::ReceiveFixed => cf.amount,
                PayReceive::PayFixed => cf.amount * -1.0,
            };
            all_flows.push(CashFlow {
                date: cf.date,
                reset_date: cf.reset_date,
                amount: amt,
                kind: cf.kind, // Preserve precise CFKind
                accrual_factor: cf.accrual_factor,
                rate: cf.rate,
            });
        }
    }

    // Add floating leg flows
    for cf in float_sched.flows {
        if cf.kind == CFKind::FloatReset {
            let amt = match irs.side {
                PayReceive::ReceiveFixed => cf.amount * -1.0,
                PayReceive::PayFixed => cf.amount,
            };
            all_flows.push(CashFlow {
                date: cf.date,
                reset_date: cf.reset_date,
                amount: amt,
                kind: cf.kind, // Preserve precise CFKind
                accrual_factor: cf.accrual_factor,
                rate: cf.rate,
            });
        }
    }

    // Sort flows by date and CFKind priority
    all_flows.sort_by(|a, b| {
        use core::cmp::Ordering;
        match a.date.cmp(&b.date) {
            Ordering::Equal => {
                // Use kind ranking logic from cashflow builder
                let rank_a = match a.kind {
                    CFKind::Fixed | CFKind::Stub | CFKind::FloatReset => 0,
                    CFKind::Fee => 1,
                    CFKind::Amortization => 2,
                    CFKind::PIK => 3,
                    CFKind::Notional => 4,
                    _ => 5,
                };
                let rank_b = match b.kind {
                    CFKind::Fixed | CFKind::Stub | CFKind::FloatReset => 0,
                    CFKind::Fee => 1,
                    CFKind::Amortization => 2,
                    CFKind::PIK => 3,
                    CFKind::Notional => 4,
                    _ => 5,
                };
                rank_a.cmp(&rank_b)
            }
            other => other,
        }
    });

    // Create notional spec for swap (notional doesn't amortize)
    let notional = Notional::par(irs.notional.amount(), irs.notional.currency());

    Ok(CashFlowSchedule {
        flows: all_flows,
        notional,
        day_count: irs.fixed.day_count, // Use fixed leg day count as representative
        meta: Default::default(),
    })
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use finstack_core::cashflow::CFKind;

    #[test]
    fn irs_leg_schedules_do_not_emit_notional_flows() {
        let irs = InterestRateSwap::example().expect("example IRS");
        let fixed = fixed_leg_schedule(&irs).expect("fixed schedule");
        assert!(
            fixed
                .flows
                .iter()
                .all(|cf| cf.kind == CFKind::Fixed || cf.kind == CFKind::Stub),
            "fixed_leg_schedule should be coupon-only"
        );

        let float = float_leg_schedule(&irs).expect("float schedule");
        assert!(
            float.flows.iter().all(|cf| cf.kind == CFKind::FloatReset),
            "float_leg_schedule should be coupon-only"
        );
    }
}
