//! Cashflow construction helpers for interest rate swaps.
//!
//! This module centralizes cashflow schedule generation for `InterestRateSwap`:
//! - Fixed-leg and floating-leg `CashFlowSchedule` builders
//! - Combined signed schedules with `CFKind` metadata used by `CashflowProvider`
//!
//! Pricing logic (discounting, forwards, PV) lives in `pricer.rs` and consumes
//! these schedules where appropriate.
//!
//! # Important: Accrual-End Dates vs Payment Dates
//!
//! **All schedules generated by this module use accrual-end dates, not payment dates.**
//!
//! The `CashFlow::date` field represents the end of the accrual period, which is
//! typically when the coupon "fixes" or finalizes. The actual payment date may differ
//! due to `payment_lag_days` configured on the leg specification.
//!
//! For example, with `payment_lag_days = 2`:
//! - Accrual period: Jan 1 → Apr 1 (date = Apr 1)
//! - Actual payment: Apr 3 (2 business days after accrual end)
//!
//! The pricer applies payment delay when discounting, so the PV calculation uses
//! the correct payment date. Consumers who need actual payment dates should apply
//! `add_payment_delay()` from `crate::instruments::rates::irs::dates`.

use finstack_core::dates::CalendarRegistry;
use finstack_core::dates::{Date, DateExt, DayCountContext};
use finstack_core::market_data::context::MarketContext;
use finstack_core::market_data::scalars::ScalarTimeSeries;
use finstack_core::market_data::term_structures::{DiscountCurve, ForwardCurve};
use finstack_core::money::Money;
use finstack_core::Result;
use rust_decimal::prelude::ToPrimitive;
use rust_decimal::Decimal;

use crate::cashflow::builder::{
    periods::{build_periods, BuildPeriodsParams},
    CashFlowSchedule, FixedCouponSpec, FloatingCouponSpec, FloatingRateSpec, Notional,
};
use crate::instruments::rates::irs::{FloatingLegCompounding, InterestRateSwap, PayReceive};

fn default_rfr_calendar(currency: finstack_core::currency::Currency) -> Option<&'static str> {
    use finstack_core::currency::Currency;

    match currency {
        Currency::USD => Some("nyse"),
        Currency::EUR => Some("target"),
        Currency::GBP => Some("london"),
        Currency::JPY => Some("tokyo"),
        Currency::AUD => Some("sydney"),
        Currency::CAD => Some("toronto"),
        Currency::CHF => Some("zurich"),
        Currency::SEK => Some("stockholm"),
        Currency::NOK => Some("oslo"),
        Currency::DKK => Some("copenhagen"),
        Currency::NZD => Some("wellington"),
        _ => None,
    }
}

fn compounded_total_shift_days(compounding: FloatingLegCompounding) -> i32 {
    match compounding {
        FloatingLegCompounding::CompoundedInArrears {
            lookback_days,
            observation_shift,
        } => -lookback_days + observation_shift.unwrap_or(0),
        FloatingLegCompounding::CompoundedWithObservationShift { shift_days } => -shift_days,
        FloatingLegCompounding::Simple => 0,
    }
}

fn uses_observation_shift_dcf(compounding: FloatingLegCompounding) -> bool {
    matches!(
        compounding,
        FloatingLegCompounding::CompoundedWithObservationShift { .. }
    )
}

struct OvernightProjectionInputs<'a> {
    proj: Option<&'a ForwardCurve>,
    disc_fallback: Option<&'a DiscountCurve>,
    fixings: Option<&'a ScalarTimeSeries>,
    projection_base_date: Date,
    float: &'a crate::instruments::common_impl::parameters::legs::FloatLegSpec,
}

fn builder_overnight_method(
    compounding: FloatingLegCompounding,
) -> Option<crate::cashflow::builder::OvernightCompoundingMethod> {
    use crate::cashflow::builder::OvernightCompoundingMethod;

    match compounding {
        FloatingLegCompounding::Simple => None,
        FloatingLegCompounding::CompoundedInArrears {
            lookback_days,
            observation_shift,
        } => {
            if observation_shift.unwrap_or(0) == 0 {
                if lookback_days == 0 {
                    Some(OvernightCompoundingMethod::CompoundedInArrears)
                } else {
                    Some(OvernightCompoundingMethod::CompoundedWithLookback {
                        lookback_days: lookback_days as u32,
                    })
                }
            } else if lookback_days == 0 {
                Some(OvernightCompoundingMethod::CompoundedWithObservationShift {
                    shift_days: observation_shift.unwrap_or(0) as u32,
                })
            } else {
                // The generic builder does not yet model this hybrid convention exactly.
                Some(OvernightCompoundingMethod::CompoundedWithLookback {
                    lookback_days: lookback_days as u32,
                })
            }
        }
        FloatingLegCompounding::CompoundedWithObservationShift { shift_days } => {
            Some(OvernightCompoundingMethod::CompoundedWithObservationShift {
                shift_days: shift_days as u32,
            })
        }
    }
}

fn resolve_compounded_fixing_calendar(
    irs: &InterestRateSwap,
) -> Result<Option<&'static dyn finstack_core::dates::HolidayCalendar>> {
    let float = irs.resolved_float_leg();
    let calendar_id = float
        .fixing_calendar_id
        .as_deref()
        .or(float.calendar_id.as_deref());

    if let Some(id) = calendar_id {
        return Ok(Some(
            CalendarRegistry::global().resolve_str(id).ok_or_else(|| {
                finstack_core::Error::Validation(format!(
                    "Fixing calendar '{}' not found in registry for compounded RFR swap '{}'. \
                     Load the calendar or remove fixing_calendar_id to use weekday stepping.",
                    id,
                    irs.id.as_str()
                ))
            })?,
        ));
    }

    Ok(default_rfr_calendar(irs.notional.currency())
        .and_then(|id| CalendarRegistry::global().resolve_str(id)))
}

fn projected_overnight_rate(
    obs_start: Date,
    obs_end: Date,
    dcf: f64,
    inputs: &OvernightProjectionInputs<'_>,
) -> Result<f64> {
    if obs_start < inputs.projection_base_date {
        return finstack_core::market_data::fixings::require_fixing_value(
            inputs.fixings,
            inputs.float.forward_curve_id.as_str(),
            obs_start,
            inputs.projection_base_date,
        );
    }

    if let Some(proj) = inputs.proj {
        let t0 = if obs_start <= proj.base_date() {
            0.0
        } else {
            proj.day_count()
                .year_fraction(proj.base_date(), obs_start, DayCountContext::default())?
        };
        let t1 = if obs_end <= proj.base_date() {
            0.0
        } else {
            proj.day_count()
                .year_fraction(proj.base_date(), obs_end, DayCountContext::default())?
        };
        return Ok(if (t1 - t0).abs() > f64::EPSILON {
            proj.rate_period(t0, t1)
        } else {
            proj.rate(t0)
        });
    }

    if let Some(disc) = inputs.disc_fallback {
        let df_between = disc.df_between_dates(obs_start, obs_end)?;
        if !df_between.is_finite() || df_between <= 0.0 {
            return Err(finstack_core::Error::Validation(format!(
                "Invalid discount factor between observation dates ({} -> {}): df={:.3e}",
                obs_start, obs_end, df_between
            )));
        }
        const MIN_DCF_THRESHOLD: f64 = 1e-8;
        if dcf < MIN_DCF_THRESHOLD {
            return Err(finstack_core::Error::Validation(format!(
                "Day-count fraction {:.2e} is below minimum threshold ({:.0e}). \
                 This may indicate calendar misconfiguration causing same-day observations \
                 or invalid date ordering ({} -> {}).",
                dcf, MIN_DCF_THRESHOLD, obs_start, obs_end
            )));
        }
        let comp = 1.0 / df_between;
        return Ok((comp - 1.0) / dcf);
    }

    Err(finstack_core::Error::Input(
        finstack_core::InputError::NotFound {
            id: format!(
                "forward curve '{}' not found for reset date {} (overnight compounding)",
                inputs.float.forward_curve_id.as_str(),
                obs_start
            ),
        },
    ))
}

pub(crate) fn projected_compounded_float_leg_schedule(
    irs: &InterestRateSwap,
    disc: &DiscountCurve,
    proj: Option<&ForwardCurve>,
    as_of: Date,
    fixings: Option<&ScalarTimeSeries>,
) -> Result<CashFlowSchedule> {
    use finstack_core::cashflow::{CFKind, CashFlow};

    let float = irs.resolved_float_leg();
    let periods = build_periods(BuildPeriodsParams {
        start: float.start,
        end: float.end,
        frequency: float.frequency,
        stub: float.stub,
        bdc: float.bdc,
        calendar_id: float
            .calendar_id
            .as_deref()
            .unwrap_or(crate::cashflow::builder::calendar::WEEKENDS_ONLY_ID),
        end_of_month: float.end_of_month,
        day_count: float.day_count,
        payment_lag_days: float.payment_lag_days,
        reset_lag_days: None,
    })?;
    if periods.is_empty() {
        return Ok(crate::cashflow::traits::schedule_from_classified_flows(
            Vec::new(),
            float.day_count,
            crate::cashflow::traits::ScheduleBuildOpts {
                notional_hint: Some(irs.notional),
                ..Default::default()
            },
        ));
    }

    let cal = resolve_compounded_fixing_calendar(irs)?;
    let total_shift = compounded_total_shift_days(float.compounding.clone());
    let shift_dcf = uses_observation_shift_dcf(float.compounding.clone());
    let disc_fallback = if proj.is_none() { Some(disc) } else { None };
    let projection = OvernightProjectionInputs {
        proj,
        disc_fallback,
        fixings,
        projection_base_date: proj
            .map(ForwardCurve::base_date)
            .unwrap_or_else(|| disc.base_date()),
        float: &float,
    };

    let mut flows = Vec::with_capacity(periods.len());
    for period in periods {
        if period.payment_date <= as_of {
            continue;
        }

        let accrual_start = period.accrual_start;
        let accrual_end = period.accrual_end;
        let allow_fast_path =
            as_of <= accrual_start && total_shift == 0 && proj.is_none_or(|p| disc.id() == p.id());

        let compound_factor = if allow_fast_path {
            1.0 / crate::instruments::common_impl::pricing::swap_legs::robust_relative_df(
                disc,
                accrual_start,
                accrual_end,
            )?
        } else {
            let mut acc = 1.0;
            let mut d = accrual_start;
            while d < accrual_end {
                let next_d = if let Some(cal) = cal {
                    d.add_business_days(1, cal)?
                } else {
                    d.add_weekdays(1)
                };
                let step_end = if next_d > accrual_end {
                    accrual_end
                } else {
                    next_d
                };

                let obs_start = if total_shift == 0 {
                    d
                } else if let Some(cal) = cal {
                    d.add_business_days(total_shift, cal)?
                } else {
                    d.add_weekdays(total_shift)
                };
                let obs_end = if total_shift == 0 {
                    step_end
                } else if let Some(cal) = cal {
                    step_end.add_business_days(total_shift, cal)?
                } else {
                    step_end.add_weekdays(total_shift)
                };

                let (dcf_start, dcf_end) = if shift_dcf {
                    (obs_start, obs_end)
                } else {
                    (d, step_end)
                };
                let dcf =
                    float
                        .day_count
                        .year_fraction(dcf_start, dcf_end, DayCountContext::default())?;

                if obs_end <= obs_start {
                    return Err(finstack_core::Error::Validation(format!(
                        "Invalid observation period after applying shift: obs_start={}, obs_end={}, \
                         total_shift={} days. This may indicate lookback exceeds the daily step size \
                         or an invalid observation_shift configuration.",
                        obs_start, obs_end, total_shift
                    )));
                }

                let r = projected_overnight_rate(obs_start, obs_end, dcf, &projection)?;
                acc *= 1.0 + r * dcf;
                d = step_end;
            }
            acc
        };

        let spread_bp = float.spread_bp.to_f64().ok_or_else(|| {
            finstack_core::Error::Validation(format!(
                "float leg spread_bp value {} cannot be converted to f64",
                float.spread_bp
            ))
        })?;
        let interest = irs.notional.amount() * (compound_factor - 1.0);
        let spread_contrib = irs.notional.amount()
            * spread_bp
            * crate::constants::ONE_BASIS_POINT
            * period.accrual_year_fraction;
        let coupon_amount = interest + spread_contrib;
        let all_in_rate = if period.accrual_year_fraction.abs() > f64::EPSILON {
            (compound_factor - 1.0) / period.accrual_year_fraction
                + spread_bp * crate::constants::ONE_BASIS_POINT
        } else {
            spread_bp * crate::constants::ONE_BASIS_POINT
        };

        flows.push(CashFlow {
            date: period.accrual_end,
            reset_date: None,
            amount: Money::new(coupon_amount, irs.notional.currency()),
            kind: CFKind::FloatReset,
            accrual_factor: period.accrual_year_fraction,
            rate: Some(all_in_rate),
        });
    }

    Ok(crate::cashflow::traits::schedule_from_classified_flows(
        flows,
        float.day_count,
        crate::cashflow::traits::ScheduleBuildOpts {
            notional_hint: Some(irs.notional),
            ..Default::default()
        },
    ))
}

/// Build an unsigned fixed-leg cashflow schedule for an IRS.
///
/// The resulting schedule has positive notionals and coupon amounts; caller is
/// responsible for applying `PayReceive` sign conventions.
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build the schedule
///
/// # Returns
///
/// A `CashFlowSchedule` containing all fixed leg cashflows with `CFKind::Fixed`
/// or `CFKind::Stub` classifications. Amounts are unsigned (positive).
///
/// # Errors
///
/// Returns an error if the cashflow schedule cannot be built (e.g., invalid
/// date ranges or calendar lookups fail).
///
/// # Examples
///
/// ```ignore
/// use finstack_valuations::instruments::rates::irs::{InterestRateSwap, cashflow};
///
/// # fn example() -> finstack_core::Result<()> {
/// let irs = InterestRateSwap::example()?;
/// let schedule = cashflow::fixed_leg_schedule(&irs)?;
///
/// // Schedule contains fixed coupon flows
/// assert!(!schedule.flows.is_empty());
/// # Ok(())
/// # }
/// ```
pub(crate) fn fixed_leg_schedule(irs: &InterestRateSwap) -> Result<CashFlowSchedule> {
    let fixed = irs.resolved_fixed_leg();
    let mut fixed_b = CashFlowSchedule::builder();
    let _ = fixed_b
        .principal(irs.notional, fixed.start, fixed.end)
        .fixed_cf(FixedCouponSpec {
            coupon_type: crate::cashflow::builder::CouponType::Cash,
            rate: fixed.rate,
            freq: fixed.frequency,
            dc: fixed.day_count,
            bdc: fixed.bdc,
            calendar_id: fixed
                .calendar_id
                .clone()
                .unwrap_or_else(|| "weekends_only".to_string()),
            stub: fixed.stub,
            end_of_month: fixed.end_of_month,
            payment_lag_days: fixed.payment_lag_days,
        });
    let mut sched = fixed_b.build_with_curves(None)?;
    // IRS do not exchange notionals; return coupon-only schedule as documented.
    sched.flows.retain(|cf| {
        cf.kind == crate::cashflow::primitives::CFKind::Fixed
            || cf.kind == crate::cashflow::primitives::CFKind::Stub
    });
    Ok(sched)
}

/// Build an unsigned floating-leg cashflow schedule for an IRS with market curves.
///
/// When curves are provided, the schedule includes actual forward rate projections.
/// Without curves, only the spread contribution is used (useful for structure-only schedules).
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build the schedule
/// * `curves` - Optional market context containing forward curves
///
/// # Returns
///
/// A `CashFlowSchedule` containing all floating leg cashflows with `CFKind::FloatReset`
/// classifications.
pub(crate) fn float_leg_schedule_with_curves(
    irs: &InterestRateSwap,
    curves: Option<&MarketContext>,
) -> Result<CashFlowSchedule> {
    float_leg_schedule_with_curves_as_of(irs, curves, None)
}

pub(crate) fn float_leg_schedule_with_curves_as_of(
    irs: &InterestRateSwap,
    curves: Option<&MarketContext>,
    as_of: Option<Date>,
) -> Result<CashFlowSchedule> {
    let float = irs.resolved_float_leg();
    if matches!(
        float.compounding,
        FloatingLegCompounding::CompoundedInArrears { .. }
            | FloatingLegCompounding::CompoundedWithObservationShift { .. }
    ) {
        if let Some(market) = curves {
            let disc = market.get_discount(irs.fixed.discount_curve_id.as_ref())?;
            let proj = if irs.is_single_curve_ois() {
                market.get_forward(float.forward_curve_id.as_str()).ok()
            } else {
                Some(market.get_forward(float.forward_curve_id.as_str())?)
            };
            let fixings = finstack_core::market_data::fixings::get_fixing_series(
                market,
                float.forward_curve_id.as_str(),
            )
            .ok();
            let valuation_date = as_of.unwrap_or_else(|| {
                proj.as_ref()
                    .map(|c| c.base_date())
                    .unwrap_or_else(|| disc.base_date())
            });
            return projected_compounded_float_leg_schedule(
                irs,
                disc.as_ref(),
                proj.as_deref(),
                valuation_date,
                fixings,
            );
        }
    }

    let mut float_b = CashFlowSchedule::builder();
    let _ = float_b
        .principal(irs.notional, float.start, float.end)
        .floating_cf(FloatingCouponSpec {
            rate_spec: FloatingRateSpec {
                index_id: float.forward_curve_id.to_owned(),
                spread_bp: float.spread_bp,
                gearing: Decimal::ONE,
                gearing_includes_spread: true,
                index_floor_bp: None,
                all_in_cap_bp: None,
                all_in_floor_bp: None,
                index_cap_bp: None,
                reset_freq: float.frequency,
                reset_lag_days: float.reset_lag_days,
                dc: float.day_count,
                bdc: float.bdc,
                calendar_id: float
                    .calendar_id
                    .clone()
                    .unwrap_or_else(|| "weekends_only".to_string()),
                fixing_calendar_id: float.fixing_calendar_id.clone(),
                end_of_month: float.end_of_month,
                payment_lag_days: float.payment_lag_days,
                overnight_compounding: builder_overnight_method(float.compounding.clone()),
                overnight_basis: None,
                fallback: if curves.is_some() {
                    crate::cashflow::builder::FloatingRateFallback::Error
                } else {
                    crate::cashflow::builder::FloatingRateFallback::SpreadOnly
                },
            },
            coupon_type: crate::cashflow::builder::CouponType::Cash,
            freq: float.frequency,
            stub: float.stub,
        });
    let mut sched = float_b.build_with_curves(curves)?;
    // IRS do not exchange notionals; return coupon-only schedule as documented.
    sched
        .flows
        .retain(|cf| cf.kind == crate::cashflow::primitives::CFKind::FloatReset);
    Ok(sched)
}

/// Build a full, signed cashflow schedule with `CFKind` metadata for an IRS with market curves.
///
/// When curves are provided, floating leg amounts include forward rate projections.
///
/// # Arguments
///
/// * `irs` - The interest rate swap for which to build the full schedule
/// * `curves` - Optional market context containing forward curves
#[cfg(test)]
pub(crate) fn full_signed_schedule_with_curves(
    irs: &InterestRateSwap,
    curves: Option<&MarketContext>,
) -> Result<CashFlowSchedule> {
    full_signed_schedule_with_curves_as_of(irs, curves, None)
}

pub(crate) fn full_signed_schedule_with_curves_as_of(
    irs: &InterestRateSwap,
    curves: Option<&MarketContext>,
    as_of: Option<Date>,
) -> Result<CashFlowSchedule> {
    use crate::instruments::common_impl::pricing::swap_legs::add_payment_delay;
    use finstack_core::cashflow::{CFKind, CashFlow};

    let fixed_sched = fixed_leg_schedule(irs)?;
    let float_sched = match as_of {
        Some(as_of_date) => float_leg_schedule_with_curves_as_of(irs, curves, Some(as_of_date))?,
        None => float_leg_schedule_with_curves(irs, curves)?,
    };

    // Combine flows from both legs with proper CFKind classification
    let mut all_flows: Vec<CashFlow> =
        Vec::with_capacity(fixed_sched.flows.len() + float_sched.flows.len());

    // Add fixed leg flows
    for cf in fixed_sched.flows {
        if cf.kind == CFKind::Fixed || cf.kind == CFKind::Stub {
            let amt = match irs.side {
                PayReceive::ReceiveFixed => cf.amount,
                PayReceive::PayFixed => cf.amount * -1.0,
            };
            all_flows.push(CashFlow {
                date: cf.date,
                reset_date: cf.reset_date,
                amount: amt,
                kind: cf.kind, // Preserve precise CFKind
                accrual_factor: cf.accrual_factor,
                rate: cf.rate,
            });
        }
    }

    // Add floating leg flows
    for cf in float_sched.flows {
        if cf.kind == CFKind::FloatReset {
            let amt = match irs.side {
                PayReceive::ReceiveFixed => cf.amount * -1.0,
                PayReceive::PayFixed => cf.amount,
            };
            all_flows.push(CashFlow {
                date: cf.date,
                reset_date: cf.reset_date,
                amount: amt,
                kind: cf.kind, // Preserve precise CFKind
                accrual_factor: cf.accrual_factor,
                rate: cf.rate,
            });
        }
    }

    // Sort flows by date and CFKind priority
    all_flows.sort_by(|a, b| {
        use core::cmp::Ordering;
        match a.date.cmp(&b.date) {
            Ordering::Equal => {
                // Use kind ranking logic from cashflow builder
                let rank_a = match a.kind {
                    CFKind::Fixed | CFKind::Stub | CFKind::FloatReset => 0,
                    CFKind::Fee => 1,
                    CFKind::Amortization => 2,
                    CFKind::PIK => 3,
                    CFKind::Notional => 4,
                    _ => 5,
                };
                let rank_b = match b.kind {
                    CFKind::Fixed | CFKind::Stub | CFKind::FloatReset => 0,
                    CFKind::Fee => 1,
                    CFKind::Amortization => 2,
                    CFKind::PIK => 3,
                    CFKind::Notional => 4,
                    _ => 5,
                };
                rank_a.cmp(&rank_b)
            }
            other => other,
        }
    });

    if let Some(as_of) = as_of {
        all_flows.retain(|flow| {
            let payment_date = match flow.kind {
                CFKind::Fixed | CFKind::Stub => add_payment_delay(
                    flow.date,
                    irs.fixed.payment_lag_days,
                    irs.fixed.calendar_id.as_deref(),
                ),
                CFKind::FloatReset => add_payment_delay(
                    flow.date,
                    irs.float.payment_lag_days,
                    irs.float.calendar_id.as_deref(),
                ),
                _ => Ok(flow.date),
            };

            match payment_date {
                Ok(payment_date) => payment_date > as_of,
                Err(_) => true,
            }
        });
    }

    // Create notional spec for swap (notional doesn't amortize)
    let notional = Notional::par(irs.notional.amount(), irs.notional.currency());

    Ok(CashFlowSchedule {
        flows: all_flows,
        notional,
        day_count: irs.fixed.day_count, // Use fixed leg day count as representative
        meta: Default::default(),
    })
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use finstack_core::cashflow::CFKind;

    #[test]
    fn irs_leg_schedules_do_not_emit_notional_flows() {
        let irs = InterestRateSwap::example().expect("example IRS");
        let fixed = fixed_leg_schedule(&irs).expect("fixed schedule");
        assert!(
            fixed
                .flows
                .iter()
                .all(|cf| cf.kind == CFKind::Fixed || cf.kind == CFKind::Stub),
            "fixed_leg_schedule should be coupon-only"
        );

        let float = float_leg_schedule_with_curves(&irs, None).expect("float schedule");
        assert!(
            float.flows.iter().all(|cf| cf.kind == CFKind::FloatReset),
            "float_leg_schedule should be coupon-only"
        );
    }
}
