"""Analysis submodule type stubs for statement modeling."""

from __future__ import annotations

class ParameterSpec: ...
class SensitivityMode: ...
class SensitivityConfig: ...
class SensitivityScenario: ...
class SensitivityResult: ...
class SensitivityAnalyzer: ...
class TornadoEntry: ...

def generate_tornado_chart(*args: object, **kwargs: object) -> object: ...

class ExplanationStep: ...
class Explanation: ...
class FormulaExplainer: ...
class DependencyTree: ...
class DependencyTracer: ...

def render_tree_ascii(*args: object, **kwargs: object) -> str: ...
def render_tree_detailed(*args: object, **kwargs: object) -> str: ...

class Alignment: ...
class Report: ...
class TableBuilder: ...
class PLSummaryReport(Report): ...
class CreditAssessmentReport(Report): ...
class DebtSummaryReport(Report): ...

def print_debt_summary(*args: object, **kwargs: object) -> None: ...

class VarianceConfig: ...
class VarianceRow: ...
class VarianceReport: ...
class BridgeStep: ...
class BridgeChart: ...
class VarianceAnalyzer: ...
class ScenarioDefinition: ...
class ScenarioSet: ...
class ScenarioResults: ...
class ScenarioDiff: ...
class MonteCarloConfig: ...
class PercentileSeries: ...
class ForecastMetrics: ...

def backtest_forecast(*args: object, **kwargs: object) -> object: ...

class CreditContextMetrics: ...

def compute_credit_context(*args: object, **kwargs: object) -> object: ...

class DcfOptions: ...
class CorporateValuationResult: ...

def evaluate_dcf(*args: object, **kwargs: object) -> object: ...
def evaluate_dcf_with_options(*args: object, **kwargs: object) -> object: ...
def evaluate_dcf_with_market(*args: object, **kwargs: object) -> object: ...
def forecast_covenant(*args: object, **kwargs: object) -> object: ...
def forecast_covenants(*args: object, **kwargs: object) -> object: ...
def forecast_breaches(*args: object, **kwargs: object) -> object: ...

class CreditInstrumentAnalysis: ...
class CorporateAnalysis: ...
class CorporateAnalysisBuilder: ...

__all__ = [
    "Alignment",
    "backtest_forecast",
    "BridgeChart",
    "BridgeStep",
    "compute_credit_context",
    "CorporateAnalysis",
    "CorporateAnalysisBuilder",
    "CorporateValuationResult",
    "CreditAssessmentReport",
    "CreditContextMetrics",
    "CreditInstrumentAnalysis",
    "DcfOptions",
    "DebtSummaryReport",
    "DependencyTracer",
    "DependencyTree",
    "evaluate_dcf",
    "evaluate_dcf_with_market",
    "evaluate_dcf_with_options",
    "Explanation",
    "ExplanationStep",
    "forecast_breaches",
    "forecast_covenant",
    "forecast_covenants",
    "ForecastMetrics",
    "FormulaExplainer",
    "generate_tornado_chart",
    "MonteCarloConfig",
    "ParameterSpec",
    "PercentileSeries",
    "PLSummaryReport",
    "print_debt_summary",
    "render_tree_ascii",
    "render_tree_detailed",
    "Report",
    "ScenarioDefinition",
    "ScenarioDiff",
    "ScenarioResults",
    "ScenarioSet",
    "SensitivityAnalyzer",
    "SensitivityConfig",
    "SensitivityMode",
    "SensitivityResult",
    "SensitivityScenario",
    "TableBuilder",
    "TornadoEntry",
    "VarianceAnalyzer",
    "VarianceConfig",
    "VarianceReport",
    "VarianceRow",
]
