"""Capital structure cashflow aggregation."""

from __future__ import annotations
from datetime import date
from typing import Optional

from ..core.dates.periods import Period, PeriodId
from ..core.money import Money
from ..core.market_data.context import MarketContext
from .types import CapitalStructureSpec

class CashflowBreakdown:
    """Per-period cashflow breakdown for a single instrument or aggregate."""
    @property
    def interest_expense_cash(self) -> Money: ...
    @property
    def interest_expense_pik(self) -> Money: ...
    @property
    def interest_expense_total(self) -> Money: ...
    @property
    def principal_payment(self) -> Money: ...
    @property
    def fees(self) -> Money: ...
    @property
    def debt_balance(self) -> Money: ...
    @property
    def accrued_interest(self) -> Money: ...
    def __repr__(self) -> str: ...

class CapitalStructureCashflows:
    """Aggregated capital structure cashflows across instruments and periods."""
    @property
    def instrument_ids(self) -> list[str]: ...
    @property
    def period_ids(self) -> list[PeriodId]: ...
    def get_interest(self, instrument_id: str, period_id: PeriodId) -> float: ...
    def get_interest_cash(self, instrument_id: str, period_id: PeriodId) -> float: ...
    def get_interest_pik(self, instrument_id: str, period_id: PeriodId) -> float: ...
    def get_principal(self, instrument_id: str, period_id: PeriodId) -> float: ...
    def get_debt_balance(self, instrument_id: str, period_id: PeriodId) -> float: ...
    def get_accrued_interest(self, instrument_id: str, period_id: PeriodId) -> float: ...
    def get_total_interest(self, period_id: PeriodId) -> float: ...
    def get_total_interest_cash(self, period_id: PeriodId) -> float: ...
    def get_total_interest_pik(self, period_id: PeriodId) -> float: ...
    def get_total_principal(self, period_id: PeriodId) -> float: ...
    def get_total_debt_balance(self, period_id: PeriodId) -> float: ...
    def get_total_accrued_interest(self, period_id: PeriodId) -> float: ...
    def get_breakdown(self, instrument_id: str, period_id: PeriodId) -> CashflowBreakdown | None: ...
    def get_total_breakdown(self, period_id: PeriodId) -> CashflowBreakdown | None: ...
    def __repr__(self) -> str: ...

def aggregate_instrument_cashflows(
    spec: CapitalStructureSpec,
    periods: list[Period],
    market: MarketContext,
    as_of: date,
) -> CapitalStructureCashflows:
    """Aggregate cashflows across all instruments in a capital structure."""
    ...

__all__ = [
    "CashflowBreakdown",
    "CapitalStructureCashflows",
    "aggregate_instrument_cashflows",
]
