"""Inflation swap instruments (zero-coupon and year-on-year)."""

from __future__ import annotations
from datetime import date
from ....core.currency import Currency
from ....core.money import Money
from ....core.dates.daycount import DayCount
from ....core.dates.schedule import Frequency
from ...common import InstrumentType

class InflationSwapBuilder:
    """Fluent builder returned by :meth:`InflationSwap.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def notional(self, notional: Money) -> InflationSwapBuilder: ...
    def fixed_rate(self, fixed_rate: float) -> InflationSwapBuilder: ...
    def start_date(self, start_date: date) -> InflationSwapBuilder: ...
    def maturity(self, maturity: date) -> InflationSwapBuilder: ...
    def discount_curve(self, discount_curve: str) -> InflationSwapBuilder: ...
    def inflation_index_id(self, inflation_index_id: str) -> InflationSwapBuilder: ...
    def inflation_index(self, inflation_index: str) -> InflationSwapBuilder: ...
    def inflation_curve(self, inflation_curve: str) -> InflationSwapBuilder:
        """Deprecated: use :meth:`inflation_index` instead."""
        ...
    def side(self, side: str) -> InflationSwapBuilder: ...
    def day_count(self, day_count: DayCount | str) -> InflationSwapBuilder: ...
    def lag_override(self, lag_override: str | None = ...) -> InflationSwapBuilder: ...
    def base_cpi(self, base_cpi: float | None = ...) -> InflationSwapBuilder: ...
    def calendar_id(self, calendar_id: str | None = ...) -> InflationSwapBuilder: ...
    def build(self) -> InflationSwap: ...

class InflationSwap:
    """Inflation swap for exchanging fixed rate for inflation-linked payments.

    InflationSwap represents a swap where one party pays a fixed rate and
    receives inflation-linked payments (or vice versa). The swap is typically
    zero-coupon, with all payments occurring at maturity.

    Inflation swaps are used to hedge inflation risk, speculate on inflation
    expectations, and create inflation-linked investment strategies. They require
    a discount curve and an inflation curve.

    Examples
    --------
    Create an inflation swap (pay fixed, receive inflation):

        >>> from finstack.valuations.instruments import InflationSwap
        >>> from finstack import Money, Currency
        >>> from datetime import date
        >>> inflation_swap = (
        ...     InflationSwap
        ...     .builder("INFLATION-SWAP-5Y")
        ...     .notional(Money(10_000_000, Currency("USD")))
        ...     .fixed_rate(0.025)  # 2.5% fixed rate
        ...     .start_date(date(2024, 1, 1))
        ...     .maturity(date(2029, 1, 1))  # 5-year swap
        ...     .discount_curve("USD")
        ...     .inflation_index("US-CPI")
        ...     .side("pay_fixed")  # Pay fixed, receive inflation
        ...     .build()
        ... )

    Notes
    -----
    - Inflation swaps require discount curve and inflation curve
    - Fixed rate is the break-even inflation rate
    - Inflation leg pays based on CPI appreciation
    - Typically zero-coupon (all payments at maturity)
    - Side determines who pays fixed vs receives inflation

    MarketContext Requirements
    -------------------------
    - Discount curve: ``discount_curve`` (required).
    - Inflation curve/index: ``inflation_index`` and/or ``inflation_index_id`` (required for CPI projection).

    See Also
    --------
    :class:`InflationLinkedBond`: Inflation-linked bonds
    :class:`InflationCurve`: CPI curves
    :class:`PricerRegistry`: Pricing entry point

    Sources
    -------
    - Brigo & Mercurio (2006): see ``docs/REFERENCES.md#brigoMercurio2006``.
    - Hull (text): see ``docs/REFERENCES.md#hullOptionsFuturesDerivatives``.
    """

    @classmethod
    def builder(cls, instrument_id: str) -> InflationSwapBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def fixed_rate(self) -> float: ...
    @property
    def maturity(self) -> date: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class YoYInflationSwapBuilder:
    """Fluent builder returned by :meth:`YoYInflationSwap.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def notional(self, notional: Money) -> YoYInflationSwapBuilder: ...
    def fixed_rate(self, fixed_rate: float) -> YoYInflationSwapBuilder: ...
    def start_date(self, start_date: date) -> YoYInflationSwapBuilder: ...
    def maturity(self, maturity: date) -> YoYInflationSwapBuilder: ...
    def frequency(self, frequency: Frequency | str | int) -> YoYInflationSwapBuilder: ...
    def discount_curve(self, discount_curve: str) -> YoYInflationSwapBuilder: ...
    def inflation_index_id(self, inflation_index_id: str) -> YoYInflationSwapBuilder: ...
    def inflation_index(self, inflation_index: str) -> YoYInflationSwapBuilder: ...
    def inflation_curve(self, inflation_curve: str) -> YoYInflationSwapBuilder:
        """Deprecated: use :meth:`inflation_index` instead."""
        ...
    def side(self, side: str) -> YoYInflationSwapBuilder: ...
    def day_count(self, day_count: DayCount | str) -> YoYInflationSwapBuilder: ...
    def lag_override(self, lag_override: str | None = ...) -> YoYInflationSwapBuilder: ...
    def calendar_id(self, calendar_id: str | None = ...) -> YoYInflationSwapBuilder: ...
    def build(self) -> YoYInflationSwap: ...

class YoYInflationSwap:
    """Year-on-year inflation swap.

    Exchanges a fixed coupon stream for year-on-year CPI-linked payments
    at a given frequency.
    """

    @classmethod
    def builder(cls, instrument_id: str) -> YoYInflationSwapBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def fixed_rate(self) -> float: ...
    @property
    def maturity(self) -> date: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
