"""Interest rate future option instrument (builder-only API)."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.money import Money
from ...common import InstrumentType

class IrFutureOptionBuilder:
    """Fluent builder returned by :meth:`IrFutureOption.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def futures_price(self, futures_price: float) -> IrFutureOptionBuilder: ...
    def strike(self, strike: float) -> IrFutureOptionBuilder: ...
    def expiry(self, expiry: date) -> IrFutureOptionBuilder: ...
    def option_type(self, option_type: str) -> IrFutureOptionBuilder: ...
    def money(self, money: Money) -> IrFutureOptionBuilder: ...
    def notional(self, amount: float) -> IrFutureOptionBuilder: ...
    def currency(self, currency: str | Currency) -> IrFutureOptionBuilder: ...
    def tick_size(self, tick_size: float) -> IrFutureOptionBuilder: ...
    def tick_value(self, tick_value: float) -> IrFutureOptionBuilder: ...
    def volatility(self, volatility: float) -> IrFutureOptionBuilder: ...
    def discount_curve(self, curve_id: str) -> IrFutureOptionBuilder: ...
    def build(self) -> IrFutureOption: ...

class IrFutureOption:
    """Exchange-traded option on an interest rate future."""

    @classmethod
    def builder(cls, instrument_id: str) -> IrFutureOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def futures_price(self) -> float: ...
    @property
    def strike(self) -> float: ...
    @property
    def expiry(self) -> date: ...
    @property
    def option_type(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def tick_size(self) -> float: ...
    @property
    def tick_value(self) -> float: ...
    @property
    def volatility(self) -> float: ...
    @property
    def discount_curve(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
