"""Cross-currency swap instrument."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.dates.calendar import BusinessDayConvention
from ....core.dates.daycount import DayCount
from ....core.dates.schedule import Frequency, StubKind
from ...common import InstrumentType

class CrossCurrencySwapBuilder:
    """Fluent builder returned by :meth:`CrossCurrencySwap.builder`."""

    def __init__(self, instrument_id: str) -> None: ...

    # Common fields
    def reporting_currency(self, currency: str | Currency) -> CrossCurrencySwapBuilder: ...
    def notional_exchange(self, exchange: str) -> CrossCurrencySwapBuilder:
        """Set notional exchange convention ('none', 'final', or 'initial_and_final')."""
        ...
    def start_date(self, date: date) -> CrossCurrencySwapBuilder:
        """Set start date for both legs."""
        ...
    def maturity_date(self, date: date) -> CrossCurrencySwapBuilder:
        """Set maturity (end) date for both legs."""
        ...

    # Leg 1 methods
    def leg1_currency(self, currency: str | Currency) -> CrossCurrencySwapBuilder: ...
    def leg1_notional(self, amount: float, currency: str | Currency) -> CrossCurrencySwapBuilder: ...
    def leg1_side(self, side: str) -> CrossCurrencySwapBuilder: ...
    def leg1_forward_curve(self, curve_id: str) -> CrossCurrencySwapBuilder: ...
    def leg1_discount_curve(self, curve_id: str) -> CrossCurrencySwapBuilder: ...
    def leg1_start(self, date: date) -> CrossCurrencySwapBuilder: ...
    def leg1_end(self, date: date) -> CrossCurrencySwapBuilder: ...
    def leg1_frequency(self, frequency: str | Frequency) -> CrossCurrencySwapBuilder: ...
    def leg1_day_count(self, day_count: DayCount | str) -> CrossCurrencySwapBuilder: ...
    def leg1_bdc(self, bdc: BusinessDayConvention | str) -> CrossCurrencySwapBuilder: ...
    def leg1_stub(self, stub: str) -> CrossCurrencySwapBuilder: ...
    def leg1_spread(self, spread: float) -> CrossCurrencySwapBuilder:
        """Set leg 1 spread in basis points (e.g., 10.0 = 10bp)."""
        ...
    def leg1_payment_lag_days(self, days: int) -> CrossCurrencySwapBuilder: ...
    def leg1_calendar_id(self, calendar_id: str | None) -> CrossCurrencySwapBuilder: ...
    def leg1_start_date(self, date: date) -> CrossCurrencySwapBuilder:
        """Set leg 1 start date (overrides shared start_date)."""
        ...
    def leg1_end_date(self, date: date) -> CrossCurrencySwapBuilder:
        """Set leg 1 end date (overrides shared maturity_date)."""
        ...

    # Leg 2 methods
    def leg2_currency(self, currency: str | Currency) -> CrossCurrencySwapBuilder: ...
    def leg2_notional(self, amount: float, currency: str | Currency) -> CrossCurrencySwapBuilder: ...
    def leg2_side(self, side: str) -> CrossCurrencySwapBuilder: ...
    def leg2_forward_curve(self, curve_id: str) -> CrossCurrencySwapBuilder: ...
    def leg2_discount_curve(self, curve_id: str) -> CrossCurrencySwapBuilder: ...
    def leg2_start(self, date: date) -> CrossCurrencySwapBuilder: ...
    def leg2_end(self, date: date) -> CrossCurrencySwapBuilder: ...
    def leg2_frequency(self, frequency: str | Frequency) -> CrossCurrencySwapBuilder: ...
    def leg2_day_count(self, day_count: DayCount | str) -> CrossCurrencySwapBuilder: ...
    def leg2_bdc(self, bdc: BusinessDayConvention | str) -> CrossCurrencySwapBuilder: ...
    def leg2_stub(self, stub: str) -> CrossCurrencySwapBuilder: ...
    def leg2_spread(self, spread: float) -> CrossCurrencySwapBuilder:
        """Set leg 2 spread in basis points (e.g., 10.0 = 10bp)."""
        ...
    def leg2_payment_lag_days(self, days: int) -> CrossCurrencySwapBuilder: ...
    def leg2_calendar_id(self, calendar_id: str | None) -> CrossCurrencySwapBuilder: ...
    def leg2_start_date(self, date: date) -> CrossCurrencySwapBuilder:
        """Set leg 2 start date (overrides shared start_date)."""
        ...
    def leg2_end_date(self, date: date) -> CrossCurrencySwapBuilder:
        """Set leg 2 end date (overrides shared maturity_date)."""
        ...

    def build(self) -> CrossCurrencySwap:
        """Build the CrossCurrencySwap instrument."""
        ...

class CrossCurrencySwap:
    """Cross-currency floating-for-floating swap.

    Swaps floating cashflows in two currencies with optional notional exchange.
    Each leg has its own forward curve, discount curve, and spread.

    Examples
    --------
    Create a USD/EUR cross-currency basis swap:

        >>> from finstack.valuations.instruments import CrossCurrencySwap
        >>> swap = (
        ...     CrossCurrencySwap
        ...     .builder("XCCY_USD_EUR_001")
        ...     .start_date(date(2024, 1, 1))
        ...     .maturity_date(date(2029, 1, 1))
        ...     .reporting_currency("USD")
        ...     .leg1_currency("USD")
        ...     .leg1_notional(10_000_000, "USD")
        ...     .leg1_side("pay")
        ...     .leg1_forward_curve("USD-SOFR")
        ...     .leg1_discount_curve("USD-OIS")
        ...     .leg1_frequency("quarterly")
        ...     .leg1_spread(10.0)
        ...     .leg2_currency("EUR")
        ...     .leg2_notional(9_000_000, "EUR")
        ...     .leg2_side("receive")
        ...     .leg2_forward_curve("EUR-ESTR")
        ...     .leg2_discount_curve("EUR-OIS")
        ...     .leg2_frequency("quarterly")
        ...     .leg2_spread(0.0)
        ...     .notional_exchange("initial_and_final")
        ...     .build()
        ... )

    See Also
    --------
    :class:`InterestRateSwap`: Single-currency interest rate swap
    :class:`BasisSwap`: Single-currency basis swap
    """

    @classmethod
    def builder(cls, instrument_id: str) -> CrossCurrencySwapBuilder:
        """Create a builder for a cross-currency swap."""
        ...
    @property
    def id(self) -> str:
        """Instrument identifier."""
        ...
    @property
    def reporting_currency(self) -> Currency:
        """Reporting currency."""
        ...
    @property
    def instrument_type(self) -> InstrumentType:
        """Instrument type enum."""
        ...
    def __repr__(self) -> str: ...
