"""Calibration configuration types exposed by :mod:`finstack.valuations.calibration`."""

from __future__ import annotations

from typing import Any

from finstack.core.currency import Currency
from finstack.core.dates.daycount import DayCount
from finstack.core.math.interp import ExtrapolationPolicy, InterpStyle

from .validation import ValidationConfig

class ResidualWeightingScheme:
    """Residual weighting for global solve calibration."""

    EQUAL: ResidualWeightingScheme
    LINEAR_TIME: ResidualWeightingScheme
    SQRT_TIME: ResidualWeightingScheme
    INVERSE_DURATION: ResidualWeightingScheme

    @classmethod
    def from_name(cls, name: str) -> ResidualWeightingScheme: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class RateBoundsPolicy:
    """How CalibrationConfig obtains rate bounds."""

    AUTO_CURRENCY: RateBoundsPolicy
    EXPLICIT: RateBoundsPolicy

    @classmethod
    def from_name(cls, name: str) -> RateBoundsPolicy: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class RatesStepConventions:
    """Step-level conventions for rates calibration."""

    def __init__(self, curve_day_count: DayCount | str | None = None) -> None: ...
    @property
    def curve_day_count(self) -> DayCount | None: ...
    def __repr__(self) -> str: ...

class HazardCurveSolveConfig:
    """Hazard-curve specific solver configuration."""

    def __init__(
        self,
        hazard_hard_min: float | None = None,
        hazard_hard_max: float | None = None,
        weighting_scheme: ResidualWeightingScheme | None = None,
        validation_tolerance: float | None = None,
    ) -> None: ...
    @classmethod
    def distressed(cls) -> HazardCurveSolveConfig: ...
    @property
    def hazard_hard_min(self) -> float: ...
    @property
    def hazard_hard_max(self) -> float: ...
    @property
    def weighting_scheme(self) -> ResidualWeightingScheme: ...
    @property
    def validation_tolerance(self) -> float: ...
    def __repr__(self) -> str: ...

class InflationCurveSolveConfig:
    """Inflation-curve specific solver configuration."""

    def __init__(
        self,
        weighting_scheme: ResidualWeightingScheme | None = None,
        validation_tolerance: float | None = None,
    ) -> None: ...
    @property
    def weighting_scheme(self) -> ResidualWeightingScheme: ...
    @property
    def validation_tolerance(self) -> float: ...
    def __repr__(self) -> str: ...

class DiscountCurveSolveConfig:
    """Discount-curve specific solver configuration."""

    def __init__(
        self,
        scan_grid_points: int | None = None,
        min_scan_grid_points: int | None = None,
        scan_grid_step: float | None = None,
        df_hard_min: float | None = None,
        df_hard_max: float | None = None,
        min_t_spot: float | None = None,
        interp_style: InterpStyle | str | None = None,
        extrapolation_policy: ExtrapolationPolicy | str | None = None,
        bootstrap_seed_global_solve: bool | None = None,
        allow_non_monotonic_final: bool | None = None,
        weighting_scheme: ResidualWeightingScheme | None = None,
        jacobian_step_size: float | None = None,
        validation_tolerance: float | None = None,
    ) -> None: ...
    @property
    def scan_grid_points(self) -> int: ...
    @property
    def min_scan_grid_points(self) -> int: ...
    @property
    def scan_grid_step(self) -> float: ...
    @property
    def df_hard_min(self) -> float: ...
    @property
    def df_hard_max(self) -> float: ...
    @property
    def min_t_spot(self) -> float: ...
    @property
    def interp_style(self) -> InterpStyle: ...
    @property
    def extrapolation_policy(self) -> ExtrapolationPolicy: ...
    @property
    def bootstrap_seed_global_solve(self) -> bool: ...
    @property
    def allow_non_monotonic_final(self) -> bool | None: ...
    @property
    def weighting_scheme(self) -> ResidualWeightingScheme: ...
    @property
    def jacobian_step_size(self) -> float: ...
    @property
    def validation_tolerance(self) -> float: ...
    def __repr__(self) -> str: ...

class SolverKind:
    """Solver kind enumeration."""

    NEWTON: SolverKind
    BRENT: SolverKind

    @classmethod
    def from_name(cls, name: str) -> SolverKind: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class CalibrationMethod:
    """Calibration method selection."""

    BOOTSTRAP: CalibrationMethod
    GLOBAL_SOLVE: CalibrationMethod

    @classmethod
    def from_name(cls, name: str, use_analytical_jacobian: bool = False) -> CalibrationMethod: ...
    @property
    def name(self) -> str: ...
    @property
    def use_analytical_jacobian(self) -> bool: ...
    def with_use_analytical_jacobian(self, value: bool) -> CalibrationMethod: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ValidationMode:
    """Runtime validation behavior for arbitrage/consistency checks."""

    WARN: ValidationMode
    ERROR: ValidationMode

    @classmethod
    def from_name(cls, name: str) -> ValidationMode: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class RateBounds:
    """Bounds for forward/zero rates during calibration."""

    def __init__(self, min_rate: float = -0.02, max_rate: float = 0.50) -> None: ...
    @classmethod
    def emerging_markets(cls) -> RateBounds: ...
    @classmethod
    def negative_rate_environment(cls) -> RateBounds: ...
    @classmethod
    def stress_test(cls) -> RateBounds: ...
    @classmethod
    def for_currency(cls, currency: Currency | str) -> RateBounds: ...
    @property
    def min_rate(self) -> float: ...
    @property
    def max_rate(self) -> float: ...
    def contains(self, rate: float) -> bool: ...
    def clamp(self, rate: float) -> float: ...
    def __repr__(self) -> str: ...

class CalibrationConfig:
    """Calibration configuration."""

    def __init__(
        self,
        *,
        tolerance: float | None = None,
        max_iterations: int | None = None,
        use_parallel: bool | None = None,
        verbose: bool | None = None,
        solver_kind: SolverKind | None = None,
        calibration_method: CalibrationMethod | None = None,
        validation_mode: ValidationMode | None = None,
        validation: ValidationConfig | None = None,
        rate_bounds: RateBounds | None = None,
        rate_bounds_policy: RateBoundsPolicy | None = None,
        explain: bool | None = None,
        compute_diagnostics: bool | None = None,
        discount_curve: DiscountCurveSolveConfig | None = None,
        hazard_curve: HazardCurveSolveConfig | None = None,
        inflation_curve: InflationCurveSolveConfig | None = None,
    ) -> None: ...
    @classmethod
    def conservative(cls) -> CalibrationConfig: ...
    @classmethod
    def aggressive(cls) -> CalibrationConfig: ...
    @classmethod
    def fast(cls) -> CalibrationConfig: ...
    @property
    def tolerance(self) -> float: ...
    @property
    def max_iterations(self) -> int: ...
    @property
    def use_parallel(self) -> bool: ...
    @property
    def verbose(self) -> bool: ...
    @property
    def solver_kind(self) -> SolverKind: ...
    @property
    def calibration_method(self) -> CalibrationMethod: ...
    @property
    def validation_mode(self) -> ValidationMode: ...
    @property
    def validation_config(self) -> ValidationConfig: ...
    @property
    def rate_bounds(self) -> RateBounds: ...
    @property
    def rate_bounds_policy(self) -> RateBoundsPolicy: ...
    @property
    def explain_enabled(self) -> bool: ...
    @property
    def compute_diagnostics(self) -> bool: ...
    @property
    def discount_curve(self) -> DiscountCurveSolveConfig: ...
    @property
    def hazard_curve(self) -> HazardCurveSolveConfig: ...
    @property
    def inflation_curve(self) -> InflationCurveSolveConfig: ...
    def with_tolerance(self, tolerance: float) -> CalibrationConfig: ...
    def with_max_iterations(self, max_iterations: int) -> CalibrationConfig: ...
    def with_parallel(self, flag: bool) -> CalibrationConfig: ...
    def with_verbose(self, verbose: bool) -> CalibrationConfig: ...
    def with_solver_kind(self, kind: SolverKind) -> CalibrationConfig: ...
    def with_calibration_method(self, method: CalibrationMethod) -> CalibrationConfig: ...
    def with_validation_mode(self, mode: ValidationMode) -> CalibrationConfig: ...
    def with_validation_config(self, config: ValidationConfig) -> CalibrationConfig: ...
    def with_rate_bounds(self, bounds: RateBounds) -> CalibrationConfig: ...
    def with_rate_bounds_policy(self, policy: RateBoundsPolicy) -> CalibrationConfig: ...
    def with_explain(self) -> CalibrationConfig: ...
    def with_compute_diagnostics(self, enabled: bool) -> CalibrationConfig: ...
    def with_discount_curve(self, config: DiscountCurveSolveConfig) -> CalibrationConfig: ...
    def with_hazard_curve(self, config: HazardCurveSolveConfig) -> CalibrationConfig: ...
    def with_inflation_curve(self, config: InflationCurveSolveConfig) -> CalibrationConfig: ...
    def with_rate_bounds_for_currency(self, currency: Currency | str) -> CalibrationConfig: ...
    def effective_rate_bounds(self, currency: Currency | str) -> RateBounds: ...
    def __repr__(self) -> str: ...
