"""Calibration configuration types exposed by :mod:`finstack.valuations.calibration`."""

from __future__ import annotations

from .validation import ValidationConfig

class SolverKind:
    """Solver kind enumeration."""

    NEWTON: SolverKind
    BRENT: SolverKind

    @classmethod
    def from_name(cls, name: str) -> SolverKind: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __richcmp__(self, other: object, op: int) -> object: ...

class CalibrationMethod:
    """Calibration method selection."""

    BOOTSTRAP: CalibrationMethod
    GLOBAL_SOLVE: CalibrationMethod

    @classmethod
    def from_name(cls, name: str, use_analytical_jacobian: bool = False) -> CalibrationMethod: ...
    @property
    def name(self) -> str: ...
    @property
    def use_analytical_jacobian(self) -> bool: ...
    def with_use_analytical_jacobian(self, value: bool) -> CalibrationMethod: ...
    def __repr__(self) -> str: ...

class ValidationMode:
    """Runtime validation behavior for arbitrage/consistency checks."""

    WARN: ValidationMode
    ERROR: ValidationMode

    @classmethod
    def from_name(cls, name: str) -> ValidationMode: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RateBounds:
    """Bounds for forward/zero rates during calibration."""

    def __init__(self, min_rate: float = -0.02, max_rate: float = 0.50) -> None: ...
    @classmethod
    def emerging_markets(cls) -> RateBounds: ...
    @classmethod
    def negative_rate_environment(cls) -> RateBounds: ...
    @classmethod
    def stress_test(cls) -> RateBounds: ...
    @property
    def min_rate(self) -> float: ...
    @property
    def max_rate(self) -> float: ...
    def __repr__(self) -> str: ...

class CalibrationConfig:
    """Calibration configuration."""

    def __init__(
        self,
        *,
        tolerance: float | None = None,
        max_iterations: int | None = None,
        use_parallel: bool | None = None,
        verbose: bool | None = None,
        solver_kind: SolverKind | None = None,
        calibration_method: CalibrationMethod | None = None,
        validation_mode: ValidationMode | None = None,
        validation: ValidationConfig | None = None,
        rate_bounds: RateBounds | None = None,
        explain: bool | None = None,
    ) -> None: ...
    @property
    def tolerance(self) -> float: ...
    @property
    def max_iterations(self) -> int: ...
    @property
    def use_parallel(self) -> bool: ...
    @property
    def verbose(self) -> bool: ...
    @property
    def solver_kind(self) -> SolverKind: ...
    @property
    def calibration_method(self) -> CalibrationMethod: ...
    @property
    def validation_mode(self) -> ValidationMode: ...
    @property
    def validation_config(self) -> ValidationConfig: ...
    @property
    def rate_bounds(self) -> RateBounds: ...
    @property
    def explain_enabled(self) -> bool: ...
    def with_tolerance(self, tolerance: float) -> CalibrationConfig: ...
    def with_max_iterations(self, max_iterations: int) -> CalibrationConfig: ...
    def with_parallel(self, flag: bool) -> CalibrationConfig: ...
    def with_verbose(self, verbose: bool) -> CalibrationConfig: ...
    def with_solver_kind(self, kind: SolverKind) -> CalibrationConfig: ...
    def with_calibration_method(self, method: CalibrationMethod) -> CalibrationConfig: ...
    def with_validation_mode(self, mode: ValidationMode) -> CalibrationConfig: ...
    def with_validation_config(self, config: ValidationConfig) -> CalibrationConfig: ...
    def with_rate_bounds(self, bounds: RateBounds) -> CalibrationConfig: ...
    def with_explain(self) -> CalibrationConfig: ...
    def __repr__(self) -> str: ...
