"""Calibration configuration types exposed by :mod:`finstack.valuations.calibration`."""

from __future__ import annotations

from typing import Dict, Optional

class SolverKind:
    """Solver kind enumeration."""

    NEWTON: SolverKind
    BRENT: SolverKind
    GLOBAL_NEWTON: SolverKind

    @classmethod
    def from_name(cls, name: str) -> SolverKind: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __richcmp__(self, other: object, op: int) -> object: ...

class CalibrationMethod:
    """Calibration method selection."""

    BOOTSTRAP: CalibrationMethod
    GLOBAL_SOLVE: CalibrationMethod

    @classmethod
    def from_name(cls, name: str, use_analytical_jacobian: bool = False) -> CalibrationMethod: ...
    @property
    def name(self) -> str: ...
    @property
    def use_analytical_jacobian(self) -> bool: ...
    def with_use_analytical_jacobian(self, value: bool) -> CalibrationMethod: ...
    def __repr__(self) -> str: ...

class ValidationMode:
    """Runtime validation behavior for arbitrage/consistency checks."""

    WARN: ValidationMode
    ERROR: ValidationMode

    @classmethod
    def from_name(cls, name: str) -> ValidationMode: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RateBounds:
    """Bounds for forward/zero rates during calibration."""

    def __init__(self, min_rate: float = -0.02, max_rate: float = 0.50) -> None: ...
    @classmethod
    def emerging_markets(cls) -> RateBounds: ...
    @classmethod
    def negative_rate_environment(cls) -> RateBounds: ...
    @classmethod
    def stress_test(cls) -> RateBounds: ...
    @property
    def min_rate(self) -> float: ...
    @property
    def max_rate(self) -> float: ...
    def __repr__(self) -> str: ...

class MultiCurveConfig:
    """Multi-curve calibration configuration."""

    def __init__(self, calibrate_basis: bool = True, enforce_separation: bool = True) -> None: ...
    @classmethod
    def new_standard(cls) -> MultiCurveConfig: ...
    @property
    def calibrate_basis(self) -> bool: ...
    @property
    def enforce_separation(self) -> bool: ...
    def with_calibrate_basis(self, value: bool) -> MultiCurveConfig: ...
    def with_enforce_separation(self, value: bool) -> MultiCurveConfig: ...
    def __repr__(self) -> str: ...

class CalibrationConfig:
    """Calibration configuration."""

    def __init__(
        self,
        *,
        tolerance: float = 1e-10,
        max_iterations: int = 100,
        use_parallel: bool = False,
        random_seed: Optional[int] = 42,
        verbose: bool = False,
        solver_kind: Optional[SolverKind] = None,
        multi_curve: Optional[MultiCurveConfig] = None,
        entity_seniority: Optional[Dict[str, str]] = None,
        calibration_method: Optional[CalibrationMethod] = None,
        use_fd_sabr_gradients: Optional[bool] = None,
        validation_mode: Optional[ValidationMode] = None,
        validation: Optional["ValidationConfig"] = None,
        rate_bounds: Optional[RateBounds] = None,
        explain: Optional[bool] = None,
    ) -> None: ...
    @classmethod
    def multi_curve(cls) -> CalibrationConfig: ...
    @property
    def tolerance(self) -> float: ...
    @property
    def max_iterations(self) -> int: ...
    @property
    def use_parallel(self) -> bool: ...
    @property
    def random_seed(self) -> Optional[int]: ...
    @property
    def verbose(self) -> bool: ...
    @property
    def solver_kind(self) -> SolverKind: ...
    @property
    def calibration_method(self) -> CalibrationMethod: ...
    @property
    def multi_curve_config(self) -> MultiCurveConfig: ...
    @property
    def entity_seniority(self) -> Dict[str, str]: ...
    @property
    def use_fd_sabr_gradients(self) -> bool: ...
    @property
    def validation_mode(self) -> ValidationMode: ...
    @property
    def validation_config(self) -> "ValidationConfig": ...
    @property
    def rate_bounds(self) -> RateBounds: ...
    @property
    def explain_enabled(self) -> bool: ...
    def with_tolerance(self, tolerance: float) -> CalibrationConfig: ...
    def with_max_iterations(self, max_iterations: int) -> CalibrationConfig: ...
    def with_parallel(self, flag: bool) -> CalibrationConfig: ...
    def with_random_seed(self, seed: Optional[int]) -> CalibrationConfig: ...
    def with_verbose(self, verbose: bool) -> CalibrationConfig: ...
    def with_solver_kind(self, kind: SolverKind) -> CalibrationConfig: ...
    def with_calibration_method(self, method: CalibrationMethod) -> CalibrationConfig: ...
    def with_multi_curve_config(self, config: MultiCurveConfig) -> CalibrationConfig: ...
    def with_entity_seniority(self, mapping: Dict[str, str]) -> CalibrationConfig: ...
    def with_use_fd_sabr_gradients(self, flag: bool) -> CalibrationConfig: ...
    def with_validation_mode(self, mode: ValidationMode) -> CalibrationConfig: ...
    def with_validation_config(self, config: "ValidationConfig") -> CalibrationConfig: ...
    def with_rate_bounds(self, bounds: RateBounds) -> CalibrationConfig: ...
    def with_explain(self) -> CalibrationConfig: ...
    def __repr__(self) -> str: ...

from .validation import ValidationConfig  # noqa: E402
