"""Calibration methods and calibrator classes exposed by :mod:`finstack.valuations.calibration`."""

from __future__ import annotations

from typing import Any, Optional, Sequence, Tuple

from .config import CalibrationConfig

class DiscountCurveCalibrator:
    def __init__(self, curve_id: str, base_date: Any, currency: Any) -> None: ...
    def with_config(self, config: CalibrationConfig) -> DiscountCurveCalibrator: ...
    def with_multi_curve_config(self, multi_curve: Any) -> DiscountCurveCalibrator: ...
    def with_solve_interp(self, interp: Any) -> DiscountCurveCalibrator: ...
    def with_calibration_method(self, method: Any) -> DiscountCurveCalibrator: ...
    def with_extrapolation(self, policy: Any) -> DiscountCurveCalibrator: ...
    def with_calendar_id(self, calendar_id: str) -> DiscountCurveCalibrator: ...
    def with_settlement_days(self, days: int) -> DiscountCurveCalibrator: ...
    def with_payment_delay(self, days: int) -> DiscountCurveCalibrator: ...
    def with_curve_day_count(self, day_count: Any) -> DiscountCurveCalibrator: ...
    def calibrate(self, quotes: Sequence[Any], market: Optional[Any] = None) -> Tuple[Any, Any]: ...

class ForwardCurveCalibrator:
    def __init__(
        self,
        curve_id: str,
        tenor_years: float,
        base_date: Any,
        currency: Any,
        discount_curve_id: str,
    ) -> None: ...
    def with_config(self, config: CalibrationConfig) -> ForwardCurveCalibrator: ...
    def with_solve_interp(self, interp: Any) -> ForwardCurveCalibrator: ...
    def with_time_dc(self, day_count: Any) -> ForwardCurveCalibrator: ...
    def calibrate(self, quotes: Sequence[Any], market: Any) -> Tuple[Any, Any]: ...

class HazardCurveCalibrator:
    def __init__(
        self,
        entity: str,
        seniority: str,
        recovery_rate: float,
        base_date: Any,
        currency: Any,
        discount_curve: Optional[str] = None,
    ) -> None: ...
    def with_config(self, config: CalibrationConfig) -> HazardCurveCalibrator: ...
    def with_par_interp(self, interpolation: str) -> HazardCurveCalibrator: ...
    def calibrate(self, quotes: Sequence[Any], market: Any) -> Tuple[Any, Any]: ...

class InflationCurveCalibrator:
    def __init__(
        self,
        curve_id: str,
        base_date: Any,
        currency: Any,
        base_cpi: float,
        discount_curve_id: str,
    ) -> None: ...
    def with_config(self, config: CalibrationConfig) -> InflationCurveCalibrator: ...
    def with_solve_interp(self, interp: Any) -> InflationCurveCalibrator: ...
    def with_time_dc(self, day_count: Any) -> InflationCurveCalibrator: ...
    def with_accrual_dc(self, day_count: Any) -> InflationCurveCalibrator: ...
    def with_inflation_lag_months(self, months: int) -> InflationCurveCalibrator: ...
    def with_inflation_lag_days(self, days: int) -> InflationCurveCalibrator: ...
    def with_no_inflation_lag(self) -> InflationCurveCalibrator: ...
    def with_seasonality_adjustments(self, adjustments: Sequence[float]) -> InflationCurveCalibrator: ...
    def with_inflation_interpolation(self, interpolation: Optional[str]) -> InflationCurveCalibrator: ...
    def calibrate(self, quotes: Sequence[Any], market: Optional[Any] = None) -> Tuple[Any, Any]: ...

class VolSurfaceCalibrator:
    def __init__(
        self, surface_id: str, beta: float, target_expiries: Sequence[float], target_strikes: Sequence[float]
    ) -> None: ...
    def with_base_date(self, base_date: Any) -> VolSurfaceCalibrator: ...
    def with_config(self, config: CalibrationConfig) -> VolSurfaceCalibrator: ...
    def with_base_currency(self, currency: Any) -> VolSurfaceCalibrator: ...
    def with_time_dc(self, day_count: Any) -> VolSurfaceCalibrator: ...
    def with_surface_interp(self, interpolation: Optional[str]) -> VolSurfaceCalibrator: ...
    def with_discount_id(self, discount_curve_id: str) -> VolSurfaceCalibrator: ...
    def with_spot_override(self, spot: float) -> VolSurfaceCalibrator: ...
    def with_dividend_yield_override(self, dividend_yield: float) -> VolSurfaceCalibrator: ...
    def calibrate(self, quotes: Sequence[Any], market: Any) -> Tuple[Any, Any]: ...

class BaseCorrelationCalibrator:
    def __init__(self, index_id: str, series: int, maturity_years: float, base_date: Any) -> None: ...
    def with_config(self, config: CalibrationConfig) -> BaseCorrelationCalibrator: ...
    def with_detachment_points(self, points: Sequence[float]) -> BaseCorrelationCalibrator: ...
    def with_discount_curve_id(self, discount_curve_id: Any) -> BaseCorrelationCalibrator: ...
    def calibrate(self, quotes: Sequence[Any], market: Any) -> Tuple[Any, Any]: ...
