"""Calibration report types exposed by :mod:`finstack.valuations.calibration`."""

from __future__ import annotations

from typing import Any, Dict

from .config import SolverKind

class QuoteQuality:
    def __init__(
        self,
        quote_label: str,
        target_value: float,
        fitted_value: float,
        residual: float,
        sensitivity: float,
    ) -> None: ...
    @property
    def quote_label(self) -> str: ...
    @property
    def target_value(self) -> float: ...
    @property
    def fitted_value(self) -> float: ...
    @property
    def residual(self) -> float: ...
    @property
    def sensitivity(self) -> float: ...
    def __repr__(self) -> str: ...

class CalibrationDiagnostics:
    def __init__(
        self,
        per_quote: list[QuoteQuality],
        *,
        condition_number: float | None = ...,
        singular_values: list[float] | None = ...,
        max_residual: float,
        rms_residual: float,
        r_squared: float | None = ...,
    ) -> None: ...
    @property
    def per_quote(self) -> list[QuoteQuality]: ...
    @property
    def condition_number(self) -> float | None: ...
    @property
    def singular_values(self) -> list[float] | None: ...
    @property
    def max_residual(self) -> float: ...
    @property
    def rms_residual(self) -> float: ...
    @property
    def r_squared(self) -> float | None: ...
    def to_dict(self) -> Any: ...
    def __repr__(self) -> str: ...

class CalibrationReport:
    @property
    def success(self) -> bool: ...
    @property
    def residuals(self) -> Dict[str, float]: ...
    @property
    def iterations(self) -> int: ...
    @property
    def objective_value(self) -> float: ...
    @property
    def max_residual(self) -> float: ...
    @property
    def rmse(self) -> float: ...
    @property
    def convergence_reason(self) -> str: ...
    @property
    def metadata(self) -> Dict[str, str]: ...
    @property
    def results_meta(self) -> Any: ...
    @property
    def explanation(self) -> Any | None: ...
    @property
    def validation_passed(self) -> bool: ...
    @property
    def validation_error(self) -> str | None: ...
    @property
    def solver_config(self) -> SolverKind: ...
    @property
    def model_version(self) -> str | None: ...
    @property
    def diagnostics(self) -> CalibrationDiagnostics | None: ...
    def explain_json(self) -> str | None: ...
    def to_dict(self) -> Any: ...
    def explain(self) -> Any | None: ...
    def __repr__(self) -> str: ...
