"""Calibration report types exposed by :mod:`finstack.valuations.calibration`."""

from __future__ import annotations

from typing import Any, Dict, Optional

class CalibrationReport:
    @property
    def success(self) -> bool: ...
    @property
    def residuals(self) -> Dict[str, float]: ...
    @property
    def iterations(self) -> int: ...
    @property
    def objective_value(self) -> float: ...
    @property
    def max_residual(self) -> float: ...
    @property
    def rmse(self) -> float: ...
    @property
    def convergence_reason(self) -> str: ...
    @property
    def metadata(self) -> Dict[str, str]: ...
    @property
    def results_meta(self) -> Any: ...
    @property
    def explanation(self) -> Optional[Any]: ...
    def explain_json(self) -> Optional[str]: ...
    def to_dict(self) -> Any: ...
    def explain(self) -> Optional[Any]: ...
    def __repr__(self) -> str: ...
