//! Yield-to-N-years calculators for term loans.
//!
//! Computes IRR to fixed horizons (2y, 3y, 4y) using kind-aware cashflow
//! filtering and outstanding principal at the horizon date for redemption.

use crate::instruments::TermLoan;
use crate::metrics::{MetricCalculator, MetricContext};
use finstack_core::dates::Date;

use super::irr_helpers::solve_irr_to_date;

/// Compute a date N years ahead of `as_of`, with leap-year fallback.
///
/// For Feb 29 valuations in non-leap target years, falls back to Feb 28.
/// Returns an error if the target date cannot be constructed at all.
fn years_ahead(as_of: Date, years: i32) -> finstack_core::Result<Date> {
    match Date::from_calendar_date(as_of.year() + years, as_of.month(), as_of.day()) {
        Ok(d) => Ok(d),
        Err(_) => {
            // Feb 29 → Feb 28 fallback for leap year → non-leap year transitions
            Date::from_calendar_date(as_of.year() + years, as_of.month(), 28)
                .map_err(|_| finstack_core::InputError::InvalidDateRange.into())
        }
    }
}

macro_rules! define_ytn {
    ($name:ident, $years:expr) => {
        /// Yield-to-N-year calculator for callable term loans (generated by macro)
        pub struct $name;

        impl MetricCalculator for $name {
            fn calculate(&self, context: &mut MetricContext) -> finstack_core::Result<f64> {
                let loan: &TermLoan = context.instrument_as()?;
                let as_of = context.as_of;

                let target = years_ahead(as_of, $years)?;
                let exercise_date = if target < loan.maturity {
                    target
                } else {
                    loan.maturity
                };
                if exercise_date <= as_of {
                    return Err(finstack_core::InputError::InvalidDateRange.into());
                }

                solve_irr_to_date(
                    loan,
                    &context.curves,
                    as_of,
                    context.base_value,
                    exercise_date,
                )
            }
        }
    };
}

define_ytn!(Yt2yCalculator, 2);
define_ytn!(Yt3yCalculator, 3);
define_ytn!(Yt4yCalculator, 4);
