"""Discounted cash flow instrument bindings."""

from __future__ import annotations
from typing import Self

from datetime import date

from ....core.currency import Currency
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class TerminalValueSpec:
    """Terminal value specification for DCF analysis."""

    @classmethod
    def gordon_growth(cls, growth_rate: float) -> TerminalValueSpec: ...
    @classmethod
    def exit_multiple(cls, terminal_metric: float, multiple: float) -> TerminalValueSpec: ...
    @classmethod
    def h_model(
        cls, high_growth_rate: float, stable_growth_rate: float, half_life_years: float
    ) -> TerminalValueSpec: ...
    @property
    def growth_rate(self) -> float | None: ...
    @property
    def terminal_metric(self) -> float | None: ...
    @property
    def multiple(self) -> float | None: ...
    @property
    def high_growth_rate(self) -> float | None: ...
    @property
    def stable_growth_rate(self) -> float | None: ...
    @property
    def half_life_years(self) -> float | None: ...
    @property
    def name(self) -> str: ...

class EquityBridge:
    def __init__(
        self,
        total_debt: float = 0.0,
        cash: float = 0.0,
        preferred_equity: float = 0.0,
        minority_interest: float = 0.0,
        non_operating_assets: float = 0.0,
        other_adjustments: list[tuple[str, float]] | None = None,
    ) -> None: ...
    @property
    def total_debt(self) -> float: ...
    @property
    def cash(self) -> float: ...
    @property
    def preferred_equity(self) -> float: ...
    @property
    def minority_interest(self) -> float: ...
    @property
    def non_operating_assets(self) -> float: ...
    @property
    def other_adjustments(self) -> list[tuple[str, float]]: ...
    def net_adjustment(self) -> float: ...
    def to_json(self) -> str:
        """Serialize to JSON in envelope format.

        Returns:
            str: JSON string with schema version and tagged instrument spec.
        """
        ...

    @classmethod
    def from_json(cls, json_str: str) -> "Self":
        """Deserialize from JSON in envelope format.

        Args:
            json_str: JSON string in envelope format.

        Returns:
            The deserialized instrument.

        Raises:
            ValueError: If JSON is malformed or contains a different instrument type.
        """
        ...

class ValuationDiscounts:
    def __init__(
        self,
        dlom: float | None = None,
        dloc: float | None = None,
        other_discount: float | None = None,
    ) -> None: ...
    @property
    def dlom(self) -> float | None: ...
    @property
    def dloc(self) -> float | None: ...
    @property
    def other_discount(self) -> float | None: ...
    def apply(self, equity_value: float) -> float: ...

class DilutionSecurity:
    def __init__(self, name: str, quantity: float, exercise_price: float) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def quantity(self) -> float: ...
    @property
    def exercise_price(self) -> float: ...

class DiscountedCashFlowBuilder:
    def __init__(self, instrument_id: str) -> None: ...
    def currency(self, currency: str | Currency) -> DiscountedCashFlowBuilder: ...
    def flows(self, flows: list[tuple[date, float]]) -> DiscountedCashFlowBuilder: ...
    def wacc(self, wacc: float) -> DiscountedCashFlowBuilder: ...
    def terminal_value(self, terminal_value: TerminalValueSpec) -> DiscountedCashFlowBuilder: ...
    def net_debt(self, net_debt: float) -> DiscountedCashFlowBuilder: ...
    def valuation_date(self, valuation_date: date) -> DiscountedCashFlowBuilder: ...
    def discount_curve(self, discount_curve_id: str) -> DiscountedCashFlowBuilder: ...
    def disc_id(self, discount_curve_id: str) -> DiscountedCashFlowBuilder: ...
    def mid_year_convention(self, enabled: bool) -> DiscountedCashFlowBuilder: ...
    def equity_bridge(self, equity_bridge: EquityBridge) -> DiscountedCashFlowBuilder: ...
    def shares_outstanding(self, shares_outstanding: float) -> DiscountedCashFlowBuilder: ...
    def dilution_securities(self, dilution_securities: list[DilutionSecurity]) -> DiscountedCashFlowBuilder: ...
    def valuation_discounts(self, valuation_discounts: ValuationDiscounts) -> DiscountedCashFlowBuilder: ...
    def build(self) -> DiscountedCashFlow: ...

class DiscountedCashFlow:
    @classmethod
    def builder(cls, instrument_id: str) -> DiscountedCashFlowBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def flows(self) -> list[tuple[date, float]]: ...
    @property
    def wacc(self) -> float: ...
    @property
    def terminal_value(self) -> TerminalValueSpec: ...
    @property
    def net_debt(self) -> float: ...
    @property
    def valuation_date(self) -> date: ...
    @property
    def discount_curve(self) -> str: ...
    @property
    def mid_year_convention(self) -> bool: ...
    @property
    def equity_bridge(self) -> EquityBridge | None: ...
    @property
    def shares_outstanding(self) -> float | None: ...
    @property
    def dilution_securities(self) -> list[DilutionSecurity]: ...
    @property
    def valuation_discounts(self) -> ValuationDiscounts | None: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def calculate_pv_explicit_flows(self) -> float: ...
    def calculate_terminal_value(self) -> float: ...
    def discount_terminal_value(self, terminal_value: float) -> float: ...
    def effective_net_debt(self) -> float: ...
    def diluted_shares(self, equity_value: float) -> float | None: ...
    def equity_value_per_share(self, equity_value: float) -> float | None: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
