"""DCF terminal value types."""

from __future__ import annotations

class TerminalValueSpec:
    """Terminal value specification for DCF analysis."""
    @classmethod
    def gordon_growth(cls, growth_rate: float) -> TerminalValueSpec: ...
    @classmethod
    def exit_multiple(cls, terminal_metric: float, multiple: float) -> TerminalValueSpec: ...
    @classmethod
    def h_model(
        cls, high_growth_rate: float, stable_growth_rate: float, half_life_years: float
    ) -> TerminalValueSpec: ...
    @property
    def growth_rate(self) -> float | None: ...
    @property
    def terminal_metric(self) -> float | None: ...
    @property
    def multiple(self) -> float | None: ...
    @property
    def high_growth_rate(self) -> float | None: ...
    @property
    def stable_growth_rate(self) -> float | None: ...
    @property
    def half_life_years(self) -> float | None: ...
    @property
    def name(self) -> str: ...
