"""Equity option instrument (builder-only API)."""

from __future__ import annotations
from datetime import date
from ....core.money import Money
from ....core.currency import Currency
from ....core.dates.daycount import DayCount
from ....core.market_data.context import MarketContext
from ...common import InstrumentType

class EquityOptionGreeks:
    """Greeks for an equity option (delta, gamma, vega, theta, rho)."""

    @property
    def delta(self) -> float: ...
    @property
    def gamma(self) -> float: ...
    @property
    def vega(self) -> float: ...
    @property
    def theta(self) -> float: ...
    @property
    def rho(self) -> float: ...
    def __repr__(self) -> str: ...

class EquityOptionBuilder:
    """Fluent builder returned by :meth:`EquityOption.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def ticker(self, ticker: str) -> "EquityOptionBuilder": ...
    def strike(self, strike: float) -> "EquityOptionBuilder": ...
    def option_type(self, option_type: str) -> "EquityOptionBuilder": ...
    def exercise_style(self, exercise_style: str) -> "EquityOptionBuilder": ...
    def expiry(self, expiry: date) -> "EquityOptionBuilder": ...
    def notional(self, notional: Money) -> "EquityOptionBuilder": ...
    def day_count(self, day_count: DayCount | str) -> "EquityOptionBuilder": ...
    def settlement(self, settlement: str) -> "EquityOptionBuilder": ...
    def disc_id(self, curve_id: str) -> "EquityOptionBuilder": ...
    def spot_id(self, spot_id: str) -> "EquityOptionBuilder": ...
    def vol_surface(self, vol_surface: str) -> "EquityOptionBuilder": ...
    def div_yield_id(self, div_yield_id: str | None = ...) -> "EquityOptionBuilder": ...
    def add_discrete_dividend(self, ex_date: date, amount: float) -> "EquityOptionBuilder": ...
    def exercise_schedule(self, dates: list[date]) -> "EquityOptionBuilder": ...
    def build(self) -> "EquityOption": ...

class EquityOption:
    """Equity option instrument for pricing European and American options.

    EquityOption represents a call or put option on a single equity or equity
    index. Options are priced using Black-Scholes or similar models, requiring
    a discount curve, spot price, and volatility surface in the MarketContext.

    Examples
    --------
    Create a European call option:

        >>> from datetime import date
        >>> from finstack.core.currency import Currency
        >>> from finstack.core.money import Money
        >>> from finstack.valuations.instruments import EquityOption
        >>> option = (
        ...     EquityOption
        ...     .builder("SPX-CALL-4500")
        ...     .ticker("SPX")
        ...     .strike(4500.0)
        ...     .expiry(date(2024, 12, 20))
        ...     .option_type("call")
        ...     .exercise_style("european")
        ...     .disc_id("USD-OIS")
        ...     .spot_id("SPX")
        ...     .vol_surface("EQUITY-VOL")
        ...     .build()
        ... )

    MarketContext Requirements
    -------------------------
    - Discount curve: ``discount_curve`` (required).
    - Spot price: ``spot_id`` (required).
    - Volatility surface: ``vol_surface`` (required).
    - Dividend yield: ``div_yield_id`` (optional).

    Sources
    -------
    - Black & Scholes (1973): see ``docs/REFERENCES.md#blackScholes1973``.
    - Merton (1973): see ``docs/REFERENCES.md#merton1973``.
    - Hull (text): see ``docs/REFERENCES.md#hullOptionsFuturesDerivatives``.
    """

    @classmethod
    def builder(cls, instrument_id: str) -> EquityOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def ticker(self) -> str: ...
    @property
    def strike(self) -> float: ...
    @property
    def notional(self) -> Money: ...
    @property
    def option_type(self) -> str: ...
    @property
    def exercise_style(self) -> str: ...
    @property
    def expiry(self) -> date: ...
    @property
    def discount_curve(self) -> str: ...
    @property
    def vol_surface(self) -> str: ...
    @property
    def day_count(self) -> DayCount: ...
    @property
    def settlement(self) -> str: ...
    @property
    def spot_id(self) -> str: ...
    @property
    def div_yield_id(self) -> str | None: ...
    @property
    def discrete_dividends(self) -> list[tuple[date, float]]: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def greeks(self, market: MarketContext, as_of: date) -> EquityOptionGreeks: ...
    def delta(self, market: MarketContext, as_of: date) -> float: ...
    def gamma(self, market: MarketContext, as_of: date) -> float: ...
    def vega(self, market: MarketContext, as_of: date) -> float: ...
    def theta(self, market: MarketContext, as_of: date) -> float: ...
    def rho(self, market: MarketContext, as_of: date) -> float: ...
    def implied_vol(self, market: MarketContext, as_of: date, market_price: float) -> float: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
