"""Volatility index future instrument (builder-only API)."""

from __future__ import annotations
from datetime import date

from ....core.currency import Currency
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class VolatilityIndexFutureBuilder:
    """Fluent builder returned by :meth:`VolatilityIndexFuture.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def notional(self, amount: float) -> "VolatilityIndexFutureBuilder": ...
    def currency(self, currency: str | Currency) -> "VolatilityIndexFutureBuilder": ...
    def money(self, money: Money) -> "VolatilityIndexFutureBuilder": ...
    def quoted_price(self, quoted_price: float) -> "VolatilityIndexFutureBuilder": ...
    def expiry(self, expiry: date) -> "VolatilityIndexFutureBuilder": ...
    def disc_id(self, curve_id: str) -> "VolatilityIndexFutureBuilder": ...
    def vol_index_curve_id(self, curve_id: str) -> "VolatilityIndexFutureBuilder": ...
    def position(self, position: str | None = ...) -> "VolatilityIndexFutureBuilder": ...
    def multiplier(self, multiplier: float) -> "VolatilityIndexFutureBuilder": ...
    def tick_size(self, tick_size: float) -> "VolatilityIndexFutureBuilder": ...
    def tick_value(self, tick_value: float) -> "VolatilityIndexFutureBuilder": ...
    def index_id(self, index_id: str) -> "VolatilityIndexFutureBuilder": ...
    def build(self) -> "VolatilityIndexFuture": ...

class VolatilityIndexFuture:
    """Volatility index future wrapper (e.g., VIX futures)."""

    @classmethod
    def builder(cls, instrument_id: str) -> VolatilityIndexFutureBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def quoted_price(self) -> float: ...
    @property
    def expiry(self) -> date: ...
    @property
    def position(self) -> str: ...
    @property
    def discount_curve_id(self) -> str: ...
    @property
    def vol_index_curve_id(self) -> str: ...
    @property
    def multiplier(self) -> float: ...
    @property
    def tick_size(self) -> float: ...
    @property
    def tick_value(self) -> float: ...
    @property
    def index_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def npv_raw(self, market: MarketContext) -> float: ...
    def forward_vol(self, market: MarketContext) -> float: ...
    def delta_vol(self) -> float: ...
    def num_contracts(self) -> float: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
