"""Volatility index option instrument (builder-only API)."""

from __future__ import annotations
from typing import Self
from datetime import date

from ....core.currency import Currency
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class VolIndexOptionSpecs:
    """Volatility index option specifications."""
    def __init__(self, multiplier: float, index_id: str) -> None: ...
    @property
    def multiplier(self) -> float: ...
    @property
    def index_id(self) -> str: ...

class VolatilityIndexOptionBuilder:
    """Fluent builder returned by :meth:`VolatilityIndexOption.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def notional(self, amount: float) -> "VolatilityIndexOptionBuilder": ...
    def currency(self, currency: str | Currency) -> "VolatilityIndexOptionBuilder": ...
    def money(self, money: Money) -> "VolatilityIndexOptionBuilder": ...
    def strike(self, strike: float) -> "VolatilityIndexOptionBuilder": ...
    def expiry(self, expiry: date) -> "VolatilityIndexOptionBuilder": ...
    def disc_id(self, curve_id: str) -> "VolatilityIndexOptionBuilder": ...
    def vol_index_curve_id(self, curve_id: str) -> "VolatilityIndexOptionBuilder": ...
    def vol_of_vol_surface_id(self, curve_id: str) -> "VolatilityIndexOptionBuilder": ...
    def option_type(self, option_type: str) -> "VolatilityIndexOptionBuilder": ...
    def exercise_style(self, exercise_style: str) -> "VolatilityIndexOptionBuilder": ...
    def multiplier(self, multiplier: float) -> "VolatilityIndexOptionBuilder": ...
    def index_id(self, index_id: str) -> "VolatilityIndexOptionBuilder": ...
    def build(self) -> "VolatilityIndexOption": ...

class VolatilityIndexOption:
    """Volatility index option wrapper (e.g., VIX options)."""

    @classmethod
    def builder(cls, instrument_id: str) -> VolatilityIndexOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def strike(self) -> float: ...
    @property
    def option_type(self) -> str: ...
    @property
    def expiry(self) -> date: ...
    @property
    def exercise_style(self) -> str: ...
    @property
    def discount_curve_id(self) -> str: ...
    @property
    def vol_index_curve_id(self) -> str: ...
    @property
    def vol_of_vol_surface_id(self) -> str: ...
    @property
    def multiplier(self) -> float: ...
    @property
    def index_id_spec(self) -> str: ...
    @property
    def contract_specs(self) -> VolIndexOptionSpecs: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def npv_raw(self, market: MarketContext, as_of: date) -> float: ...
    def forward_vol(self, market: MarketContext, as_of: date) -> float: ...
    def delta(self, market: MarketContext, as_of: date) -> float: ...
    def gamma(self, market: MarketContext, as_of: date) -> float: ...
    def vega(self, market: MarketContext, as_of: date) -> float: ...
    def theta(self, market: MarketContext, as_of: date) -> float: ...
    def intrinsic_value(self, market: MarketContext, as_of: date) -> float: ...
    def time_value(self, market: MarketContext, as_of: date) -> float: ...
    def num_contracts(self) -> float: ...
    def black_price(self, forward: float, sigma: float, t: float) -> float: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def to_json(self) -> str:
        """Serialize to JSON in envelope format.

        Returns:
            str: JSON string with schema version and tagged instrument spec.
        """
        ...

    @classmethod
    def from_json(cls, json_str: str) -> "Self":
        """Deserialize from JSON in envelope format.

        Args:
            json_str: JSON string in envelope format.

        Returns:
            The deserialized instrument.

        Raises:
            ValueError: If JSON is malformed or contains a different instrument type.
        """
        ...
