"""Dynamic metric registry system."""

from __future__ import annotations

class AliasRegistry:
    def __init__(self) -> None: ...
    @classmethod
    def new(cls) -> AliasRegistry: ...
    @classmethod
    def with_threshold(cls, fuzzy_threshold: float) -> AliasRegistry: ...
    def add_alias(self, alias: str, canonical: str) -> None: ...
    def add_aliases(self, canonical: str, aliases: list[str]) -> None: ...
    def normalize(self, input: str) -> str | None: ...
    def load_standard_aliases(self) -> None: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __repr__(self) -> str: ...

from .registry import Registry
from .schema import MetricDefinition, MetricRegistry, UnitType

__all__ = [
    "AliasRegistry",
    "Registry",
    "MetricDefinition",
    "MetricRegistry",
    "UnitType",
]
