"""Type stubs for finstack.statements module."""

from typing import Any, Dict, List, Optional, Tuple
from finstack.core.currency import Currency
from finstack.core.dates import Period, PeriodId
from finstack.core.market_data.context import MarketContext
import datetime

# Types module
class NodeType:
    VALUE: NodeType
    CALCULATED: NodeType
    MIXED: NodeType

class NodeSpec:
    def __init__(self, node_id: str, node_type: NodeType) -> None: ...
    def with_name(self, name: str) -> NodeSpec: ...
    def with_values(
        self, values: Dict[PeriodId, AmountOrScalar] | List[Tuple[PeriodId, AmountOrScalar]]
    ) -> NodeSpec: ...
    def with_formula(self, formula: str) -> NodeSpec: ...
    def with_forecast(self, forecast_spec: ForecastSpec) -> NodeSpec: ...
    def with_tags(self, tags: List[str]) -> NodeSpec: ...
    @property
    def node_id(self) -> str: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def node_type(self) -> NodeType: ...
    @property
    def values(self) -> Optional[Dict[PeriodId, AmountOrScalar]]: ...
    @property
    def forecast(self) -> Optional[ForecastSpec]: ...
    @property
    def formula_text(self) -> Optional[str]: ...
    @property
    def where_text(self) -> Optional[str]: ...
    @property
    def tags(self) -> List[str]: ...
    @property
    def meta(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> NodeSpec: ...

class ForecastMethod:
    FORWARD_FILL: ForecastMethod
    GROWTH_PCT: ForecastMethod
    CURVE_PCT: ForecastMethod
    OVERRIDE: ForecastMethod
    NORMAL: ForecastMethod
    LOG_NORMAL: ForecastMethod
    TIME_SERIES: ForecastMethod
    SEASONAL: ForecastMethod

class SeasonalMode:
    ADDITIVE: SeasonalMode
    MULTIPLICATIVE: SeasonalMode

class ForecastSpec:
    def __init__(self, method: ForecastMethod, params: Optional[Dict[str, Any]] = None) -> None: ...
    @staticmethod
    def forward_fill() -> ForecastSpec: ...
    @staticmethod
    def growth(rate: float) -> ForecastSpec: ...
    @staticmethod
    def curve(rates: List[float]) -> ForecastSpec: ...
    @staticmethod
    def normal(mean: float, std: float, seed: int) -> ForecastSpec: ...
    @staticmethod
    def lognormal(mean: float, std: float, seed: int) -> ForecastSpec: ...
    @property
    def method(self) -> ForecastMethod: ...
    @property
    def params(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> ForecastSpec: ...

class AmountOrScalar:
    @staticmethod
    def scalar(value: float) -> AmountOrScalar: ...
    @staticmethod
    def amount(value: float, currency: Currency) -> AmountOrScalar: ...
    @property
    def is_scalar(self) -> bool: ...
    @property
    def value(self) -> float: ...
    @property
    def currency(self) -> Optional[Currency]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> AmountOrScalar: ...

class CapitalStructureSpec:
    def __init__(
        self,
        debt_instruments: Optional[List[DebtInstrumentSpec]] = None,
        equity_instruments: Optional[List[Any]] = None,
    ) -> None: ...
    @property
    def debt_instruments(self) -> List[DebtInstrumentSpec]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> CapitalStructureSpec: ...

class DebtInstrumentSpec:
    @staticmethod
    def bond(id: str, spec: Dict[str, Any]) -> DebtInstrumentSpec: ...
    @staticmethod
    def swap(id: str, spec: Dict[str, Any]) -> DebtInstrumentSpec: ...
    @staticmethod
    def generic(id: str, spec: Dict[str, Any]) -> DebtInstrumentSpec: ...
    def to_json(self) -> str: ...

class FinancialModelSpec:
    def __init__(self, id: str, periods: List[Period]) -> None: ...
    def add_node(self, node: NodeSpec) -> None: ...
    def get_node(self, node_id: str) -> Optional[NodeSpec]: ...
    def has_node(self, node_id: str) -> bool: ...
    @property
    def id(self) -> str: ...
    @property
    def periods(self) -> List[Period]: ...
    @property
    def nodes(self) -> Dict[str, NodeSpec]: ...
    @property
    def capital_structure(self) -> Optional[CapitalStructureSpec]: ...
    @property
    def meta(self) -> Dict[str, Any]: ...
    @property
    def schema_version(self) -> int: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> FinancialModelSpec: ...

# Builder module
class ModelBuilder:
    @staticmethod
    def new(id: str) -> ModelBuilder: ...
    def periods(self, range: str, actuals_until: Optional[str] = None) -> None: ...
    def periods_explicit(self, periods: List[Period]) -> None: ...
    def value(
        self,
        node_id: str,
        values: List[Tuple[PeriodId, AmountOrScalar]] | Dict[PeriodId, AmountOrScalar],
    ) -> None: ...
    def compute(self, node_id: str, formula: str) -> None: ...
    def forecast(self, node_id: str, forecast_spec: ForecastSpec) -> None: ...
    def with_meta(self, key: str, value: Any) -> None: ...
    def build(self) -> FinancialModelSpec: ...

# Evaluator module
class ResultsMeta:
    @property
    def eval_time_ms(self) -> Optional[int]: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_periods(self) -> int: ...

class Results:
    def get(self, node_id: str, period_id: PeriodId) -> Optional[float]: ...
    def get_node(self, node_id: str) -> Optional[Dict[PeriodId, float]]: ...
    def get_or(self, node_id: str, period_id: PeriodId, default: float) -> float: ...
    def all_periods(self, node_id: str) -> List[Tuple[PeriodId, float]]: ...
    @property
    def nodes(self) -> Dict[str, Dict[PeriodId, float]]: ...
    @property
    def meta(self) -> ResultsMeta: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> Results: ...

class Evaluator:
    @staticmethod
    def new() -> Evaluator: ...
    def evaluate(self, model: FinancialModelSpec) -> Results: ...
    def evaluate_with_market_context(
        self, model: FinancialModelSpec, market_ctx: MarketContext, as_of: datetime.date
    ) -> Results: ...

# Extensions module
class ExtensionMetadata:
    def __init__(
        self,
        name: str,
        version: str,
        description: Optional[str] = None,
        author: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def description(self) -> Optional[str]: ...
    @property
    def author(self) -> Optional[str]: ...

class ExtensionStatus:
    SUCCESS: ExtensionStatus
    FAILED: ExtensionStatus
    NOT_IMPLEMENTED: ExtensionStatus
    SKIPPED: ExtensionStatus

class ExtensionResult:
    @staticmethod
    def success(message: str) -> ExtensionResult: ...
    @staticmethod
    def failure(message: str) -> ExtensionResult: ...
    @staticmethod
    def skipped(message: str) -> ExtensionResult: ...
    @property
    def status(self) -> ExtensionStatus: ...
    @property
    def message(self) -> str: ...
    @property
    def data(self) -> Dict[str, Any]: ...

class ExtensionContext:
    @property
    def model(self) -> FinancialModelSpec: ...
    @property
    def results(self) -> Results: ...
    @property
    def config(self) -> Any: ...

class ExtensionRegistry:
    @staticmethod
    def new() -> ExtensionRegistry: ...
    def execute_all(self, model: FinancialModelSpec, results: Results) -> Dict[str, ExtensionResult]: ...

class CorkscrewExtension:
    @staticmethod
    def new() -> CorkscrewExtension: ...

class CreditScorecardExtension:
    @staticmethod
    def new() -> CreditScorecardExtension: ...

# Registry module
class UnitType:
    PERCENTAGE: UnitType
    CURRENCY: UnitType
    RATIO: UnitType
    COUNT: UnitType
    TIME_PERIOD: UnitType

class MetricDefinition:
    def __init__(
        self,
        id: str,
        name: str,
        formula: str,
        description: Optional[str] = None,
        category: Optional[str] = None,
        unit_type: Optional[UnitType] = None,
        requires: Optional[List[str]] = None,
        tags: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def formula(self) -> str: ...
    @property
    def description(self) -> Optional[str]: ...
    @property
    def category(self) -> Optional[str]: ...
    @property
    def unit_type(self) -> Optional[UnitType]: ...
    @property
    def requires(self) -> List[str]: ...
    @property
    def tags(self) -> List[str]: ...
    @property
    def meta(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> MetricDefinition: ...

class MetricRegistry:
    def __init__(self, namespace: str, metrics: List[MetricDefinition], schema_version: Optional[int] = 1) -> None: ...
    @property
    def namespace(self) -> str: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def metrics(self) -> List[MetricDefinition]: ...
    @property
    def meta(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> MetricRegistry: ...

class Registry:
    @staticmethod
    def new() -> Registry: ...
    def load_builtins(self) -> None: ...
    def load_from_json(self, path: str) -> None: ...
    def load_from_json_str(self, json_str: str) -> MetricRegistry: ...
    def get(self, metric_id: str) -> MetricDefinition: ...
    def list_metrics(self, namespace: Optional[str] = None) -> List[str]: ...
    def has_metric(self, metric_id: str) -> bool: ...
