//! Yield-to-N-years calculators for term loans.
//!
//! Computes IRR to fixed horizons (2y, 3y, 4y) using holder-view cashflows
//! and outstanding principal at the horizon date for redemption.

use crate::instruments::TermLoan;
use crate::metrics::{MetricCalculator, MetricContext};
use finstack_core::dates::Date;

use super::irr_helpers::solve_irr_to_date;

fn years_ahead(as_of: Date, years: i32) -> Date {
    // Attempt to construct same month/day years ahead; fall back to maturity elsewhere
    // We'll clamp invalid days (e.g., Feb 29) by using last valid day of month via simple fallback to day 28
    // but since we only use min with maturity, we can try direct construct and on error, use as_of end-of-month heuristic.
    match Date::from_calendar_date(as_of.year() + years, as_of.month(), as_of.day()) {
        Ok(d) => d,
        Err(_) => {
            // Fallback to 28th of same month
            let day = 28;
            Date::from_calendar_date(as_of.year() + years, as_of.month(), day).unwrap_or(as_of)
        }
    }
}

macro_rules! define_ytn {
    ($name:ident, $years:expr) => {
        /// Yield-to-N-year calculator for callable term loans (generated by macro)
        pub struct $name;

        impl MetricCalculator for $name {
            fn calculate(&self, context: &mut MetricContext) -> finstack_core::Result<f64> {
                let loan: &TermLoan = context.instrument_as()?;
                let as_of = context.as_of;

                let target = years_ahead(as_of, $years);
                let exercise_date = if target < loan.maturity {
                    target
                } else {
                    loan.maturity
                };
                if exercise_date <= as_of {
                    return Ok(0.0);
                }

                solve_irr_to_date(loan, &context.curves, as_of, context.base_value, exercise_date)
            }
        }
    };
}

define_ytn!(Yt2yCalculator, 2);
define_ytn!(Yt3yCalculator, 3);
define_ytn!(Yt4yCalculator, 4);
