//! Yield-to-N-years calculators for term loans.
//!
//! Computes IRR to fixed horizons (2y, 3y, 4y) using holder-view cashflows
//! and outstanding principal at the horizon date for redemption.

use crate::instruments::TermLoan;
use crate::metrics::{MetricCalculator, MetricContext};
use finstack_core::dates::Date;
use finstack_core::money::Money;

/// Solve IRR to a fixed horizon using holder-view cashflows and outstanding at horizon.
fn solve_irr_to_date(
    loan: &TermLoan,
    curves: &finstack_core::market_data::MarketContext,
    as_of: Date,
    target_price: Money,
    exercise_date: Date,
) -> finstack_core::Result<f64> {
    use crate::cashflow::traits::CashflowProvider;
    
    // Build full schedule to get outstanding path
    let schedule = crate::instruments::term_loan::cashflows::generate_cashflows(
        loan,
        curves,
        as_of,
    )?;
    
    // Get holder-view flows
    let holder_flows = loan.build_schedule(curves, as_of)?;
    
    let mut flows: Vec<(Date, Money)> = Vec::new();
    // Initial price leg
    flows.push((
        as_of,
        Money::new(-target_price.amount(), target_price.currency()),
    ));
    
    // Add holder-view flows up to exercise date
    for (date, amount) in holder_flows {
        if date > as_of && date <= exercise_date {
            flows.push((date, amount));
        }
    }

    // Redemption = outstanding at exercise date
    let out_path = schedule.outstanding_by_date_including_notional();
    let mut outstanding_at = Money::new(0.0, loan.currency);
    for (d, amt) in &out_path {
        if *d <= exercise_date {
            outstanding_at = *amt;
        } else {
            break;
        }
    }
    flows.push((exercise_date, outstanding_at));

    crate::instruments::private_markets_fund::metrics::calculate_irr(&flows, loan.day_count)
}

fn years_ahead(as_of: Date, years: i32) -> Date {
    // Attempt to construct same month/day years ahead; fall back to maturity elsewhere
    // We'll clamp invalid days (e.g., Feb 29) by using last valid day of month via simple fallback to day 28
    // but since we only use min with maturity, we can try direct construct and on error, use as_of end-of-month heuristic.
    match Date::from_calendar_date(as_of.year() + years, as_of.month(), as_of.day()) {
        Ok(d) => d,
        Err(_) => {
            // Fallback to 28th of same month
            let day = 28;
            Date::from_calendar_date(as_of.year() + years, as_of.month(), day).unwrap_or(as_of)
        }
    }
}

macro_rules! define_ytn {
    ($name:ident, $years:expr) => {
        /// Yield-to-N-year calculator for callable term loans (generated by macro)
        pub struct $name;

        impl MetricCalculator for $name {
            fn calculate(&self, context: &mut MetricContext) -> finstack_core::Result<f64> {
                let loan: &TermLoan = context.instrument_as()?;
                let as_of = context.as_of;

                let target = years_ahead(as_of, $years);
                let exercise_date = if target < loan.maturity {
                    target
                } else {
                    loan.maturity
                };
                if exercise_date <= as_of {
                    return Ok(0.0);
                }

                solve_irr_to_date(loan, &context.curves, as_of, context.base_value, exercise_date)
            }
        }
    };
}

define_ytn!(Yt2yCalculator, 2);
define_ytn!(Yt3yCalculator, 3);
define_ytn!(Yt4yCalculator, 4);
