"""Book hierarchy types for portfolio management."""

from __future__ import annotations
from typing import List, Optional

class BookId:
    """Unique identifier for a book."""

    def __init__(self, id: str) -> None: ...
    @property
    def id(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Book:
    """A hierarchical book that holds positions and child books."""

    def __init__(
        self,
        id: BookId,
        name: str,
        parent_id: Optional[BookId] = None,
        tags: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def id(self) -> BookId: ...
    @property
    def name(self) -> str: ...
    @property
    def parent_id(self) -> Optional[BookId]: ...
    @property
    def is_root(self) -> bool: ...
    @property
    def meta(self) -> dict: ...
    @property
    def tags(self) -> List[str]: ...
    def position_ids(self) -> List[str]: ...
    def child_book_ids(self) -> List[BookId]: ...
    def add_position(self, position_id: str) -> None: ...
    def remove_position(self, position_id: str) -> None: ...
    def contains_position(self, position_id: str) -> bool: ...
    def add_child(self, book_id: BookId) -> None: ...
    def remove_child(self, book_id: BookId) -> None: ...
    def contains_child(self, book_id: BookId) -> bool: ...
    def __repr__(self) -> str: ...

__all__ = ["Book", "BookId"]
