"""Portfolio optimization DSL: objectives, constraints, trade universes, and solver.

This module exposes the full portfolio optimization framework including enum-like
configuration types, per-position metric sources, portfolio-level metric
expressions, constraint builders, trade universe definitions, and the
optimization problem itself.

Typical workflow::

    from finstack.portfolio.optimization import (
        PerPositionMetric,
        MetricExpr,
        Objective,
        Constraint,
        PortfolioOptimizationProblem,
    )
    from finstack.valuations.metrics import MetricId

    ytm = PerPositionMetric.metric(MetricId.YTM)
    obj = Objective.maximize(MetricExpr.value_weighted_average(ytm))
    problem = PortfolioOptimizationProblem.new(portfolio, obj)
    problem = problem.with_constraint(Constraint.tag_exposure_limit(None, "rating", "CCC", 0.10))
    result = problem.optimize(market_context)
"""

from __future__ import annotations

from typing import Any

from finstack.portfolio.portfolio import Portfolio
from finstack.portfolio.types import PositionUnit
from finstack.core.config import FinstackConfig
from finstack.core.market_data.context import MarketContext
from finstack.valuations.metrics import MetricId

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class WeightingScheme:
    """How optimization weights are defined.

    Attributes
    ----------
    VALUE_WEIGHT : WeightingScheme
        Weight ``w_i`` is the share of portfolio present value.
    NOTIONAL_WEIGHT : WeightingScheme
        Weight ``w_i`` is the share of notional exposure.
    UNIT_SCALING : WeightingScheme
        Weight ``w_i`` scales the current position size.

    Examples
    --------
    >>> from finstack.portfolio.optimization import WeightingScheme
    >>> WeightingScheme.VALUE_WEIGHT
    """

    VALUE_WEIGHT: WeightingScheme
    NOTIONAL_WEIGHT: WeightingScheme
    UNIT_SCALING: WeightingScheme

    def __repr__(self) -> str: ...

class MissingMetricPolicy:
    """Policy for handling positions that lack a required metric.

    Attributes
    ----------
    ZERO : MissingMetricPolicy
        Treat missing metric values as ``0.0`` (default).
    EXCLUDE : MissingMetricPolicy
        Exclude the position from the relevant constraint.
    STRICT : MissingMetricPolicy
        Raise an error when a metric is missing.

    Examples
    --------
    >>> from finstack.portfolio.optimization import MissingMetricPolicy
    >>> MissingMetricPolicy.ZERO
    """

    ZERO: MissingMetricPolicy
    EXCLUDE: MissingMetricPolicy
    STRICT: MissingMetricPolicy

    def __repr__(self) -> str: ...

class Inequality:
    """Inequality / equality operator used in constraints.

    Attributes
    ----------
    LE : Inequality
        Less-than or equal (``<=``).
    GE : Inequality
        Greater-than or equal (``>=``).
    EQ : Inequality
        Equality (``==``).

    Examples
    --------
    >>> from finstack.portfolio.optimization import Inequality
    >>> Inequality.LE
    """

    LE: Inequality
    GE: Inequality
    EQ: Inequality

    def __repr__(self) -> str: ...

class OptimizationStatus:
    """Status of a completed optimization run.

    The status is returned as part of :class:`OptimizationResult` and indicates
    whether the solver found an optimal, feasible, or infeasible solution.

    Examples
    --------
    >>> result.status.is_feasible()
    True
    """

    def is_feasible(self) -> bool:
        """Return ``True`` when the solution is feasible (optimal or sub-optimal).

        Returns
        -------
        bool
            Whether the solver found a feasible solution.
        """
        ...

    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class TradeDirection:
    """Direction of a trade generated by the optimizer.

    Attributes
    ----------
    BUY : TradeDirection
        Position weight increased.
    SELL : TradeDirection
        Position weight decreased.
    HOLD : TradeDirection
        No change in position weight.

    Examples
    --------
    >>> from finstack.portfolio.optimization import TradeDirection
    >>> TradeDirection.BUY
    """

    BUY: TradeDirection
    SELL: TradeDirection
    HOLD: TradeDirection

    def __repr__(self) -> str: ...

class TradeType:
    """Whether a trade targets an existing or new position.

    Attributes
    ----------
    EXISTING : TradeType
        Trade on an existing portfolio position.
    NEW_POSITION : TradeType
        Trade to add a new candidate instrument.
    CLOSE_OUT : TradeType
        Trade to fully exit an existing position.

    Examples
    --------
    >>> from finstack.portfolio.optimization import TradeType
    >>> TradeType.EXISTING
    """

    EXISTING: TradeType
    NEW_POSITION: TradeType
    CLOSE_OUT: TradeType

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Per-Position Metrics
# ---------------------------------------------------------------------------

class PerPositionMetric:
    """Source of a per-position scalar metric used in expressions.

    Factory methods specify where each position's metric value comes from --
    a standard ``MetricId``, a custom key, present value, a tag indicator, or
    a constant.

    Examples
    --------
    >>> from finstack.portfolio.optimization import PerPositionMetric
    >>> from finstack.valuations.metrics import MetricId
    >>> PerPositionMetric.metric(MetricId.DURATION_MOD)
    >>> PerPositionMetric.pv_base()
    >>> PerPositionMetric.constant(1.0)
    """

    @staticmethod
    def metric(metric_id: MetricId) -> PerPositionMetric:
        """Create from a standard :class:`MetricId`.

        Parameters
        ----------
        metric_id : MetricId
            The metric identifier (e.g., ``MetricId.DURATION_MOD``).

        Returns
        -------
        PerPositionMetric
            Metric source backed by a valuation metric.
        """
        ...

    @staticmethod
    def custom_key(key: str) -> PerPositionMetric:
        """Create from a custom string key.

        Parameters
        ----------
        key : str
            Arbitrary key looked up in position metadata.

        Returns
        -------
        PerPositionMetric
            Metric source backed by custom position data.
        """
        ...

    @staticmethod
    def pv_base() -> PerPositionMetric:
        """Use base-currency present value.

        Returns
        -------
        PerPositionMetric
            PV in the portfolio's base currency.
        """
        ...

    @staticmethod
    def pv_native() -> PerPositionMetric:
        """Use native-currency present value.

        Returns
        -------
        PerPositionMetric
            PV in the instrument's native currency.
        """
        ...

    @staticmethod
    def tag_equals(key: str, value: str) -> PerPositionMetric:
        """Tag-based 0/1 indicator (1 when ``tag[key] == value``).

        Parameters
        ----------
        key : str
            Tag key to check.
        value : str
            Tag value to match.

        Returns
        -------
        PerPositionMetric
            Binary indicator metric.
        """
        ...

    @staticmethod
    def constant(value: float) -> PerPositionMetric:
        """Constant scalar for all positions.

        Parameters
        ----------
        value : float
            Constant value applied uniformly.

        Returns
        -------
        PerPositionMetric
            Constant metric source.
        """
        ...

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Metric Expressions
# ---------------------------------------------------------------------------

class MetricExpr:
    """Portfolio-level scalar metric expressed in terms of position metrics and weights.

    Metric expressions are the building blocks of objectives and constraints.
    They define how per-position metrics are aggregated into a single
    portfolio-level scalar.

    Examples
    --------
    >>> from finstack.portfolio.optimization import MetricExpr, PerPositionMetric
    >>> from finstack.valuations.metrics import MetricId
    >>> MetricExpr.weighted_sum(PerPositionMetric.metric(MetricId.DURATION_MOD))
    >>> MetricExpr.value_weighted_average(PerPositionMetric.metric(MetricId.YTM))
    >>> MetricExpr.tag_exposure_share("rating", "HY")
    """

    @staticmethod
    def weighted_sum(metric: PerPositionMetric) -> MetricExpr:
        """Weighted sum: ``sum_i  w_i * m_i``.

        Parameters
        ----------
        metric : PerPositionMetric
            Per-position metric source.

        Returns
        -------
        MetricExpr
            Weighted-sum expression.
        """
        ...

    @staticmethod
    def value_weighted_average(metric: PerPositionMetric) -> MetricExpr:
        """Value-weighted average with implicit budget normalisation.

        Parameters
        ----------
        metric : PerPositionMetric
            Per-position metric source.

        Returns
        -------
        MetricExpr
            Value-weighted average expression.
        """
        ...

    @staticmethod
    def tag_exposure_share(tag_key: str, tag_value: str) -> MetricExpr:
        """Tag exposure share: ``sum_i  w_i * I[tag == value]``.

        Parameters
        ----------
        tag_key : str
            Tag key to filter on.
        tag_value : str
            Tag value that triggers the indicator.

        Returns
        -------
        MetricExpr
            Tag-exposure-share expression.
        """
        ...

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Objectives
# ---------------------------------------------------------------------------

class Objective:
    """Optimization direction and target expression.

    Examples
    --------
    >>> from finstack.portfolio.optimization import Objective, MetricExpr, PerPositionMetric
    >>> from finstack.valuations.metrics import MetricId
    >>> ytm = PerPositionMetric.metric(MetricId.YTM)
    >>> Objective.maximize(MetricExpr.value_weighted_average(ytm))
    """

    @staticmethod
    def maximize(metric_expr: MetricExpr) -> Objective:
        """Maximize a portfolio-level metric.

        Parameters
        ----------
        metric_expr : MetricExpr
            Expression to maximize.

        Returns
        -------
        Objective
            Maximization objective.
        """
        ...

    @staticmethod
    def minimize(metric_expr: MetricExpr) -> Objective:
        """Minimize a portfolio-level metric.

        Parameters
        ----------
        metric_expr : MetricExpr
            Expression to minimize.

        Returns
        -------
        Objective
            Minimization objective.
        """
        ...

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Position Filters
# ---------------------------------------------------------------------------

class PositionFilter:
    """Filter selecting which positions participate in a constraint.

    Examples
    --------
    >>> from finstack.portfolio.optimization import PositionFilter
    >>> PositionFilter.all()
    >>> PositionFilter.by_tag("rating", "HY")
    >>> PositionFilter.by_position_ids(["pos_1", "pos_2"])
    """

    @staticmethod
    def all() -> PositionFilter:
        """All positions in the portfolio.

        Returns
        -------
        PositionFilter
            Unfiltered selection.
        """
        ...

    @staticmethod
    def by_entity_id(entity_id: str) -> PositionFilter:
        """Filter by entity identifier.

        Parameters
        ----------
        entity_id : str
            Entity to select.

        Returns
        -------
        PositionFilter
            Entity-based filter.
        """
        ...

    @staticmethod
    def by_tag(key: str, value: str) -> PositionFilter:
        """Filter by tag key/value pair.

        Parameters
        ----------
        key : str
            Tag key.
        value : str
            Tag value to match.

        Returns
        -------
        PositionFilter
            Tag-based filter.
        """
        ...

    @staticmethod
    def by_position_ids(position_ids: list[str]) -> PositionFilter:
        """Filter by explicit list of position identifiers.

        Parameters
        ----------
        position_ids : list[str]
            Position identifiers to include.

        Returns
        -------
        PositionFilter
            Position-id-based filter.
        """
        ...

    @staticmethod
    def not_(filter: PositionFilter) -> PositionFilter:
        """Exclude positions matching the inner filter.

        Parameters
        ----------
        filter : PositionFilter
            Filter whose matches should be excluded.

        Returns
        -------
        PositionFilter
            Negated filter.
        """
        ...

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Constraints
# ---------------------------------------------------------------------------

class Constraint:
    """Declarative constraint specification for the optimizer.

    Constraints are built via static factory methods and added to a
    :class:`PortfolioOptimizationProblem`.

    Examples
    --------
    >>> from finstack.portfolio.optimization import (
    ...     Constraint,
    ...     MetricExpr,
    ...     PerPositionMetric,
    ...     Inequality,
    ... )
    >>> from finstack.valuations.metrics import MetricId
    >>> dur = PerPositionMetric.metric(MetricId.DURATION_MOD)
    >>> Constraint.metric_bound("dur_limit", MetricExpr.weighted_sum(dur), Inequality.LE, 4.0)
    >>> Constraint.tag_exposure_limit("ccc_cap", "rating", "CCC", 0.10)
    >>> Constraint.max_turnover("low_turnover", 0.20)
    """

    @staticmethod
    def metric_bound(
        label: str | None,
        metric: MetricExpr,
        op: Inequality,
        rhs: float,
    ) -> Constraint:
        """General metric bound (e.g., ``duration <= 4.0``).

        Parameters
        ----------
        label : str or None
            Human-readable constraint label.
        metric : MetricExpr
            Portfolio-level metric expression.
        op : Inequality
            Comparison operator (``LE``, ``GE``, or ``EQ``).
        rhs : float
            Right-hand side of the inequality.

        Returns
        -------
        Constraint
            Metric-bound constraint.
        """
        ...

    @staticmethod
    def tag_exposure_limit(
        label: str | None,
        tag_key: str,
        tag_value: str,
        max_share: float,
    ) -> Constraint:
        """Tag exposure limit (e.g., ``rating=CCC weight <= 0.10``).

        Parameters
        ----------
        label : str or None
            Constraint label.
        tag_key : str
            Tag key to filter positions.
        tag_value : str
            Tag value to match.
        max_share : float
            Maximum allowed weight share (0.0 -- 1.0).

        Returns
        -------
        Constraint
            Tag-exposure-limit constraint.
        """
        ...

    @staticmethod
    def tag_exposure_minimum(
        label: str | None,
        tag_key: str,
        tag_value: str,
        min_share: float,
    ) -> Constraint:
        """Minimum tag exposure (e.g., ``rating=IG weight >= 0.50``).

        Parameters
        ----------
        label : str or None
            Constraint label.
        tag_key : str
            Tag key to filter positions.
        tag_value : str
            Tag value to match.
        min_share : float
            Minimum required weight share (0.0 -- 1.0).

        Returns
        -------
        Constraint
            Tag-exposure-minimum constraint.
        """
        ...

    @staticmethod
    def weight_bounds(
        label: str | None,
        filter: PositionFilter,
        min: float,
        max: float,
    ) -> Constraint:
        """Per-position weight bounds for all positions matching *filter*.

        Parameters
        ----------
        label : str or None
            Constraint label.
        filter : PositionFilter
            Position selection filter.
        min : float
            Minimum per-position weight.
        max : float
            Maximum per-position weight.

        Returns
        -------
        Constraint
            Weight-bounds constraint.
        """
        ...

    @staticmethod
    def max_turnover(label: str | None, max_turnover: float) -> Constraint:
        """Maximum total turnover constraint.

        Parameters
        ----------
        label : str or None
            Constraint label.
        max_turnover : float
            Maximum allowed sum of absolute weight changes.

        Returns
        -------
        Constraint
            Max-turnover constraint.
        """
        ...

    @staticmethod
    def max_position_delta(
        label: str | None,
        filter: PositionFilter,
        max_delta: float,
    ) -> Constraint:
        """Maximum single-position weight change.

        Parameters
        ----------
        label : str or None
            Constraint label.
        filter : PositionFilter
            Position selection filter.
        max_delta : float
            Maximum absolute weight change per position.

        Returns
        -------
        Constraint
            Max-position-delta constraint.
        """
        ...

    @staticmethod
    def budget(rhs: float) -> Constraint:
        """Budget / normalisation constraint (typically ``sum w_i == 1.0``).

        Parameters
        ----------
        rhs : float
            Target budget value.

        Returns
        -------
        Constraint
            Budget constraint.
        """
        ...

    def label(self) -> str | None:
        """Return the constraint label, if set.

        Returns
        -------
        str or None
            Human-readable label.
        """
        ...

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Trade Specification
# ---------------------------------------------------------------------------

class TradeSpec:
    """Trade specification for a single position produced by the optimizer.

    Attributes
    ----------
    position_id : str
        Position identifier.
    instrument_id : str
        Underlying instrument identifier.
    trade_type : TradeType
        Type of trade (existing, new position, close-out).
    current_quantity : float
        Pre-trade quantity.
    target_quantity : float
        Post-trade quantity.
    delta_quantity : float
        Quantity change (``target - current``).
    direction : TradeDirection
        Buy / Sell / Hold classification.
    current_weight : float
        Pre-trade portfolio weight.
    target_weight : float
        Post-trade portfolio weight.
    """

    position_id: str
    instrument_id: str
    trade_type: TradeType
    current_quantity: float
    target_quantity: float
    delta_quantity: float
    direction: TradeDirection
    current_weight: float
    target_weight: float

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Optimization Result
# ---------------------------------------------------------------------------

class OptimizationResult:
    """Solution of an optimization problem.

    Provides optimal weights, weight deltas, trade lists, and diagnostics
    such as binding constraints and turnover.

    Examples
    --------
    >>> result = problem.optimize(market_context)
    >>> result.objective_value
    0.0523
    >>> result.status.is_feasible()
    True
    >>> trades = result.to_trade_list()
    """

    @property
    def optimal_weights(self) -> dict[str, float]:
        """Optimal weights per position.

        Returns
        -------
        dict[str, float]
            Mapping of position id to target weight.
        """
        ...

    @property
    def current_weights(self) -> dict[str, float]:
        """Pre-trade weights per position.

        Returns
        -------
        dict[str, float]
            Mapping of position id to current weight.
        """
        ...

    @property
    def weight_deltas(self) -> dict[str, float]:
        """Weight changes per position (``optimal - current``).

        Returns
        -------
        dict[str, float]
            Mapping of position id to weight delta.
        """
        ...

    @property
    def objective_value(self) -> float:
        """Objective value at the optimal solution.

        Returns
        -------
        float
            Scalar objective value.
        """
        ...

    @property
    def status(self) -> OptimizationStatus:
        """Optimization status.

        Returns
        -------
        OptimizationStatus
            Status indicating optimality or infeasibility.
        """
        ...

    def to_rebalanced_portfolio(self) -> Portfolio:
        """Generate a new portfolio with quantities adjusted to target weights.

        Returns
        -------
        Portfolio
            Rebalanced portfolio.

        Raises
        ------
        RuntimeError
            If rebalancing fails.
        """
        ...

    def to_trade_list(self) -> list[TradeSpec]:
        """Generate a trade list sorted by absolute quantity delta.

        Returns
        -------
        list[TradeSpec]
            Trades required to move from current to optimal weights.
        """
        ...

    def new_position_trades(self) -> list[TradeSpec]:
        """Get trades for new positions only (from candidates).

        Returns
        -------
        list[TradeSpec]
            Trades for candidate instruments added by the optimizer.
        """
        ...

    def binding_constraints(self) -> dict[str, float]:
        """Get constraints that are binding at the solution (slack ~ 0).

        Returns
        -------
        dict[str, float]
            Mapping of constraint label to slack value.
        """
        ...

    def turnover(self) -> float:
        """Calculate total turnover (sum of absolute weight changes).

        Returns
        -------
        float
            Total portfolio turnover.
        """
        ...

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Candidate Position
# ---------------------------------------------------------------------------

class CandidatePosition:
    """Candidate instrument that could be added to the portfolio by the optimizer.

    Examples
    --------
    >>> from finstack.portfolio.optimization import CandidatePosition
    >>> candidate = CandidatePosition.new("bond_1", "fund_1", instrument, "FaceValue")
    >>> candidate = candidate.with_tag("rating", "BBB")
    >>> candidate = candidate.with_max_weight(0.05)
    """

    @staticmethod
    def new(
        id: str,
        entity_id: str,
        instrument: Any,
        unit: str | PositionUnit,
    ) -> CandidatePosition:
        """Create a candidate position.

        Parameters
        ----------
        id : str
            Candidate position identifier.
        entity_id : str
            Owning entity identifier.
        instrument : Any
            Instrument object (Bond, Equity, etc.).
        unit : str or PositionUnit
            Position unit type (``"Units"``, ``"Notional"``, ``"FaceValue"``,
            ``"Percentage"``).

        Returns
        -------
        CandidatePosition
            New candidate.

        Raises
        ------
        ValueError
            If *unit* is not a recognised position unit string.
        """
        ...

    def with_tag(self, key: str, value: str) -> CandidatePosition:
        """Add a tag to the candidate.

        Parameters
        ----------
        key : str
            Tag key.
        value : str
            Tag value.

        Returns
        -------
        CandidatePosition
            New candidate with the tag added.
        """
        ...

    def with_max_weight(self, max: float) -> CandidatePosition:
        """Set the maximum weight for this candidate.

        Parameters
        ----------
        max : float
            Upper weight bound.

        Returns
        -------
        CandidatePosition
            New candidate with maximum weight set.
        """
        ...

    def with_min_weight(self, min: float) -> CandidatePosition:
        """Set the minimum weight (if included) for this candidate.

        Parameters
        ----------
        min : float
            Lower weight bound.

        Returns
        -------
        CandidatePosition
            New candidate with minimum weight set.
        """
        ...

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Trade Universe
# ---------------------------------------------------------------------------

class TradeUniverse:
    """Defines which instruments the optimizer is allowed to trade.

    Examples
    --------
    >>> from finstack.portfolio.optimization import TradeUniverse, PositionFilter
    >>> universe = TradeUniverse.all_positions()
    >>> universe = TradeUniverse.filtered(PositionFilter.by_tag("rating", "HY"))
    >>> universe = universe.with_candidate(candidate)
    """

    @staticmethod
    def all_positions() -> TradeUniverse:
        """Create a universe where all existing positions are tradeable.

        Returns
        -------
        TradeUniverse
            Universe containing all positions.
        """
        ...

    @staticmethod
    def filtered(filter: PositionFilter) -> TradeUniverse:
        """Create a universe with only specific positions tradeable.

        Parameters
        ----------
        filter : PositionFilter
            Filter determining tradeable positions.

        Returns
        -------
        TradeUniverse
            Filtered universe.
        """
        ...

    def with_candidate(self, candidate: CandidatePosition) -> TradeUniverse:
        """Add a candidate position to the universe.

        Parameters
        ----------
        candidate : CandidatePosition
            Candidate to add.

        Returns
        -------
        TradeUniverse
            New universe with the candidate included.
        """
        ...

    def with_candidates(self, candidates: list[CandidatePosition]) -> TradeUniverse:
        """Add multiple candidate positions.

        Parameters
        ----------
        candidates : list[CandidatePosition]
            Candidates to add.

        Returns
        -------
        TradeUniverse
            New universe with the candidates included.
        """
        ...

    def with_held_positions(self, filter: PositionFilter) -> TradeUniverse:
        """Set positions to hold constant (not trade).

        Parameters
        ----------
        filter : PositionFilter
            Positions to hold.

        Returns
        -------
        TradeUniverse
            New universe with held positions.
        """
        ...

    def allow_shorting_candidates(self) -> TradeUniverse:
        """Allow short selling of candidate positions.

        Returns
        -------
        TradeUniverse
            New universe with shorting enabled for candidates.
        """
        ...

    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Optimization Problem
# ---------------------------------------------------------------------------

class PortfolioOptimizationProblem:
    """Complete optimization problem specification.

    Build a problem from a portfolio and objective, add constraints and
    a trade universe, then call :meth:`optimize` to solve.

    Examples
    --------
    >>> from finstack.portfolio.optimization import (
    ...     PortfolioOptimizationProblem,
    ...     Objective,
    ...     MetricExpr,
    ...     PerPositionMetric,
    ...     Constraint,
    ... )
    >>> from finstack.valuations.metrics import MetricId
    >>> ytm = PerPositionMetric.metric(MetricId.YTM)
    >>> obj = Objective.maximize(MetricExpr.value_weighted_average(ytm))
    >>> problem = PortfolioOptimizationProblem.new(portfolio, obj)
    >>> problem = problem.with_constraint(Constraint.tag_exposure_limit(None, "rating", "CCC", 0.10))
    >>> result = problem.optimize(market_context)
    """

    weighting: WeightingScheme
    """Weighting scheme for the optimisation (write-only setter)."""

    missing_metric_policy: MissingMetricPolicy
    """Policy for positions missing a required metric (write-only setter)."""

    label: str | None
    """Human-readable label for the problem (write-only setter)."""

    @staticmethod
    def new(portfolio: Portfolio, objective: Objective) -> PortfolioOptimizationProblem:
        """Create a basic problem optimizing all positions in the portfolio.

        Parameters
        ----------
        portfolio : Portfolio
            Portfolio to optimize.
        objective : Objective
            Optimization objective.

        Returns
        -------
        PortfolioOptimizationProblem
            New optimization problem.
        """
        ...

    def with_trade_universe(self, universe: TradeUniverse) -> PortfolioOptimizationProblem:
        """Set the trade universe.

        Parameters
        ----------
        universe : TradeUniverse
            Trade universe definition.

        Returns
        -------
        PortfolioOptimizationProblem
            New problem with the universe set.
        """
        ...

    def with_constraint(self, constraint: Constraint) -> PortfolioOptimizationProblem:
        """Add a single constraint.

        Parameters
        ----------
        constraint : Constraint
            Constraint to add.

        Returns
        -------
        PortfolioOptimizationProblem
            New problem with the constraint added.
        """
        ...

    def with_constraints(self, constraints: list[Constraint]) -> PortfolioOptimizationProblem:
        """Add multiple constraints.

        Parameters
        ----------
        constraints : list[Constraint]
            Constraints to add.

        Returns
        -------
        PortfolioOptimizationProblem
            New problem with the constraints added.
        """
        ...

    def optimize(
        self,
        market_context: MarketContext,
        config: FinstackConfig | None = None,
    ) -> OptimizationResult:
        """Solve the optimization problem.

        Parameters
        ----------
        market_context : MarketContext
            Market data context for metric evaluation.
        config : FinstackConfig or None, optional
            Configuration overrides.

        Returns
        -------
        OptimizationResult
            Solution with optimal weights, status, and diagnostics.

        Raises
        ------
        RuntimeError
            If the solver encounters an internal error.
        """
        ...

    def __repr__(self) -> str: ...

__all__ = [
    "WeightingScheme",
    "MissingMetricPolicy",
    "Inequality",
    "OptimizationStatus",
    "TradeDirection",
    "TradeType",
    "PerPositionMetric",
    "MetricExpr",
    "Objective",
    "PositionFilter",
    "Constraint",
    "TradeSpec",
    "OptimizationResult",
    "CandidatePosition",
    "TradeUniverse",
    "PortfolioOptimizationProblem",
]
