//! Utilities for instrument pricing and metrics assembly.
//!
//! Contains helpers shared across instrument implementations, notably the
//! function to assemble a `ValuationResult` with computed metrics.

use crate::metrics::{standard_registry, MetricContext};
use finstack_core::dates::Date;
use finstack_core::market_data::MarketContext;
use finstack_core::money::Money;
use indexmap::IndexMap;
use std::sync::Arc;

/// Monomorphized schedule → PV helper for instruments using a discount curve.
///
/// - Builds the schedule via `CashflowProvider`.
/// - Retrieves the discount curve by borrowed ID using `get_discount_ref`.
/// - For legacy callers, performs NPV using a caller-supplied `DayCount`
///   passed through to the core discounting helper. Instruments that want
///   DF-by-date semantics should prefer using `DiscountCurve::df_on_date_curve`
///   directly or a dedicated helper instead of this function.
pub fn schedule_pv_impl<S>(
    instrument: &S,
    curves: &MarketContext,
    as_of: Date,
    discount_curve_id: &finstack_core::types::CurveId,
    day_count: finstack_core::dates::DayCount,
) -> finstack_core::Result<Money>
where
    S: crate::cashflow::traits::CashflowProvider,
{
    use crate::instruments::common::discountable::npv_static;

    let flows = S::build_schedule(instrument, curves, as_of)?;
    let disc = curves.get_discount_ref(discount_curve_id.as_str())?;
    // Use as_of for correct theta calculation, not curve base_date
    npv_static(disc, as_of, day_count, &flows)
}

/// Shared helper to build a ValuationResult with a set of metrics.
///
/// Centralizes the repeated pattern across instruments to compute base value,
/// build metric context, compute metrics and stamp a result.
///
/// This function uses trait objects to avoid generic monomorphization across
/// compilation units, which can cause coverage metadata mismatches.
///
/// # Performance
///
/// Accepts Arc-wrapped arguments to avoid cloning on every call. Callers should
/// clone the instrument and market context once into Arc at the call boundary.
pub fn build_with_metrics_dyn(
    instrument: Arc<dyn crate::instruments::common::traits::Instrument>,
    curves: Arc<MarketContext>,
    as_of: Date,
    base_value: Money,
    metrics: &[crate::metrics::MetricId],
) -> finstack_core::Result<crate::results::ValuationResult> {
    let mut context = MetricContext::new(instrument.clone(), curves, as_of, base_value);

    let registry = standard_registry();
    let metric_measures = registry.compute(metrics, &mut context)?;

    // Deterministic insertion order: follow the requested metrics slice order
    let mut measures: IndexMap<String, f64> = IndexMap::new();
    for metric_id in metrics {
        if let Some(value) = metric_measures.get(metric_id) {
            measures.insert(metric_id.as_str().to_string(), *value);
        }
    }

    // Also include any composite keys (bucketed series, matrices, etc.) from context.computed
    // These are generated by store_bucketed_series and similar methods
    for (metric_id, value) in &context.computed {
        let key = metric_id.as_str().to_string();
        // Only insert if not already present (requested metrics take precedence)
        if !measures.contains_key(&key) {
            measures.insert(key, *value);
        }
    }

    let mut result =
        crate::results::ValuationResult::stamped(context.instrument.id(), as_of, base_value);
    result.measures = measures;

    Ok(result)
}

/// Convert a trait object reference to Arc-wrapped trait object.
///
/// This helper clones the instrument via `clone_box()` and converts it to Arc.
/// Used by language bindings (Python/WASM) that work with trait object references.
///
/// # Implementation
///
/// Uses `clone_box()` to get a `Box<dyn Instrument>`, then converts it to `Arc`
/// using `Arc::from()`. This works because `Arc::from()` can convert from `Box<T>`
/// when `T: ?Sized` (which trait objects are).
pub fn instrument_to_arc(
    instrument: &dyn crate::instruments::common::traits::Instrument,
) -> Arc<dyn crate::instruments::common::traits::Instrument> {
    // Clone via clone_box() to get Box<dyn Instrument>
    let boxed = instrument.clone_box();
    // Convert Box to Arc using Arc::from()
    // This works because Arc::from() can convert Box<T> to Arc<T> for any T
    Arc::from(boxed)
}

/// Ensure all money amounts in a collection share the same currency.
pub fn validate_currency_consistency(amounts: &[Money]) -> finstack_core::Result<()> {
    if amounts.is_empty() {
        return Ok(());
    }

    let expected_currency = amounts[0].currency();
    for amount in amounts.iter().skip(1) {
        if amount.currency() != expected_currency {
            return Err(finstack_core::Error::CurrencyMismatch {
                expected: expected_currency,
                actual: amount.currency(),
            });
        }
    }
    Ok(())
}
