//! Currency code-generation submodule for `build.rs`.
use std::env;
use std::fs::File;
use std::io::{BufRead, BufReader, Write};
use std::path::Path;

/// In-memory representation of a single ISO-4217 row.
struct CurrencyRow {
    code: String,
    numeric: u16,
    minor_units: u8,
    name: String,
}

/// Parse the CSV file embedded in the repository and return all rows.
fn parse_csv(path: &str) -> std::io::Result<Vec<CurrencyRow>> {
    let file = File::open(path)?;
    let reader = BufReader::new(file);
    let mut lines = reader.lines();
    // skip header
    lines.next();

    let mut rows = Vec::new();
    for line in lines {
        let line = line?;
        let parts: Vec<&str> = line.split(',').collect();
        if parts.len() < 4 {
            continue; // ignore malformed
        }
        rows.push(CurrencyRow {
            code: parts[0].to_string(),
            numeric: parts[1].parse().unwrap_or_default(),
            minor_units: parts[2].parse().unwrap_or(2),
            name: parts[3].to_string(),
        });
    }
    Ok(rows)
}

/// Emit the `Currency` enum definition.
fn write_enum(w: &mut impl Write, rows: &[CurrencyRow]) -> std::io::Result<()> {
    writeln!(w, "#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, EnumString, EnumIter, Display, IntoPrimitive, TryFromPrimitive)]")?;
    writeln!(
        w,
        "#[cfg_attr(feature=\"serde\", derive(serde::Serialize, serde::Deserialize))]"
    )?;
    writeln!(w, "/// ISO 4217 currency enumeration")?;
    writeln!(w, "#[strum(ascii_case_insensitive)]")?;
    writeln!(w, "#[repr(u16)]")?;
    writeln!(w, "pub enum Currency {{")?;

    for row in rows {
        writeln!(w, "    /// {} ({})", row.name, row.numeric)?;
        writeln!(w, "    {} = {},", row.code, row.numeric)?;
    }
    writeln!(w, "}}\n")
}

/// Emit a const table mapping numeric code → decimals.
fn write_decimal_table(w: &mut impl Write, rows: &[CurrencyRow]) -> std::io::Result<()> {
    let max_numeric = rows.iter().map(|r| r.numeric).max().unwrap_or(0) as usize;
    let mut table = vec![0u8; max_numeric + 1];
    for r in rows {
        table[r.numeric as usize] = r.minor_units;
    }

    writeln!(w, "/// Number of decimal places (minor units) for each ISO 4217 currency, indexed by numeric code.")?;
    writeln!(w, "pub const MINOR_UNITS: [u8; {}] = [", table.len())?;
    for (idx, val) in table.iter().enumerate() {
        if idx % 20 == 0 {
            writeln!(w)?;
        }
        write!(w, "{}, ", val)?;
    }
    writeln!(w, "];")?;
    Ok(())
}

pub fn generate() -> std::io::Result<()> {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("currency_generated.rs");
    let mut f = File::create(&dest_path)?;

    // Tell cargo to rerun if the CSV file changes
    println!("cargo:rerun-if-changed=data/iso_4217.csv");

    let rows = parse_csv("data/iso_4217.csv")?;

    // Preamble
    writeln!(f, "// Auto-generated by build.rs – DO NOT EDIT")?;
    writeln!(f, "use strum_macros::{{EnumIter, EnumString, Display}};")?;
    writeln!(f, "use num_enum::{{IntoPrimitive, TryFromPrimitive}};")?;
    writeln!(f)?;

    write_enum(&mut f, &rows)?;

    write_decimal_table(&mut f, &rows)?;

    // impl block with helpers
    writeln!(f, "impl Currency {{")?;
    writeln!(
        f,
        "    /// ISO-4217 decimal precision for this currency (e.g. USD → 2)"
    )?;
    writeln!(f, "    #[inline] pub const fn decimals(self) -> u8 {{")?;
    writeln!(f, "        MINOR_UNITS[self.numeric() as usize]")?;
    writeln!(f, "    }}")?;
    writeln!(f, "    /// ISO 4217 numeric code as `u16`.")?;
    writeln!(
        f,
        "    #[inline] pub const fn numeric(self) -> u16 {{ self as u16 }}"
    )?;
    writeln!(f, "}}\n")?;

    // --------------------------------------------------------------------
    // Additionally, emit a copy into `src/generated/` so that IDEs (e.g.
    // rust-analyzer) can parse the generated enum without relying on the
    // `include!(concat!(env!("OUT_DIR"), ...))` indirection.
    // --------------------------------------------------------------------

    let src_generated_dir = Path::new("src/generated");
    if std::fs::create_dir_all(src_generated_dir).is_ok() {
        let dest_src_path = src_generated_dir.join("currency_generated.rs");
        // Ignore copy errors; not fatal for the build.
        let _ = std::fs::copy(&dest_path, &dest_src_path);
    }

    Ok(())
}
