"""Compounding convention bindings."""

from typing import Optional

class Compounding:
    """Compounding convention for interest rates."""

    def __init__(self, kind: str, periods_per_year: Optional[int] = None) -> None: ...
    @staticmethod
    def continuous() -> "Compounding": ...
    @staticmethod
    def annual() -> "Compounding": ...
    @staticmethod
    def simple() -> "Compounding": ...
    @staticmethod
    def semi_annual() -> "Compounding": ...
    @staticmethod
    def quarterly() -> "Compounding": ...
    @staticmethod
    def monthly() -> "Compounding": ...
    @staticmethod
    def periodic(n: int) -> "Compounding": ...
    @property
    def periods_per_year(self) -> Optional[int]: ...
    @property
    def is_periodic(self) -> bool: ...
    def df_from_rate(self, rate: float, t: float) -> float: ...
    def rate_from_df(self, df: float, t: float) -> float: ...
    def try_rate_from_df(self, df: float, t: float) -> float: ...
    def convert_rate(self, rate: float, t: float, to: "Compounding") -> float: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
