"""Linear algebra utilities."""

from typing import List, Sequence, Tuple

def cholesky_decomposition(matrix: List[List[float]]) -> List[List[float]]: ...
def validate_correlation_matrix(matrix: List[List[float]], tolerance: float = 1e-10) -> bool: ...
def apply_correlation(cholesky: List[List[float]], independent: List[float]) -> List[float]: ...
def build_correlation_matrix(
    n: int,
    correlations: Sequence[Tuple[int, int, float]],
) -> List[List[float]]: ...
