"""Random number utilities."""

from __future__ import annotations
from typing import Tuple

class SimpleRng:
    """Deterministic pseudo-random number generator."""

    def __init__(self, seed: int) -> None: ...
    def uniform(self) -> float: ...
    def normal(self, mean: float = ..., std_dev: float = ...) -> float: ...
    def bernoulli(self, p: float) -> bool: ...

def box_muller_transform(u1: float, u2: float) -> Tuple[float, float]: ...
