# flake8: noqa: PYI021
from collections.abc import Callable
from typing import Optional

class NewtonSolver:
    def __init__(
        self,
        *,
        tolerance: float = 1e-12,
        max_iterations: int = 50,
        fd_step: float = 1e-8,
    ) -> None: ...
    @property
    def tolerance(self) -> float: ...
    @tolerance.setter
    def tolerance(self, value: float) -> None: ...
    @property
    def max_iterations(self) -> int: ...
    @max_iterations.setter
    def max_iterations(self, value: int) -> None: ...
    @property
    def fd_step(self) -> float: ...
    @fd_step.setter
    def fd_step(self, value: float) -> None: ...
    def solve(self, func: Callable[[float], float], initial_guess: float) -> float: ...
    def __repr__(self) -> str: ...

class BrentSolver:
    def __init__(
        self,
        *,
        tolerance: float = 1e-12,
        max_iterations: int = 100,
        bracket_expansion: float = 2.0,
        initial_bracket_size: Optional[float] = None,
    ) -> None: ...
    @property
    def tolerance(self) -> float: ...
    @tolerance.setter
    def tolerance(self, value: float) -> None: ...
    @property
    def max_iterations(self) -> int: ...
    @max_iterations.setter
    def max_iterations(self, value: int) -> None: ...
    @property
    def bracket_expansion(self) -> float: ...
    @bracket_expansion.setter
    def bracket_expansion(self, value: float) -> None: ...
    @property
    def initial_bracket_size(self) -> Optional[float]: ...
    @initial_bracket_size.setter
    def initial_bracket_size(self, value: Optional[float]) -> None: ...
    def solve(self, func: Callable[[float], float], initial_guess: float) -> float: ...
    def __repr__(self) -> str: ...

class HybridSolver:
    def __init__(
        self,
        *,
        tolerance: float = 1e-12,
        max_iterations: int = 100,
    ) -> None: ...
    @property
    def tolerance(self) -> float: ...
    @tolerance.setter
    def tolerance(self, value: float) -> None: ...
    @property
    def max_iterations(self) -> int: ...
    @max_iterations.setter
    def max_iterations(self, value: int) -> None: ...
    def solve(self, func: Callable[[float], float], initial_guess: float) -> float: ...
    def __repr__(self) -> str: ...

__all__ = ["NewtonSolver", "BrentSolver", "HybridSolver"]
