"""Special mathematical functions."""

def norm_cdf(x: float, mean: float = 0.0, std_dev: float = 1.0) -> float: ...
def norm_pdf(x: float, mean: float = 0.0, std_dev: float = 1.0) -> float: ...
def standard_normal_inv_cdf(p: float) -> float: ...
def erf(x: float) -> float: ...
