"""Summation algorithms for reduced floating-point error."""

from typing import List

def kahan_sum(values: List[float]) -> float: ...
def pairwise_sum(values: List[float]) -> float: ...
def stable_sum(values: List[float]) -> float: ...
