"""Time grid bindings for Monte Carlo simulation."""

from typing import List

class TimeGrid:
    """Time grid for Monte Carlo simulation."""

    @staticmethod
    def uniform(t_max: float, num_steps: int) -> "TimeGrid": ...
    @staticmethod
    def uniform_with_required_times(
        t_max: float,
        steps_per_year: float,
        min_steps: int,
        required_times: List[float],
    ) -> "TimeGrid": ...
    @staticmethod
    def from_times(times: List[float]) -> "TimeGrid": ...
    @property
    def num_steps(self) -> int: ...
    @property
    def t_max(self) -> float: ...
    def time(self, step: int) -> float: ...
    def dt(self, step: int) -> float: ...
    @property
    def times(self) -> List[float]: ...
    @property
    def dts(self) -> List[float]: ...
    @property
    def is_uniform(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
