"""Type stubs for ``finstack.valuations.credit_derivatives``."""

from __future__ import annotations

from finstack.core.market_data import MarketContext
from finstack.valuations import ValuationResult

__all__ = ["CreditDefaultSwap", "CDSIndex", "CDSTranche", "CDSOption"]

class _CreditDerivative:
    @staticmethod
    def example() -> _CreditDerivative: ...
    @staticmethod
    def from_json(json: str) -> _CreditDerivative: ...
    def to_json(self) -> str: ...
    def validate(self) -> None: ...
    def price(self, market: MarketContext, as_of: str) -> ValuationResult: ...

class CreditDefaultSwap(_CreditDerivative):
    @staticmethod
    def example() -> CreditDefaultSwap: ...
    @staticmethod
    def from_json(json: str) -> CreditDefaultSwap: ...

class CDSIndex(_CreditDerivative):
    @staticmethod
    def example() -> CDSIndex: ...
    @staticmethod
    def from_json(json: str) -> CDSIndex: ...

class CDSTranche(_CreditDerivative):
    @staticmethod
    def example() -> CDSTranche: ...
    @staticmethod
    def from_json(json: str) -> CDSTranche: ...

class CDSOption(_CreditDerivative):
    @staticmethod
    def example() -> CDSOption: ...
    @staticmethod
    def from_json(json: str) -> CDSOption: ...
