"""Margin and collateral management type stubs."""

from __future__ import annotations

import datetime
from typing import Any

from finstack.core.currency import Currency
from finstack.core.money import Money

class MarginTenor:
    """Margin call frequency."""

    DAILY: MarginTenor
    WEEKLY: MarginTenor
    MONTHLY: MarginTenor
    ON_DEMAND: MarginTenor

    @property
    def name(self) -> str: ...

class ImMethodology:
    """Initial margin methodology."""

    HAIRCUT: ImMethodology
    SIMM: ImMethodology
    SCHEDULE: ImMethodology
    INTERNAL_MODEL: ImMethodology
    CLEARING_HOUSE: ImMethodology

    @property
    def name(self) -> str: ...

class MarginCallTiming:
    def __init__(
        self,
        *,
        notification_deadline_hours: int | None = ...,
        response_deadline_hours: int | None = ...,
        dispute_resolution_days: int | None = ...,
        delivery_grace_days: int | None = ...,
    ) -> None: ...
    @staticmethod
    def regulatory_standard() -> MarginCallTiming: ...
    @property
    def notification_deadline_hours(self) -> int: ...
    @property
    def response_deadline_hours(self) -> int: ...
    @property
    def dispute_resolution_days(self) -> int: ...
    @property
    def delivery_grace_days(self) -> int: ...

class VmParameters:
    def __init__(
        self,
        threshold: Money,
        mta: Money,
        *,
        rounding: Money | None = ...,
        independent_amount: Money | None = ...,
        frequency: MarginTenor | str | None = ...,
        settlement_lag: int | None = ...,
    ) -> None: ...
    @staticmethod
    def regulatory_standard(currency: Currency | str) -> VmParameters: ...
    @staticmethod
    def with_threshold(threshold: Money, mta: Money) -> VmParameters: ...
    @property
    def threshold(self) -> Money: ...
    @property
    def mta(self) -> Money: ...
    @property
    def rounding(self) -> Money: ...
    @property
    def independent_amount(self) -> Money: ...
    @property
    def frequency(self) -> MarginTenor: ...
    @property
    def settlement_lag(self) -> int: ...

class ImParameters:
    def __init__(
        self,
        methodology: ImMethodology | str,
        mpor_days: int,
        threshold: Money,
        mta: Money,
        *,
        segregated: bool = ...,
    ) -> None: ...
    @staticmethod
    def simm_standard(currency: Currency | str) -> ImParameters: ...
    @staticmethod
    def schedule_based(currency: Currency | str) -> ImParameters: ...
    @staticmethod
    def cleared(currency: Currency | str) -> ImParameters: ...
    @staticmethod
    def repo_haircut(currency: Currency | str) -> ImParameters: ...
    @property
    def methodology(self) -> ImMethodology: ...
    @property
    def mpor_days(self) -> int: ...
    @property
    def threshold(self) -> Money: ...
    @property
    def mta(self) -> Money: ...
    @property
    def segregated(self) -> bool: ...

class EligibleCollateralSchedule:
    def __init__(self) -> None: ...
    @staticmethod
    def cash_only() -> EligibleCollateralSchedule: ...
    @staticmethod
    def bcbs_standard() -> EligibleCollateralSchedule: ...
    @staticmethod
    def us_treasuries() -> EligibleCollateralSchedule: ...
    @property
    def default_haircut(self) -> float | None: ...
    @property
    def rehypothecation_allowed(self) -> bool: ...
    @property
    def eligible(self) -> Any: ...

class CsaSpec:
    def __init__(
        self,
        id: str,
        base_currency: Currency | str,
        vm_params: VmParameters,
        *,
        im_params: ImParameters | None = ...,
        eligible_collateral: EligibleCollateralSchedule | None = ...,
        call_timing: MarginCallTiming | None = ...,
        collateral_curve_id: str,
    ) -> None: ...
    @staticmethod
    def usd_regulatory() -> CsaSpec: ...
    @staticmethod
    def eur_regulatory() -> CsaSpec: ...
    @property
    def id(self) -> str: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def vm_params(self) -> VmParameters: ...
    @property
    def im_params(self) -> ImParameters | None: ...
    @property
    def eligible_collateral(self) -> EligibleCollateralSchedule: ...
    @property
    def call_timing(self) -> MarginCallTiming: ...
    @property
    def collateral_curve_id(self) -> str: ...
    def requires_im(self) -> bool: ...
    def vm_threshold(self) -> Money: ...
    def im_threshold(self) -> Money | None: ...

# --- New types ---

class MarginCallType:
    """Type of margin call."""

    INITIAL_MARGIN: MarginCallType
    VARIATION_MARGIN_DELIVERY: MarginCallType
    VARIATION_MARGIN_RETURN: MarginCallType
    TOP_UP: MarginCallType
    SUBSTITUTION: MarginCallType

    @property
    def name(self) -> str: ...

class CollateralAssetClass:
    """BCBS-IOSCO collateral asset class."""

    CASH: CollateralAssetClass
    GOVERNMENT_BONDS: CollateralAssetClass
    AGENCY_BONDS: CollateralAssetClass
    COVERED_BONDS: CollateralAssetClass
    CORPORATE_BONDS: CollateralAssetClass
    EQUITY: CollateralAssetClass
    GOLD: CollateralAssetClass
    MUTUAL_FUNDS: CollateralAssetClass

    @staticmethod
    def custom(name: str) -> CollateralAssetClass: ...
    @property
    def name(self) -> str: ...
    def standard_haircut(self) -> float: ...

class ClearingStatus:
    """Clearing status: bilateral or cleared through a CCP."""

    @staticmethod
    def bilateral() -> ClearingStatus: ...
    @staticmethod
    def cleared(ccp: str) -> ClearingStatus: ...
    @property
    def is_bilateral(self) -> bool: ...
    @property
    def is_cleared(self) -> bool: ...
    @property
    def ccp(self) -> str | None: ...

class SimmRiskClass:
    """ISDA SIMM risk class."""

    INTEREST_RATE: SimmRiskClass
    CREDIT_QUALIFYING: SimmRiskClass
    CREDIT_NON_QUALIFYING: SimmRiskClass
    EQUITY: SimmRiskClass
    COMMODITY: SimmRiskClass
    FX: SimmRiskClass

    @property
    def name(self) -> str: ...

class RepoMarginType:
    """Repo margin mechanism type."""

    NONE: RepoMarginType
    MARK_TO_MARKET: RepoMarginType
    NET_EXPOSURE: RepoMarginType
    TRIPARTY: RepoMarginType

    @property
    def name(self) -> str: ...

class MarginCall:
    """A margin call event with all relevant details."""

    @property
    def call_date(self) -> datetime.date: ...
    @property
    def settlement_date(self) -> datetime.date: ...
    @property
    def call_type(self) -> MarginCallType: ...
    @property
    def amount(self) -> Money: ...
    @property
    def collateral_type(self) -> CollateralAssetClass | None: ...
    @property
    def mtm_trigger(self) -> Money: ...
    @property
    def threshold(self) -> Money: ...
    @property
    def mta_applied(self) -> Money: ...
    def is_delivery(self) -> bool: ...
    def is_return(self) -> bool: ...
    def days_to_settle(self) -> int: ...

class VmResult:
    """Variation margin calculation result."""

    @property
    def date(self) -> datetime.date: ...
    @property
    def gross_exposure(self) -> Money: ...
    @property
    def net_exposure(self) -> Money: ...
    @property
    def delivery_amount(self) -> Money: ...
    @property
    def return_amount(self) -> Money: ...
    @property
    def settlement_date(self) -> datetime.date: ...
    def net_margin(self) -> Money: ...
    def requires_call(self) -> bool: ...

class ImResult:
    """Initial margin calculation result."""

    @property
    def amount(self) -> Money: ...
    @property
    def methodology(self) -> ImMethodology: ...
    @property
    def as_of(self) -> datetime.date: ...
    @property
    def mpor_days(self) -> int: ...
    @property
    def breakdown(self) -> dict[str, Money]: ...

class InstrumentMarginResult:
    """Per-instrument margin calculation result."""

    @property
    def instrument_id(self) -> str: ...
    @property
    def as_of(self) -> datetime.date: ...
    @property
    def initial_margin(self) -> Money: ...
    @property
    def variation_margin(self) -> Money: ...
    @property
    def total_margin(self) -> Money: ...
    @property
    def im_methodology(self) -> ImMethodology: ...
    @property
    def is_cleared(self) -> bool: ...

class SimmSensitivities:
    """SIMM sensitivity inputs organized by risk class."""

    def __init__(self, base_currency: Currency | str) -> None: ...
    @property
    def base_currency(self) -> Currency: ...
    def add_ir_delta(self, currency: Currency | str, tenor: str, delta: float) -> None: ...
    def add_ir_vega(self, currency: Currency | str, tenor: str, vega: float) -> None: ...
    def add_credit_delta(self, name: str, qualifying: bool, tenor: str, delta: float) -> None: ...
    def add_equity_delta(self, underlier: str, delta: float) -> None: ...
    def add_equity_vega(self, underlier: str, vega: float) -> None: ...
    def add_fx_delta(self, currency: Currency | str, delta: float) -> None: ...
    def is_empty(self) -> bool: ...
    def total_ir_delta(self) -> float: ...
    def total_credit_delta(self) -> float: ...
    def total_equity_delta(self) -> float: ...
    def merge(self, other: SimmSensitivities) -> None: ...

class OtcMarginSpec:
    """OTC derivative margin specification (ISDA CSA compliant)."""

    @staticmethod
    def bilateral_simm(csa: CsaSpec) -> OtcMarginSpec: ...
    @staticmethod
    def bilateral_schedule(csa: CsaSpec) -> OtcMarginSpec: ...
    @staticmethod
    def cleared_spec(ccp: str, currency: Currency | str) -> OtcMarginSpec: ...
    @staticmethod
    def usd_bilateral() -> OtcMarginSpec: ...
    @staticmethod
    def eur_bilateral() -> OtcMarginSpec: ...
    @staticmethod
    def lch_swapclear(currency: Currency | str) -> OtcMarginSpec: ...
    @staticmethod
    def cme_cleared(currency: Currency | str) -> OtcMarginSpec: ...
    @staticmethod
    def ice_clear_credit() -> OtcMarginSpec: ...
    @property
    def csa(self) -> CsaSpec: ...
    @property
    def clearing_status(self) -> ClearingStatus: ...
    @property
    def im_methodology(self) -> ImMethodology: ...
    @property
    def vm_frequency(self) -> MarginTenor: ...
    @property
    def settlement_lag(self) -> int: ...
    def is_cleared(self) -> bool: ...
    def is_bilateral(self) -> bool: ...
    def ccp(self) -> str | None: ...
    def base_currency(self) -> Currency: ...

class RepoMarginSpec:
    """GMRA 2011 compliant repo margin specification."""

    def __init__(
        self,
        margin_type: RepoMarginType | str,
        margin_ratio: float,
        margin_call_threshold: float,
        *,
        call_frequency: MarginTenor | str | None = ...,
        settlement_lag: int = ...,
        pays_margin_interest: bool = ...,
        margin_interest_rate: float | None = ...,
        substitution_allowed: bool = ...,
    ) -> None: ...
    @staticmethod
    def none() -> RepoMarginSpec: ...
    @staticmethod
    def mark_to_market(margin_ratio: float, threshold: float) -> RepoMarginSpec: ...
    @staticmethod
    def triparty(margin_ratio: float) -> RepoMarginSpec: ...
    @property
    def margin_type(self) -> RepoMarginType: ...
    @property
    def margin_ratio(self) -> float: ...
    @property
    def margin_call_threshold(self) -> float: ...
    @property
    def call_frequency(self) -> MarginTenor: ...
    @property
    def settlement_lag(self) -> int: ...
    @property
    def pays_margin_interest(self) -> bool: ...
    @property
    def margin_interest_rate(self) -> float | None: ...
    @property
    def substitution_allowed(self) -> bool: ...
    def has_margining(self) -> bool: ...
    def required_collateral(self, cash_amount: float) -> float: ...
    def call_trigger_value(self, cash_amount: float) -> float: ...
    def requires_margin_call(self, cash_amount: float, current_collateral: float) -> bool: ...
    def margin_deficit(self, cash_amount: float, current_collateral: float) -> float: ...
    def excess_collateral(self, cash_amount: float, current_collateral: float) -> float: ...

class VmCalculator:
    """Variation margin calculator following ISDA CSA rules."""

    def __init__(self, csa: CsaSpec) -> None: ...
    def calculate(
        self,
        exposure: Money,
        posted_collateral: Money,
        as_of: datetime.date,
    ) -> VmResult: ...
    def generate_margin_calls(
        self,
        exposures: list[tuple[datetime.date, Money]],
        initial_collateral: Money,
    ) -> list[MarginCall]: ...
    def margin_call_dates(
        self,
        start: datetime.date,
        end: datetime.date,
    ) -> list[datetime.date]: ...

class SimmVersion:
    """SIMM version identifier."""

    V2_5: SimmVersion
    V2_6: SimmVersion

    @property
    def name(self) -> str: ...

class SimmCalculator:
    """ISDA SIMM calculator for sensitivity-based IM."""

    def __init__(self, version: SimmVersion | None = ...) -> None: ...
    def calculate_from_sensitivities(
        self,
        sensitivities: SimmSensitivities,
        currency: Currency | str,
    ) -> tuple[float, dict[str, Money]]: ...

__all__ = [
    "MarginTenor",
    "ImMethodology",
    "MarginCallTiming",
    "VmParameters",
    "ImParameters",
    "EligibleCollateralSchedule",
    "CsaSpec",
    "MarginCallType",
    "CollateralAssetClass",
    "ClearingStatus",
    "SimmRiskClass",
    "RepoMarginType",
    "MarginCall",
    "VmResult",
    "ImResult",
    "InstrumentMarginResult",
    "SimmSensitivities",
    "OtcMarginSpec",
    "RepoMarginSpec",
    "VmCalculator",
    "SimmVersion",
    "SimmCalculator",
]
