"""Agency CMO instrument bindings."""

from __future__ import annotations

from datetime import date
from typing import Sequence

from ....core.currency import Currency
from .mbs_passthrough import AgencyProgram

class CmoTrancheType:
    """CMO tranche type classification."""

    Sequential: "CmoTrancheType"
    Pac: "CmoTrancheType"
    Support: "CmoTrancheType"
    InterestOnly: "CmoTrancheType"
    PrincipalOnly: "CmoTrancheType"

    def __repr__(self) -> str: ...

class PacCollar:
    """PAC collar boundaries."""

    def __init__(self, lower_psa: float, upper_psa: float) -> None: ...
    @classmethod
    def standard(cls) -> "PacCollar": ...
    @property
    def lower_psa(self) -> float: ...
    @property
    def upper_psa(self) -> float: ...
    def __repr__(self) -> str: ...

class CmoTranche:
    """CMO tranche definition."""

    @classmethod
    def sequential(
        cls,
        tranche_id: str,
        face: float,
        currency: str | Currency,
        coupon: float,
        priority: int,
    ) -> "CmoTranche": ...
    @classmethod
    def pac(
        cls,
        tranche_id: str,
        face: float,
        currency: str | Currency,
        coupon: float,
        priority: int,
        collar: PacCollar,
    ) -> "CmoTranche": ...
    @classmethod
    def support(
        cls,
        tranche_id: str,
        face: float,
        currency: str | Currency,
        coupon: float,
        priority: int,
    ) -> "CmoTranche": ...
    @classmethod
    def io_strip(
        cls,
        tranche_id: str,
        notional: float,
        currency: str | Currency,
        coupon: float,
    ) -> "CmoTranche": ...
    @classmethod
    def po_strip(
        cls,
        tranche_id: str,
        face: float,
        currency: str | Currency,
    ) -> "CmoTranche": ...
    @property
    def id(self) -> str: ...
    @property
    def tranche_type(self) -> CmoTrancheType: ...
    @property
    def original_face(self) -> float: ...
    @property
    def current_face(self) -> float: ...
    @property
    def coupon(self) -> float: ...
    @property
    def priority(self) -> int: ...
    def __repr__(self) -> str: ...

class CmoWaterfall:
    """CMO waterfall structure."""

    def __init__(self, tranches: Sequence[CmoTranche]) -> None: ...
    @property
    def tranches(self) -> list[CmoTranche]: ...
    def get_tranche(self, tranche_id: str) -> CmoTranche | None: ...
    def total_current_face(self) -> float: ...
    def __repr__(self) -> str: ...

class AgencyCmoBuilder:
    def __init__(self, instrument_id: str) -> None: ...
    def deal_name(self, deal_name: str) -> "AgencyCmoBuilder": ...
    def agency(self, agency: AgencyProgram) -> "AgencyCmoBuilder": ...
    def issue_date(self, issue_date: date) -> "AgencyCmoBuilder": ...
    def waterfall(self, waterfall: CmoWaterfall) -> "AgencyCmoBuilder": ...
    def reference_tranche_id(self, reference_tranche_id: str) -> "AgencyCmoBuilder": ...
    def discount_curve_id(self, discount_curve_id: str) -> "AgencyCmoBuilder": ...
    def collateral_wac(self, collateral_wac: float | None = ...) -> "AgencyCmoBuilder": ...
    def collateral_wam(self, collateral_wam: int | None = ...) -> "AgencyCmoBuilder": ...
    def build(self) -> "AgencyCmo": ...

class AgencyCmo:
    """Agency Collateralized Mortgage Obligation."""

    @classmethod
    def builder(cls, instrument_id: str) -> AgencyCmoBuilder: ...
    @classmethod
    def example(cls) -> "AgencyCmo": ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def deal_name(self) -> str: ...
    @property
    def agency(self) -> AgencyProgram: ...
    @property
    def issue_date(self) -> date: ...
    @property
    def reference_tranche_id(self) -> str: ...
    @property
    def waterfall(self) -> CmoWaterfall: ...
    @property
    def discount_curve_id(self) -> str: ...
    def __repr__(self) -> str: ...
