"""Dollar Roll instrument bindings."""

from __future__ import annotations
from typing import Self

from datetime import date

from ....core.currency import Currency
from .mbs_passthrough import AgencyProgram
from .tba import TbaTerm

class DollarRollBuilder:
    def __init__(self, instrument_id: str) -> None: ...
    def agency(self, agency: AgencyProgram) -> "DollarRollBuilder": ...
    def coupon(self, coupon: float) -> "DollarRollBuilder": ...
    def term(self, term: TbaTerm) -> "DollarRollBuilder": ...
    def notional(self, notional: float) -> "DollarRollBuilder": ...
    def currency(self, currency: str | Currency) -> "DollarRollBuilder": ...
    def front_settlement_year(self, front_settlement_year: int) -> "DollarRollBuilder": ...
    def front_settlement_month(self, front_settlement_month: int) -> "DollarRollBuilder": ...
    def back_settlement_year(self, back_settlement_year: int) -> "DollarRollBuilder": ...
    def back_settlement_month(self, back_settlement_month: int) -> "DollarRollBuilder": ...
    def front_price(self, front_price: float) -> "DollarRollBuilder": ...
    def back_price(self, back_price: float) -> "DollarRollBuilder": ...
    def discount_curve_id(self, discount_curve_id: str) -> "DollarRollBuilder": ...
    def repo_curve_id(self, repo_curve_id: str) -> "DollarRollBuilder":
        """Set repo/financing curve identifier for carry calculations."""
        ...

    def to_json(self) -> str:
        """Serialize to JSON in envelope format.

        Returns:
            str: JSON string with schema version and tagged instrument spec.
        """
        ...

    @classmethod
    def from_json(cls, json_str: str) -> "Self":
        """Deserialize from JSON in envelope format.

        Args:
            json_str: JSON string in envelope format.

        Returns:
            The deserialized instrument.

        Raises:
            ValueError: If JSON is malformed or contains a different instrument type.
        """
        ...

    def trade_date(self, trade_date: date | None = ...) -> "DollarRollBuilder": ...
    def build(self) -> "DollarRoll": ...

class DollarRoll:
    """Dollar roll between TBA settlement months."""

    @classmethod
    def builder(cls, instrument_id: str) -> DollarRollBuilder: ...
    @classmethod
    def example(cls) -> "DollarRoll": ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def agency(self) -> AgencyProgram: ...
    @property
    def coupon(self) -> float: ...
    @property
    def term(self) -> TbaTerm: ...
    @property
    def notional(self) -> float: ...
    @property
    def front_settlement_year(self) -> int: ...
    @property
    def front_settlement_month(self) -> int: ...
    @property
    def back_settlement_year(self) -> int: ...
    @property
    def back_settlement_month(self) -> int: ...
    @property
    def front_price(self) -> float: ...
    @property
    def back_price(self) -> float: ...
    @property
    def discount_curve_id(self) -> str: ...
    def drop_value(self) -> float: ...
    def drop_32nds(self) -> float: ...
    def __repr__(self) -> str: ...
