"""Fixed income index total return swap instrument."""

from __future__ import annotations
from datetime import date
from ....core.money import Money
from ....core.market_data.context import MarketContext
from ...common import InstrumentType
from ..equity.trs import TrsSide, TrsFinancingLegSpec, TrsScheduleSpec, IndexUnderlying

class FiIndexTotalReturnSwapBuilder:
    """Fluent builder for FiIndexTotalReturnSwap."""
    def __init__(self, instrument_id: str) -> None: ...
    def notional(self, notional: Money) -> "FiIndexTotalReturnSwapBuilder": ...
    def underlying(self, underlying: IndexUnderlying) -> "FiIndexTotalReturnSwapBuilder": ...
    def financing(self, financing: TrsFinancingLegSpec) -> "FiIndexTotalReturnSwapBuilder": ...
    def schedule(self, schedule: TrsScheduleSpec) -> "FiIndexTotalReturnSwapBuilder": ...
    def side(self, side: TrsSide) -> "FiIndexTotalReturnSwapBuilder": ...
    def initial_level(self, initial_level: float | None = None) -> "FiIndexTotalReturnSwapBuilder": ...
    def build(self) -> "FiIndexTotalReturnSwap": ...
    def __repr__(self) -> str: ...

class FiIndexTotalReturnSwap:
    """Fixed income index total return swap."""

    @classmethod
    def builder(cls, instrument_id: str) -> FiIndexTotalReturnSwapBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def side(self) -> str: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def pv_total_return_leg(self, market: MarketContext, as_of: date) -> Money: ...
    def pv_financing_leg(self, market: MarketContext, as_of: date) -> Money: ...
    def financing_annuity(self, market: MarketContext, as_of: date) -> float: ...
    def __repr__(self) -> str: ...
