"""Agency MBS passthrough instrument bindings."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.dates.daycount import DayCount

class AgencyProgram:
    """Agency program (FNMA, FHLMC, GNMA)."""

    Fnma: "AgencyProgram"
    Fhlmc: "AgencyProgram"
    Gnma: "AgencyProgram"
    GnmaI: "AgencyProgram"
    GnmaII: "AgencyProgram"

    def __repr__(self) -> str: ...

class PoolType:
    """Pool type classification."""

    Generic: "PoolType"
    Specified: "PoolType"

    def __repr__(self) -> str: ...

class AgencyMbsPassthroughBuilder:
    def __init__(self, instrument_id: str) -> None: ...
    def pool_id(self, pool_id: str) -> "AgencyMbsPassthroughBuilder": ...
    def agency(self, agency: AgencyProgram) -> "AgencyMbsPassthroughBuilder": ...
    def original_face(self, original_face: float) -> "AgencyMbsPassthroughBuilder": ...
    def current_face(self, current_face: float) -> "AgencyMbsPassthroughBuilder": ...
    def currency(self, currency: str | Currency) -> "AgencyMbsPassthroughBuilder": ...
    def wac(self, wac: float) -> "AgencyMbsPassthroughBuilder": ...
    def pass_through_rate(self, pass_through_rate: float) -> "AgencyMbsPassthroughBuilder": ...
    def wam(self, wam: int) -> "AgencyMbsPassthroughBuilder": ...
    def issue_date(self, issue_date: date) -> "AgencyMbsPassthroughBuilder": ...
    def maturity_date(self, maturity_date: date) -> "AgencyMbsPassthroughBuilder": ...
    def discount_curve_id(self, discount_curve_id: str) -> "AgencyMbsPassthroughBuilder": ...
    def current_factor(self, current_factor: float | None = ...) -> "AgencyMbsPassthroughBuilder": ...
    def servicing_fee_rate(self, servicing_fee_rate: float) -> "AgencyMbsPassthroughBuilder": ...
    def guarantee_fee_rate(self, guarantee_fee_rate: float) -> "AgencyMbsPassthroughBuilder": ...
    def pool_type(self, pool_type: PoolType) -> "AgencyMbsPassthroughBuilder": ...
    def psa_speed(self, psa_speed: float) -> "AgencyMbsPassthroughBuilder": ...
    def day_count(self, day_count: DayCount) -> "AgencyMbsPassthroughBuilder": ...
    def build(self) -> "AgencyMbsPassthrough": ...

class AgencyMbsPassthrough:
    """Agency mortgage-backed security passthrough."""

    @classmethod
    def builder(cls, instrument_id: str) -> AgencyMbsPassthroughBuilder: ...
    @classmethod
    def example(cls) -> "AgencyMbsPassthrough": ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def pool_id(self) -> str: ...
    @property
    def agency(self) -> AgencyProgram: ...
    @property
    def pool_type(self) -> PoolType: ...
    @property
    def original_face(self) -> float: ...
    @property
    def current_face(self) -> float: ...
    @property
    def current_factor(self) -> float: ...
    @property
    def wac(self) -> float: ...
    @property
    def pass_through_rate(self) -> float: ...
    @property
    def servicing_fee_rate(self) -> float: ...
    @property
    def guarantee_fee_rate(self) -> float: ...
    @property
    def wam(self) -> int: ...
    @property
    def issue_date(self) -> date: ...
    @property
    def maturity_date(self) -> date: ...
    @property
    def discount_curve_id(self) -> str: ...
    def __repr__(self) -> str: ...
