"""Agency TBA instrument bindings."""

from __future__ import annotations
from typing import Self

from datetime import date

from ....core.currency import Currency
from .mbs_passthrough import AgencyProgram

class TbaTerm:
    """TBA original loan term."""

    ThirtyYear: "TbaTerm"
    TwentyYear: "TbaTerm"
    FifteenYear: "TbaTerm"

    def __repr__(self) -> str: ...

class TbaSettlement:
    """TBA settlement information."""

    @property
    def settlement_date(self) -> date: ...
    @property
    def notification_date(self) -> date: ...
    def __repr__(self) -> str: ...

class AgencyTbaBuilder:
    def __init__(self, instrument_id: str) -> None: ...
    def agency(self, agency: AgencyProgram) -> "AgencyTbaBuilder": ...
    def coupon(self, coupon: float) -> "AgencyTbaBuilder": ...
    def term(self, term: TbaTerm) -> "AgencyTbaBuilder": ...
    def settlement_year(self, settlement_year: int) -> "AgencyTbaBuilder": ...
    def settlement_month(self, settlement_month: int) -> "AgencyTbaBuilder": ...
    def notional(self, notional: float) -> "AgencyTbaBuilder": ...
    def currency(self, currency: str | Currency) -> "AgencyTbaBuilder": ...
    def trade_price(self, trade_price: float) -> "AgencyTbaBuilder": ...
    def discount_curve_id(self, discount_curve_id: str) -> "AgencyTbaBuilder": ...
    def trade_date(self, trade_date: date | None = ...) -> "AgencyTbaBuilder": ...
    def build(self) -> "AgencyTba": ...

class AgencyTba:
    """Agency To-Be-Announced (TBA) forward contract."""

    @classmethod
    def builder(cls, instrument_id: str) -> AgencyTbaBuilder: ...
    @classmethod
    def example(cls) -> "AgencyTba": ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def agency(self) -> AgencyProgram: ...
    @property
    def coupon(self) -> float: ...
    @property
    def term(self) -> TbaTerm: ...
    @property
    def settlement_year(self) -> int: ...
    @property
    def settlement_month(self) -> int: ...
    @property
    def notional(self) -> float: ...
    @property
    def trade_price(self) -> float: ...
    @property
    def discount_curve_id(self) -> str: ...
    def __repr__(self) -> str: ...
    def to_json(self) -> str:
        """Serialize to JSON in envelope format.

        Returns:
            str: JSON string with schema version and tagged instrument spec.
        """
        ...

    @classmethod
    def from_json(cls, json_str: str) -> "Self":
        """Deserialize from JSON in envelope format.

        Args:
            json_str: JSON string in envelope format.

        Returns:
            The deserialized instrument.

        Raises:
            ValueError: If JSON is malformed or contains a different instrument type.
        """
        ...
