"""Direct exotic valuation instrument wrappers."""

from __future__ import annotations

from typing import Any

class _ExoticInstrument:
    def __init__(self, spec: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    @staticmethod
    def from_json(json: str) -> "_ExoticInstrument": ...
    def to_json(self) -> str: ...
    def price(self, market: Any, as_of: str, model: str = "default") -> str: ...
    def price_with_metrics(
        self,
        market: Any,
        as_of: str,
        model: str = "default",
        metrics: list[str] = ...,
        pricing_options: str | None = None,
    ) -> str: ...

class _ExoticOptionInstrument(_ExoticInstrument):
    def delta(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def gamma(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def vega(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def theta(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def rho(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def vanna(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def volga(self, market: Any, as_of: str, model: str = "default") -> float: ...
    def greeks(self, market: Any, as_of: str, model: str = "default") -> dict[str, float]: ...

class AsianOption(_ExoticOptionInstrument): ...
class BarrierOption(_ExoticOptionInstrument): ...
class LookbackOption(_ExoticOptionInstrument): ...
class Basket(_ExoticInstrument): ...

__all__: list[str]
