"""Monte Carlo path data structures for visualization and analysis."""

from datetime import date
from typing import Optional, Dict, List, Tuple, Any
from enum import Enum

class CashflowType(Enum):
    """Type of cashflow for categorization and analysis."""
    
    Principal: int
    """Principal deployment (draws) or repayment"""
    
    Interest: int
    """Interest payment on drawn amounts"""
    
    CommitmentFee: int
    """Commitment fee on undrawn amounts"""
    
    UsageFee: int
    """Usage fee on drawn amounts"""
    
    FacilityFee: int
    """Facility fee on total commitment"""
    
    UpfrontFee: int
    """One-time upfront fee"""
    
    Recovery: int
    """Recovery proceeds on default"""
    
    MarkToMarket: int
    """Mark-to-market P&L at timestep"""
    
    Other: int
    """Other/generic cashflow"""

class PathPoint:
    """A single point along a Monte Carlo path."""

    @property
    def step(self) -> int:
        """Get the step index."""
        ...

    @property
    def time(self) -> float:
        """Get the time in years."""
        ...

    @property
    def state_vars(self) -> Dict[str, float]:
        """Get state variables as a dictionary."""
        ...

    @property
    def payoff_value(self) -> Optional[float]:
        """Get the payoff value at this point (if captured)."""
        ...

    def get_var(self, key: str) -> Optional[float]:
        """Get a specific state variable by name."""
        ...

    def spot(self) -> Optional[float]:
        """Get the spot price (convenience method)."""
        ...

    def variance(self) -> Optional[float]:
        """Get the variance (convenience method)."""
        ...

    def short_rate(self) -> Optional[float]:
        """Get the short rate (convenience method)."""
        ...

    @property
    def cashflows(self) -> List[Tuple[float, float, CashflowType]]:
        """Get cashflows generated at this timestep.
        
        Returns:
            List of (time_years, amount, type) cashflow tuples generated at this step.
            For revolving credit: interest, fees, principal changes.
        """
        ...

    def get_cashflows_by_type(self, cf_type: CashflowType) -> List[Tuple[float, float]]:
        """Get cashflows of a specific type.
        
        Args:
            cf_type: CashflowType to filter by
            
        Returns:
            List of (time, amount) pairs matching the specified type
        """
        ...

    def principal_flows(self) -> List[Tuple[float, float]]:
        """Get principal flows (convenience method)."""
        ...

    def interest_flows(self) -> List[Tuple[float, float]]:
        """Get interest flows (convenience method)."""
        ...

    def total_cashflow(self) -> float:
        """Get total cashflow amount at this timestep.
        
        Returns:
            Sum of all cashflows at this timestep
        """
        ...

    def total_cashflow_by_type(self, cf_type: CashflowType) -> float:
        """Get total cashflow amount for a specific type.
        
        Args:
            cf_type: CashflowType to sum
            
        Returns:
            Sum of all cashflows of the specified type
        """
        ...

    def to_dataframe(self) -> Any:
        """Convert cashflows to a pandas DataFrame.
        
        Returns:
            pd.DataFrame with columns:
                - step: timestep index
                - time_years: time in years
                - amount: cashflow amount
                - cashflow_type: type of cashflow as string
        """
        ...

class SimulatedPath:
    """A complete simulated Monte Carlo path."""

    @property
    def path_id(self) -> int:
        """Get the path ID."""
        ...

    @property
    def points(self) -> List[PathPoint]:
        """Get all points along the path."""
        ...

    @property
    def final_value(self) -> float:
        """Get the final discounted payoff value."""
        ...

    @property
    def irr(self) -> Optional[float]:
        """Get the IRR for this path (if calculated).
        
        Returns:
            Internal Rate of Return as annualized decimal (e.g., 0.08 for 8%),
            or None if IRR wasn't calculated or doesn't exist
        """
        ...

    def num_steps(self) -> int:
        """Get the number of time steps."""
        ...

    def point(self, step: int) -> Optional[PathPoint]:
        """Get a specific point by step index."""
        ...

    def initial_point(self) -> Optional[PathPoint]:
        """Get the initial point."""
        ...

    def terminal_point(self) -> Optional[PathPoint]:
        """Get the terminal point."""
        ...

    def extract_cashflows(self) -> List[Tuple[float, float]]:
        """Extract all cashflows from the path.
        
        Returns:
            All (time_years, amount) cashflow pairs across all timesteps.
            These are undiscounted cashflows as generated by the instrument.
        """
        ...

    def extract_typed_cashflows(self) -> List[Tuple[float, float, CashflowType]]:
        """Extract typed cashflows from the path.
        
        Returns:
            All (time, amount, type) tuples across all timesteps
        """
        ...

    def extract_cashflows_by_type(self, cf_type: CashflowType) -> List[Tuple[float, float]]:
        """Extract cashflows of a specific type.
        
        Args:
            cf_type: CashflowType to filter by
            
        Returns:
            All (time, amount) pairs matching the specified type
        """
        ...

    def to_dataframe(self) -> Any:
        """Convert all cashflows from the path to a pandas DataFrame.
        
        Returns:
            pd.DataFrame with columns:
                - path_id: path identifier
                - step: timestep index
                - time_years: time in years
                - amount: cashflow amount
                - cashflow_type: type of cashflow as string
        """
        ...

    def get_cashflows_with_dates(self, base_date: date) -> List[Tuple[date, float]]:
        """Get cashflows with calendar dates.
        
        Args:
            base_date: Commitment/start date of the facility (used to convert year fractions to dates)
            
        Returns:
            List of (date, amount) pairs suitable for XIRR calculation.
            Dates are approximated using 365.25 days per year from base_date.
        """
        ...

    def __len__(self) -> int: ...

class PathDataset:
    """Collection of simulated paths with metadata."""

    @property
    def paths(self) -> List[SimulatedPath]:
        """Get all captured paths."""
        ...

    @property
    def num_paths_total(self) -> int:
        """Get the total number of paths in the simulation."""
        ...

    @property
    def sampling_method(self) -> str:
        """Get the sampling method used."""
        ...

    def num_captured(self) -> int:
        """Get the number of captured paths."""
        ...

    def path(self, index: int) -> Optional[SimulatedPath]:
        """Get a specific path by index."""
        ...

    def is_complete(self) -> bool:
        """Check if all paths were captured."""
        ...

    def sampling_ratio(self) -> float:
        """Get the sampling ratio (captured / total)."""
        ...

    def state_var_keys(self) -> List[str]:
        """Get all state variable keys present in the dataset."""
        ...

    def to_dict(self) -> Dict[str, List]:
        """
        Convert to a long-format dictionary suitable for pandas DataFrame.

        Returns a dictionary with columns:
        - path_id: Path identifier
        - step: Time step index
        - time: Time in years
        - final_value: Final discounted payoff for this path
        - One column per state variable (e.g., 'spot', 'variance')
        - payoff_value: Optional payoff at each step (if captured)
        """
        ...

    def to_wide_dict(self, state_var: str) -> Dict[str, List]:
        """
        Convert to a wide-format dictionary (paths as columns).

        Args:
            state_var: Name of the state variable to extract (e.g., 'spot')

        Returns a dictionary with:
        - time: Time points (shared across all paths)
        - step: Step indices
        - path_0, path_1, ...: State variable values for each path
        """
        ...

    def to_dataframe(self) -> Any:
        """Convert to pandas DataFrame.
        
        Returns:
            pd.DataFrame: Long-format DataFrame with all paths and state variables
        """
        ...

    def cashflows_to_dataframe(self) -> Any:
        """Convert all cashflows from all paths to a pandas DataFrame.
        
        Returns:
            pd.DataFrame with columns:
                - path_id: path identifier
                - step: timestep index
                - time_years: time in years
                - amount: cashflow amount
                - cashflow_type: type of cashflow as string
        """
        ...

    def __len__(self) -> int: ...

__all__ = ["CashflowType", "PathPoint", "SimulatedPath", "PathDataset"]
