// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalibrationMethod } from "./CalibrationMethod";
import type { MultiCurveConfig } from "./MultiCurveConfig";
import type { RateBounds } from "./RateBounds";
import type { RateBoundsPolicy } from "./RateBoundsPolicy";
import type { SolverKind } from "./SolverKind";
import type { ValidationMode } from "./ValidationMode";

/**
 * Configuration for calibration processes.
 */
export type CalibrationConfig = { 
/**
 * Solver tolerance for convergence checks
 */
tolerance: number, 
/**
 * Maximum iterations for solver
 */
max_iterations: number, 
/**
 * Use parallel processing when available
 */
use_parallel: boolean, 
/**
 * Random seed for reproducible results
 */
random_seed: bigint | null, 
/**
 * Enable verbose logging
 */
verbose: boolean, 
/**
 * Solver type selection
 */
solver_kind: SolverKind, 
/**
 * Entity-specific seniority mappings for credit calibration
 */
entity_seniority: Record<string, string>, 
/**
 * Multi-curve framework configuration
 */
multi_curve: MultiCurveConfig, 
/**
 * Use finite-difference gradients for SABR calibration instead of analytical approximations.
 * Analytical gradients are faster but use approximations (treating x(z) as ~constant).
 * FD gradients are slower but more accurate, especially for far-from-ATM strikes.
 */
use_fd_sabr_gradients: boolean, 
/**
 * Runtime validation mode (warnings vs errors). Feature `strict_validation` may still harden checks.
 */
validation_mode: ValidationMode, 
/**
 * Validation configuration with thresholds and checks
 */
validation: Record<string, unknown>, 
/**
 * Policy for selecting rate bounds (explicit vs currency-derived).
 *
 * - `auto_currency` is market-standard: bounds depend on currency/market regime.
 * - `explicit` uses `rate_bounds` as provided.
 */
rate_bounds_policy: RateBoundsPolicy, 
/**
 * Rate bounds for forward/zero rate calibration.
 * Currency-specific defaults can be set via `with_rate_bounds_for_currency()`.
 */
rate_bounds: RateBounds, 
/**
 * Calibration method (bootstrap vs global solve).
 */
calibration_method: CalibrationMethod, };
