// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calibration method selection (bootstrap vs global solve).
 */
export type CalibrationMethod = "Bootstrap" | { "GlobalSolve": { 
/**
 * Use analytical Jacobian if available (otherwise finite-difference).
 */
use_analytical_jacobian: boolean, } };
