// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Credit instrument quotes for hazard curve and correlation calibration.
 */
export type CreditQuote = { "c_d_s": {
/**
 * Reference entity
 */
entity: string,
/**
 * CDS maturity
 */
maturity: string,
/**
 * Par spread in basis points
 */
spread_bp: number,
/**
 * Recovery rate assumption
 */
recovery_rate: number,
/**
 * Currency
 */
currency: string, } } | { "c_d_s_upfront": {
/**
 * Reference entity
 */
entity: string,
/**
 * CDS maturity
 */
maturity: string,
/**
 * Upfront payment (% of notional, positive = protection buyer pays)
 */
upfront_pct: number,
/**
 * Running spread in basis points
 */
running_spread_bp: number,
/**
 * Recovery rate assumption
 */
recovery_rate: number,
/**
 * Currency
 */
currency: string, } } | { "c_d_s_tranche": {
/**
 * Index name (e.g., "CDX.NA.IG.42")
 */
index: string,
/**
 * Attachment point (%)
 */
attachment: number,
/**
 * Detachment point (%)
 */
detachment: number,
/**
 * Maturity date
 */
maturity: string,
/**
 * Upfront payment (% of notional)
 */
upfront_pct: number,
/**
 * Running spread (bps)
 */
running_spread_bp: number, } };
