// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResidualWeightingScheme } from "./ResidualWeightingScheme";

/**
 * Discount-curve specific numerical solver configuration.
 *
 * Controls the search space and numerical stability of the discount curve
 * bootstrapping or global solve process.
 *
 * # Invariants
 * - `df_hard_min` > 0
 * - `scan_grid_points` > 0
 *
 * # Examples
 * ```rust,no_run
 * use finstack_valuations::calibration::DiscountCurveSolveConfig;
 *
 * let config = DiscountCurveSolveConfig {
 *     scan_grid_points: 64,
 *     df_hard_min: 1e-10,
 *     ..Default::default()
 * };
 * ```
 */
export type DiscountCurveSolveConfig = { 
/**
 * Number of points in the initial geometric scan grid.
 */
scan_grid_points: number, 
/**
 * Minimum required success points in scan before attempting polish.
 */
min_scan_grid_points: number, 
/**
 * Initial step size for geometric scan grid.
 */
scan_grid_step: number, 
/**
 * Absolute minimum allowed discount factor (prevents singularity).
 */
df_hard_min: number, 
/**
 * Absolute maximum allowed discount factor (prevents divergence).
 */
df_hard_max: number, 
/**
 * Minimum time threshold for considering a knot at spot (t=0).
 */
min_t_spot: number, 
/**
 * Whether to use a sequential bootstrap to seed a global solve.
 */
bootstrap_seed_global_solve: boolean, 
/**
 * Override final-curve monotonicity enforcement (None = policy-driven).
 */
allow_non_monotonic_final: boolean | null, 
/**
 * Weighting scheme for global solve residuals.
 */
weighting_scheme: ResidualWeightingScheme, 
/**
 * Step size (h) for finite-difference Jacobian calculation.
 */
jacobian_step_size: number, 
/**
 * Tolerance for determining calibration success (applied to residuals).
 */
validation_tolerance: number, };
