// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Specifications for interest rate futures contracts.
 */
export type FutureSpecs = {
/**
 * Contract multiplier
 */
multiplier: number,
/**
 * Face value
 */
face_value: number,
/**
 * Number of delivery months
 */
delivery_months: number,
/**
 * Day count convention
 */
day_count: string,
/**
 * Convexity adjustment (for long-dated futures)
 */
convexity_adjustment: number | null,
/**
 * Tick size (minimum price increment, e.g., 0.0025 for STIR)
 */
tick_size: number,
/**
 * Tick value (dollar value per tick, e.g., 6.25 for CME 3M SOFR)
 */
tick_value: number, };
