// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResidualWeightingScheme } from "./ResidualWeightingScheme";

/**
 * Hazard-curve specific numerical solver configuration.
 *
 * Controls the search space and numerical stability of hazard curve
 * bootstrapping or global solve for credit curve calibration.
 *
 * # Invariants
 * - `hazard_hard_min` >= 0 (hazard rates must be non-negative)
 * - `hazard_hard_max` > `hazard_hard_min`
 *
 * # Examples
 * ```rust,no_run
 * use finstack_valuations::calibration::HazardCurveSolveConfig;
 *
 * // For distressed debt scenarios, increase the max hazard rate
 * let config = HazardCurveSolveConfig {
 *     hazard_hard_max: 100.0,  // Allow up to ~100% default probability per year
 *     ..Default::default()
 * };
 * ```
 */
export type HazardCurveSolveConfig = { 
/**
 * Minimum allowed hazard rate (must be non-negative for survival monotonicity).
 */
hazard_hard_min: number, 
/**
 * Maximum allowed hazard rate.
 *
 * The default of 10.0 corresponds to roughly 99.995% 1Y default probability.
 * For distressed/distressed sovereign scenarios, increase to 50.0 or 100.0.
 */
hazard_hard_max: number, 
/**
 * Weighting scheme for global solve residuals.
 */
weighting_scheme: ResidualWeightingScheme, 
/**
 * Tolerance for determining calibration success (applied to residuals).
 */
validation_tolerance: number, };
