// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-instrument conventions for calibration.
 *
 * These optional fields allow each quote to specify its own settlement,
 * payment, and fixing conventions. When not specified, the calibrator
 * uses currency-specific defaults.
 *
 * # Example
 *
 * ```ignore
 * let conventions = InstrumentConventions {
 *     settlement_days: Some(0),  // T+0 for this instrument
 *     calendar_id: Some("gblo".to_string()),
 *     ..Default::default()
 * };
 * ```
 */
export type InstrumentConventions = { 
/**
 * Settlement lag in business days from trade date (e.g., 0 for T+0, 2 for T+2)
 */
settlement_days: number | null, 
/**
 * Payment delay in business days after period end
 */
payment_delay_days: number | null, 
/**
 * Reset lag in business days for floating rate fixings
 */
reset_lag: number | null, 
/**
 * Calendar identifier for schedule generation and business day adjustments
 */
calendar_id: string | null, };
