// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notional exchange convention for XCCY swaps.
 */
export type NotionalExchange = "none" | "final" | "initial_and_final";
