// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FutureSpecs } from "./FutureSpecs";
import type { InstrumentConventions } from "./InstrumentConventions";

/**
 * Interest rate instrument quotes for yield curve calibration.
 */
export type RatesQuote = { "deposit": { 
/**
 * Maturity date
 */
maturity: string, 
/**
 * Quoted rate (decimal)
 */
rate: number, 
/**
 * Day count convention
 */
day_count: string, 
/**
 * Per-instrument conventions (settlement, calendar, etc.)
 */
conventions: InstrumentConventions, } } | { "f_r_a": { 
/**
 * Start date
 */
start: string, 
/**
 * End date
 */
end: string, 
/**
 * Quoted rate (decimal)
 */
rate: number, 
/**
 * Day count convention
 */
day_count: string, 
/**
 * Per-instrument conventions (settlement, reset lag, etc.)
 */
conventions: InstrumentConventions, } } | { "future": { 
/**
 * Expiry date
 */
expiry: string, 
/**
 * Contract price (e.g., 99.25 for 0.75% implied rate)
 */
price: number, 
/**
 * Contract specifications
 */
specs: FutureSpecs, 
/**
 * Per-instrument conventions (reset lag, etc.)
 */
conventions: InstrumentConventions, } } | { "swap": { 
/**
 * Swap maturity
 */
maturity: string, 
/**
 * Par rate (decimal)
 */
rate: number, 
/**
 * Fixed leg frequency
 */
fixed_freq: string, 
/**
 * Float leg frequency
 */
float_freq: string, 
/**
 * Fixed leg day count
 */
fixed_dc: string, 
/**
 * Float leg day count
 */
float_dc: string, 
/**
 * Float leg index (e.g., "3M-LIBOR")
 */
index: string, 
/**
 * Per-instrument conventions (settlement, payment delay, reset lag, calendar)
 */
conventions: InstrumentConventions, } } | { "basis_swap": { 
/**
 * Swap maturity
 */
maturity: string, 
/**
 * Primary leg index (e.g., "3M-LIBOR", "3M-SOFR")
 */
primary_index: string, 
/**
 * Reference leg index (e.g., "6M-LIBOR", "1M-SOFR")
 */
reference_index: string, 
/**
 * Basis spread in basis points (primary pays reference + spread)
 */
spread_bp: number, 
/**
 * Primary leg frequency
 */
primary_freq: string, 
/**
 * Reference leg frequency
 */
reference_freq: string, 
/**
 * Primary leg day count
 */
primary_dc: string, 
/**
 * Reference leg day count
 */
reference_dc: string, 
/**
 * Currency for both legs
 */
currency: string, 
/**
 * Per-instrument conventions (settlement, reset lag, calendar)
 */
conventions: InstrumentConventions, } };
