// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step-level conventions for rates calibration (discount and forward curves).
 *
 * This is a Bloomberg/FinCad-style design: curve construction uses a small set of
 * *step-level* conventions (e.g., curve time-axis day count).
 */
export type RatesStepConventions = {
/**
 * Day count used to map dates to year fractions for curve knot times.
 */
curve_day_count: string | null, };
