// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How `CalibrationConfig` obtains rate bounds.
 *
 * Market-standard bounds depend on currency/market regime. `AutoCurrency` makes this choice
 * explicit and avoids relying on `RateBounds::default()` as an implicit assumption.
 */
export type RateBoundsPolicy = "auto_currency" | "explicit";
