// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Policy for weighting residuals in global solve calibration.
 *
 * Determines how the objective function weights individual instrument fitting
 * errors (residuals) during optimization.
 *
 * # Variants
 * - [`Equal`]: Every instrument contributes equally to the objective.
 * - [`LinearTime`]: Weights increase linearly with time to maturity.
 * - [`SqrtTime`]: Weights increase with the square root of time (market-standard).
 * - [`InverseDuration`]: Weights based on inverse DV01 approximation.
 */
export type ResidualWeightingScheme = "Equal" | "LinearTime" | "SqrtTime" | "InverseDuration";
