// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Volatility quotes for surface calibration.
 */
export type VolQuote = { "option_vol": { 
/**
 * Underlying identifier
 */
underlying: string, 
/**
 * Option expiry
 */
expiry: string, 
/**
 * Strike (rate for swaptions, price for equity/FX)
 */
strike: number, 
/**
 * Implied volatility
 */
vol: number, 
/**
 * Option type ("Call", "Put", "Straddle")
 */
option_type: string, } } | { "swaption_vol": { 
/**
 * Option expiry
 */
expiry: string, 
/**
 * Underlying swap maturity date
 */
maturity: string, 
/**
 * Strike rate
 */
strike: number, 
/**
 * Implied volatility
 */
vol: number, 
/**
 * Quote type (ATM, OTM, etc.)
 */
quote_type: string, } };
