//! Variance swap type definitions.

use finstack_core::{
    dates::{Date, DayCount, Frequency},
    market_data::context::MarketContext,
    math::stats::{realized_variance, RealizedVarMethod},
    money::Money,
    types::id::{CurveId, InstrumentId},
    Result, F,
};

use crate::{
    cashflow::traits::{CashflowProvider, DatedFlows},
    instruments::common::traits::Attributes,
};


/// Side of the variance swap (pay or receive variance).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PayReceive {
    /// Pay variance (short variance)
    Pay,
    /// Receive variance (long variance)
    Receive,
}

impl PayReceive {
    /// Get the sign multiplier for PV calculation.
    pub fn sign(&self) -> F {
        match self {
            PayReceive::Pay => -1.0,
            PayReceive::Receive => 1.0,
        }
    }
}

/// Variance swap instrument.
///
/// A variance swap is a forward contract on realized variance with payoff:
/// Notional * (Realized Variance - Strike Variance)
#[derive(Clone, Debug, finstack_macros::FinancialBuilder)]
pub struct VarianceSwap {
    /// Unique instrument identifier
    pub id: InstrumentId,
    /// Underlying identifier (equity/index)
    pub underlying_id: String,
    /// Variance notional (in variance units)
    pub notional: Money,
    /// Strike variance (annualized)
    pub strike_variance: F,
    /// Start date of observation period
    pub start_date: Date,
    /// Maturity/settlement date
    pub maturity: Date,
    /// Observation frequency
    pub observation_freq: Frequency,
    /// Method for calculating realized variance
    pub realized_var_method: RealizedVarMethod,
    /// Pay/receive variance
    pub side: PayReceive,
    /// Discount curve identifier
    pub disc_id: CurveId,
    /// Day count convention for time calculations
    pub day_count: DayCount,
    /// Attributes for scenario selection
    pub attributes: Attributes,
}

impl VarianceSwap {
    // (builder generated by derive)

    /// Calculate payoff given realized variance.
    pub fn payoff(&self, realized_variance: F) -> Money {
        let variance_diff = realized_variance - self.strike_variance;
        let sign = self.side.sign();
        Money::new(
            self.notional.amount() * variance_diff * sign,
            self.notional.currency(),
        )
    }

    /// Get observation dates based on frequency.
    pub fn observation_dates(&self) -> Vec<Date> {
        use finstack_core::dates::utils::add_months;

        // Simple date generation based on frequency
        let mut dates = Vec::new();
        let mut current = self.start_date;

        // Determine the step based on frequency
        if let Some(months_step) = self.observation_freq.months() {
            // Month-based frequency
            while current <= self.maturity {
                dates.push(current);
                current = add_months(current, months_step as i32);

                if current > self.maturity {
                    break;
                }
            }
        } else if let Some(days_step) = self.observation_freq.days() {
            // Day-based frequency
            while current <= self.maturity {
                dates.push(current);
                current += time::Duration::days(days_step as i64);

                if current > self.maturity {
                    break;
                }
            }
        } else {
            // Default to daily for unknown frequency
            while current <= self.maturity {
                dates.push(current);
                current += time::Duration::days(1);

                if current > self.maturity {
                    break;
                }
            }
        }

        // Ensure maturity is included if not already
        if dates.is_empty() || dates.last() != Some(&self.maturity) {
            dates.push(self.maturity);
        }

        dates
    }

    /// Calculate annualization factor based on observation frequency.
    pub fn annualization_factor(&self) -> F {
        // Check month-based frequencies first
        if let Some(months) = self.observation_freq.months() {
            match months {
                1 => 12.0,  // Monthly
                3 => 4.0,   // Quarterly
                6 => 2.0,   // Semi-annual
                12 => 1.0,  // Annual
                _ => 252.0, // Default to daily for other month counts
            }
        } else if let Some(days) = self.observation_freq.days() {
            // Handle day-based frequencies
            match days {
                1 => 252.0,             // Daily (trading days)
                7 => 52.0,              // Weekly
                14 => 26.0,             // Bi-weekly
                _ => 365.0 / days as F, // General day-based approximation
            }
        } else {
            252.0 // Default to daily
        }
    }

    /// Sampling policy aware annualization factor (uses market overrides when available).
    pub(crate) fn annualization_factor_with_policy(&self, context: &MarketContext) -> F {
        // Allow market override via unitless scalars
        // Priority: UNDERLYING_TRADING_DAYS_PER_YEAR, TRADING_DAYS_PER_YEAR
        let tdy_override = context
            .price(format!("{}_TRADING_DAYS_PER_YEAR", self.underlying_id))
            .ok()
            .and_then(|s| match s {
                finstack_core::market_data::scalars::MarketScalar::Unitless(v) => Some(*v),
                _ => None,
            })
            .or_else(|| {
                context
                    .price("TRADING_DAYS_PER_YEAR")
                    .ok()
                    .and_then(|s| match s {
                        finstack_core::market_data::scalars::MarketScalar::Unitless(v) => Some(*v),
                        _ => None,
                    })
            })
            .unwrap_or(252.0);

        if let Some(months) = self.observation_freq.months() {
            return match months {
                1 => 12.0,
                3 => 4.0,
                6 => 2.0,
                12 => 1.0,
                _ => tdy_override,
            };
        }
        if let Some(days) = self.observation_freq.days() {
            return match days {
                1 => tdy_override,
                7 => 52.0,
                14 => 26.0,
                _ => 365.0 / days as F,
            };
        }
        tdy_override
    }

    /// Calculate the fraction of time elapsed in the observation period.
    pub fn time_elapsed_fraction(&self, as_of: Date) -> F {
        if as_of <= self.start_date {
            return 0.0;
        }
        if as_of >= self.maturity {
            return 1.0;
        }

        let total_days = (self.maturity - self.start_date).whole_days() as F;
        let elapsed_days = (as_of - self.start_date).whole_days() as F;
        elapsed_days / total_days
    }

    /// Calculate realized fraction based on observation counts (sampling-based weight).
    pub(crate) fn realized_fraction_by_observations(&self, as_of: Date) -> F {
        let all = self.observation_dates();
        if all.is_empty() {
            return 0.0;
        }
        if as_of <= self.start_date {
            return 0.0;
        }
        if as_of >= self.maturity {
            return 1.0;
        }
        let total = all.len() as F;
        let realized = all.iter().filter(|&&d| d <= as_of).count() as F;
        (realized / total).clamp(0.0, 1.0)
    }

    /// Get historical prices aligned to observation dates when available.
    pub(crate) fn get_historical_prices(
        &self,
        context: &MarketContext,
        as_of: Date,
    ) -> Result<Vec<F>> {
        // Try generic time series first (preferred)
        if let Ok(series) = context.series(&self.underlying_id) {
            let dates: Vec<Date> = self
                .observation_dates()
                .into_iter()
                .filter(|&d| d <= as_of)
                .collect();
            if dates.len() >= 2 {
                return series.values_on(&dates);
            }
        }
        // Fallback to single spot scalar
        if let Ok(scalar) = context.price(&self.underlying_id) {
            let spot = match scalar {
                finstack_core::market_data::scalars::MarketScalar::Unitless(v) => *v,
                finstack_core::market_data::scalars::MarketScalar::Price(p) => p.amount(),
            };
            Ok(vec![spot])
        } else {
            Ok(vec![])
        }
    }

    /// Calculate partial realized variance for the elapsed period.
    pub(crate) fn partial_realized_variance(
        &self,
        context: &MarketContext,
        as_of: Date,
    ) -> Result<F> {
        let prices = self.get_historical_prices(context, as_of)?;
        if prices.len() < 2 {
            return Ok(0.0);
        }
        Ok(realized_variance(
            &prices,
            self.realized_var_method,
            self.annualization_factor_with_policy(context),
        ))
    }

    /// Calculate implied forward variance for the remaining period.
    pub(crate) fn remaining_forward_variance(
        &self,
        context: &MarketContext,
        _as_of: Date,
    ) -> Result<F> {
        // Prefer replication from a vol surface; fallback to ATM surface vol,
        // then scalar implied vol, and finally strike variance.

        // Remaining tenor in years
        let t = self
            .day_count
            .year_fraction(_as_of, self.maturity, Default::default())?;

        // Try surfaces with common ids first
        for sid in [
            self.underlying_id.as_str(),
            &format!("{}_VOL", self.underlying_id),
            &format!("{}_IMPL_VOL", self.underlying_id),
        ] {
            if let Ok(surface) = context.surface_ref(sid) {
                // Attempt variance replication (VIX-like)
                if let Ok(disc) = context.get_ref::<finstack_core::market_data::term_structures::discount_curve::DiscountCurve>(self.disc_id.as_str()) {
                    if let Ok(spot_scalar) = context.price(&self.underlying_id) {
                        let spot = match spot_scalar {
                            finstack_core::market_data::scalars::MarketScalar::Unitless(v) => *v,
                            finstack_core::market_data::scalars::MarketScalar::Price(p) => p.amount(),
                        };
                        let r = disc.zero(t.max(1e-8));
                        let q = context
                            .price(format!("{}-DIVYIELD", self.underlying_id))
                            .ok()
                            .and_then(|s| match s {
                                finstack_core::market_data::scalars::MarketScalar::Unitless(v) => Some(*v),
                                _ => None,
                            })
                            .unwrap_or(0.0);
                        // Forward price
                        let fwd = spot * ((r - q) * t).exp();
                        let strikes = surface.strikes();
                        if t > 0.0 && strikes.len() >= 3 && fwd.is_finite() && fwd > 0.0 {
                            // Find K0 (strike just below forward)
                            let mut k0_idx = 0usize;
                            for (i, &k) in strikes.iter().enumerate() {
                                if k <= fwd {
                                    k0_idx = i;
                                } else {
                                    break;
                                }
                            }
                            let k0 = strikes[k0_idx].max(1e-12);

                            // Compute sum over OTM options
                            let mut sum = 0.0;
                            for i in 0..strikes.len() {
                                let k = strikes[i].max(1e-12);
                                // ΔK
                                let dk = if i == 0 {
                                    strikes[1] - strikes[0]
                                } else if i + 1 == strikes.len() {
                                    strikes[i] - strikes[i - 1]
                                } else {
                                    0.5 * (strikes[i + 1] - strikes[i - 1])
                                };

                                // Option price Q(K): OTM put for K < F, OTM call for K > F, average at K0
                                let vol = surface.value_clamped(t, k).max(1e-8);
                                let sqrt_t = t.sqrt();
                                // Black-Scholes helper
                                let d1 = if vol > 0.0 && t > 0.0 {
                                    ((spot / k).ln() + (r - q + 0.5 * vol * vol) * t) / (vol * sqrt_t)
                                } else {
                                    0.0
                                };
                                let d2 = d1 - vol * sqrt_t;
                                let exp_mqt = (-q * t).exp();
                                let exp_mrt = (-r * t).exp();
                                let call = spot * exp_mqt * finstack_core::math::norm_cdf(d1)
                                    - k * exp_mrt * finstack_core::math::norm_cdf(d2);
                                let put = k * exp_mrt * finstack_core::math::norm_cdf(-d2)
                                    - spot * exp_mqt * finstack_core::math::norm_cdf(-d1);

                                let qk = if (i == k0_idx) || ((k0 - k).abs() < 1e-12 && (fwd - k0).abs() < 1e-12) {
                                    0.5 * (call + put)
                                } else if k < fwd {
                                    put
                                } else {
                                    call
                                };
                                sum += (dk / (k * k)) * qk;
                            }
                            let variance = (2.0 * (r * t).exp() / t) * sum - (1.0 / t) * ((fwd / k0 - 1.0).powi(2));
                            if variance.is_finite() && variance > 0.0 {
                                return Ok(variance);
                            }
                        }
                        // Fallback to ATM vol at spot as strike
                        let vol_atm = surface.value_clamped(t.max(1e-8), spot);
                        if vol_atm.is_finite() && vol_atm > 0.0 {
                            return Ok(vol_atm * vol_atm);
                        }
                    }
                }
            }
        }

        // Try to get implied vol from scalar market data
        if let Ok(scalar) = context.price(format!("{}_IMPL_VOL", self.underlying_id)) {
            let vol = match scalar {
                finstack_core::market_data::scalars::MarketScalar::Unitless(v) => *v,
                finstack_core::market_data::scalars::MarketScalar::Price(p) => p.amount(),
            };
            Ok(vol * vol)
        } else {
            // Default to strike variance as forward estimate
            Ok(self.strike_variance)
        }
    }
}

// Use the macro to implement Instrument with pricing
crate::impl_instrument!(
    VarianceSwap, 
    "VarianceSwap",
    pv = |s, curves, as_of| crate::instruments::variance_swap::pricing::engine::price(s, curves, as_of)
);

// Do not add explicit Instrument impl; provided by blanket impl.

// Attributable implementation is provided by the impl_instrument! macro

impl CashflowProvider for VarianceSwap {
    fn build_schedule(&self, _context: &MarketContext, _as_of: Date) -> Result<DatedFlows> {
        // Variance swaps have a single payment at maturity
        // The amount is not known until maturity (path-dependent)
        Ok(vec![(
            self.maturity,
            Money::new(0.0, self.notional.currency()),
        )])
    }
}
