"""Apply deterministic schema overrides for instrument JSON docs.

These schema files are checked in and can be regenerated by upstream tooling.
This script reapplies local behavior/documentation overrides so they persist
across regeneration.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

BOND_SCHEMA = ROOT / "finstack/valuations/schemas/instruments/1/fixed_income/bond.schema.json"
IR_FUTURE_SCHEMA = ROOT / "finstack/valuations/schemas/instruments/1/rates/interest_rate_future.schema.json"

BOND_DESCRIPTION = (
    "Fixed income bond instrument with fixed, floating, or amortizing cashflows. "
    "`issue`/`issue_date` is typically provided; when omitted, deserialization "
    "requires `pricing_overrides.quoted_clean_price`."
)
IR_FUTURE_DESCRIPTION = (
    "Exchange-traded interest rate future. `fixing_date`, `period_start`, and "
    "`period_end` are optional and may be derived from `expiry_date` and contract conventions."
)


def _load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _write_json(path: Path, payload: dict) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")


def _sync_bond_schema() -> None:
    schema = _load_json(BOND_SCHEMA)
    schema["description"] = BOND_DESCRIPTION

    top_spec = schema["examples"][0]["instrument"]["spec"]
    top_spec.pop("issue", None)
    top_spec.pop("issue_date", None)
    top_spec["pricing_overrides"]["quoted_clean_price"] = 98.75

    _write_json(BOND_SCHEMA, schema)


def _sync_ir_future_schema() -> None:
    schema = _load_json(IR_FUTURE_SCHEMA)
    schema["description"] = IR_FUTURE_DESCRIPTION

    example_spec = schema["properties"]["instrument"]["example"]["spec"]
    example_spec.pop("fixing_date", None)
    example_spec.pop("period_start", None)
    example_spec.pop("period_end", None)

    _write_json(IR_FUTURE_SCHEMA, schema)


def main() -> None:
    """Sync checked-in instrument schemas with local override policy."""
    _sync_bond_schema()
    _sync_ir_future_schema()
    print("Synchronized instrument schema overrides.")


if __name__ == "__main__":
    main()
