#![allow(missing_docs)]

//! Built-in holiday calendars (behind the `holidays` feature).
//!
//! This module auto-discovers all `*.rs` files inside the `src/dates/calendars` directory at
//! compile time.  A build script generates a file listing `pub mod <name>;` and corresponding
//! re-exports for each calendar module.  We simply include that generated file here so that any
//! new calendars added to the directory are picked up automatically without having to modify
//! this file.

// Auto-generated by `build.rs` (`OUT_DIR/generated_calendars.rs`)
include!(concat!(env!("OUT_DIR"), "/generated_calendars.rs"));
