"""FX spot, option, and swap instrument wrappers."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.dates.daycount import DayCount
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class FxSpotBuilder:
    """Fluent builder returned by :meth:`FxSpot.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def base_currency(self, ccy: str | Currency) -> FxSpotBuilder: ...
    def quote_currency(self, ccy: str | Currency) -> FxSpotBuilder: ...
    def settlement(self, settlement: date) -> FxSpotBuilder: ...
    def settlement_lag_days(self, settlement_lag_days: int) -> FxSpotBuilder: ...
    def spot_rate(self, spot_rate: float) -> FxSpotBuilder: ...
    def notional(self, notional: Money) -> FxSpotBuilder: ...
    def bdc(self, bdc: str) -> FxSpotBuilder: ...
    def base_calendar(self, calendar_id: str) -> FxSpotBuilder: ...
    def quote_calendar(self, calendar_id: str) -> FxSpotBuilder: ...
    def build(self) -> FxSpot: ...
    def __repr__(self) -> str: ...

class FxSpot:
    """FX spot instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> FxSpotBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def quote_currency(self) -> Currency: ...
    @property
    def notional(self) -> Money: ...
    @property
    def spot_rate(self) -> float | None: ...
    @property
    def settlement(self) -> date | None: ...
    @property
    def settlement_lag_days(self) -> int | None: ...
    @property
    def business_day_convention(self) -> str: ...
    @property
    def base_calendar(self) -> str | None: ...
    @property
    def quote_calendar(self) -> str | None: ...
    @property
    def pair_name(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def effective_settlement_date(self, as_of: date) -> date: ...
    def is_t1_pair(self) -> bool: ...
    def __repr__(self) -> str: ...

class FxOptionBuilder:
    """Fluent builder returned by :meth:`FxOption.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def base_currency(self, ccy: str | Currency) -> FxOptionBuilder: ...
    def quote_currency(self, ccy: str | Currency) -> FxOptionBuilder: ...
    def strike(self, strike: float) -> FxOptionBuilder: ...
    def expiry(self, expiry: date) -> FxOptionBuilder: ...
    def notional(self, notional: Money) -> FxOptionBuilder: ...
    def domestic_discount_curve(self, curve_id: str) -> FxOptionBuilder: ...
    def foreign_discount_curve(self, curve_id: str) -> FxOptionBuilder: ...
    def vol_surface(self, surface_id: str) -> FxOptionBuilder: ...
    def option_type(self, option_type: str) -> FxOptionBuilder: ...
    def exercise_style(self, exercise_style: str) -> FxOptionBuilder: ...
    def settlement(self, settlement: str) -> FxOptionBuilder: ...
    def day_count(self, dc: DayCount) -> FxOptionBuilder: ...
    def build(self) -> FxOption: ...
    def __repr__(self) -> str: ...

class FxOption:
    """FX option (Garman-Kohlhagen) instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> FxOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def quote_currency(self) -> Currency: ...
    @property
    def notional(self) -> Money: ...
    @property
    def strike(self) -> float: ...
    @property
    def expiry(self) -> date: ...
    @property
    def option_type(self) -> str: ...
    @property
    def exercise_style(self) -> str: ...
    @property
    def settlement(self) -> str: ...
    @property
    def domestic_discount_curve(self) -> str: ...
    @property
    def foreign_discount_curve(self) -> str: ...
    @property
    def vol_surface(self) -> str: ...
    @property
    def day_count(self) -> DayCount: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def implied_vol(
        self,
        market: MarketContext,
        as_of: date,
        target_price: float,
        initial_guess: float | None = None,
    ) -> float: ...
    @staticmethod
    def atm_forward_strike(spot: float, df_domestic: float, df_foreign: float) -> float: ...
    @staticmethod
    def atm_dns_strike(forward: float, vol: float, time_to_expiry: float, use_forward_delta: bool) -> float: ...
    def __repr__(self) -> str: ...

class FxSwapBuilder:
    """Fluent builder returned by :meth:`FxSwap.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def base_currency(self, ccy: str | Currency) -> FxSwapBuilder: ...
    def quote_currency(self, ccy: str | Currency) -> FxSwapBuilder: ...
    def notional(self, notional: Money) -> FxSwapBuilder: ...
    def near_date(self, near_date: date) -> FxSwapBuilder: ...
    def far_date(self, far_date: date) -> FxSwapBuilder: ...
    def domestic_discount_curve(self, curve_id: str) -> FxSwapBuilder: ...
    def foreign_discount_curve(self, curve_id: str) -> FxSwapBuilder: ...
    def near_rate(self, near_rate: float | None = None) -> FxSwapBuilder: ...
    def far_rate(self, far_rate: float | None = None) -> FxSwapBuilder: ...
    def base_calendar(self, calendar_id: str) -> FxSwapBuilder: ...
    def quote_calendar(self, calendar_id: str) -> FxSwapBuilder: ...
    def build(self) -> FxSwap: ...
    def __repr__(self) -> str: ...

class FxSwap:
    """FX swap instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> FxSwapBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def quote_currency(self) -> Currency: ...
    @property
    def base_notional(self) -> Money: ...
    @property
    def near_date(self) -> date: ...
    @property
    def far_date(self) -> date: ...
    @property
    def near_rate(self) -> float | None: ...
    @property
    def far_rate(self) -> float | None: ...
    @property
    def domestic_discount_curve(self) -> str: ...
    @property
    def foreign_discount_curve(self) -> str: ...
    @property
    def base_calendar(self) -> str | None: ...
    @property
    def quote_calendar(self) -> str | None: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def __repr__(self) -> str: ...
