"""FX barrier option instrument."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.dates.daycount import DayCount
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class FxBarrierOptionBuilder:
    """Fluent builder returned by :meth:`FxBarrierOption.builder`."""

    def base_currency(self, ccy: str | Currency) -> FxBarrierOptionBuilder: ...
    def quote_currency(self, ccy: str | Currency) -> FxBarrierOptionBuilder: ...
    def strike(self, strike: float) -> FxBarrierOptionBuilder: ...
    def barrier(self, barrier: float) -> FxBarrierOptionBuilder: ...
    def rebate(self, rebate: float) -> FxBarrierOptionBuilder: ...
    def option_type(self, option_type: str) -> FxBarrierOptionBuilder: ...
    def barrier_type(self, barrier_type: str) -> FxBarrierOptionBuilder: ...
    def expiry(self, date: date) -> FxBarrierOptionBuilder: ...
    def notional(self, notional: Money) -> FxBarrierOptionBuilder: ...
    def domestic_discount_curve(self, curve_id: str) -> FxBarrierOptionBuilder: ...
    def foreign_discount_curve(self, curve_id: str) -> FxBarrierOptionBuilder: ...
    def vol_surface(self, surface_id: str) -> FxBarrierOptionBuilder: ...
    def fx_spot_id(self, spot_id: str) -> FxBarrierOptionBuilder: ...
    def use_gobet_miri(self, flag: bool) -> FxBarrierOptionBuilder: ...
    def day_count(self, dc: DayCount) -> FxBarrierOptionBuilder: ...
    def build(self) -> FxBarrierOption: ...
    def __repr__(self) -> str: ...

class FxBarrierOption:
    """FX barrier option instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> FxBarrierOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def quote_currency(self) -> Currency: ...
    @property
    def strike(self) -> float: ...
    @property
    def barrier(self) -> float: ...
    @property
    def rebate(self) -> float | None: ...
    @property
    def option_type(self) -> str: ...
    @property
    def barrier_type(self) -> str: ...
    @property
    def expiry(self) -> date: ...
    @property
    def notional(self) -> Money: ...
    @property
    def domestic_discount_curve(self) -> str: ...
    @property
    def foreign_discount_curve(self) -> str: ...
    @property
    def vol_surface(self) -> str: ...
    @property
    def fx_spot_id(self) -> str | None: ...
    @property
    def use_gobet_miri(self) -> bool: ...
    @property
    def day_count(self) -> DayCount: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def __repr__(self) -> str: ...
