"""FX digital (binary) option instrument."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.dates.daycount import DayCount
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class DigitalPayoutType:
    """Digital option payout type."""

    CASH_OR_NOTHING: DigitalPayoutType
    ASSET_OR_NOTHING: DigitalPayoutType
    @classmethod
    def from_name(cls, name: str) -> DigitalPayoutType: ...
    @property
    def name(self) -> str: ...

class FxDigitalOptionBuilder:
    """Fluent builder returned by :meth:`FxDigitalOption.builder`."""

    def base_currency(self, ccy: str | Currency) -> FxDigitalOptionBuilder: ...
    def quote_currency(self, ccy: str | Currency) -> FxDigitalOptionBuilder: ...
    def strike(self, strike: float) -> FxDigitalOptionBuilder: ...
    def option_type(self, option_type: str) -> FxDigitalOptionBuilder: ...
    def payout_type(self, payout_type: str | DigitalPayoutType) -> FxDigitalOptionBuilder: ...
    def payout_amount(self, amount: Money) -> FxDigitalOptionBuilder: ...
    def expiry(self, date: date) -> FxDigitalOptionBuilder: ...
    def notional(self, notional: Money) -> FxDigitalOptionBuilder: ...
    def domestic_discount_curve(self, curve_id: str) -> FxDigitalOptionBuilder: ...
    def foreign_discount_curve(self, curve_id: str) -> FxDigitalOptionBuilder: ...
    def vol_surface(self, surface_id: str) -> FxDigitalOptionBuilder: ...
    def day_count(self, dc: DayCount) -> FxDigitalOptionBuilder: ...
    def build(self) -> FxDigitalOption: ...
    def __repr__(self) -> str: ...

class FxDigitalOption:
    """FX digital (binary) option instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> FxDigitalOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def quote_currency(self) -> Currency: ...
    @property
    def strike(self) -> float: ...
    @property
    def option_type(self) -> str: ...
    @property
    def payout_type(self) -> DigitalPayoutType: ...
    @property
    def payout_amount(self) -> Money: ...
    @property
    def expiry(self) -> date: ...
    @property
    def notional(self) -> Money: ...
    @property
    def domestic_discount_curve(self) -> str: ...
    @property
    def foreign_discount_curve(self) -> str: ...
    @property
    def vol_surface(self) -> str: ...
    @property
    def day_count(self) -> DayCount: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def __repr__(self) -> str: ...
