"""FX forward (outright forward) instrument."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class FxForwardBuilder:
    """Fluent builder returned by :meth:`FxForward.builder`."""

    def base_currency(self, ccy: str | Currency) -> FxForwardBuilder: ...
    def quote_currency(self, ccy: str | Currency) -> FxForwardBuilder: ...
    def maturity(self, date: date) -> FxForwardBuilder: ...
    def notional(self, notional: Money) -> FxForwardBuilder: ...
    def contract_rate(self, rate: float) -> FxForwardBuilder: ...
    def domestic_discount_curve(self, curve_id: str) -> FxForwardBuilder: ...
    def foreign_discount_curve(self, curve_id: str) -> FxForwardBuilder: ...
    def spot_rate_override(self, rate: float) -> FxForwardBuilder: ...
    def base_calendar(self, calendar_id: str) -> FxForwardBuilder: ...
    def quote_calendar(self, calendar_id: str) -> FxForwardBuilder: ...
    def build(self) -> FxForward: ...
    def __repr__(self) -> str: ...

class FxForward:
    """FX forward (outright forward) instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> FxForwardBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def quote_currency(self) -> Currency: ...
    @property
    def maturity(self) -> date: ...
    @property
    def notional(self) -> Money: ...
    @property
    def contract_rate(self) -> float | None: ...
    @property
    def spot_rate_override(self) -> float | None: ...
    @property
    def domestic_discount_curve(self) -> str: ...
    @property
    def foreign_discount_curve(self) -> str: ...
    @property
    def base_calendar(self) -> str | None: ...
    @property
    def quote_calendar(self) -> str | None: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def market_forward_rate(self, market: MarketContext, as_of: date) -> float: ...
    def __repr__(self) -> str: ...
