"""FX touch option (American binary option) instrument."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.dates.daycount import DayCount
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class FxTouchOptionBuilder:
    """Fluent builder returned by :meth:`FxTouchOption.builder`."""

    def base_currency(self, ccy: str | Currency) -> FxTouchOptionBuilder: ...
    def quote_currency(self, ccy: str | Currency) -> FxTouchOptionBuilder: ...
    def barrier_level(self, level: float) -> FxTouchOptionBuilder: ...
    def touch_type(self, touch_type: str) -> FxTouchOptionBuilder: ...
    def barrier_direction(self, direction: str) -> FxTouchOptionBuilder: ...
    def payout_amount(self, amount: Money) -> FxTouchOptionBuilder: ...
    def payout_timing(self, timing: str) -> FxTouchOptionBuilder: ...
    def expiry(self, date: date) -> FxTouchOptionBuilder: ...
    def domestic_discount_curve(self, curve_id: str) -> FxTouchOptionBuilder: ...
    def foreign_discount_curve(self, curve_id: str) -> FxTouchOptionBuilder: ...
    def vol_surface(self, surface_id: str) -> FxTouchOptionBuilder: ...
    def day_count(self, dc: DayCount) -> FxTouchOptionBuilder: ...
    def build(self) -> FxTouchOption: ...
    def __repr__(self) -> str: ...

class FxTouchOption:
    """FX touch option (American binary option) instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> FxTouchOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def quote_currency(self) -> Currency: ...
    @property
    def barrier_level(self) -> float: ...
    @property
    def touch_type(self) -> str: ...
    @property
    def barrier_direction(self) -> str: ...
    @property
    def payout_amount(self) -> Money: ...
    @property
    def payout_timing(self) -> str: ...
    @property
    def expiry(self) -> date: ...
    @property
    def domestic_discount_curve(self) -> str: ...
    @property
    def foreign_discount_curve(self) -> str: ...
    @property
    def vol_surface(self) -> str: ...
    @property
    def day_count(self) -> DayCount: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def __repr__(self) -> str: ...
