"""FX variance swap instrument."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.dates.daycount import DayCount
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class FxVarianceDirection:
    """Variance direction (pay or receive variance)."""

    PAY: FxVarianceDirection
    RECEIVE: FxVarianceDirection

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FxRealizedVarianceMethod:
    """Realized variance calculation method."""

    CLOSE_TO_CLOSE: FxRealizedVarianceMethod
    PARKINSON: FxRealizedVarianceMethod
    GARMAN_KLASS: FxRealizedVarianceMethod
    ROGERS_SATCHELL: FxRealizedVarianceMethod
    YANG_ZHANG: FxRealizedVarianceMethod

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FxVarianceSwapBuilder:
    """Fluent builder returned by :meth:`FxVarianceSwap.builder`."""

    def base_currency(self, ccy: str | Currency) -> FxVarianceSwapBuilder: ...
    def quote_currency(self, ccy: str | Currency) -> FxVarianceSwapBuilder: ...
    def spot_id(self, id: str) -> FxVarianceSwapBuilder: ...
    def notional(self, notional: Money) -> FxVarianceSwapBuilder: ...
    def strike_variance(self, variance: float) -> FxVarianceSwapBuilder: ...
    def start_date(self, date: date) -> FxVarianceSwapBuilder: ...
    def maturity(self, date: date) -> FxVarianceSwapBuilder: ...
    def observation_freq(self, freq: str) -> FxVarianceSwapBuilder: ...
    def realized_method(self, method: str | FxRealizedVarianceMethod) -> FxVarianceSwapBuilder: ...
    def side(self, direction: str | FxVarianceDirection) -> FxVarianceSwapBuilder: ...
    def domestic_discount_curve(self, curve_id: str) -> FxVarianceSwapBuilder: ...
    def foreign_discount_curve(self, curve_id: str) -> FxVarianceSwapBuilder: ...
    def vol_surface(self, surface_id: str) -> FxVarianceSwapBuilder: ...
    def day_count(self, dc: DayCount) -> FxVarianceSwapBuilder: ...
    def build(self) -> FxVarianceSwap: ...
    def __repr__(self) -> str: ...

class FxVarianceSwap:
    """FX variance swap instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> FxVarianceSwapBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def quote_currency(self) -> Currency: ...
    @property
    def notional(self) -> Money: ...
    @property
    def strike_variance(self) -> float: ...
    @property
    def start_date(self) -> date: ...
    @property
    def maturity(self) -> date: ...
    @property
    def side(self) -> FxVarianceDirection: ...
    @property
    def observation_freq(self) -> str: ...
    @property
    def realized_var_method(self) -> FxRealizedVarianceMethod: ...
    @property
    def spot_id(self) -> str | None: ...
    @property
    def domestic_discount_curve(self) -> str: ...
    @property
    def foreign_discount_curve(self) -> str: ...
    @property
    def vol_surface(self) -> str: ...
    @property
    def day_count(self) -> DayCount: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def payoff(self, realized_variance: float) -> Money: ...
    def observation_dates(self) -> list[date]: ...
    def annualization_factor(self) -> float: ...
    def partial_realized_variance(self, market: MarketContext, as_of: date) -> float: ...
    def remaining_forward_variance(self, market: MarketContext, as_of: date) -> float: ...
    def __repr__(self) -> str: ...
