"""Non-Deliverable Forward (NDF) instrument."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class NdfBuilder:
    """Fluent builder returned by :meth:`Ndf.builder`."""

    def base_currency(self, ccy: str | Currency) -> NdfBuilder: ...
    def settlement_currency(self, ccy: str | Currency) -> NdfBuilder: ...
    def fixing_date(self, date: date) -> NdfBuilder: ...
    def maturity_date(self, date: date) -> NdfBuilder: ...
    def notional(self, notional: Money) -> NdfBuilder: ...
    def contract_rate(self, rate: float) -> NdfBuilder: ...
    def domestic_discount_curve(self, curve_id: str) -> NdfBuilder: ...
    def foreign_discount_curve(self, curve_id: str) -> NdfBuilder: ...
    def fixing_rate(self, rate: float) -> NdfBuilder: ...
    def fixing_source_enum(self, source: str) -> NdfBuilder: ...
    def quote_convention(self, convention: str) -> NdfBuilder: ...
    def spot_rate_override(self, rate: float) -> NdfBuilder: ...
    def base_calendar(self, calendar_id: str) -> NdfBuilder: ...
    def quote_calendar(self, calendar_id: str) -> NdfBuilder: ...
    def build(self) -> Ndf: ...
    def __repr__(self) -> str: ...

class Ndf:
    """Non-Deliverable Forward (NDF) instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> NdfBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def settlement_currency(self) -> Currency: ...
    @property
    def fixing_date(self) -> date: ...
    @property
    def maturity_date(self) -> date: ...
    @property
    def notional(self) -> Money: ...
    @property
    def contract_rate(self) -> float: ...
    @property
    def fixing_rate(self) -> float | None: ...
    @property
    def fixing_source_enum(self) -> str | None: ...
    @property
    def domestic_discount_curve(self) -> str: ...
    @property
    def foreign_discount_curve(self) -> str | None: ...
    @property
    def quote_convention(self) -> str: ...
    @property
    def spot_rate_override(self) -> float | None: ...
    @property
    def base_calendar(self) -> str | None: ...
    @property
    def quote_calendar(self) -> str | None: ...
    def is_fixed(self) -> bool: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def validate_fixing_source(self) -> None: ...
    def __repr__(self) -> str: ...
