"""Quanto option instrument."""

from __future__ import annotations

from datetime import date

from ....core.currency import Currency
from ....core.dates.daycount import DayCount
from ....core.market_data.context import MarketContext
from ....core.money import Money
from ...common import InstrumentType

class QuantoOptionBuilder:
    """Fluent builder returned by :meth:`QuantoOption.builder`."""

    def base_currency(self, ccy: str | Currency) -> QuantoOptionBuilder: ...
    def quote_currency(self, ccy: str | Currency) -> QuantoOptionBuilder: ...
    def ticker(self, ticker: str) -> QuantoOptionBuilder: ...
    def equity_strike(self, strike: float) -> QuantoOptionBuilder: ...
    def option_type(self, option_type: str) -> QuantoOptionBuilder: ...
    def expiry(self, date: date) -> QuantoOptionBuilder: ...
    def notional(self, notional: Money) -> QuantoOptionBuilder: ...
    def correlation(self, correlation: float) -> QuantoOptionBuilder: ...
    def domestic_discount_curve(self, curve_id: str) -> QuantoOptionBuilder: ...
    def foreign_discount_curve(self, curve_id: str) -> QuantoOptionBuilder: ...
    def spot_id(self, id: str) -> QuantoOptionBuilder: ...
    def vol_surface(self, surface_id: str) -> QuantoOptionBuilder: ...
    def div_yield_id(self, curve_id: str) -> QuantoOptionBuilder: ...
    def fx_rate_id(self, rate_id: str) -> QuantoOptionBuilder: ...
    def fx_vol_id(self, vol_id: str) -> QuantoOptionBuilder: ...
    def day_count(self, dc: DayCount) -> QuantoOptionBuilder: ...
    def build(self) -> QuantoOption: ...
    def __repr__(self) -> str: ...

class QuantoOption:
    """Quanto option instrument."""

    @classmethod
    def builder(cls, instrument_id: str) -> QuantoOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def base_currency(self) -> Currency: ...
    @property
    def quote_currency(self) -> Currency: ...
    @property
    def ticker(self) -> str: ...
    @property
    def equity_strike(self) -> Money: ...
    @property
    def option_type(self) -> str: ...
    @property
    def expiry(self) -> date: ...
    @property
    def notional(self) -> Money: ...
    @property
    def correlation(self) -> float: ...
    @property
    def domestic_discount_curve(self) -> str: ...
    @property
    def foreign_discount_curve(self) -> str: ...
    @property
    def spot_id(self) -> str: ...
    @property
    def vol_surface(self) -> str: ...
    @property
    def div_yield_id(self) -> str | None: ...
    @property
    def fx_rate_id(self) -> str | None: ...
    @property
    def fx_vol_id(self) -> str | None: ...
    @property
    def day_count(self) -> DayCount: ...
    def value(self, market: MarketContext, as_of: date) -> Money: ...
    def __repr__(self) -> str: ...
