"""Fixed-income bond instrument with convenience constructors."""

from __future__ import annotations
import datetime
from typing import List, Any, TypedDict
from .....core.money import Money
from .....core.currency import Currency
from .....core.dates.schedule import Frequency, StubKind
from .....core.dates.daycount import DayCount
from .....core.dates.calendar import BusinessDayConvention
from .....core.market_data.context import MarketContext
from ....cashflow.builder import AmortizationSpec, CashFlowSchedule
from ....common import InstrumentType
from .mc_config import MertonMcConfig, MertonMcResult
from .merton import MertonAssetDynamics, MertonBarrierType, MertonModel
from .endogenous_hazard import EndogenousHazardSpec
from .dynamic_recovery import DynamicRecoverySpec
from .toggle_exercise import ToggleExerciseModel

class CallScheduleItem(TypedDict):
    date: datetime.date
    price_pct: float

class PutScheduleItem(TypedDict):
    date: datetime.date
    price_pct: float

class BondSettlementConvention:
    """Bond settlement and ex-coupon conventions."""
    def __init__(
        self,
        settlement_days: int,
        ex_coupon_days: int = 0,
        ex_coupon_calendar_id: str | None = None,
    ) -> None: ...
    @property
    def settlement_days(self) -> int: ...
    @property
    def ex_coupon_days(self) -> int: ...
    @property
    def ex_coupon_calendar_id(self) -> str | None: ...
    def __repr__(self) -> str: ...

class AccrualMethod:
    """Accrual method for bond interest calculation."""

    LINEAR: AccrualMethod
    COMPOUNDED: AccrualMethod
    def __repr__(self) -> str: ...

class MakeWholeSpec:
    """Make-whole call specification."""
    def __init__(self, reference_curve_id: str, spread_bps: float) -> None: ...
    @property
    def reference_curve_id(self) -> str: ...
    @property
    def spread_bps(self) -> float: ...
    def __repr__(self) -> str: ...

class CallPut:
    """Call or put option on a bond."""
    def __init__(
        self,
        date: datetime.date,
        price_pct_of_par: float,
        end_date: datetime.date | None = None,
        make_whole: MakeWholeSpec | None = None,
    ) -> None: ...
    @property
    def date(self) -> datetime.date: ...
    @property
    def price_pct_of_par(self) -> float: ...
    @property
    def end_date(self) -> datetime.date | None: ...
    def __repr__(self) -> str: ...

class CallPutSchedule:
    """Schedule of call and put options for a bond."""
    def __init__(
        self,
        calls: list[CallPut] | None = None,
        puts: list[CallPut] | None = None,
    ) -> None: ...
    def has_options(self) -> bool: ...
    @property
    def call_count(self) -> int: ...
    @property
    def put_count(self) -> int: ...
    def __repr__(self) -> str: ...

class CashflowSpec:
    """Cashflow specification (fixed, floating, or amortizing)."""
    @property
    def spec_type(self) -> str: ...
    def __repr__(self) -> str: ...

class BondBuilder:
    """Fluent builder returned by :meth:`Bond.builder` when only an ID is provided."""

    def __init__(self, instrument_id: str) -> None: ...
    def notional(self, amount: float) -> BondBuilder: ...
    def currency(self, currency: str | Currency) -> BondBuilder: ...
    def money(self, money: Money) -> BondBuilder: ...
    def cashflows(self, schedule: CashFlowSchedule) -> BondBuilder: ...
    def issue(self, issue: datetime.date) -> BondBuilder: ...
    def maturity(self, maturity: datetime.date) -> BondBuilder: ...
    def disc_id(self, curve_id: str) -> BondBuilder: ...
    def credit_curve(self, curve_id: str | None = ...) -> BondBuilder: ...
    def coupon_rate(self, rate: float) -> BondBuilder: ...
    def coupon_type(self, coupon_type: str) -> BondBuilder:
        """Set coupon type: 'cash' (default) or 'pik'."""
        ...
    def merton_mc(self, config: "MertonMcConfig") -> BondBuilder:
        """Attach a Merton MC configuration for structural credit pricing via the pricer registry."""
        ...
    def frequency(self, frequency: Frequency | str | int) -> BondBuilder: ...
    def day_count(self, day_count: DayCount | str) -> BondBuilder: ...
    def bdc(self, bdc: BusinessDayConvention | str) -> BondBuilder: ...
    def stub(self, stub: StubKind | str) -> BondBuilder: ...
    def calendar(self, calendar_id: str | None = ...) -> BondBuilder: ...
    def amortization(self, amortization: AmortizationSpec | None = ...) -> BondBuilder: ...
    def settlement_convention(self, convention: BondSettlementConvention) -> BondBuilder: ...
    def call_schedule(self, schedule: List[CallScheduleItem]) -> BondBuilder: ...
    def put_schedule(self, schedule: List[PutScheduleItem]) -> BondBuilder: ...
    def quoted_clean_price(self, price: float | None = ...) -> BondBuilder: ...
    def forward_curve(self, curve_id: str | None = ...) -> BondBuilder: ...
    def float_margin_bp(self, margin_bp: float) -> BondBuilder: ...
    def float_gearing(self, gearing: float) -> BondBuilder: ...
    def float_reset_lag_days(self, lag_days: int) -> BondBuilder: ...
    def build(self) -> "Bond": ...

class Bond:
    """Fixed-income bond instrument for pricing and risk analysis."""

    @classmethod
    def builder(cls, instrument_id: str) -> BondBuilder:
        """Start a fluent builder (builder-only API)."""
        ...

    @property
    def id(self) -> str: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def coupon(self) -> float: ...
    @property
    def issue(self) -> datetime.date: ...
    @property
    def maturity(self) -> datetime.date: ...
    @property
    def discount_curve(self) -> str: ...
    @property
    def hazard_curve(self) -> str | None: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def settlement_days(self) -> int | None: ...
    @property
    def ex_coupon_days(self) -> int | None: ...
    @property
    def ex_coupon_calendar_id(self) -> str | None: ...
    @property
    def accrual_method(self) -> str: ...
    @property
    def has_call_put(self) -> bool: ...
    def validate(self) -> None: ...
    def get_full_schedule(self, market: MarketContext) -> CashFlowSchedule: ...
    def pricing_cashflows(
        self,
        market: MarketContext,
        *,
        as_of: datetime.date | None = None,
    ) -> Any: ...
    @property
    def cashflow_spec(self) -> CashflowSpec: ...
    def price_merton_mc(
        self,
        config: MertonMcConfig,
        discount_rate: float,
        as_of: datetime.date,
    ) -> MertonMcResult: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

__all__ = [
    "Bond",
    "BondBuilder",
    "BondSettlementConvention",
    "AccrualMethod",
    "MakeWholeSpec",
    "CallPut",
    "CallPutSchedule",
    "CashflowSpec",
    "MertonMcConfig",
    "MertonMcResult",
    "MertonModel",
    "MertonAssetDynamics",
    "MertonBarrierType",
    "EndogenousHazardSpec",
    "DynamicRecoverySpec",
    "ToggleExerciseModel",
]
