"""Agency MBS instruments (passthroughs, TBAs, dollar rolls, CMOs)."""

from __future__ import annotations

from datetime import date
from typing import List, Sequence, Tuple

from ...core.currency import Currency
from ...core.dates.daycount import DayCount
from ...core.money import Money
from ..common import InstrumentType

class AgencyProgram:
    """Agency program (FNMA, FHLMC, GNMA)."""

    Fnma: "AgencyProgram"
    Fhlmc: "AgencyProgram"
    Gnma: "AgencyProgram"

class PoolType:
    """Pool type classification."""

    Generic: "PoolType"
    Specified: "PoolType"

class TbaTerm:
    """TBA original loan term."""

    ThirtyYear: "TbaTerm"
    FifteenYear: "TbaTerm"

class CmoTrancheType:
    """CMO tranche type classification."""

class PacCollar:
    """PAC collar specification."""

class CmoTranche:
    """CMO tranche specification."""

    @classmethod
    def sequential(
        cls,
        tranche_id: str,
        current_face: float,
        currency: str | Currency,
        coupon_rate: float,
        priority: int,
    ) -> "CmoTranche": ...

class CmoWaterfall:
    """Waterfall structure with tranches."""

    def __init__(self, tranches: Sequence[CmoTranche]) -> None: ...

class AgencyMbsPassthroughBuilder:
    def __init__(self, instrument_id: str) -> None: ...
    def pool_id(self, pool_id: str) -> "AgencyMbsPassthroughBuilder": ...
    def agency(self, agency: AgencyProgram) -> "AgencyMbsPassthroughBuilder": ...
    def original_face(self, original_face: float) -> "AgencyMbsPassthroughBuilder": ...
    def current_face(self, current_face: float) -> "AgencyMbsPassthroughBuilder": ...
    def currency(self, currency: str | Currency) -> "AgencyMbsPassthroughBuilder": ...
    def wac(self, wac: float) -> "AgencyMbsPassthroughBuilder": ...
    def pass_through_rate(self, pass_through_rate: float) -> "AgencyMbsPassthroughBuilder": ...
    def wam(self, wam: int) -> "AgencyMbsPassthroughBuilder": ...
    def issue_date(self, issue_date: date) -> "AgencyMbsPassthroughBuilder": ...
    def maturity_date(self, maturity_date: date) -> "AgencyMbsPassthroughBuilder": ...
    def discount_curve_id(self, discount_curve_id: str) -> "AgencyMbsPassthroughBuilder": ...
    def current_factor(self, current_factor: float | None = ...) -> "AgencyMbsPassthroughBuilder": ...
    def servicing_fee_rate(self, servicing_fee_rate: float) -> "AgencyMbsPassthroughBuilder": ...
    def guarantee_fee_rate(self, guarantee_fee_rate: float) -> "AgencyMbsPassthroughBuilder": ...
    def pool_type(self, pool_type: PoolType) -> "AgencyMbsPassthroughBuilder": ...
    def psa_speed(self, psa_speed: float) -> "AgencyMbsPassthroughBuilder": ...
    def day_count(self, day_count: DayCount) -> "AgencyMbsPassthroughBuilder": ...
    def build(self) -> "AgencyMbsPassthrough": ...

class AgencyMbsPassthrough:
    @classmethod
    def builder(cls, instrument_id: str) -> AgencyMbsPassthroughBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...

class AgencyTbaBuilder:
    def __init__(self, instrument_id: str) -> None: ...
    def agency(self, agency: AgencyProgram) -> "AgencyTbaBuilder": ...
    def coupon(self, coupon: float) -> "AgencyTbaBuilder": ...
    def term(self, term: TbaTerm) -> "AgencyTbaBuilder": ...
    def settlement_year(self, settlement_year: int) -> "AgencyTbaBuilder": ...
    def settlement_month(self, settlement_month: int) -> "AgencyTbaBuilder": ...
    def notional(self, notional: float) -> "AgencyTbaBuilder": ...
    def currency(self, currency: str | Currency) -> "AgencyTbaBuilder": ...
    def trade_price(self, trade_price: float) -> "AgencyTbaBuilder": ...
    def discount_curve_id(self, discount_curve_id: str) -> "AgencyTbaBuilder": ...
    def trade_date(self, trade_date: date | None = ...) -> "AgencyTbaBuilder": ...
    def build(self) -> "AgencyTba": ...

class AgencyTba:
    @classmethod
    def builder(cls, instrument_id: str) -> AgencyTbaBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...

class DollarRollBuilder:
    def __init__(self, instrument_id: str) -> None: ...
    def agency(self, agency: AgencyProgram) -> "DollarRollBuilder": ...
    def coupon(self, coupon: float) -> "DollarRollBuilder": ...
    def term(self, term: TbaTerm) -> "DollarRollBuilder": ...
    def notional(self, notional: float) -> "DollarRollBuilder": ...
    def currency(self, currency: str | Currency) -> "DollarRollBuilder": ...
    def front_settlement_year(self, front_settlement_year: int) -> "DollarRollBuilder": ...
    def front_settlement_month(self, front_settlement_month: int) -> "DollarRollBuilder": ...
    def back_settlement_year(self, back_settlement_year: int) -> "DollarRollBuilder": ...
    def back_settlement_month(self, back_settlement_month: int) -> "DollarRollBuilder": ...
    def front_price(self, front_price: float) -> "DollarRollBuilder": ...
    def back_price(self, back_price: float) -> "DollarRollBuilder": ...
    def discount_curve_id(self, discount_curve_id: str) -> "DollarRollBuilder": ...
    def trade_date(self, trade_date: date | None = ...) -> "DollarRollBuilder": ...
    def build(self) -> "DollarRoll": ...

class DollarRoll:
    @classmethod
    def builder(cls, instrument_id: str) -> DollarRollBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...

class AgencyCmoBuilder:
    def __init__(self, instrument_id: str) -> None: ...
    def deal_name(self, deal_name: str) -> "AgencyCmoBuilder": ...
    def agency(self, agency: AgencyProgram) -> "AgencyCmoBuilder": ...
    def issue_date(self, issue_date: date) -> "AgencyCmoBuilder": ...
    def waterfall(self, waterfall: CmoWaterfall) -> "AgencyCmoBuilder": ...
    def reference_tranche_id(self, reference_tranche_id: str) -> "AgencyCmoBuilder": ...
    def discount_curve_id(self, discount_curve_id: str) -> "AgencyCmoBuilder": ...
    def collateral_wac(self, collateral_wac: float | None = ...) -> "AgencyCmoBuilder": ...
    def collateral_wam(self, collateral_wam: int | None = ...) -> "AgencyCmoBuilder": ...
    def build(self) -> "AgencyCmo": ...

class AgencyCmo:
    @classmethod
    def builder(cls, instrument_id: str) -> AgencyCmoBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
