"""Commodity option instrument (builder-only API)."""

from typing import Optional, Union
from datetime import date

from ...core.currency import Currency
from ...core.dates.daycount import DayCount
from ..common import InstrumentType

class CommodityOptionBuilder:
    """Fluent builder returned by :meth:`CommodityOption.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def commodity_type(self, commodity_type: str) -> "CommodityOptionBuilder": ...
    def ticker(self, ticker: str) -> "CommodityOptionBuilder": ...
    def strike(self, strike: float) -> "CommodityOptionBuilder": ...
    def option_type(self, option_type: str) -> "CommodityOptionBuilder": ...
    def exercise_style(self, exercise_style: str) -> "CommodityOptionBuilder": ...
    def expiry(self, expiry: date) -> "CommodityOptionBuilder": ...
    def quantity(self, quantity: float) -> "CommodityOptionBuilder": ...
    def unit(self, unit: str) -> "CommodityOptionBuilder": ...
    def currency(self, currency: Union[str, Currency]) -> "CommodityOptionBuilder": ...
    def forward_curve_id(self, curve_id: str) -> "CommodityOptionBuilder": ...
    def discount_curve_id(self, curve_id: str) -> "CommodityOptionBuilder": ...
    def vol_surface_id(self, curve_id: str) -> "CommodityOptionBuilder": ...
    def multiplier(self, multiplier: float) -> "CommodityOptionBuilder": ...
    def settlement_type(self, settlement_type: str) -> "CommodityOptionBuilder": ...
    def day_count(self, day_count: Union[DayCount, str]) -> "CommodityOptionBuilder": ...
    def spot_id(self, spot_id: Optional[str] = ...) -> "CommodityOptionBuilder": ...
    def quoted_forward(self, quoted_forward: Optional[float] = ...) -> "CommodityOptionBuilder": ...
    def implied_volatility(self, implied_volatility: Optional[float] = ...) -> "CommodityOptionBuilder": ...
    def tree_steps(self, tree_steps: Optional[int] = ...) -> "CommodityOptionBuilder": ...
    def build(self) -> "CommodityOption": ...

class CommodityOption:
    """Commodity option (call or put on commodity forward/spot)."""

    @classmethod
    def builder(cls, instrument_id: str) -> CommodityOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def commodity_type(self) -> str: ...
    @property
    def ticker(self) -> str: ...
    @property
    def strike(self) -> float: ...
    @property
    def option_type(self) -> str: ...
    @property
    def exercise_style(self) -> str: ...
    @property
    def expiry(self) -> date: ...
    @property
    def quantity(self) -> float: ...
    @property
    def unit(self) -> str: ...
    @property
    def multiplier(self) -> float: ...
    @property
    def settlement_type(self) -> str: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def forward_curve_id(self) -> str: ...
    @property
    def discount_curve_id(self) -> str: ...
    @property
    def vol_surface_id(self) -> str: ...
    @property
    def spot_id(self) -> Optional[str]: ...
    @property
    def quoted_forward(self) -> Optional[float]: ...
    @property
    def day_count(self) -> DayCount: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
