"""Commodity swap instrument (builder-only API)."""

from __future__ import annotations
from datetime import date

from ...core.currency import Currency
from ..common import InstrumentType

class CommoditySwapBuilder:
    """Fluent builder returned by :meth:`CommoditySwap.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def commodity_type(self, commodity_type: str) -> "CommoditySwapBuilder": ...
    def ticker(self, ticker: str) -> "CommoditySwapBuilder": ...
    def unit(self, unit: str) -> "CommoditySwapBuilder": ...
    def currency(self, currency: str | Currency) -> "CommoditySwapBuilder": ...
    def notional_quantity(self, notional_quantity: float) -> "CommoditySwapBuilder": ...
    def fixed_price(self, fixed_price: float) -> "CommoditySwapBuilder": ...
    def floating_index_id(self, curve_id: str) -> "CommoditySwapBuilder": ...
    def pay_fixed(self, pay_fixed: bool) -> "CommoditySwapBuilder": ...
    def start_date(self, start_date: date) -> "CommoditySwapBuilder": ...
    def end_date(self, end_date: date) -> "CommoditySwapBuilder": ...
    def payment_frequency(self, payment_frequency: str) -> "CommoditySwapBuilder": ...
    def discount_curve_id(self, curve_id: str) -> "CommoditySwapBuilder": ...
    def calendar_id(self, calendar_id: str | None = ...) -> "CommoditySwapBuilder": ...
    def bdc(self, bdc: str | None = ...) -> "CommoditySwapBuilder": ...
    def index_lag_days(self, index_lag_days: int | None = ...) -> "CommoditySwapBuilder": ...
    def build(self) -> "CommoditySwap": ...

class CommoditySwap:
    """Commodity swap (fixed-for-floating commodity price exchange)."""

    @classmethod
    def builder(cls, instrument_id: str) -> CommoditySwapBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def commodity_type(self) -> str: ...
    @property
    def ticker(self) -> str: ...
    @property
    def unit(self) -> str: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def notional_quantity(self) -> float: ...
    @property
    def fixed_price(self) -> float: ...
    @property
    def pay_fixed(self) -> bool: ...
    @property
    def start_date(self) -> date: ...
    @property
    def end_date(self) -> date: ...
    @property
    def floating_index_id(self) -> str: ...
    @property
    def discount_curve_id(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
