"""Term loan instrument."""

from typing import Optional, Dict, Any
from datetime import date
from ...core.money import Money
from ...core.currency import Currency
from ..common import InstrumentType

class TermLoan:
    """Term loan instrument with DDTL (Delayed Draw Term Loan) support."""

    @classmethod
    def from_json(cls, json_str: str) -> "TermLoan":
        """Create a term loan from a JSON string specification."""
        ...

    def to_json(self) -> str:
        """Serialize the term loan to a JSON string."""
        ...

    @property
    def instrument_id(self) -> str: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def notional_limit(self) -> Money: ...
    @property
    def issue(self) -> date: ...
    @property
    def maturity(self) -> date: ...
    @property
    def discount_curve(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
