"""Volatility index option instrument (builder-only API)."""

from __future__ import annotations
from datetime import date

from ...core.currency import Currency
from ...core.money import Money
from ..common import InstrumentType

class VolatilityIndexOptionBuilder:
    """Fluent builder returned by :meth:`VolatilityIndexOption.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def notional(self, amount: float) -> "VolatilityIndexOptionBuilder": ...
    def currency(self, currency: str | Currency) -> "VolatilityIndexOptionBuilder": ...
    def money(self, money: Money) -> "VolatilityIndexOptionBuilder": ...
    def strike(self, strike: float) -> "VolatilityIndexOptionBuilder": ...
    def expiry(self, expiry: date) -> "VolatilityIndexOptionBuilder": ...
    def disc_id(self, curve_id: str) -> "VolatilityIndexOptionBuilder": ...
    def vol_index_curve_id(self, curve_id: str) -> "VolatilityIndexOptionBuilder": ...
    def vol_of_vol_surface_id(self, curve_id: str) -> "VolatilityIndexOptionBuilder": ...
    def option_type(self, option_type: str) -> "VolatilityIndexOptionBuilder": ...
    def exercise_style(self, exercise_style: str) -> "VolatilityIndexOptionBuilder": ...
    def multiplier(self, multiplier: float) -> "VolatilityIndexOptionBuilder": ...
    def index_id(self, index_id: str) -> "VolatilityIndexOptionBuilder": ...
    def build(self) -> "VolatilityIndexOption": ...

class VolatilityIndexOption:
    """Volatility index option wrapper (e.g., VIX options)."""

    @classmethod
    def builder(cls, instrument_id: str) -> VolatilityIndexOptionBuilder: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def strike(self) -> float: ...
    @property
    def option_type(self) -> str: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
