"""Type stubs for the Performance analytics class."""

from __future__ import annotations
from typing import TypedDict
from datetime import date

import pandas
import polars

class BetaResult(TypedDict):
    beta: float
    std_err: float
    ci_lower: float
    ci_upper: float

class GreeksResult(TypedDict):
    alpha: float
    beta: float
    r_squared: float

class MultiFactorResult(TypedDict):
    alpha: float
    betas: list[float]
    r_squared: float
    adjusted_r_squared: float
    residual_vol: float

class DrawdownEpisodeDict(TypedDict):
    start: str
    valley: str
    end: str | None
    duration_days: int
    max_drawdown: float
    near_recovery_threshold: float

class LookbackResult(TypedDict):
    mtd: list[float]
    qtd: list[float]
    ytd: list[float]

class PeriodStatsResult(TypedDict):
    best: float
    worst: float
    consecutive_wins: int
    consecutive_losses: int
    win_rate: float
    avg_return: float
    avg_win: float
    avg_loss: float
    payoff_ratio: float
    profit_ratio: float
    profit_factor: float
    cpc_ratio: float
    kelly_criterion: float

class Performance:
    """Performance analytics engine.

    Construct from a Polars or pandas DataFrame. For Polars, the first column
    must be a Date column followed by price columns (one per ticker). For pandas,
    the index should contain dates and each column should be a price series.

    Parameters
    ----------
    prices : polars.DataFrame | pandas.DataFrame
        For polars: first column is Date, remaining are price series.
        For pandas: index is dates, columns are price series.
    benchmark_ticker : str, optional
        Name of the benchmark column. Defaults to the first price column.
    freq : str
        Observation frequency: ``"daily"``, ``"weekly"``, ``"monthly"``,
        ``"quarterly"``, ``"semiannual"``, ``"annual"``.
    log_returns : bool
        If True, use log returns; otherwise use simple returns.
    """

    def __init__(
        self,
        prices: polars.DataFrame | pandas.DataFrame,
        benchmark_ticker: str | None = None,
        freq: str = "daily",
        log_returns: bool = False,
    ) -> None: ...

    # ── Accessors (properties) ──

    @property
    def ticker_names(self) -> list[str]: ...
    @property
    def benchmark_idx(self) -> int: ...
    @property
    def freq(self) -> str: ...
    @property
    def log_returns(self) -> bool: ...
    @property
    def dates(self) -> polars.DataFrame: ...

    # ── Mutators ──

    def reset_date_range(self, start: date, end: date) -> None: ...
    def reset_bench_ticker(self, ticker: str) -> None: ...

    # ── Scalar metrics ──

    def cagr(self) -> polars.DataFrame: ...
    def mean_return(self, annualize: bool = True) -> polars.DataFrame: ...
    def volatility(self, annualize: bool = True) -> polars.DataFrame: ...
    def sharpe(self, risk_free_rate: float = 0.0) -> polars.DataFrame: ...
    def sortino(self) -> polars.DataFrame: ...
    def calmar(self) -> polars.DataFrame: ...
    def max_drawdown(self) -> polars.DataFrame: ...
    def value_at_risk(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def expected_shortfall(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def tail_ratio(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def ulcer_index(self) -> polars.DataFrame: ...
    def risk_of_ruin(self) -> polars.DataFrame: ...
    def skewness(self) -> polars.DataFrame: ...
    def kurtosis(self) -> polars.DataFrame: ...
    def geometric_mean(self) -> polars.DataFrame: ...
    def downside_deviation(self, mar: float = 0.0) -> polars.DataFrame: ...
    def max_drawdown_duration(self) -> polars.DataFrame: ...
    def omega_ratio(self, threshold: float = 0.0) -> polars.DataFrame: ...
    def treynor(self, risk_free_rate: float = 0.0) -> polars.DataFrame: ...
    def gain_to_pain(self) -> polars.DataFrame: ...
    def martin_ratio(self) -> polars.DataFrame: ...
    def parametric_var(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def cornish_fisher_var(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def recovery_factor(self) -> polars.DataFrame: ...
    def sterling_ratio(self, risk_free_rate: float = 0.0, n: int = 5) -> polars.DataFrame: ...
    def burke_ratio(self, risk_free_rate: float = 0.0, n: int = 5) -> polars.DataFrame: ...
    def pain_index(self) -> polars.DataFrame: ...
    def pain_ratio(self, risk_free_rate: float = 0.0) -> polars.DataFrame: ...
    def cdar(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def m_squared(self, risk_free_rate: float = 0.0) -> polars.DataFrame: ...
    def modified_sharpe(self, risk_free_rate: float = 0.0, confidence: float = 0.95) -> polars.DataFrame: ...

    # ── Benchmark-relative scalar metrics ──

    def tracking_error(self) -> polars.DataFrame: ...
    def information_ratio(self) -> polars.DataFrame: ...
    def r_squared(self) -> polars.DataFrame: ...
    def beta(self) -> dict[str, BetaResult]: ...
    def greeks(self) -> dict[str, GreeksResult]: ...
    def up_capture(self) -> polars.DataFrame: ...
    def down_capture(self) -> polars.DataFrame: ...
    def capture_ratio(self) -> polars.DataFrame: ...
    def batting_average(self) -> polars.DataFrame: ...

    # ── Series outputs (with date column) ──

    def cumulative_returns(self) -> polars.DataFrame: ...
    def drawdown_series(self) -> polars.DataFrame: ...
    def correlation(self) -> polars.DataFrame: ...
    def cumulative_returns_outperformance(self) -> polars.DataFrame: ...
    def drawdown_outperformance(self) -> polars.DataFrame: ...
    def excess_returns(self, rf: list[float], nperiods: float | None = None) -> polars.DataFrame: ...

    # ── Per-ticker rolling metrics ──

    def rolling_volatility(self, ticker: str, window: int) -> polars.DataFrame: ...
    def rolling_sortino(self, ticker: str, window: int) -> polars.DataFrame: ...
    def rolling_sharpe(self, ticker: str, window: int, risk_free_rate: float = 0.0) -> polars.DataFrame: ...
    def rolling_greeks(self, ticker: str, window: int) -> polars.DataFrame: ...
    def multi_factor_greeks(
        self,
        ticker: str,
        factor_returns: polars.DataFrame,
    ) -> MultiFactorResult: ...

    # ── Drawdown episodes ──

    def drawdown_details(self, ticker: str, n: int = 5) -> list[DrawdownEpisodeDict]: ...
    def stats_during_bench_drawdowns(self, n: int = 5) -> list[DrawdownEpisodeDict]: ...

    # ── Lookback and aggregation ──

    def lookback_returns(self, ref_date: date) -> LookbackResult: ...
    def period_stats(self, ticker: str, agg_freq: str = "monthly") -> PeriodStatsResult: ...
    def __repr__(self) -> str: ...
