"""CDS index instrument."""

from __future__ import annotations
from datetime import date
from ....core.money import Money
from ...common import InstrumentType
from .cds import CDSConvention, CDSPayReceive
from ....core.market_data.context import MarketContext

class CDSIndexConstituent:
    """Constituent in a CDS index."""

    @property
    def credit_curve(self) -> str: ...
    @property
    def recovery_rate(self) -> float: ...
    @property
    def weight(self) -> float: ...
    @property
    def defaulted(self) -> bool: ...
    def __repr__(self) -> str: ...

class CDSIndexBuilder:
    """Fluent builder returned by :meth:`CDSIndex.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def index_name(self, index_name: str) -> "CDSIndexBuilder": ...
    def series(self, series: int) -> "CDSIndexBuilder": ...
    def version(self, version: int) -> "CDSIndexBuilder": ...
    def notional(self, notional: Money) -> "CDSIndexBuilder": ...
    def money(self, money: Money) -> "CDSIndexBuilder": ...
    def fixed_coupon_bp(self, fixed_coupon_bp: float) -> "CDSIndexBuilder": ...
    def start_date(self, start_date: date) -> "CDSIndexBuilder": ...
    def maturity(self, maturity: date) -> "CDSIndexBuilder": ...
    def discount_curve(self, discount_curve: str) -> "CDSIndexBuilder": ...
    def credit_curve(self, credit_curve: str) -> "CDSIndexBuilder": ...
    def side(self, side: str) -> "CDSIndexBuilder": ...
    def recovery_rate(self, recovery_rate: float) -> "CDSIndexBuilder": ...
    def index_factor(self, index_factor: float | None = ...) -> "CDSIndexBuilder": ...
    def convention(self, convention: CDSConvention) -> "CDSIndexBuilder": ...
    def build(self) -> "CDSIndex": ...

class CDSIndex:
    """CDS index for portfolio credit risk exposure.

    CDSIndex represents a credit default swap on a standardized index of
    reference entities (e.g., CDX, iTraxx).

    Examples
    --------
        >>> from finstack.valuations.instruments import CDSIndex
        >>> from finstack import Money, Currency
        >>> from datetime import date
        >>> cds_index = (
        ...     CDSIndex
        ...     .builder("CDX-IG-5Y")
        ...     .index_name("CDX.NA.IG")
        ...     .series(40)
        ...     .version(1)
        ...     .money(Money(10_000_000, Currency("USD")))
        ...     .fixed_coupon_bp(100.0)
        ...     .start_date(date(2024, 1, 1))
        ...     .maturity(date(2029, 1, 1))
        ...     .discount_curve("USD")
        ...     .credit_curve("CDX-IG-40")
        ...     .side("pay_protection")
        ...     .build()
        ... )

    Sources
    -------
    - ISDA (2006) Definitions: see ``docs/REFERENCES.md#isda2006Definitions``.
    - O'Kane (2008): see ``docs/REFERENCES.md#okane2008``.
    """

    @classmethod
    def builder(cls, instrument_id: str) -> CDSIndexBuilder:
        """Start a fluent builder (builder-only API).

        Parameters
        ----------
        instrument_id : str
            Unique identifier for the CDS index.

        Returns
        -------
        CDSIndexBuilder
        """
        ...

    @property
    def instrument_id(self) -> str: ...
    @property
    def index_name(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def fixed_coupon_bp(self) -> float: ...
    @property
    def side(self) -> CDSPayReceive: ...
    @property
    def discount_curve(self) -> str: ...
    @property
    def credit_curve(self) -> str: ...
    @property
    def maturity(self) -> date: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    @property
    def series(self) -> int: ...
    @property
    def version(self) -> int: ...
    @property
    def index_factor(self) -> float: ...
    @property
    def start_date(self) -> date: ...
    @property
    def recovery_rate(self) -> float: ...
    @property
    def convention(self) -> CDSConvention: ...
    @property
    def constituents(self) -> list[CDSIndexConstituent]: ...
    @property
    def pricing_mode(self) -> str: ...
    def pv_protection_leg(self, market: MarketContext, as_of: date) -> Money:
        """Calculate protection leg present value."""
        ...

    def pv_premium_leg(self, market: MarketContext, as_of: date) -> Money:
        """Calculate premium leg present value."""
        ...

    def par_spread(self, market: MarketContext, as_of: date) -> float:
        """Calculate par spread in basis points."""
        ...

    def risky_pv01(self, market: MarketContext, as_of: date) -> float:
        """Calculate risky PV01."""
        ...

    def cs01(self, market: MarketContext, as_of: date) -> float:
        """Calculate CS01 (credit spread sensitivity)."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
