"""CDS tranche instrument."""

from __future__ import annotations
from datetime import date
from ....core.money import Money
from ....core.dates.daycount import DayCount
from ....core.dates.calendar import BusinessDayConvention
from ...common import InstrumentType
from ....core.market_data.context import MarketContext

class TrancheSide:
    """Buy/sell protection side for CDS tranches."""

    BUY_PROTECTION: "TrancheSide"
    SELL_PROTECTION: "TrancheSide"

    @classmethod
    def from_name(cls, name: str) -> "TrancheSide": ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class CDSTrancheBuilder:
    """Fluent builder returned by :meth:`CDSTranche.builder`."""

    def __init__(self, instrument_id: str) -> None: ...
    def index_name(self, index_name: str) -> "CDSTrancheBuilder": ...
    def series(self, series: int) -> "CDSTrancheBuilder": ...
    def attach_pct(self, attach_pct: float) -> "CDSTrancheBuilder": ...
    def detach_pct(self, detach_pct: float) -> "CDSTrancheBuilder": ...
    def notional(self, notional: Money) -> "CDSTrancheBuilder": ...
    def maturity(self, maturity: date) -> "CDSTrancheBuilder": ...
    def running_coupon_bp(self, running_coupon_bp: float) -> "CDSTrancheBuilder": ...
    def discount_curve(self, discount_curve: str) -> "CDSTrancheBuilder": ...
    def credit_index_curve(self, credit_index_curve: str) -> "CDSTrancheBuilder": ...
    def side(self, side: str) -> "CDSTrancheBuilder": ...
    def payments_per_year(self, payments_per_year: int) -> "CDSTrancheBuilder": ...
    def day_count(self, day_count: DayCount | str) -> "CDSTrancheBuilder": ...
    def business_day_convention(self, business_day_convention: BusinessDayConvention | str) -> "CDSTrancheBuilder": ...
    def calendar(self, calendar: str | None = ...) -> "CDSTrancheBuilder": ...
    def effective_date(self, effective_date: date | None = ...) -> "CDSTrancheBuilder": ...
    def build(self) -> "CDSTranche": ...

class CDSTranche:
    """CDS tranche for structured credit exposure.

    CDSTranche represents a tranche of a CDS index, providing exposure to
    a specific loss layer (attachment point to detachment point).

    Examples
    --------
        >>> from finstack.valuations.instruments import CDSTranche
        >>> from finstack import Money, Currency
        >>> from datetime import date
        >>> tranche = (
        ...     CDSTranche
        ...     .builder("CDX-IG-0-3")
        ...     .index_name("CDX.NA.IG")
        ...     .series(40)
        ...     .attach_pct(0.0)
        ...     .detach_pct(3.0)
        ...     .notional(Money(10_000_000, Currency("USD")))
        ...     .maturity(date(2029, 1, 1))
        ...     .running_coupon_bp(500.0)
        ...     .discount_curve("USD")
        ...     .credit_index_curve("CDX-IG-40")
        ...     .build()
        ... )

    Sources
    -------
    - Li (2000): see ``docs/REFERENCES.md#liGaussianCopula2000``.
    - O'Kane (2008): see ``docs/REFERENCES.md#okane2008``.
    """

    @classmethod
    def builder(cls, instrument_id: str) -> CDSTrancheBuilder:
        """Start a fluent builder (builder-only API).

        Parameters
        ----------
        instrument_id : str
            Unique identifier for the tranche.

        Returns
        -------
        CDSTrancheBuilder
        """
        ...

    @property
    def instrument_id(self) -> str: ...
    @property
    def notional(self) -> Money: ...
    @property
    def attach_pct(self) -> float: ...
    @property
    def detach_pct(self) -> float: ...
    @property
    def running_coupon_bp(self) -> float: ...
    @property
    def maturity(self) -> date: ...
    @property
    def discount_curve(self) -> str: ...
    @property
    def credit_index_curve(self) -> str: ...
    @property
    def index_name(self) -> str: ...
    @property
    def series(self) -> int: ...
    @property
    def side(self) -> TrancheSide: ...
    @property
    def frequency(self) -> str: ...
    @property
    def day_count(self) -> str: ...
    @property
    def bdc(self) -> str: ...
    @property
    def calendar(self) -> str | None: ...
    @property
    def effective_date(self) -> date | None: ...
    @property
    def accumulated_loss(self) -> float: ...
    @property
    def standard_imm_dates(self) -> bool: ...
    @property
    def instrument_type(self) -> InstrumentType: ...
    def upfront(self, market: MarketContext, as_of: date) -> float:
        """Calculate upfront amount."""
        ...

    def spread_dv01(self, market: MarketContext, as_of: date) -> float:
        """Calculate spread DV01."""
        ...

    def par_spread(self, market: MarketContext, as_of: date) -> float:
        """Calculate par spread in basis points."""
        ...

    def expected_loss(self, market: MarketContext) -> float:
        """Calculate expected loss."""
        ...

    def jump_to_default(self, market: MarketContext, as_of: date) -> float:
        """Calculate jump-to-default metric."""
        ...

    def correlation_delta(self, market: MarketContext, as_of: date) -> float:
        """Calculate correlation delta."""
        ...

    def accrued_premium(self, market: MarketContext, as_of: date) -> float:
        """Calculate accrued premium."""
        ...

    def expected_loss_curve(self, market: MarketContext, as_of: date) -> list[tuple[date, float]]:
        """Calculate expected loss curve over time."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
