//! Variance swap type definitions.

use finstack_core::{
    dates::{Date, DayCount, Tenor},
    market_data::context::MarketContext,
    math::stats::{realized_variance, RealizedVarMethod},
    money::Money,
    types::{CurveId, InstrumentId},
    Result,
};
use time::macros::date;

use crate::impl_instrument_base;
use crate::{cashflow::traits::CashflowProvider, instruments::common::traits::Attributes};

pub use crate::instruments::common_impl::parameters::PayReceive;

/// Variance swap instrument.
///
/// A variance swap is a forward contract on realized variance with payoff:
/// ```text
/// Payoff = Notional_variance × (σ²_realized - K²_variance)
/// ```
///
/// # Notional Conventions
///
/// Variance swaps use **variance notional** (in variance units), not vega notional.
/// The notional represents the P&L per unit of variance point (e.g., per 0.0001 change
/// in annualized variance).
///
/// ## Variance Notional vs Vega Notional
///
/// Traders often quote positions in **vega notional** (sensitivity to 1% vol change).
/// The conversion between notional types is:
///
/// ```text
/// Notional_variance = Notional_vega / (2 × σ_strike)
/// ```
///
/// where `σ_strike` is the strike volatility (square root of strike variance).
///
/// ### Example
///
/// For a variance swap with strike vol of 20% (strike variance = 0.04):
/// - Vega notional of $100,000 → Variance notional = $100,000 / (2 × 0.20) = $250,000
/// - If realized variance is 0.05 (22.4% vol) vs strike 0.04:
///   - Payoff = $250,000 × (0.05 - 0.04) = $2,500
///
/// # Realized Variance Calculation
///
/// Uses **log returns** (not simple returns) per market standard:
/// ```text
/// σ²_realized = (252/N) × Σ [ln(S_i / S_{i-1})]²
/// ```
///
/// where 252 is the standard trading days per year for equity markets.
///
/// # References
///
/// - Demeterfi, K. et al. (1999). "More Than You Ever Wanted to Know About Volatility Swaps."
/// - Carr, P. & Madan, D. (1998). "Towards a Theory of Volatility Trading."
#[derive(
    Clone, Debug, finstack_valuations_macros::FinancialBuilder, serde::Serialize, serde::Deserialize,
)]
#[serde(deny_unknown_fields)]
pub struct VarianceSwap {
    /// Unique instrument identifier
    pub id: InstrumentId,
    /// Underlying identifier (equity/index)
    #[serde(alias = "underlying_id")]
    pub underlying_ticker: crate::instruments::equity::spot::Ticker,
    /// Variance notional (in variance units)
    pub notional: Money,
    /// Strike variance (annualized)
    pub strike_variance: f64,
    /// Start date of observation period
    pub start_date: Date,
    /// Maturity/settlement date
    pub maturity: Date,
    /// Observation frequency
    pub observation_freq: Tenor,
    /// Method for calculating realized variance (defaults to CloseToClose)
    #[serde(default)]
    #[builder(default)]
    pub realized_var_method: RealizedVarMethod,
    /// Pay/receive variance
    pub side: PayReceive,
    /// Discount curve identifier
    pub discount_curve_id: CurveId,
    /// Day count convention for time calculations
    pub day_count: DayCount,
    /// Attributes for scenario selection
    #[serde(default)]
    #[builder(default)]
    pub pricing_overrides: crate::instruments::PricingOverrides,
    /// Attributes for scenario selection and tagging
    pub attributes: Attributes,
}

impl VarianceSwap {
    // (builder generated by derive)

    /// Convert vega notional to variance notional.
    ///
    /// Traders often quote positions in **vega notional** (sensitivity to 1 vol point change).
    /// This converts to the variance notional used internally:
    ///
    /// ```text
    /// Notional_variance = Notional_vega / (2 × σ_strike)
    /// ```
    ///
    /// where `σ_strike` is the strike volatility (square root of strike variance).
    ///
    /// # Arguments
    ///
    /// * `vega_notional` - Vega notional amount (P&L per 1 vol point move)
    /// * `strike_vol` - Strike volatility as a decimal (e.g., 0.20 for 20%)
    ///
    /// # Returns
    ///
    /// Variance notional amount (P&L per unit of variance)
    ///
    /// # Panics
    ///
    /// Returns 0.0 if `strike_vol <= 0.0` to avoid division by zero.
    ///
    /// # Example
    ///
    /// ```
    /// use finstack_valuations::instruments::equity::variance_swap::VarianceSwap;
    ///
    /// // $100,000 vega notional at 20% strike vol → $250,000 variance notional
    /// let var_notional = VarianceSwap::vega_to_variance_notional(100_000.0, 0.20);
    /// assert!((var_notional - 250_000.0).abs() < 1e-6);
    /// ```
    pub fn vega_to_variance_notional(vega_notional: f64, strike_vol: f64) -> f64 {
        if strike_vol <= 0.0 {
            return 0.0;
        }
        vega_notional / (2.0 * strike_vol)
    }

    /// Convert variance notional to vega notional.
    ///
    /// Inverse of [`vega_to_variance_notional`](Self::vega_to_variance_notional):
    ///
    /// ```text
    /// Notional_vega = Notional_variance × 2 × σ_strike
    /// ```
    ///
    /// # Arguments
    ///
    /// * `variance_notional` - Variance notional amount
    /// * `strike_vol` - Strike volatility as a decimal (e.g., 0.20 for 20%)
    ///
    /// # Returns
    ///
    /// Vega notional amount (P&L per 1 vol point move)
    pub fn variance_to_vega_notional(variance_notional: f64, strike_vol: f64) -> f64 {
        variance_notional * 2.0 * strike_vol
    }

    /// Create a canonical example equity variance swap (SPX, 1Y).
    pub fn example() -> Self {
        use finstack_core::currency::Currency;
        // SAFETY: All inputs are compile-time validated constants
        VarianceSwap::builder()
            .id(InstrumentId::new("VARSPX-1Y"))
            .underlying_ticker("SPX".to_string())
            .notional(Money::new(1_000_000.0, Currency::USD))
            .strike_variance(0.04) // 20% vol squared
            .start_date(date!(2024 - 01 - 01))
            .maturity(date!(2025 - 01 - 01))
            .observation_freq(finstack_core::dates::Tenor::daily())
            .realized_var_method(RealizedVarMethod::Parkinson)
            .side(PayReceive::Receive)
            .discount_curve_id(CurveId::new("USD-OIS"))
            .day_count(DayCount::Act365F)
            .attributes(Attributes::new())
            .build()
            .unwrap_or_else(|_| {
                unreachable!("Example VarianceSwap with valid constants should never fail")
            })
    }

    /// Validate that as_of is compatible with the market context.
    ///
    /// Checks for obvious misalignments between the as_of date and market data:
    /// - as_of must not be before the discount curve base date
    /// - as_of must align with instrument dates (not before start_date minus reasonable lookback)
    ///
    /// Returns a descriptive error if validation fails.
    fn validate_as_of(&self, context: &MarketContext, as_of: Date) -> Result<()> {
        // Check discount curve base date alignment
        let disc = context.get_discount(self.discount_curve_id.as_str())?;
        let curve_base = disc.base_date();

        if as_of < curve_base {
            return Err(finstack_core::Error::Validation(format!(
                "VarianceSwap valuation as_of date ({}) is before discount curve '{}' base date ({}). \
                 Market data must be aligned with or precede the valuation date.",
                as_of, self.discount_curve_id.as_str(), curve_base
            )));
        }

        Ok(())
    }

    /// Get the discount curve ID for this variance swap.
    pub fn discount_curve_id(&self) -> &CurveId {
        &self.discount_curve_id
    }

    /// Calculate payoff given realized variance.
    pub fn payoff(&self, realized_variance: f64) -> Money {
        let variance_diff = realized_variance - self.strike_variance;
        let sign = self.side.sign();
        Money::new(
            self.notional.amount() * variance_diff * sign,
            self.notional.currency(),
        )
    }

    /// Get observation dates based on frequency.
    pub fn observation_dates(&self) -> Vec<Date> {
        use finstack_core::dates::DateExt;

        // Simple date generation based on frequency
        let mut dates = Vec::new();
        let mut current = self.start_date;

        // Determine the step based on frequency
        if let Some(months_step) = self.observation_freq.months() {
            // Month-based frequency
            while current <= self.maturity {
                dates.push(current);
                current = current.add_months(months_step as i32);

                if current > self.maturity {
                    break;
                }
            }
        } else if let Some(days_step) = self.observation_freq.days() {
            // Day-based frequency
            while current <= self.maturity {
                dates.push(current);
                current += time::Duration::days(days_step as i64);

                if current > self.maturity {
                    break;
                }
            }
        } else {
            // Default to daily for unknown frequency
            while current <= self.maturity {
                dates.push(current);
                current += time::Duration::days(1);

                if current > self.maturity {
                    break;
                }
            }
        }

        // Ensure maturity is included if not already
        if dates.is_empty() || dates.last() != Some(&self.maturity) {
            dates.push(self.maturity);
        }

        dates
    }

    /// Calculate annualization factor based on observation frequency.
    ///
    /// Equity variance swaps use **252 trading days per year** as the market standard
    /// (Demeterfi et al., 1999). This converts sample variance to annualized variance:
    /// σ²_annual = (252/N) × Σ [ln(S_i/S_{i-1})]² for N observations.
    pub fn annualization_factor(&self) -> f64 {
        const TRADING_DAYS_PER_YEAR: f64 = 252.0;

        // Check month-based frequencies first
        if let Some(months) = self.observation_freq.months() {
            match months {
                1 => 12.0,                  // Monthly
                3 => 4.0,                   // Quarterly
                6 => 2.0,                   // Semi-annual
                12 => 1.0,                  // Annual
                _ => TRADING_DAYS_PER_YEAR, // Default to daily for other month counts
            }
        } else if let Some(days) = self.observation_freq.days() {
            // Handle day-based frequencies; use 252 (trading days) for equity convention
            match days {
                1 => TRADING_DAYS_PER_YEAR,               // Daily (trading days)
                7 => TRADING_DAYS_PER_YEAR / 7.0,         // Weekly (~36)
                14 => TRADING_DAYS_PER_YEAR / 14.0,       // Bi-weekly (~18)
                _ => TRADING_DAYS_PER_YEAR / days as f64, // General: 252/days (trading days)
            }
        } else {
            TRADING_DAYS_PER_YEAR // Default to daily
        }
    }

    /// Sampling policy aware annualization factor (uses market overrides when available).
    pub fn annualization_factor_with_policy(&self, context: &MarketContext) -> f64 {
        // Allow market override via unitless scalars
        // Priority: UNDERLYING_TRADING_DAYS_PER_YEAR, TRADING_DAYS_PER_YEAR
        let tdy_override = context
            .price(format!("{}_TRADING_DAYS_PER_YEAR", self.underlying_ticker))
            .ok()
            .and_then(|s| match s {
                finstack_core::market_data::scalars::MarketScalar::Unitless(v) => Some(*v),
                _ => None,
            })
            .or_else(|| {
                context
                    .price("TRADING_DAYS_PER_YEAR")
                    .ok()
                    .and_then(|s| match s {
                        finstack_core::market_data::scalars::MarketScalar::Unitless(v) => Some(*v),
                        _ => None,
                    })
            })
            .unwrap_or(252.0);

        if let Some(months) = self.observation_freq.months() {
            return match months {
                1 => 12.0,
                3 => 4.0,
                6 => 2.0,
                12 => 1.0,
                _ => tdy_override,
            };
        }
        if let Some(days) = self.observation_freq.days() {
            return match days {
                1 => tdy_override,
                7 => tdy_override / 7.0,
                14 => tdy_override / 14.0,
                _ => tdy_override / days as f64, // 252/days for equity (trading days convention)
            };
        }
        tdy_override
    }

    /// Calculate the fraction of time elapsed in the observation period.
    pub fn time_elapsed_fraction(&self, as_of: Date) -> f64 {
        if as_of <= self.start_date {
            return 0.0;
        }
        if as_of >= self.maturity {
            return 1.0;
        }

        // Use day-count to compute precise fractions rather than raw day counts
        let total = self
            .day_count
            .year_fraction(self.start_date, self.maturity, Default::default())
            .unwrap_or(0.0);
        if total <= 0.0 {
            return 0.0;
        }
        let elapsed = self
            .day_count
            .year_fraction(self.start_date, as_of, Default::default())
            .unwrap_or(0.0)
            .clamp(0.0, total);
        (elapsed / total).clamp(0.0, 1.0)
    }

    /// Calculate realized fraction based on observation counts (sampling-based weight).
    pub fn realized_fraction_by_observations(&self, as_of: Date) -> f64 {
        let all = self.observation_dates();
        if all.is_empty() {
            return 0.0;
        }
        if as_of <= self.start_date {
            return 0.0;
        }
        if as_of >= self.maturity {
            return 1.0;
        }
        let total = all.len() as f64;
        let realized = all.iter().filter(|&&d| d <= as_of).count() as f64;
        (realized / total).clamp(0.0, 1.0)
    }

    /// Get historical prices aligned to observation dates when available.
    pub fn get_historical_prices(&self, context: &MarketContext, as_of: Date) -> Result<Vec<f64>> {
        // Try generic time series first (preferred)
        if let Ok(series) = context.series(&self.underlying_ticker) {
            let dates: Vec<Date> = self
                .observation_dates()
                .into_iter()
                .filter(|&d| d <= as_of)
                .collect();
            if dates.len() >= 2 {
                return series.values_on(&dates);
            }
        }
        // Fallback to single spot scalar
        if let Ok(scalar) = context.price(&self.underlying_ticker) {
            let spot = match scalar {
                finstack_core::market_data::scalars::MarketScalar::Unitless(v) => *v,
                finstack_core::market_data::scalars::MarketScalar::Price(p) => p.amount(),
            };
            Ok(vec![spot])
        } else {
            Ok(vec![])
        }
    }

    /// Calculate partial realized variance for the elapsed period.
    pub fn partial_realized_variance(&self, context: &MarketContext, as_of: Date) -> Result<f64> {
        let prices = self.get_historical_prices(context, as_of)?;
        if prices.len() < 2 {
            return Ok(0.0);
        }
        Ok(realized_variance(
            &prices,
            self.realized_var_method,
            self.annualization_factor_with_policy(context),
        ))
    }

    /// Calculate implied forward variance for the remaining period.
    ///
    /// Uses the Carr-Madan (1998) replication formula when a volatility surface is available:
    /// ```text
    /// E[σ²] = (2/T) × e^(rT) × ∫ [V(K)/K²] dK - (1/T) × (F/K₀ - 1)²
    /// ```
    /// where V(K) are OTM put/call prices, F is the forward price, and K₀ is the strike at
    /// or just below the forward. Falls back to ATM vol² or strike variance if no surface.
    ///
    /// Reference: Carr, P. & Madan, D. (1998). "Towards a Theory of Volatility Trading."
    pub fn remaining_forward_variance(&self, context: &MarketContext, _as_of: Date) -> Result<f64> {
        // Prefer replication from a vol surface; fallback to ATM surface vol,
        // then scalar implied vol, and finally strike variance.

        // Remaining tenor in years
        let t = self
            .day_count
            .year_fraction(_as_of, self.maturity, Default::default())?;

        // Try surfaces with common ids first
        for sid in [
            self.underlying_ticker.as_str(),
            &format!("{}_VOL", self.underlying_ticker),
            &format!("{}_IMPL_VOL", self.underlying_ticker),
        ] {
            if let Ok(surface) = context.surface(sid) {
                // Attempt variance replication (VIX-like)
                if let Ok(disc) = context.get_discount(&self.discount_curve_id) {
                    if let Ok(spot_scalar) = context.price(&self.underlying_ticker) {
                        let spot = match spot_scalar {
                            finstack_core::market_data::scalars::MarketScalar::Unitless(v) => *v,
                            finstack_core::market_data::scalars::MarketScalar::Price(p) => {
                                p.amount()
                            }
                        };
                        let r = disc.zero(t.max(1e-8));
                        let q = context
                            .price(format!("{}-DIVYIELD", self.underlying_ticker))
                            .ok()
                            .and_then(|s| match s {
                                finstack_core::market_data::scalars::MarketScalar::Unitless(v) => {
                                    Some(*v)
                                }
                                _ => None,
                            })
                            .unwrap_or(0.0);
                        // Forward price
                        let fwd = spot * ((r - q) * t).exp();
                        let strikes = surface.strikes();
                        if t > 0.0 && strikes.len() >= 3 && fwd.is_finite() && fwd > 0.0 {
                            // Find K0 (strike just below forward)
                            let mut k0_idx = 0usize;
                            for (i, &k) in strikes.iter().enumerate() {
                                if k <= fwd {
                                    k0_idx = i;
                                } else {
                                    break;
                                }
                            }
                            let k0 = strikes[k0_idx].max(1e-12);

                            // Compute sum over OTM options
                            let mut sum = 0.0;
                            for i in 0..strikes.len() {
                                let k = strikes[i].max(1e-12);
                                // ΔK
                                let dk = if i == 0 {
                                    strikes[1] - strikes[0]
                                } else if i + 1 == strikes.len() {
                                    strikes[i] - strikes[i - 1]
                                } else {
                                    0.5 * (strikes[i + 1] - strikes[i - 1])
                                };

                                // Option price Q(K): OTM put for K < F, OTM call for K > F, average at K0
                                let vol = surface.value_clamped(t, k).max(1e-8);
                                let sqrt_t = t.sqrt();
                                // Black-Scholes helper
                                let d1 = if vol > 0.0 && t > 0.0 {
                                    ((spot / k).ln() + (r - q + 0.5 * vol * vol) * t)
                                        / (vol * sqrt_t)
                                } else {
                                    0.0
                                };
                                let d2 = d1 - vol * sqrt_t;
                                let exp_mqt = (-q * t).exp();
                                let exp_mrt = (-r * t).exp();
                                let call = spot * exp_mqt * finstack_core::math::norm_cdf(d1)
                                    - k * exp_mrt * finstack_core::math::norm_cdf(d2);
                                let put = k * exp_mrt * finstack_core::math::norm_cdf(-d2)
                                    - spot * exp_mqt * finstack_core::math::norm_cdf(-d1);

                                let qk = if (i == k0_idx)
                                    || ((k0 - k).abs() < 1e-12 && (fwd - k0).abs() < 1e-12)
                                {
                                    0.5 * (call + put)
                                } else if k < fwd {
                                    put
                                } else {
                                    call
                                };
                                sum += (dk / (k * k)) * qk;
                            }
                            let variance = (2.0 * (r * t).exp() / t) * sum
                                - (1.0 / t) * ((fwd / k0 - 1.0).powi(2));
                            if variance.is_finite() && variance > 0.0 {
                                return Ok(variance);
                            }
                        }
                        // Fallback to ATM vol at spot as strike
                        let vol_atm = surface.value_clamped(t.max(1e-8), spot);
                        if vol_atm.is_finite() && vol_atm > 0.0 {
                            return Ok(vol_atm * vol_atm);
                        }
                    }
                }
            }
        }

        // Try to get implied vol from scalar market data
        if let Ok(scalar) = context.price(format!("{}_IMPL_VOL", self.underlying_ticker)) {
            let vol = match scalar {
                finstack_core::market_data::scalars::MarketScalar::Unitless(v) => *v,
                finstack_core::market_data::scalars::MarketScalar::Price(p) => p.amount(),
            };
            Ok(vol * vol)
        } else {
            // Default to strike variance as forward estimate
            Ok(self.strike_variance)
        }
    }
}

// Use the macro to implement Instrument with pricing
impl crate::instruments::common_impl::traits::Instrument for VarianceSwap {
    impl_instrument_base!(crate::pricer::InstrumentType::VarianceSwap);

    fn value(
        &self,
        curves: &finstack_core::market_data::context::MarketContext,
        as_of: finstack_core::dates::Date,
    ) -> finstack_core::Result<finstack_core::money::Money> {
        // Validate strike variance is non-negative (variance is σ², must be ≥ 0)
        if self.strike_variance < 0.0 {
            return Err(finstack_core::Error::Validation(format!(
                "VarianceSwap strike_variance ({:.6}) must be non-negative",
                self.strike_variance
            )));
        }

        // Validate as_of alignment with market data
        self.validate_as_of(curves, as_of)?;

        // Get discount curve
        let disc = curves.get_discount(self.discount_curve_id.as_str())?;

        // If expired, compute final payoff from realized variance (if any prices)
        if as_of >= self.maturity {
            let prices = self.get_historical_prices(curves, as_of)?;
            if prices.is_empty() {
                return Ok(finstack_core::money::Money::new(
                    0.0,
                    self.notional.currency(),
                ));
            }

            // Use policy-aware annualization factor for consistency with partial
            // observation pricing. This respects market overrides such as
            // custom trading days per year for non-US underlyings.
            let realized_var = realized_variance(
                &prices,
                self.realized_var_method,
                self.annualization_factor_with_policy(curves),
            );
            return Ok(self.payoff(realized_var));
        }

        // If not yet started, value using forward (implied) variance and discount
        if as_of < self.start_date {
            let forward_var = self.remaining_forward_variance(curves, as_of)?;
            let undiscounted = self.payoff(forward_var);
            let t = self
                .day_count
                .year_fraction(as_of, self.maturity, Default::default())?;
            let df = disc.df(t);
            return Ok(undiscounted * df);
        }

        // Partially observed: blend realized-to-date with forward for remaining using observation counts
        let realized = self.partial_realized_variance(curves, as_of)?;
        let forward = self.remaining_forward_variance(curves, as_of)?;
        let w = self.realized_fraction_by_observations(as_of);
        let expected_var = realized * w + forward * (1.0 - w);
        let undiscounted = self.payoff(expected_var);

        let t = self
            .day_count
            .year_fraction(as_of, self.maturity, Default::default())?;
        let df = disc.df(t);
        Ok(undiscounted * df)
    }

    fn as_cashflow_provider(&self) -> Option<&dyn crate::cashflow::traits::CashflowProvider> {
        Some(self)
    }

    fn expiry(&self) -> Option<finstack_core::dates::Date> {
        Some(self.maturity)
    }

    fn effective_start_date(&self) -> Option<finstack_core::dates::Date> {
        Some(self.start_date)
    }

    fn scenario_overrides_mut(
        &mut self,
    ) -> Option<&mut crate::instruments::pricing_overrides::PricingOverrides> {
        Some(&mut self.pricing_overrides)
    }

    fn scenario_overrides(
        &self,
    ) -> Option<&crate::instruments::pricing_overrides::PricingOverrides> {
        Some(&self.pricing_overrides)
    }
}

// Implement CurveDependencies for DV01 calculator
impl crate::instruments::common_impl::traits::CurveDependencies for VarianceSwap {
    fn curve_dependencies(
        &self,
    ) -> finstack_core::Result<crate::instruments::common_impl::traits::InstrumentCurves> {
        crate::instruments::common_impl::traits::InstrumentCurves::builder()
            .discount(self.discount_curve_id.clone())
            .build()
    }
}

impl CashflowProvider for VarianceSwap {
    fn notional(&self) -> Option<Money> {
        Some(self.notional)
    }

    fn build_full_schedule(
        &self,
        _context: &MarketContext,
        _as_of: Date,
    ) -> Result<crate::cashflow::builder::CashFlowSchedule> {
        // Variance swaps have a single settlement payment at maturity.
        Ok(crate::cashflow::traits::schedule_from_dated_flows(
            vec![(self.maturity, Money::new(0.0, self.notional.currency()))],
            self.notional(),
            self.day_count,
        ))
    }
}
