//! Variance swap type definitions.

use finstack_core::{
    dates::{Date, DayCount, Tenor},
    market_data::context::MarketContext,
    math::stats::RealizedVarMethod,
    money::Money,
    types::{CurveId, InstrumentId},
    Result,
};
use time::macros::date;

use super::pricer;
use crate::impl_instrument_base;
use crate::{
    cashflow::traits::CashflowProvider,
    instruments::{common_impl::traits::Attributes, MarketDependencies},
};

pub use crate::instruments::common_impl::parameters::PayReceive;

/// Variance swap instrument.
///
/// A variance swap is a forward contract on realized variance with payoff:
/// ```text
/// Payoff = Notional_variance × (σ²_realized - K²_variance)
/// ```
///
/// # Notional Conventions
///
/// Variance swaps use **variance notional** (in variance units), not vega notional.
/// The notional represents the P&L per unit of variance point (e.g., per 0.0001 change
/// in annualized variance).
///
/// ## Variance Notional vs Vega Notional
///
/// Traders often quote positions in **vega notional** (sensitivity to 1% vol change).
/// The conversion between notional types is:
///
/// ```text
/// Notional_variance = Notional_vega / (2 × σ_strike)
/// ```
///
/// where `σ_strike` is the strike volatility (square root of strike variance).
///
/// ### Example
///
/// For a variance swap with strike vol of 20% (strike variance = 0.04):
/// - Vega notional of $100,000 → Variance notional = $100,000 / (2 × 0.20) = $250,000
/// - If realized variance is 0.05 (22.4% vol) vs strike 0.04:
///   - Payoff = $250,000 × (0.05 - 0.04) = $2,500
///
/// # Realized Variance Calculation
///
/// Uses **log returns** (not simple returns) per market standard:
/// ```text
/// σ²_realized = (252/N) × Σ [ln(S_i / S_{i-1})]²
/// ```
///
/// where 252 is the standard trading days per year for equity markets.
///
/// # References
///
/// - Demeterfi, K. et al. (1999). "More Than You Ever Wanted to Know About Volatility Swaps."
/// - Carr, P. & Madan, D. (1998). "Towards a Theory of Volatility Trading."
#[derive(
    Clone,
    Debug,
    finstack_valuations_macros::FinancialBuilder,
    serde::Serialize,
    serde::Deserialize,
    schemars::JsonSchema,
)]
#[serde(deny_unknown_fields)]
pub struct VarianceSwap {
    /// Unique instrument identifier
    pub id: InstrumentId,
    /// Underlying identifier (equity/index)
    pub underlying_ticker: crate::instruments::equity::spot::Ticker,
    /// Variance notional (in variance units)
    pub notional: Money,
    /// Strike variance (annualized)
    pub strike_variance: f64,
    /// Start date of observation period
    #[schemars(with = "String")]
    pub start_date: Date,
    /// Maturity/settlement date
    #[schemars(with = "String")]
    pub maturity: Date,
    /// Observation frequency
    pub observation_freq: Tenor,
    /// Method for calculating realized variance (defaults to CloseToClose)
    #[serde(default)]
    #[builder(default)]
    pub realized_var_method: RealizedVarMethod,
    /// Series ID for open prices (required for Parkinson, GarmanKlass, RogersSatchell, YangZhang).
    /// Defaults to `underlying_ticker` when absent.
    #[serde(default)]
    #[builder(optional)]
    pub open_series_id: Option<String>,
    /// Series ID for high prices (required for Parkinson, GarmanKlass, RogersSatchell, YangZhang).
    /// Defaults to `underlying_ticker` when absent.
    #[serde(default)]
    #[builder(optional)]
    pub high_series_id: Option<String>,
    /// Series ID for low prices (required for Parkinson, GarmanKlass, RogersSatchell, YangZhang).
    /// Defaults to `underlying_ticker` when absent.
    #[serde(default)]
    #[builder(optional)]
    pub low_series_id: Option<String>,
    /// Series ID for close prices. Defaults to `underlying_ticker` when absent.
    #[serde(default)]
    #[builder(optional)]
    pub close_series_id: Option<String>,
    /// Pay/receive variance
    pub side: PayReceive,
    /// Discount curve identifier
    pub discount_curve_id: CurveId,
    /// Day count convention for time calculations
    pub day_count: DayCount,
    /// Attributes for scenario selection
    #[serde(default)]
    #[builder(default)]
    pub pricing_overrides: crate::instruments::PricingOverrides,
    /// Attributes for scenario selection and tagging
    pub attributes: Attributes,
}

impl VarianceSwap {
    // (builder generated by derive)

    /// Convert vega notional to variance notional.
    ///
    /// Traders often quote positions in **vega notional** (sensitivity to 1 vol point change).
    /// This converts to the variance notional used internally:
    ///
    /// ```text
    /// Notional_variance = Notional_vega / (2 × σ_strike)
    /// ```
    ///
    /// where `σ_strike` is the strike volatility (square root of strike variance).
    ///
    /// # Arguments
    ///
    /// * `vega_notional` - Vega notional amount (P&L per 1 vol point move)
    /// * `strike_vol` - Strike volatility as a decimal (e.g., 0.20 for 20%)
    ///
    /// # Returns
    ///
    /// Variance notional amount (P&L per unit of variance)
    ///
    /// # Panics
    ///
    /// Returns 0.0 if `strike_vol <= 0.0` to avoid division by zero.
    ///
    /// # Example
    ///
    /// ```
    /// use finstack_valuations::instruments::equity::variance_swap::VarianceSwap;
    ///
    /// // $100,000 vega notional at 20% strike vol → $250,000 variance notional
    /// let var_notional = VarianceSwap::vega_to_variance_notional(100_000.0, 0.20);
    /// assert!((var_notional - 250_000.0).abs() < 1e-6);
    /// ```
    pub fn vega_to_variance_notional(vega_notional: f64, strike_vol: f64) -> f64 {
        if strike_vol <= 0.0 {
            return 0.0;
        }
        vega_notional / (2.0 * strike_vol)
    }

    /// Convert variance notional to vega notional.
    ///
    /// Inverse of [`vega_to_variance_notional`](Self::vega_to_variance_notional):
    ///
    /// ```text
    /// Notional_vega = Notional_variance × 2 × σ_strike
    /// ```
    ///
    /// # Arguments
    ///
    /// * `variance_notional` - Variance notional amount
    /// * `strike_vol` - Strike volatility as a decimal (e.g., 0.20 for 20%)
    ///
    /// # Returns
    ///
    /// Vega notional amount (P&L per 1 vol point move)
    pub fn variance_to_vega_notional(variance_notional: f64, strike_vol: f64) -> f64 {
        variance_notional * 2.0 * strike_vol
    }

    /// Create a canonical example equity variance swap (SPX, 1Y).
    pub fn example() -> finstack_core::Result<Self> {
        use finstack_core::currency::Currency;
        // SAFETY: All inputs are compile-time validated constants
        VarianceSwap::builder()
            .id(InstrumentId::new("VARSPX-1Y"))
            .underlying_ticker("SPX".to_string())
            .notional(Money::new(1_000_000.0, Currency::USD))
            .strike_variance(0.04) // 20% vol squared
            .start_date(date!(2024 - 01 - 01))
            .maturity(date!(2025 - 01 - 01))
            .observation_freq(finstack_core::dates::Tenor::daily())
            .realized_var_method(RealizedVarMethod::CloseToClose)
            .side(PayReceive::Receive)
            .discount_curve_id(CurveId::new("USD-OIS"))
            .day_count(DayCount::Act365F)
            .attributes(Attributes::new())
            .build()
    }

    /// Validate that as_of is compatible with the market context.
    ///
    /// Checks for obvious misalignments between the as_of date and market data:
    /// - as_of must not be before the discount curve base date
    /// - as_of must align with instrument dates (not before start_date minus reasonable lookback)
    ///
    /// Returns a descriptive error if validation fails.
    pub(crate) fn validate_as_of(&self, context: &MarketContext, as_of: Date) -> Result<()> {
        // Check discount curve base date alignment
        let disc = context.get_discount(self.discount_curve_id.as_str())?;
        let curve_base = disc.base_date();

        if as_of < curve_base {
            return Err(finstack_core::Error::Validation(format!(
                "VarianceSwap valuation as_of date ({}) is before discount curve '{}' base date ({}). \
                 Market data must be aligned with or precede the valuation date.",
                as_of, self.discount_curve_id.as_str(), curve_base
            )));
        }

        Ok(())
    }

    /// Get the discount curve ID for this variance swap.
    pub fn discount_curve_id(&self) -> &CurveId {
        &self.discount_curve_id
    }

    /// Calculate payoff given realized variance.
    pub fn payoff(&self, realized_variance: f64) -> Money {
        let variance_diff = realized_variance - self.strike_variance;
        let sign = self.side.sign();
        Money::new(
            self.notional.amount() * variance_diff * sign,
            self.notional.currency(),
        )
    }

    /// Get observation dates based on frequency.
    pub fn observation_dates(&self) -> Vec<Date> {
        pricer::observation_dates(self)
    }

    /// Calculate annualization factor based on observation frequency.
    ///
    /// Equity variance swaps use **252 trading days per year** as the market standard
    /// (Demeterfi et al., 1999). This converts sample variance to annualized variance:
    /// σ²_annual = (252/N) × Σ [ln(S_i/S_{i-1})]² for N observations.
    pub fn annualization_factor(&self) -> f64 {
        pricer::annualization_factor(self)
    }

    /// Sampling policy aware annualization factor (uses market overrides when available).
    pub fn annualization_factor_with_policy(&self, context: &MarketContext) -> f64 {
        pricer::annualization_factor_with_policy(self, context)
    }

    /// Calculate the fraction of time elapsed in the observation period.
    pub fn time_elapsed_fraction(&self, as_of: Date) -> f64 {
        if as_of <= self.start_date {
            return 0.0;
        }
        if as_of >= self.maturity {
            return 1.0;
        }

        // Use day-count to compute precise fractions rather than raw day counts
        let total = self
            .day_count
            .year_fraction(self.start_date, self.maturity, Default::default())
            .unwrap_or(0.0);
        if total <= 0.0 {
            return 0.0;
        }
        let elapsed = self
            .day_count
            .year_fraction(self.start_date, as_of, Default::default())
            .unwrap_or(0.0)
            .clamp(0.0, total);
        (elapsed / total).clamp(0.0, 1.0)
    }

    /// Calculate realized fraction based on observation counts (sampling-based weight).
    pub fn realized_fraction_by_observations(&self, as_of: Date) -> f64 {
        pricer::realized_fraction_by_observations(self, as_of)
    }

    /// Get historical prices aligned to observation dates when available.
    pub fn get_historical_prices(&self, context: &MarketContext, as_of: Date) -> Result<Vec<f64>> {
        pricer::get_historical_prices(self, context, as_of)
    }

    /// Calculate partial realized variance for the elapsed period.
    pub fn partial_realized_variance(&self, context: &MarketContext, as_of: Date) -> Result<f64> {
        pricer::partial_realized_variance(self, context, as_of)
    }

    /// Calculate implied forward variance for the remaining period.
    ///
    /// Uses the Carr-Madan (1998) replication formula when a volatility surface is available:
    /// ```text
    /// E[σ²] = (2/T) × e^(rT) × ∫ [V(K)/K²] dK - (1/T) × (F/K₀ - 1)²
    /// ```
    /// where V(K) are OTM put/call prices, F is the forward price, and K₀ is the strike at
    /// or just below the forward. Falls back to ATM vol² or strike variance if no surface.
    ///
    /// Reference: Carr, P. & Madan, D. (1998). "Towards a Theory of Volatility Trading."
    pub fn remaining_forward_variance(&self, context: &MarketContext, _as_of: Date) -> Result<f64> {
        pricer::remaining_forward_variance(self, context, _as_of)
    }
}

// Use the macro to implement Instrument with pricing
impl crate::instruments::common_impl::traits::Instrument for VarianceSwap {
    impl_instrument_base!(crate::pricer::InstrumentType::VarianceSwap);

    fn base_value(
        &self,
        curves: &finstack_core::market_data::context::MarketContext,
        as_of: finstack_core::dates::Date,
    ) -> finstack_core::Result<finstack_core::money::Money> {
        pricer::compute_pv(self, curves, as_of)
    }

    fn expiry(&self) -> Option<finstack_core::dates::Date> {
        Some(self.maturity)
    }

    fn effective_start_date(&self) -> Option<finstack_core::dates::Date> {
        Some(self.start_date)
    }

    fn pricing_overrides_mut(
        &mut self,
    ) -> Option<&mut crate::instruments::pricing_overrides::PricingOverrides> {
        Some(&mut self.pricing_overrides)
    }

    fn pricing_overrides(
        &self,
    ) -> Option<&crate::instruments::pricing_overrides::PricingOverrides> {
        Some(&self.pricing_overrides)
    }

    fn market_dependencies(&self) -> finstack_core::Result<MarketDependencies> {
        let mut deps = MarketDependencies::from_curve_dependencies(self)?;
        if self.realized_var_method.requires_ohlc() {
            for series_id in [
                self.open_series_id.as_deref(),
                self.high_series_id.as_deref(),
                self.low_series_id.as_deref(),
                self.close_series_id.as_deref(),
            ]
            .iter()
            .filter_map(|&s| s)
            {
                deps.add_series_id(series_id);
            }
        } else if let Some(close_id) = self.close_series_id.as_deref() {
            deps.add_series_id(close_id);
        } else {
            deps.add_series_id(self.underlying_ticker.as_str());
        }
        Ok(deps)
    }
}

// Implement CurveDependencies for DV01 calculator
impl crate::instruments::common_impl::traits::CurveDependencies for VarianceSwap {
    fn curve_dependencies(
        &self,
    ) -> finstack_core::Result<crate::instruments::common_impl::traits::InstrumentCurves> {
        crate::instruments::common_impl::traits::InstrumentCurves::builder()
            .discount(self.discount_curve_id.clone())
            .build()
    }
}

impl CashflowProvider for VarianceSwap {
    fn notional(&self) -> Option<Money> {
        Some(self.notional)
    }

    fn cashflow_schedule(
        &self,
        _context: &MarketContext,
        _as_of: Date,
    ) -> Result<crate::cashflow::builder::CashFlowSchedule> {
        Ok(crate::cashflow::traits::schedule_from_classified_flows(
            Vec::new(),
            self.day_count,
            crate::cashflow::traits::ScheduleBuildOpts {
                notional_hint: self.notional(),
                representation: crate::cashflow::builder::CashflowRepresentation::Placeholder,
                ..Default::default()
            },
        ))
    }
}
