"""Type stubs for the Performance analytics class."""

from typing import Optional
from datetime import date

import polars

class Performance:
    """Performance analytics engine.

    Construct from a Polars DataFrame with a Date column followed by price
    columns (one per ticker). Computes returns, drawdowns, and benchmark-
    relative metrics.

    Parameters
    ----------
    prices : polars.DataFrame
        DataFrame with ``Date`` column as the first column and price series
        as subsequent columns (one per ticker).
    benchmark_ticker : str, optional
        Name of the benchmark column. Defaults to the first price column.
    freq : str
        Observation frequency: ``"daily"``, ``"weekly"``, ``"monthly"``,
        ``"quarterly"``, ``"semiannual"``, ``"annual"``.
    log_returns : bool
        If True, use log returns; otherwise use simple returns.
    """

    def __init__(
        self,
        prices: polars.DataFrame,
        benchmark_ticker: Optional[str] = None,
        freq: str = "daily",
        log_returns: bool = False,
    ) -> None: ...
    def reset_date_range(self, start: date, end: date) -> None: ...
    def reset_bench_ticker(self, ticker: str) -> None: ...
    def cagr(self) -> polars.DataFrame: ...
    def mean_return(self, annualize: bool = True) -> polars.DataFrame: ...
    def volatility(self, annualize: bool = True) -> polars.DataFrame: ...
    def sharpe(self, risk_free_rate: float = 0.0) -> polars.DataFrame: ...
    def sortino(self) -> polars.DataFrame: ...
    def calmar(self) -> polars.DataFrame: ...
    def max_drawdown(self) -> polars.DataFrame: ...
    def value_at_risk(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def expected_shortfall(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def tail_ratio(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def ulcer_index(self) -> polars.DataFrame: ...
    def risk_of_ruin(self) -> polars.DataFrame: ...
    def tracking_error(self) -> polars.DataFrame: ...
    def information_ratio(self) -> polars.DataFrame: ...
    def r_squared(self) -> polars.DataFrame: ...
    def beta(self) -> dict[str, dict[str, float]]: ...
    def greeks(self) -> dict[str, dict[str, float]]: ...
    def skewness(self) -> polars.DataFrame: ...
    def kurtosis(self) -> polars.DataFrame: ...
    def geometric_mean(self) -> polars.DataFrame: ...
    def downside_deviation(self, mar: float = 0.0) -> polars.DataFrame: ...
    def max_drawdown_duration(self) -> polars.DataFrame: ...
    def up_capture(self) -> polars.DataFrame: ...
    def down_capture(self) -> polars.DataFrame: ...
    def capture_ratio(self) -> polars.DataFrame: ...
    def omega_ratio(self, threshold: float = 0.0) -> polars.DataFrame: ...
    def treynor(self, risk_free_rate: float = 0.0) -> polars.DataFrame: ...
    def gain_to_pain(self) -> polars.DataFrame: ...
    def martin_ratio(self) -> polars.DataFrame: ...
    def parametric_var(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def cornish_fisher_var(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def recovery_factor(self) -> polars.DataFrame: ...
    def sterling_ratio(self, risk_free_rate: float = 0.0, n: int = 5) -> polars.DataFrame: ...
    def burke_ratio(self, risk_free_rate: float = 0.0, n: int = 5) -> polars.DataFrame: ...
    def pain_index(self) -> polars.DataFrame: ...
    def pain_ratio(self, risk_free_rate: float = 0.0) -> polars.DataFrame: ...
    def cdar(self, confidence: float = 0.95) -> polars.DataFrame: ...
    def rolling_volatility(self, ticker_idx: int, window: int) -> polars.DataFrame: ...
    def rolling_sortino(self, ticker_idx: int, window: int) -> polars.DataFrame: ...
    def multi_factor_greeks(
        self,
        ticker_idx: int,
        factor_returns: polars.DataFrame,
    ) -> dict[str, object]: ...
    def batting_average(self) -> polars.DataFrame: ...
    def m_squared(self, risk_free_rate: float = 0.0) -> polars.DataFrame: ...
    def modified_sharpe(self, risk_free_rate: float = 0.0, confidence: float = 0.95) -> polars.DataFrame: ...
    def cumulative_returns(self) -> polars.DataFrame: ...
    def drawdown_series(self) -> polars.DataFrame: ...
    def correlation(self) -> polars.DataFrame: ...
    def __repr__(self) -> str: ...
