"""Performance analytics type stubs."""

from __future__ import annotations

class BetaResult: ...
class DrawdownEpisodeDict: ...
class GreeksResult: ...
class LookbackResult: ...
class MultiFactorResult: ...
class PeriodStatsResult: ...
class Performance: ...

__all__ = [
    "BetaResult",
    "DrawdownEpisodeDict",
    "GreeksResult",
    "LookbackResult",
    "MultiFactorResult",
    "Performance",
    "PeriodStatsResult",
]
